"""Executable specification of a research DESIGN, never a research runner."""
HEAD='01c89aa3c24ce5840ef86e950530b6ae8caafd24'
AGENTS_HASH='15c69b79ca372b06c2faa3f49055afca50ef815519dfa146e98889e71eb9d193'
DATE='2026-09-24'
TASKS=[]

def T(id,title,question,why,inputs,prior,delta,kind,obj,method,accept,fail,heldout,stop,cost,allowed,forbidden,deps,scores,wave,blind='Not a source-selection task; premises remain explicitly supplied.'):
    """scores: information, falsification, foundation, assumption independence,
    cost penalty, duplication penalty, transferability, premise reduction (0..5)."""
    row=dict(id=id,title=title,central_question=question,importance=why,input_status=inputs,
        repo_dedup=dict(prior_work=prior,new_atom=delta),claim_type=kind,mathematical_object=obj,
        method=method,acceptance=accept,refutation=fail,held_out=heldout,stop_rule=stop,
        computational_class=cost,allowed_conclusion=allowed,forbidden_conclusion=forbidden,
        dependencies=deps,scores=scores,wave=wave,pretarget_data=blind,
        artifacts=[f'{id}/REPORT.md',f'{id}/theorem_or_counterexample.md',f'{id}/results.json',
                   f'{id}/replay.py',f'{id}/MANIFEST.sha256'],status='PLANNED_NOT_EXECUTED')
    TASKS.append(row)

T('AUD-001','Admissibility of the numerical design constants',
 'Which latest OCB numbers support rigorous error or cost claims?',
 'Prevents population design points and floating optimizers becoming power certificates.',
 'Accepted master intake; C13 supersedes C12; numerical replay variation remains.',
 ['C13:HANKEL03B_REPORT.md','C13:MEM05_REPORT.md','C13:CHANNEL05_REPORT.md','fin_physics_review/MASTER_INTAKE_20260923.md'],
 'New outward bounds and semantic gates, not another content-hash or producer replay.',
 'NUMERICAL_CERTIFICATE_TARGET','Fixed matrices, singular values, calibration radii and probability intervals in C13.',
 'Freeze hashes; recompute only decisive constants with rational/interval bounds. Distinguish r<sigma from a power proof requiring an additional deviation allowance. Check wave subprobability conventions and fitted-null membership.',
 'Each retained number has outward endpoints, dependencies and a correct theorem/design label.',
 'A supposed probability bound is negative, relies on an invalid readout, or floating error crosses a claimed sign.',
 'Perturb final bits, replace EM likelihood by a provably suboptimal value, and test boundary singularities.',
 'Stop after locating a decisive defective gate; quarantine its descendants, not unrelated carrier theorems.',
 'M','Admit exact constants in the declared fixture or retain only numerical-design status.',
 'Exact independent replay of all campaigns, global EM optimality or empirical evidence.',[],[5,5,4,5,2,1,5,3],0)

T('SRC-001','Seven-feature observable-algebra obstruction',
 'Can the retained rank-seven feature space be a closed classical observable algebra?',
 'Identifies the extra state/readout structure required before interpreting rank seven ontologically.',
 'Rank/source nonidentifiability and MP7 Fourier support closure are already established.',
 ['C00:PHY_CAMPAIGN_REPORT.md','C05:CARRIER_SOURCE_REPORT.md','fin_rank7_mathphysics_next/proofs/MP7-013_boundary_support_classification.md'],
 'Tests pointwise algebra/coarse-partition closure, not PSD symmetry or largest-gap selection again.',
 'NO_GO_TARGET','B=span{1,C3,S3,C4,S4,C5,S5,C6} in functions on Z12.',
 'Multiply character generators exactly. Classify translation-equivariant unital subalgebras as partition algebras; test whether dimension eight is possible under the transitive Z12 action. Contrast observable-product closure with log-density addition in the valid exponential family.',
 'A closure theorem or explicit missing modes, with the minimum algebraic enlargement and scope proved.',
 'Nonclosure kills the proposed exact eight-observable algebra, not the rank-seven exponential-family model.',
 'Repeat the classification on Z18 and Z24 without choosing a desired retained rank.',
 'Stop once an exact obstruction is found; do not adjust the required algebra to retain seven by definition.',
 'S','Rank-seven statics need not be a complete classical observable algebra.',
 'Refutation of MP7, derivation of a different physical rank, or spatial dimension.',
 ['AUD-001'],[5,5,5,5,1,1,5,4],1,
 'Typed cyclic action and multiplication of observable functions; no desired rank enters the general classification.')

T('SRC-002','Compositional spectral-cut rigidity',
 'Which spectral selections commute exactly with independent composition and refinement?',
 'Tests whether naturality can source a nontrivial rank cut or instead exposes an unavoidable resolution premise.',
 'C04 already derives quadratic-law rigidity; spectral eigengap and penalized-rank rules are not sources.',
 ['C02:RANK_SOURCE_REPORT.md','C04:PROTECT_SOURCE_REPORT.md','C06:results/OPERATOR-REFINE-07_intertwining_moduli.json'],
 'Classifies projector/filter functors rather than repeating the nonlinear-energy Cauchy equation.',
 'NO_GO_TARGET','Spectral filters P(A), including the constant sector, under direct sums and Kronecker-sum embeddings.',
 'State each naturality axiom separately. Derive its scalar functional equation; distinguish exact idempotent filters from approximate filters. Search for countermodels when an axiom is removed, not for a cut producing seven.',
 'Exact classification or a finite counterexample showing which composition axiom forbids a nontrivial cut.',
 'If only trivial filters survive, reject that rank-source class; do not declare all possible source laws impossible.',
 'Unequal factor dimensions and spectra with different multiplicities.',
 'No arbitrary new filter penalty after failure; export the missing resolution or observation datum.',
 'M','A premise-level rank-source obstruction or conditional filter theorem.',
 'That the chosen naturality axioms are themselves laws of nature.',
 ['SRC-001'],[4,5,5,5,2,2,5,4],1,
 'Composition maps and spectral calculus axioms fixed before inspecting the FIN cut.')

T('SRC-003','Minimal operational data selecting a state cone',
 'What extra preparation/effect data remove the abstract-operator simplex ambiguity?',
 'Separates supplied vertex ontology from a genuinely identifiable operational state space.',
 'C05 supplies isospectral Markov-cone ambiguity; full-state tomography is not yet a physical source.',
 ['C05:STATE_DYN_PROX_REPORT.md','C04:DYN_OBS_REPORT.md','AGENTS.md'],
 'Quantifies the minimal stabilizer-breaking observation package, not another abstract-A counterexample.',
 'IDENTIFIABILITY_TARGET','An operator A together with a finite preparation/effect algebra and its residual similarity gauge.',
 'Compute the gauge preserving probabilities and A. Add candidate rank-one preparations/effects one at a time; identify remaining equivalences and require held-out predictions. Distinguish a measured algebra from an axiomatically imposed basis.',
 'A necessary/sufficient finite observation package within a declared class, or indistinguishable alternative cones.',
 'Distinct cones still predict identical admitted records; ontology remains unidentifiable in that experiment.',
 'Relabelings, degenerate effects and a noncirculant operator perturbation.',
 'Stop at the first proved nonidentifiability class; do not fill missing observations with assumed vertex labels.',
 'M','Conditional operational identifiability up to a stated gauge.',
 'Unique fundamental ontology or QW-2191 discharge.',
 ['AUD-001'],[5,4,5,4,2,2,5,4],1,
 'Available preparations/effects and their independent calibration, not a preferred simplex chosen afterward.')

T('SRC-004','Resolution-relative rank without ontology claims',
 'Can an observable error budget determine a useful effective rank across carriers?',
 'Replaces unsourced rank numerology by a conditional, falsifiable approximation theorem.',
 'Eckart–Young conditional truncation and disagreeing selection criteria are old results.',
 ['C01:SOURCE_FOLLOWUP_REPORT.md','C02:RANK_SOURCE_REPORT.md','C00:PHY_CAMPAIGN_REPORT.md'],
 'Links retained rank to held-out nonlinear response errors, not matrix approximation error alone.',
 'THEOREM_TARGET','A family of observable maps and truncations with a specified error tolerance.',
 'Bound discarded-mode effects on responses and phase observables using gaps/derivative bounds. Establish when spectral-norm error is insufficient near folds. Treat tolerance, preparation family and gain window as inputs.',
 'A rank/error tradeoff that predicts required rank on a held-out family without changing its tolerance.',
 'Selected rank changes arbitrarily with unrecorded observables or cannot control the promised physical statistic.',
 'q=18,24 and a gain interval not used to set the tolerance.',
 'If no stable rank window exists, retain an adaptive effective model; never tune tolerance to seven.',
 'M','Effective resolution-dependent rank with certified errors.',
 'An intrinsic rank-seven source or a universal number of physical degrees of freedom.',
 ['SRC-001','SRC-003'],[4,4,4,4,2,2,5,3],2,
 'Observable accuracy and preparations fixed independently of the rank eventually selected.')

T('SRC-005','Admit one genuinely new parent source law',
 'Does any independently motivated parent law explain a held-out FIN operator feature?',
 'Keeps SOURCE-R7-01 open without disguising inverse design as derivation.',
 'Passive connected Laplacians, generic symmetry and prior rank selectors fail; no qualifying parent law is currently exported.',
 ['C01:SOURCE_FOLLOWUP_REPORT.md','C05:CARRIER_SOURCE_REPORT.md','C13:NEXT_ATOMS.md','AGENTS.md'],
 'A finite new-law admission challenge, not an exhaustive replay of rejected source classes.',
 'CONDITIONAL_MODEL','One declared constrained/signed/hidden-variable parent action and its elimination map.',
 'Before unblinding targets, freeze primitive variables, permitted terms and dimensionless parameters. Prove positivity/constraints and derive the effective operator. Expose any embedded projector or target coefficient. If no independent candidate is provided, issue NO_ADMISSIBLE_SOURCE rather than inventing one.',
 'A new typed law passes target-blind admission and predicts an unused carrier observable; source status of its premises stays explicit.',
 'The desired operator or rank is encoded in coefficients, constraints, topology or calibration.',
 'A predeclared q and fine-mode response outside the construction data, with no refit.',
 'At most one new law; class expansion requires new justification and human review.',
 'X','A conditional source candidate or a precise absence-of-source result.',
 'Strict derivation from a freely chosen action; legacy-role transfer.',
 ['SRC-001','SRC-002','SRC-003'],[4,5,5,2,5,3,5,5],2,
 'Only the recovered relation type, independently justified parent primitives and predeclared law grammar; hide rank target and held-out spectrum.')

T('REF-001','Finite-noisy-data continuum-order impossibility',
 'Can finite precision, size and observation time ever identify the asymptotic operator order without a tail class?',
 'Turns the old exact finite-prefix no-go into a quantitative experimental limit.',
 'C06 already gives identical finite shells with different low-k exponents.',
 ['C06:results/OPERATOR-REFINE-03_universal_no_go.json','C06:results/OPERATOR-REFINE-05_fixed_stencil.json','AGENTS.md'],
 'Adds finite-window statistical indistinguishability and crossover-scale obligations; does not append another shell.',
 'NO_GO_TARGET','Positive tail families with bounded observable differences but distinct asymptotic symbols.',
 'Construct delayed/small tails; propagate operator differences to finite-time records with semigroup bounds, then derive Le Cam-type limits. Separate a tail amplitude/onset lower bound from positivity and monotonicity.',
 'An explicit experiment-dependent indistinguishability bound and the minimum additional asymptotic restriction needed.',
 'Uniform exponent identification fails when crossover can be moved beyond every admitted scale.',
 'Two observation times and two carrier sizes not used in the construction.',
 'Stop at a constructive indistinguishability theorem; no brute-force far-shell search.',
 'M','A scoped impossibility theorem or an identifiable restricted-tail experiment.',
 'That finite-range or fractional behavior is physically selected.',
 ['AUD-001'],[5,5,5,5,2,1,5,4],1,
 'Finite record budget, errors and observation windows; no preferred continuum exponent.')

T('REF-002','Dynamic subdivision forces a memory object',
 'Can static subdivision-compatible stiffness and additive mass close dynamically with finitely many edge parameters?',
 'Links refinement to hidden-state realization rather than treating memory as optional.',
 'c(ell)=kappa0/ell and static elimination are known; dynamic Schur memory is known in finite controls.',
 ['C01:SOURCE_FOLLOWUP_REPORT.md','C06:results/OPERATOR-REFINE-06_local_schur_no_go.json','AGENTS.md'],
 'Classifies exact frequency-dependent closure across every subdivision, beyond one C8 example.',
 'NO_GO_TARGET','Two-terminal dynamic Dirichlet-to-Neumann maps and their Schur composition.',
 'Eliminate one interior massive node symbolically; track poles under repeated refinement. Test closure of stiffness-plus-lumped-mass ansatz for all frequencies. Identify cancellations and minimal passive memory order; do not infer hidden physical states from linear realization order.',
 'Exact closure classification or a pole-growth obstruction plus a minimal enlarged response type.',
 'The frequency-independent ansatz cannot reproduce the boundary transfer on an open frequency interval.',
 'Unequal and mixed binary/ternary subdivisions.',
 'Stop the constant-parameter ansatz at the first exact obstruction; move only to the specified memory extension.',
 'M','Refinement requires a response/memory object in the declared inertial model.',
 'A sourced physical inertia, clock or literal microscopic memory ontology.',
 ['AUD-001'],[5,5,5,4,2,1,5,5],1,
 'Static edge law, declared kinetic premise and composition rule, not a desired wave equation.')

T('REF-003','Classify passive two-port refinement semigroups',
 'What is determined by homogeneous segment composition once memory is retained?',
 'Tests whether added naturality reduces operator freedom or only repackages it.',
 'REF-002 identifies the required boundary-response type; static Cauchy rigidity alone is insufficient.',
 ['C01:SOURCE_FOLLOWUP_REPORT.md','C04:PROTECT_SOURCE_REPORT.md','AGENTS.md'],
 'Joint dynamic transfer/positivity classification, not the already proved static resistance equation.',
 'THEOREM_TARGET','Reciprocal passive 2x2 transfer matrices T_ell(z) with T_(a+b)=T_a T_b.',
 'Derive the regular semigroup generator, impose passivity/reciprocity and recover the static limit. Classify which frequency functions remain free. Use a uniform string as a conditional example, not the selected answer.',
 'Necessary/sufficient generator conditions and a precise list of unsourced temporal/material functions.',
 'Multiple passive generators share the static law but predict different dynamic continua.',
 'Irregular meshes and frequencies withheld from fitting.',
 'Do not add regularity or constitutive axioms merely to force the standard wave generator.',
 'L','A conditional uniqueness theorem or sharper dynamic-source nonidentifiability.',
 'Selection of heat/wave/unitary physics or SI speed.',
 ['REF-002'],[5,5,5,3,3,2,5,5],2,
 'Boundary reciprocity, passivity, concatenation and stated regularity before selecting a dispersion target.')

T('REF-004','Circular-planar realization challenge for the full strict operator',
 'Can all six strict shells be a boundary response of a positive circular-planar network?',
 'Tests a concrete local hidden-geometry alternative left open by the one-dimensional chain no-go.',
 'The unlabeled cycle is recovered; pure edge subdivision cannot produce nonnearest couplings.',
 ['C05:CARRIER_SOURCE_REPORT.md','C06:results/OPERATOR-REFINE-06_local_schur_no_go.json'],
 'Tests circular-planar response constraints, not arbitrary graph fitting or another chain subdivision.',
 'NUMERICAL_CERTIFICATE_TARGET','The full strict Laplacian as a candidate boundary response matrix in the recovered cyclic order.',
 'Fix sign/zero-mode conventions; derive or apply the exact circular-minor characterization. Enclose all decisive minors from strict spectral/kernel inputs. If feasible, construct a certified network in the admitted class; if infeasible export one signed minor witness.',
 'A realization certificate or an exact circular-planarity obstruction with boundary-order dependence explicit.',
 'A required circular minor has the forbidden sign; circular-planar passive interpretation fails.',
 'A perturbed strict tuple and a withheld boundary-current experiment; reconstruction is not uniqueness.',
 'Stop on a verified forbidden minor; do not insert nonplanar edges and keep the same claim.',
 'L','Compatibility or incompatibility with a specified hidden passive geometry.',
 'Physical dimension two, unique network, spacetime or an A7 rank source.',
 ['AUD-001'],[5,5,5,4,3,1,5,4],1,
 'Only the full typed W and its intrinsically recovered cyclic order; no target spatial dimension or chosen hidden circuit.')

T('REF-005','Fine-response experiment breaking refinement fibers',
 'Which smallest new observable distinguishes refinements invisible to all coarse records?',
 'Converts nonidentifiability into an executable observation obligation.',
 'Exact coarse intertwining leaves fine rates free; boundary realization may add hidden modes.',
 ['C06:results/OPERATOR-REFINE-07_intertwining_moduli.json','C03:HDIM_SOURCE_REPORT.md','AGENTS.md'],
 'Designs probes for the new response/refinement family, not rediscovery of the old free fiber.',
 'IDENTIFIABILITY_TARGET','Fine-sector preparation/effect maps and resolvent or transient transfer functions.',
 'Compute observable/controllable quotients; minimize added probe rank or frequency information needed to separate the surviving parameters. Provide equivalent-model counterexamples when probes are insufficient.',
 'A finite minimal-probe theorem within a specified realization class and a held-out transfer prediction.',
 'All admitted probes remain constant on the refinement fiber.',
 'An unused refinement level and nonuniform split.',
 'No further coarse-only statistics after exact blindness is proved.',
 'M','Conditional observability of refinement parameters.',
 'Physical existence or unique microscopic interpretation of hidden modes.',
 ['REF-002','REF-004'],[5,4,5,4,2,2,5,4],2,
 'Available probe algebra and cost, fixed before choosing the refinement law.')

T('REF-006','Joint operator/refinement convergence contract',
 'Which response-consistent families have a controlled continuum rather than only a convergent metric?',
 'Prevents transfer of the backbone circle limit to the dense full operator.',
 'Metric subdivision and fixed-stencil convergence are conditional known results.',
 ['C05:CARRIER_SOURCE_REPORT.md','C06:results/OPERATOR-REFINE-05_fixed_stencil.json','C06:results/OPERATOR-REFINE-07_intertwining_moduli.json'],
 'Checks joint response, measure, memory and operator convergence under the newly admitted law.',
 'THEOREM_TARGET','Dirichlet forms, measures and frequency-dependent boundary maps across a declared refinement tower.',
 'Specify topology and time/mesh scaling; prove Mosco/resolvent convergence or exhibit a defect. Keep spatially fractional and temporally nonlocal alternatives distinct. Treat fixed finite rank as an internal truncation, not a spatial differential operator.',
 'Uniform convergence/error estimates on a declared observable/frequency class, or a scoped no-go.',
 'Metric convergence coexists with incompatible operators or uncontrolled memory.',
 'Mixed subdivisions and fine modes outside the development window.',
 'No continuum claim from fitted slopes alone; X-scale proof requires a separate budget.',
 'X','A conditional continuum family with explicit residual source assumptions.',
 'Uniqueness selected by FIN or physical space/time.',
 ['REF-003','REF-005'],[4,4,5,3,5,2,5,4],3,
 'Admitted refinement law and probes, not the desired limiting symbol.')

T('PHA-001','Uniform transverse phase-locking gap',
 'Is qualitative all-orders locking quantitatively stable across amplitudes and carrier size?',
 'A uniform gap is needed before eliminating relative phases or treating a translation coordinate as slow.',
 'C04/C05 already prove relation lattices and equality sets; they do not by themselves give every required uniform gap.',
 ['C04:RESONANCE_DIMENSION_REPORT.md','C05:RESONANCE_CERT_REPORT.md','C03:HDIM_SOURCE_REPORT.md'],
 'Pays quantitative conditioning and amplitude-zero strata, not another alignment/equality proof.',
 'THEOREM_TARGET','Phase Hessians on a lattice quotient with explicit amplitude windows.',
 'Lower-bound selected positive Bessel coefficients and the relation-frame quadratic form. Separate transverse and common-shift eigenvalues; carry the metric. Determine how bounds deteriorate when a mode vanishes.',
 'Uniform bounds on a declared compact nonzero-amplitude family, with exact failure strata.',
 'No uniform gap survives the proposed window or the selected quotient changes at a boundary.',
 'q values not used in discovery and unequal modal amplitudes.',
 'Do not remove weak modes silently or interpret loss of a sufficient bound as loss of all locking.',
 'M','Controlled phase reduction in the specified model family.',
 'Additional spatial dimensions, Goldstone particles or spontaneous protection of all radii.',
 ['AUD-001'],[4,4,4,5,2,2,5,4],1)

T('PHA-002','Finite-q pinning versus finite-N resolution',
 'Which joint q,N regime resolves local phases while washing out Umklapp pinning?',
 'Connects the exact finite carrier with the continuum translation manifold quantitatively.',
 'The first Umklapp order and q/M² collision gate are already known.',
 ['C04:RESONANCE_DIMENSION_REPORT.md','C05:RESONANCE_CERT_REPORT.md','C01:SOURCE_FOLLOWUP_REPORT.md'],
 'Controls the full pinning barrier and noncommuting limits, not only its first Taylor order.',
 'THEOREM_TARGET','The common-shift free-energy barrier Delta_q and the scaled quantity N Delta_q.',
 'Bound alias tails uniformly using complex-strip/Bessel estimates. Compare N Delta_q with transverse fluctuation and phase-collision scales; prove a joint window or incompatible requirements. Fix amplitude/gain hypotheses before optimizing q.',
 'An explicit joint-limit theorem with remainder and a separate pinned regime.',
 'The chosen scaling cannot simultaneously satisfy phase coherence, diffuse geometry and pinning control.',
 'Mixed refinement schedules and q values outside powers of two.',
 'No continuum-symmetry claim from truncating every Umklapp term at a fixed order.',
 'L','Conditional quantitative finite-to-continuum phase correspondence.',
 'A physical continuum selected by FIN or disappearance of finite-q symmetry at fixed q.',
 ['PHA-001'],[5,4,4,4,3,1,5,4],2)

T('PHA-003','Observable mesoscopic phase-symmetry window',
 'Can approximate T5 symmetry coexist with statistically resolvable phases?',
 'Tests a new bridge between entropy-breaking estimates and observation information.',
 'C04 gives O(r³) entropy breaking; C03/C04 establish observable relative phases and nonprotected radii.',
 ['C04:RESONANCE_DIMENSION_REPORT.md','C04:DYN_OBS_REPORT.md','C03:HDIM_SOURCE_REPORT.md'],
 'Combines symmetry-breaking scale and Fisher/readout scale, not a repeat of shrinking-amplitude scans.',
 'THEOREM_TARGET','A declared fixed-radius or annular preparation family with copy scale N, readout count n and amplitude r.',
 'Test N r³→0 against n r²→infinity with exact normalization. The illustrative n=N window is N^-1/2 << r << N^-1/3. Prove or reject uniform likelihood and angular-measure bounds; record preparation, coherence lifetime and radial conditioning separately.',
 'A nonempty, observable conditional window with explicit error and no hidden identification of N and n.',
 'Noise, angular Jacobians, radial fluctuations or short lifetime destroy the simultaneous window.',
 'Nonuniform amplitudes, independent n,N scaling and a held-out phase contrast.',
 'If annular conditioning is essential, keep it PM; do not call the window a spontaneous stable HD phase.',
 'M','A mesoscopic operational symmetry regime or a precise incompatibility theorem.',
 'Four/five physical dimensions, exact nonlinear symmetry or a physical information source.',
 ['PHA-001','SRC-003'],[5,5,4,4,2,1,5,4],2)

T('GEO-001','Positive-weight consistency cone on RNG support',
 'Can scalar conductances on the existing sparse support repair its local anisotropy?',
 'Kills impossible weighting programmes before expensive continuum simulation.',
 'Raw RNG anisotropy and structured-grid metric obstruction already exist.',
 ['C04:PROX04_REPORT.md','C05:STATE_DYN_PROX_REPORT.md'],
 'Tests all positive weights by local moment-cone feasibility, not another unweighted random scout.',
 'NO_GO_TARGET','Weights satisfying drift cancellation and second-moment tensor consistency on fixed incident directions.',
 'Form exact/interval linear feasibility for sum w_e d_e=0 and sum w_e d_e d_e^T=target tensor. Use Farkas dual witnesses. Compare pointwise consistency with weaker homogenization; explicitly supply volume measure if needed.',
 'A positive-weight construction with bounds or a certified separating dual on a declared generic class.',
 'The target tensor lies outside the support cone; pointwise repair is impossible on that support.',
 'Rectangular tori with unseen aspect ratios and iid point populations.',
 'Do not change the graph and still claim the fixed-support weighting problem passed.',
 'M','A feasibility theorem or support-specific obstruction.',
 'Physical dimension or unique isotropic geometry from Haar density alone.',
 ['AUD-001'],[5,5,4,5,2,1,5,4],1,
 'Metric sample and measure supplied before selecting weights; no desired dimension is inferred from the consistency target.')

T('GEO-002','Homogenization of a declared relational population',
 'Can weak continuum behavior survive when pointwise RNG consistency fails?',
 'Keeps the correct probabilistic continuum question separate from an impossible local tensor limit.',
 'C05 proves Haar empirical density alone does not fix the operator; no iid/Haar continuum theorem is accepted.',
 ['C04:PROX04_REPORT.md','C05:STATE_DYN_PROX_REPORT.md','C01:SOURCE_FOLLOWUP_REPORT.md'],
 'Adds a precise stationary/mixing population law and quenched/annealed target instead of extrapolating density plots.',
 'THEOREM_TARGET','Random conductance forms on a specified RNG or minimally enlarged proximity graph.',
 'State sampling and ellipticity/moment assumptions. Seek a corrector/invariance-principle or form-convergence proof. Test whether FIN-induced correlated phase populations satisfy them; do not substitute iid sampling unnoticed.',
 'A conditional limit theorem or a trap/anisotropy counterexample within the declared population class.',
 'Missing mixing, unbounded traps or degeneracy defeats the proposed scaling.',
 'Correlated populations outside the proof class as negative controls; new aspect ratios inside it.',
 'No larger iid simulations after a structural assumption fails; identify the missing population datum.',
 'X','Conditional homogenized response, not pointwise isotropy.',
 'A sourced sampling law or unique physical metric.',
 ['GEO-001','PHA-003'],[4,4,4,3,5,2,5,4],3,
 'Population law and conductance rules fixed without using a desired continuum exponent or dimension.')

T('GEO-003','Reconcile operator geometry with path geometry',
 'Does a response-defined intrinsic metric converge where shortest-path distance fails?',
 'Offers a testable repair of the known grid L1-versus-Euclidean mismatch.',
 'C04 already separates Laplacian and shortest-path limits.',
 ['C04:PROX04_REPORT.md','C05:STATE_DYN_PROX_REPORT.md','AGENTS.md'],
 'Derives a different operational metric and its order-of-limits conditions; does not rename the old graph distance.',
 'THEOREM_TARGET','Energy-measure intrinsic distances and small-time response distances on a convergent graph family.',
 'Compare the intrinsic metric of the limiting quadratic form with finite graph metrics. Analyze mesh→0 before time→0 versus the reverse; fixed finite-graph heat kernels need not have the continuum short-time distance law.',
 'A metric/operator compatibility theorem with explicit limits and measurable response map, or a no-go.',
 'Form convergence alone fails to control distance or the proposed finite-data estimator is nonidentifiable.',
 'Rectangular and mildly irregular grids plus the admitted random family if available.',
 'Stop physical-space language until the observation map and scale regime are paid.',
 'L','A conditional response geometry with a controlled limit.',
 'That changing the metric definition derives spacetime.',
 ['GEO-001','REF-006'],[4,4,4,4,3,2,5,4],3)

T('DYN-001','Causality under state-dependent local rewiring',
 'Can an evolving phase-order graph retain an influence bound without a uniform dwell time?',
 'Addresses the actual state-sourced graph, not a frozen support that assumes away its main difficulty.',
 'Adjacent crossings alter finitely many edges, but Haar minimum gaps scale as M^-2 and uniform dwell is absent.',
 ['C01:SOURCE_FOLLOWUP_REPORT.md','C00:RELATIONAL_CONTINUATION_REPORT.md'],
 'Proves a spacetime influence estimate for the hybrid rewiring law rather than repeating the frozen-graph cone.',
 'THEOREM_TARGET','Time-ordered local generators on a phase-sorted graph with explicit collision/update rules.',
 'Define event supports and pathwise coupling. Bound chronological influence using angular transport and update intensity; examine whether singular conductances at small gaps destroy uniformity. Charge every collision rule or hard-core premise.',
 'A size-uniform conditional bound in a stated metric or an explicit accelerated-influence construction.',
 'Rewiring/global sorting creates uncontrolled remote influence or requires an unrecorded collision regularizer.',
 'Near-collision initial data and mixed update schedules.',
 'No uniform-dwell assumption may be silently reintroduced after its known failure.',
 'L','Conditional causal control for a specified evolving network.',
 'A physical clock, exact Lorentz cone or sourced motion law.',
 ['PHA-002','GEO-001'],[5,5,4,3,3,1,5,4],3)

T('DYN-002','Derive coarse mobility and noise from a declared microscopic update',
 'Which kinetic coefficients follow once one local update law is actually fixed?',
 'Can replace arbitrary coarse mobility by a theorem while retaining the microscopic PM boundary.',
 'Same statics/different kinetics is already proved; exact elimination can generate memory.',
 ['C00:PHY_CAMPAIGN_REPORT.md','C01:SOURCE_FOLLOWUP_REPORT.md','C02:DYNAMICAL_SOURCE_REPORT.md'],
 'Derives the coarse generator and error from microscopic updates, not another catalogue of supplied flows.',
 'CONDITIONAL_MODEL','A fixed reversible local jump law and its projected phase/amplitude generator.',
 'Use generator expansion and averaging on a certified slow manifold. Derive mobility/noise and residual memory; state spectral separation and coherence times. Compare a second attempt-rate law to isolate invariant versus kinetic factors.',
 'A controlled projected generator over a declared time/size window.',
 'No time-scale separation, unresolved radial instability or persistent memory invalidates Markov closure.',
 'An unused attempt-rate law and carrier size.',
 'If memory is non-negligible, retain it; do not improve agreement by fitting a mobility afterward.',
 'L','Coarse coefficients derived conditional on the microscopic update.',
 'Selection of a physical kinetic category or seconds from equilibrium.',
 ['REF-002','PHA-001','DYN-001'],[4,4,5,3,3,2,5,5],4)

T('DYN-003','Derived nonlinear phase potential and drift obstruction',
 'Does the controlled FIN phase reduction support a transport mechanism rather than only static walls?',
 'Separates known linear failure from a genuinely nonlinear, microscopically connected question.',
 'All-orders locking and Umklapp exist; current linear collective class lacks stable localized transport.',
 ['C00:PHY_CAMPAIGN_REPORT.md','C04:RESONANCE_DIMENSION_REPORT.md','C05:RESONANCE_CERT_REPORT.md','AGENTS.md'],
 'Derives a periodic phase potential with remainders and an energy-balance transport test; does not assume sine-Gordon or DNLS.',
 'THEOREM_TARGET','An effective phase action including leading pinning harmonic, higher harmonics and hard-mode corrections.',
 'Project the actual potential using PHA bounds. Prove the unbiased-gradient travelling-front energy identity before searching. Identify whether inertia, drive or unequal well values are necessary and label them explicitly.',
 'A controlled nonlinear reduction and a transport/no-drift theorem in its declared dynamics.',
 'The proposed autonomous moving structure contradicts energy balance or relies on neglected leading terms.',
 'Unbiased/bias-reversed controls and q values outside the fitted reduction.',
 'Stop gradient travelling-wave searches when the exact balance forbids nonzero speed.',
 'L','A conditional nonlinear transport mechanism or obstruction.',
 'Fundamental matter, a sourced pump or an already stable soliton.',
 ['PHA-002','REF-003'],[4,5,4,3,3,2,5,4],4)

T('DYN-004','Persistence and orbital stability in the full coupled model',
 'Does any reduced moving pattern survive radial modes, lattice pinning and perturbations?',
 'A reduced analytic kink is not yet a FIN excitation.',
 'Existing nonlinear DNLS/VK and linear recurrence results are not proofs for this newly derived phase model.',
 ['C00:PHY_CAMPAIGN_REPORT.md','AGENTS.md'],
 'Tests persistence from DYN-003 in the full multi-mode/refined model, rather than repeating older nonlinear kicks.',
 'NUMERICAL_CERTIFICATE_TARGET','A specified travelling/relative-periodic branch, conserved quantities and its linearized operator.',
 'Attempt validated continuation, localization and spectral/orbital stability with radiation and pinning controls. Include finite-energy tails and collision-free validity of the dynamic geometry; use the actual conditional kinetic law.',
 'A complete existence/localization/stability certificate or a bounded counterexample to persistence.',
 'Only tuned transient copying, uncontrolled radiation or nonrobust pinned states survive.',
 'Two larger meshes, perturbed radial coordinates and a non-fitting initial condition.',
 'One branch only; an X campaign requires separate approval and durable checkpoints.',
 'X','A mathematically stable transported pattern in a specified conditional model.',
 'Physical particles, universal solitons, immortality or a collision theory.',
 ['DYN-002','DYN-003','REF-006'],[4,4,4,2,5,3,4,3],4)

T('MEM-001','Type the null before testing memory dimension',
 'Which inclusions hold between the actual finite-block, Hankel and positive-process null classes?',
 'A rank-three block factorization is not automatically a three-state all-horizon HMM.',
 'C09 gives exact rank for explicit families; C13 distinguishes block-latent and single-jump challengers.',
 ['C09:HANKEL_MEMORY_REPORT.md','C10:MEM03_REPORT.md','C13:MEM05_REPORT.md','C13:HANKEL03B_REPORT.md'],
 'Builds certified class-inclusion/separation witnesses for the present design, not another rank-four minor.',
 'IDENTIFIABILITY_TARGET','Rank of the featured 4x4 H, rank/nonnegative rank of the raw 9x9 block table, complete path-Hankel rank, state-/edge-emitting HMMs and reset policies.',
 'Define stationarity, homogeneity, emission convention and reset independence separately. Distinguish rank(T_F Q T_G^T)<=3 from rank(Q)<=3: the featured null can be strictly larger. Prove inclusions/counterexamples and state which null admits each reused bound.',
 'A typed inclusion diagram and explicit legal scope of every reused rank/sample bound.',
 'A claimed hidden-state lower bound uses a challenger outside its declared process class.',
 'Five- and six-jump consistency plus an edge-emitting versus state-emitting control.',
 'No optimizer run until the null class and allowed resets are fixed.',
 'S','Correct finite-record dimension claims and their process limitations.',
 'Unique hidden ontology or complete rank certification from one block.',
 ['AUD-001'],[5,5,5,5,1,1,5,4],1)

T('MEM-002','Certify the explicit closest-known null witness',
 'What rigorous information lower bound follows from the stored MEM-05 challenger alone?',
 'A single verified close null suffices for a lower bound; global optimality is unnecessary.',
 'The stored EM witness has numerical KL near 6.10e-6; exact optimum and byte-identical replay are absent.',
 ['C13:MEM05_REPORT.md','C13:results/OCB-MEM-05_broader_rank3.json'],
 'Rationalizes and verifies one admissible witness with outward information bounds, not more EM starts.',
 'NUMERICAL_CERTIFICATE_TARGET','Rational mixture weights/block laws and interval KL, TV and Hellinger coefficients.',
 'Produce exactly normalized nonnegative factors; reconstruct their rank bound algebraically. Enclose the true alternative and logs, then pay rounding error in the 11-symbol lift. Re-derive necessary counts for the precise error criterion.',
 'An explicit feasible null with certified distance and legal minimax lower bound.',
 'Rounding destroys feasibility or the distance interval cannot support the quoted lower count.',
 'Independent category-to-symbol reconstruction and a perturbed admissible delta.',
 'Stop after one sufficient witness; do not call it the globally nearest process.',
 'M','A rigorous lower bound for the null class containing that witness.',
 'Sufficient sample size, global projection optimality or a physical hidden state.',
 ['MEM-001'],[5,4,4,5,2,1,5,3],1)

T('MEM-003','Convex-hull obstruction to one-reset universal betting',
 'Can a nontrivial one-reset e-factor be fair under every broad rank-three null?',
 'May rule out a whole statistical architecture before implementation.',
 'Determinant batching and checkpoint matrix tests exist; unrestricted one-reset betting was not established.',
 ['C11:HANKEL03_REPORT.md','C13:HANKEL03B_REPORT.md'],
 'Tests the geometry of the null and conditional validity, not another determinant e-process.',
 'NO_GO_TARGET','Nonnegative e(Y) with sup_Q E_Q e<=1 over the specified one-reset null.',
 'Use rank-one point masses, or their full-support limits, to compute the convex hull. Test whether fairness forces e<=1 pointwise. Treat pair-matched constraints separately. Distinguish a test supermartingale, an e-process dominated under each fixed null, and a batch e-value.',
 'An exact no-go or nontrivial construction with the correct conditional/reset quantifiers.',
 'A claimed universal single-reset bet grows only by violating fairness for an admissible null.',
 'Pair-matched and unrestricted nulls; histories with positive null probability.',
 'If the hull obstruction applies, pivot to batches, confidence sets or extra structure, not a tuned betting fraction.',
 'S','A validity architecture constraint and minimum new statistical structure.',
 'Impossibility of all anytime tests for a fixed iid composite null.',
 ['MEM-001'],[5,5,4,5,1,1,5,5],1)

T('MEM-004','All-reset-time variance-adaptive matrix confidence sets',
 'Can direct rank evidence be made valid at every reset time without the worst-case fixed-grid cost?',
 'Extends completed HANKEL-03B to a genuinely stronger inferential object.',
 'C13 controls a frozen nine-checkpoint grid; exact pair matching is an extra premise.',
 ['C13:HANKEL03B_REPORT.md','C10:HANKEL02_REPORT.md','AGENTS.md'],
 'New all-time/unknown-variance control and power analysis, not relabeling finite checkpoints as a continuous e-process.',
 'THEOREM_TARGET','Time-uniform matrix-mean confidence sets intersected with the rank<=3 variety.',
 'Use maximal/stitching or mixture matrix concentration with valid variance bounds. Handle estimated whitening by independent data or joint confidence sets. Prove crossing control at arbitrary reset stopping times; distinguish an e-process from a supermartingale.',
 'Uniform Type-I theorem plus nonasymptotic power bounds under an explicit singular-gap alternative.',
 'Variance/whitening reuse invalidates the bound or improvement assumes exact pair matching not supplied.',
 'Nulls near rank boundaries and alternatives outside the frozen period-two family.',
 'Stop if the new bound cannot improve the certified benchmark in a declared regime; preserve validity result without a practicality claim.',
 'L','An all-reset-time composite test with stated power/cost.',
 'Physical-time validity or universal optimal rank discrimination.',
 ['MEM-001','MEM-003'],[5,4,4,4,3,2,5,4],2)

T('MEM-005','Safe likelihood denominators without an exact optimizer',
 'Can certified upper relaxations of null likelihood make a practical split/batch e-test?',
 'The denominator needs an upper bound, not necessarily an attained global MLE.',
 'C13 correctly rejects local EM maxima as denominator certificates.',
 ['C13:HANKEL03B_REPORT.md','C13:MEM05_REPORT.md','AGENTS.md'],
 'Computes safe data-dependent likelihood upper bounds for the declared class; no extra EM optimism.',
 'THEOREM_TARGET','L_alt(D_test)/U_null(D_test), where U_null >= sup_Q L_Q on the chosen null, including the featured-rank null if that is the tested hypothesis.',
 'Learn numerator on independent/past data. Build certified outer relaxations using simplex constraints, rank-distance information and bounded branch/SDP refinement. Optimizing only raw/nonnegative-rank-three tables does not upper-bound the larger featured-rank null. Include zero cells correctly and prove batch/sequential validity.',
 'A valid nontrivial likelihood e-value with a rigorous denominator bound and held-out power estimate.',
 'A lower/local likelihood replaces an upper bound, or a claimed gain vanishes under the necessary relaxation.',
 'Adversarial null tables, sparse observed counts and a second alias family.',
 'Bound global-search effort; a valid but powerless unconstrained bound is a stop result, not a practical solution.',
 'L','Conditional finite-sample testing without assuming exact MLE availability.',
 'Global EM optimality, arbitrary online data reuse or numerical e-values as proofs.',
 ['MEM-001','MEM-002','MEM-003'],[5,5,4,4,3,1,5,5],2)

T('MEM-006','Positive process extension of finite block models',
 'Which stored block-null tables extend to the intended positive all-horizon process with a bounded state count?',
 'Links statistical rank witnesses to a legitimate dynamical realization class.',
 'Finite block rank and all-horizon realization are explicitly separated in C13.',
 ['C13:MEM05_REPORT.md','C09:HANKEL_MEMORY_REPORT.md','AGENTS.md'],
 'Pays positivity and cross-horizon consistency, beyond ordinary linear realization or one factorized table.',
 'THEOREM_TARGET','Positive state-/edge-emitting automata extending prescribed four-jump probabilities.',
 'Form exact normalization and consistency equations across cuts; construct an extension or a separating witness. Distinguish time-inhomogeneous reset models from stationary homogeneous HMMs. Verify more than the central 2|2 factorization.',
 'An explicit positive realization with a proved state bound, or infeasibility in a specified class.',
 'The central rank certificate cannot be extended with the claimed hidden-state semantics.',
 'Unused longer words and a second reset distribution.',
 'No global ontology inference from a successful finite extension; stop at the declared state-budget cap.',
 'L','Legitimate class membership or a positive-realization obstruction.',
 'Equality of ordinary rank and nonnegative hidden-state dimension in general.',
 ['MEM-001','MEM-002'],[5,5,4,4,3,1,5,5],2)

T('MEM-007','Tight horizon obstruction under explicit reset and stationarity rules',
 'How much of the log(H)-to-H gap survives after the hidden-process assumptions are fixed?',
 'Avoids paying for the wrong adversarial memory class.',
 'C10 proves a logarithmic family lower bound and linear generic witness upper bound, not a query minimax theorem.',
 ['C10:MEM03_REPORT.md','C08:MEMORY_ALIAS_REPORT.md','C09:HANKEL_MEMORY_REPORT.md'],
 'Separates resettable nonstationary clocks from stationary ergodic aliases and seeks a sharper worst-case theorem.',
 'NO_GO_TARGET','H-state hidden processes constrained by a declared initialization/stationarity class.',
 'Test a delayed H-state reset clock for the unrestricted class; it must not be used as a stationary counterexample. For the stationary class seek a positive adversarial construction or sharper upper bound. State any mixing/gap restrictions.',
 'A corrected class-dependent horizon lower/upper bound with explicit process witnesses.',
 'The previous claimed lower bound relies on an initialization forbidden by the proposed experiment.',
 'Unknown versus controlled hidden reset and an unseen H.',
 'Stop when assumptions change the class; no exponential word enumeration presented as a universal query lower bound.',
 'M','Scoped horizon complexity, not a physical memory capacity.',
 'Uniform exclusion of unbounded memory by a finite record.',
 ['MEM-001'],[5,5,4,5,2,1,5,4],1)

T('MEM-008','Cost-aware adaptive path experiment design',
 'Which resets, path lengths and contrasts maximize worst-case information per admitted cost?',
 'Memory detection and full dimension certification need different experiments.',
 'C09/C10 already separate easy lag detection from expensive full-rank certification.',
 ['C09:ADAPTIVE_MEMORY_REPORT.md','C10:MEM03_REPORT.md','C13:MEM05_REPORT.md'],
 'Optimizes a precise action/query model against shared composite alternatives, not more exhaustive words.',
 'OPERATIONAL_PROTOCOL','Adaptive controls over reset distributions, horizons and observable contrasts with fixed reset/jump costs.',
 'Specify whether the adversary shares parameters across actions. Derive a minimax information criterion and valid predictable allocation. Check loss from three-category compression against hidden alternatives inside discarded categories.',
 'A frozen policy with valid error control and a certified or bounded information advantage over a fixed four-jump design.',
 'Apparent advantage relies on known alias structure or unpriced long paths/resets.',
 'A non-periodic HMM, detector-memory control and a withheld within-category perturbation.',
 'No adaptive feature search on the scoring data without a proved selection correction.',
 'L','A conditional experimental design and its cost/error tradeoff.',
 'A universal optimal protocol or laboratory feasibility without apparatus costs.',
 ['MEM-004','MEM-005','MEM-006','MEM-007'],[5,4,4,3,3,2,5,4],3)

T('MEM-009','Honest lower/upper power frontier',
 'What sample-cost bracket is actually certified for broad rank exclusion?',
 'Closes the semantic gap between necessary resets, population design points and sufficient power.',
 'C13 provides a close numerical null and Type-I-valid checkpoints but no minimax-optimal test.',
 ['C13:HANKEL03B_REPORT.md','C13:MEM05_REPORT.md'],
 'Combines certified necessary and sufficient counts for the same hypotheses/errors; does not compare incompatible nulls.',
 'IDENTIFIABILITY_TARGET','A testing risk surface indexed by separation, reset cost, nuisance and null class.',
 'Use MEM-002 lower bounds and proved power of MEM-004/005. For a matrix test pay both the null threshold and alternative deviation. Prove no uniform finite power as separation tends to zero; distinguish Bayes from two-sided error criteria.',
 'A reproducible valid bracket or an explicit gap too wide for operational use.',
 'Claims of practicality rest only on r<population sigma or expected log evidence crossing a threshold.',
 'At least two deltas and a non-frozen rank-four alternative.',
 'If the required cost exceeds the admitted platform budget, stop the rank assay rather than weaken its null silently.',
 'M','An error-criterion-matched cost frontier.',
 'Measured power or a globally optimal minimax constant without proof.',
 ['MEM-002','MEM-004','MEM-005'],[5,5,4,5,2,1,5,4],3)

T('OP-001','Wave response as a complete probability experiment',
 'Which complete observation model licenses treating squared wave displacement as event probabilities?',
 'The existing Chernoff attempt bound needs a probability/readout premise, not only a response amplitude.',
 'CHANNEL-03/05 use zero-velocity squared wave response and retain every attempt; apparatus interpretation remains conditional.',
 ['C10:CHANNEL03_REPORT.md','C11:CHANNEL04_REPORT.md','C13:CHANNEL05_REPORT.md'],
 'Pays the complete-outcome/dilation contract; does not repeat leading time powers.',
 'THEOREM_TARGET','C(t)=cos(t sqrt(A)), its off-diagonal squares, return channel and missing-norm outcome.',
 'Check subprobability normalization for PSD A. Construct the complementary outcome or conservative doubled-state dilation and distinguish raw intensity, normalized displacement and a calibrated Bernoulli readout. Re-derive the frozen bounds for the chosen record convention.',
 'One complete probability model with all outcomes and readout premises explicit, or a protocol-scope correction.',
 'The proposed event probabilities require undocumented renormalization or are not the outcomes used by the concentration bound.',
 'A two-eigenvalue control and a second initial preparation.',
 'Do not claim a laboratory probability rule from mathematical norm completion.',
 'S','A mathematically consistent conditional wave-readout experiment.',
 'Born-rule derivation, quantum dynamics or empirical detector behavior.',
 ['AUD-001'],[5,5,5,5,1,1,5,4],1)

T('OP-002','Clock-map-free escape–profile geometry',
 'Can destination shape as a function of escape distinguish channels without a locally linear control clock?',
 'Potentially removes one strong calibration premise of CHANNEL-04/05.',
 'Leading destination profiles and escape powers are known; existing finite protocols assume bounded control-ratio distortion.',
 ['C10:CHANNEL03_REPORT.md','C11:CHANNEL04_REPORT.md','C13:CHANNEL05_REPORT.md'],
 'Eliminates the latent time parameter between two observables; no repeat of slopes at proportional controls.',
 'THEOREM_TARGET','S=sum_(j!=i) p_ji and r_j=p_ji/S, viewed as an unparameterized curve.',
 'Derive strict-operator expansions. Candidate distinction: unitary r-r0=O(S), while zero-velocity wave r-r0=B sqrt(S)+O(S), with B nonzero unless an exceptional spectral relation holds. Prove the exception classification, finite-S remainder, calibration sensitivity and sampling cost. Heat has a different leading profile for unequal weights.',
 'A finite observable-window separation invariant under admissible monotone time reparameterization, or an exact curve-equivalence counterexample.',
 'The coefficient vanishes in the claimed class, curves are observationally equivalent, or calibration overwhelms the effect.',
 'Nonlinear control clocks, unseen spectral perturbations and the complete-graph exceptional control.',
 'If asymptotic separation has no useful finite calibrated window, report a theorem-only outcome; no practicality claim.',
 'M','Conditional clock-map-free channel discrimination from joint records.',
 'A physical clock, physical wave ontology, zero-calibration inference or a smaller sample count without proof.',
 ['OP-001'],[5,5,5,5,2,1,5,5],2)

T('OP-003','Unknown carrier versus structured detector support',
 'Can carrier topology and calibration structure be identified jointly without assuming the cycle being tested?',
 'The CAL-05 neighbor-confusion premise can become circular if inferred from the same carrier claim.',
 'Known inverse calibration and support-preserving error factors are already proved.',
 ['C08:CALIBRATION_CHANNEL_REPORT.md','C13:CAL05_REPORT.md','C07:OPERATIONAL_CARRIER_REPORT.md'],
 'Tests joint graph/calibration equivalence classes, not a further numerical radius improvement with a known cycle.',
 'IDENTIFIABILITY_TARGET','Unlabeled transition laws, preparation/effect maps and unknown support-preserving confusion patterns.',
 'Separate independently calibrated support from graph hypotheses. Search exact alternative graph/detector factorizations. Determine the minimum intervention or calibration record that breaks them, keeping label permutations as gauge.',
 'A joint identifiability theorem or an explicit calibration-only topological alias.',
 'The support assumption presupposes the carrier conclusion or independent calibration cannot distinguish alternative graphs.',
 'A noncyclic carrier and relabeled apparatus channels.',
 'No same-data calibration that selects the desired cycle after inspection.',
 'M','A noncircular conditional carrier protocol or a necessary apparatus obligation.',
 'Physical adjacency solely from largest observed rates.',
 ['SRC-003','AUD-001'],[5,5,4,4,2,1,5,5],2)

T('OP-004','Detector memory and postselection rank aliases',
 'How much observed predictive rank can be attributed to the detector rather than FIN dynamics?',
 'A system-memory claim is invalid if readout memory or conditioning can supply the same rank.',
 'C08/C13 calibration is primarily memoryless; memory aliases of the visible process are known.',
 ['C08:CALIBRATION_CHANNEL_REPORT.md','C13:MEM05_REPORT.md','C13:CAL05_REPORT.md','AGENTS.md'],
 'Joins temporal calibration with positive realization and raw-attempt bookkeeping.',
 'IDENTIFIABILITY_TARGET','A system process composed with a bounded detector transducer, including no-click records.',
 'Prove rank nonincrease/invariance under specified memoryless linear readout maps. Track what changes under finite-state detector memory and length-dependent postselection normalization. Bound system/detector ambiguity and test reset failures; do not assume iid blocks when the detector state persists.',
 'A class-dependent rank attribution bound or explicit indistinguishable system/detector allocations.',
 'The observed extra rank is fully explained by admitted calibration dynamics or conditioning.',
 'An iid system with a two-state detector and a memoryful system with memoryless readout.',
 'If detector memory is unbounded, stop unique system-rank attribution and export the required independent reset/calibration gate.',
 'M','Predictive-dimension statements robust to a declared detector class.',
 'Microscopic system ontology from visible Hankel rank.',
 ['MEM-001','MEM-006','OP-003'],[5,5,5,4,2,1,5,5],3)

T('OP-005','One joint error ledger for carrier, channel and memory',
 'Can the successive operational claims share data without invalidating their error guarantees?',
 'Separate valid protocols do not automatically compose into a valid adaptive discovery pipeline.',
 'C13 has separate rank, calibration and channel designs with different assumptions.',
 ['C13:HANKEL03B_REPORT.md','C13:CAL05_REPORT.md','C13:CHANNEL05_REPORT.md','AGENTS.md'],
 'Proves sequential composition across calibration, feature selection and claims, beyond a two-budget union bound.',
 'OPERATIONAL_PROTOCOL','A frozen protocol graph with shared nuisance variables, filtration and error budget.',
 'Specify training/calibration/scoring splits or valid predictable reuse. Couple the nuisance sets for topology, readout and rank. Carry conditional failure probabilities and abstention through the graph; reject multiplication of dependent e-values without a theorem.',
 'An end-to-end error guarantee with every attempted/no-click/reset record retained.',
 'Data-dependent selection or reused calibration makes a claimed conditional guarantee false.',
 'Adversarial ordering, stopping and calibration drift within the declared model.',
 'No empirical execution until the joint ledger and external calibration pass.',
 'M','A coherent conditional operational workflow.',
 'Independent custody, actual calibration or experimental success from a software schema.',
 ['MEM-008','MEM-009','OP-002','OP-004'],[4,4,4,4,2,2,5,4],3)

T('EMP-001','Platform readiness and information-budget gate',
 'Is any supplied real platform capable of the required preparations, resets and calibrated records?',
 'Prevents billion-reset mathematical designs becoming unsupported experimental recommendations.',
 'EXTERNAL-OCB-01 is already gated; no apparatus or raw physical records are supplied here.',
 ['C13:CHANNEL05_REPORT.md','C13:NEXT_ATOMS.md','fin_physics_review/MASTER_INTAKE_20260923.md'],
 'Evaluates readiness for the new joint protocol and its certified cost frontier; does not reannounce an experiment.',
 'EMPIRICAL_GATE','A platform capability/calibration/custody record and an admissible experiment budget.',
 'Request platform facts only when external execution is authorized. Match reset fidelity, detector memory, efficiencies, control ranges and costs to OP-005/MEM-009. Without real inputs emit NOT_READY with exact missing records.',
 'Independent records satisfy all required gates, or a precise blocked/readiness verdict is issued.',
 'Calibration is circular, resets fail the model, or guaranteed information exceeds the actual budget.',
 'An independent calibration session and held-out negative-control run.',
 'No purchases, contacts, uploads or simulated replacement for missing nature data.',
 'S','Readiness or nonreadiness of a named conditional protocol.',
 'Empirical validation or FIN ontology from apparatus capability.',
 ['OP-005'],[4,5,5,2,2,2,4,4],3)

T('EMP-002','Preregister a discriminating pilot, not a full rank campaign by default',
 'Which lowest-cost real observation would eliminate the largest admitted model class?',
 'Carrier confirmation, channel discrimination and full memory rank have very different value/cost.',
 'A platform may be admitted only through EMP-001; otherwise this remains a parameterized design.',
 ['C07:OPERATIONAL_CARRIER_REPORT.md','C13:CHANNEL05_REPORT.md','C13:MEM05_REPORT.md'],
 'Chooses among the new joint observable options using certified information, rather than automatically executing the old frozen count.',
 'OPERATIONAL_PROTOCOL','One preregistered observable/control allocation and competing system-plus-detector models.',
 'Choose carrier, escape–profile or memory assay by the proved cost frontier. Freeze effect size, nuisance bounds, abstention and maximum cost. Include the closest admitted non-FIN or detector-only alternative and a held-out prediction.',
 'A no-fit pilot with feasible error/power bounds for the admitted platform; else an explicit no-feasible-pilot verdict.',
 'Every proposed observation is observationally aliased or requires post-hoc fit freedom.',
 'Independent preparations and scoring data not used for calibration or protocol selection.',
 'Stop or redesign under a new protocol ID after failure; do not weaken the null while keeping the old success label.',
 'M','A preregistered future experiment; EV only after separately authorized physical data.',
 'A foundation-of-physics confirmation from a synthetic pilot.',
 ['EMP-001'],[5,5,5,2,2,1,5,4],3)

T('GATE-001','New operational structure before reopening quantum claims',
 'Has a new observation/composition object actually escaped the previously refuted classical or ensemble-inconsistent class?',
 'Prevents memory complexity and complex notation being promoted to QM.',
 'PHY-025/026 and older ensemble-affinity/feedback obstructions remain in force.',
 ['C00:PHY_CAMPAIGN_REPORT.md','C05:STATE_DYN_PROX_REPORT.md','AGENTS.md'],
 'Dormant admission gate for genuinely new outcomes, not another execution of the old CHSH/simplex test.',
 'SPECULATIVE_ONLY','A newly supplied state/effect/composition algebra with operational independence assumptions.',
 'Only if SRC-003/OP-004 exports new structure, test affine preparation consistency, classical simulation with the admitted memory class, noncommuting instruments and a sourced composite rule. Unlimited classical memory cannot be excluded by a finite transcript without restrictions.',
 'A precisely defined new quantum-bridge problem passing all prerequisite gates, or STOP.',
 'The result is imported QM, classical memory or an ensemble-dependent law violating its claimed operational assumptions.',
 'Equivalent mixed preparations and independent-setting controls.',
 'Default is STOP—DO NOT PROMOTE; no Standard Model or quantum derivation task is authorized.',
 'S','Admission or refusal of a later quantum research lane.',
 'QM, Born rule or physical nonlocality from the current core.',
 ['SRC-003','OP-004'],[3,4,4,1,2,4,3,2],5)

T('GATE-002','Common action and universal-probe gate before gravity',
 'Does the new dynamic graph support reciprocal backreaction and a common operational geometry?',
 'State-dependent distance alone is not gravity.',
 'The prior gravity gate is closed; new DYN/REF results would be additional conditional objects.',
 ['C00:PHY_CAMPAIGN_REPORT.md','C01:SOURCE_FOLLOWUP_REPORT.md','AGENTS.md'],
 'Dormant consistency test for a genuinely new coupled action, not re-fitting Einstein equations.',
 'SPECULATIVE_ONLY','A joint field/graph action, its conservation identities and at least two probe responses.',
 'Require one variational/balance source for both matter and graph response. Test reciprocity, conservation, causal propagation and probe universality under the same calibration. Expose independent kinetic ratios rather than identifying all speeds with c.',
 'All necessary prerequisites are explicitly met, or a typed missing-atom/STOP result.',
 'No backreaction, arbitrary probe-specific metrics or inconsistent energy exchange.',
 'Two distinct probe species and one withheld refinement.',
 'No gravity language unless all gates pass; no GR coefficient fitting or dimensional G target.',
 'S','Admission or refusal of a later gravity bridge.',
 'GR, equivalence principle or spacetime from graph deformation.',
 ['REF-006','GEO-003','DYN-004'],[3,4,5,1,2,4,3,2],5)

T('SYN-001','Adversarial proof and scope consolidation',
 'Which newly completed claims survive independent challenge in their actual domains?',
 'A large task queue needs a fail-closed integration boundary.',
 'All attempted task artifacts, including failures and gated skips; existing master sources remain immutable.',
 ['fin_physics_review/MASTER_INTAKE_20260923.md','AGENTS.md'],
 'Audits new certificates and their changed premises, not another master archive deduplication.',
 'NUMERICAL_CERTIFICATE_TARGET','New proof DAG, exact inputs, numerical enclosures and claim ladders.',
 'Check hashes, signs, null-class inclusion, lower-versus-upper bound direction and no-go scope. Challenge new results with their declared countermodels. Label same-code versus independent implementation replay; do not launch every old producer again.',
 'Each promoted claim has a complete reproducible dependency path and no unrecorded PM or numerical substitution.',
 'A missing premise or invalid certificate remains on the promotion path.',
 'Corrupted boundaries, changed detector class, stale inputs and deliberate physical-label mutations.',
 'Quarantine only dependent claims and identify the minimal repair; no fabricated global PASS.',
 'M','A review-ready set of scoped new results.',
 'Physical evidence, independent custody or blanket acceptance of execution-complete tasks.',
 [],[4,5,4,5,2,2,5,3],6)

T('SYN-002','Re-optimize the programme after outcomes, then hand off',
 'Which next atom now has highest information gain, including the possibility of stopping?',
 'Avoids sunk-cost continuation and endless boundary polishing.',
 'SYN-001 and all attempted/gated task dispositions; score sensitivity and kill ledger.',
 ['C13:NEXT_ATOMS.md','fin_physics_review/MASTER_INTAKE_20260923.md','AGENTS.md'],
 'Uses genuinely new outcomes to change the research order; the present source and OCB queues are not reopened by name.',
 'OPERATIONAL_PROTOCOL','A versioned source-obligation graph and decision ledger.',
 'Update the eight priority dimensions, document demotions and killed branches, and recommend at most three new atoms. Export portable inputs, scripts, theorem scopes and an AGENTS proposal only; preserve physical gates.',
 'A supervisor can distinguish new theorems, conditional models, numerical evidence and external blockers without the conversation.',
 'The handoff hides failed directions or recommends the same closed search without a new object.',
 'A reviewer reconstructs the first next decision using only the handoff.',
 'Stop after handoff; leave no background workers or automatic downstream campaign.',
 'S','A justified next decision or a scoped research stop.',
 'Completion of a physical theory from terminal task dispositions.',
 ['SYN-001'],[4,5,5,5,1,2,5,4],6)
