#!/usr/bin/env python3
"""Six rounds: kinetic clock source, moment closure and time-arrow audit."""
import hashlib,json,math,numpy as np
from fin_st2172_st2261_common import ROOT,strict_A_W,write_packet,write_round
def emit(lo,names,rows):
 d={}
 for i,(s,b,p) in enumerate(rows):k=lo+i;d[f'ST{k}']=write_packet(k,names[i],s,b,p)
 write_round(lo,lo+14,d)
def r1():
 names=['RateScalingOrbit','StationaryInvariance','DetailedBalanceInvariance','JumpChainInvariance','UntimedPathInvariance','WaitingTimeScaling','EquilibriumRecordNoGo','CountRecordNoGo','TimestampRequirement','InternalTimeParameter','PhysicalSecondsBoundary','ScaleTorsor','IdentifiabilityTheorem','RoundOneVerdict','RoundOneRecommendation']
 rows=[('Defined','Q_c=cQ, c>0.',{}),('Proven','pi Q=0 iff pi cQ=0.',{}),('Proven','Rate ratios unchanged.',{}),('Proven','P_xy=Q_xy/(-Q_xx) unchanged.',{}),('Proven','Ordered visited states have same law.',{}),('Proven','Holding times divide by c.',{}),('No-go','Stationary statistics contain no c.',{}),('No-go','Jump counts without calibrated duration contain no c.',{}),('Proven necessity','Calibrated waiting times or duration required.',{}),('Boundary','A dimensionless t can parameterize but not calibrate.',{}),('No-go','No seconds from dimensionless c.',{}),('Proven','Generators with same jump chain form R+ torsor.',{}),('Proven theorem','Every timestamp-free operational invariant factors through Q modulo positive scaling.',{}),('Round verdict','Clock magnitude is unidentifiable without a calibrated temporal record.',{}),('Recommendation','Test A-moment matching.',{})];emit(2712,names,rows)
def r2():
 _,A=strict_A_W();names=['SpinObservable','GeneratorAction','TernaryEnergyDifference','NonlinearHierarchy','FirstMomentNonclosure','PairMomentCoupling','ThetaZeroLimit','ThetaZeroSpectrum','StrictASpectrum','Mismatch','LinearizationBoundary','ClosureApproximation','AActivityTuning','RoundTwoVerdict','RoundTwoRecommendation']
 rows=[('Defined','Coordinate x_i on cube.',{}),('Proven','Q x_i=-2 x_i r_i(x).',{}),('Proven','DeltaE_i=2 theta x_i sum_(f contains i) tau_f product(other two).',{}),('Proven','Qx_i contains higher Walsh characters.',{}),('No-go','E[x] dynamics not closed on first moments.',{}),('Proven','Hierarchy couples first, pair, triangle and higher moments.',{}),('Proven','At theta=0 heatbath flips have rate 1/2.',{}),('Proven','Then Qx_i=-x_i and all degree-one modes have eigenvalue -1.',{}),('Computed','A has nondegenerate distance spectrum.',{'gap':float(np.linalg.eigvalsh(A)[1]),'lambda_max':float(np.linalg.eigvalsh(A)[-1])}),('Refuted','Identity degree-one decay cannot equal nontrivial A.',{'exact_match':False}),('Boundary','Small-theta closure needs truncation/state assumption.',{}),('Conditional','Moment closures are model approximations.',{}),('Underdetermined','Configuration-dependent activities can fit targets but add functions.',{}),('Round verdict','The ternary Markov law does not project exactly to FIN vertex heat dynamics.',{}),('Recommendation','Audit spectral clock conventions.',{})];emit(2727,names,rows)
def r3():
 _,A=strict_A_W();ev=np.linalg.eigvalsh(A);gap=float(ev[1]);names=['GapClockCandidate','GapNormalization','MaxEigenClock','TraceClock','MultipleSpectralClocks','ScalingCovariance','DimensionlessClock','ChannelClockMismatch','WaveClock','UnitaryHeatClock','NormalizationAxiom','RemovalAudit','StrictClockGate','RoundThreeVerdict','RoundThreeRecommendation']
 rows=[('Constructed','Set c=gap(A).',{'gap':gap}),('Conditional','Makes one relaxation mode unit rate.',{}),('Alternative','Set c=lambda_max(A).',{'lambda_max':float(ev[-1])}),('Alternative','Use trace/dimension.',{'trace_density':float(np.trace(A)/12)}),('Proven nonuniqueness','All are spectral/natural and disagree.',{}),('Proven','A->aA scales candidates but no SI anchor.',{}),('Boundary','Provides an internal dimensionless convention only.',{}),('Proven','Unitary/heat refinement clocks scale differently from wave.',{}),('Boundary','Wave uses sqrt eigenvalues.',{}),('Proven','Shared A organizes but does not identify operational clocks.',{}),('Conditional','Choosing one spectral normalization is an axiom.',{}),('Proven','Removing it restores multiple clocks.',{}),('Gate fail','No strict principle selects normalization.',{'strict_clock':False}),('Round verdict','A can define relative clocks, not a unique or dimensional time.',{}),('Recommendation','Test circulation orientation.',{})];emit(2742,names,rows)
def r4():
 names=['CirculationCandidate','C12Average','D12Reflection','D12AverageCancellation','OddRepresentation','SignPair','StationaryStateBlindness','EntropyBlindness','InitialCondition','BoundaryDrive','ChiralState','SelectorNoGo','ArrowGate','RoundFourVerdict','RoundFourRecommendation']
 rows=[('Constructed','Oriented configuration cycles.',{}),('Conditional','Rotation averaging preserves an oriented current.',{}),('Proven','Reflection reverses current.',{}),('Proven no-go','Full D12 average of a reflection-odd current is zero.',{}),('Proven','Current belongs to sign/odd sector.',{}),('Proven','J and -J equally admissible.',{}),('Proven','Same pi.',{}),('Proven','Same entropy-production magnitude.',{}),('Boundary','A prepared chiral state can choose transient sign.',{}),('Boundary','A driven reservoir can choose sign.',{}),('Receiver','State current detects supplied sign.',{}),('No-go','No strict odd resource exported.',{'QW2191':False}),('Gate fail','D12-compatible nonzero arrow needs symmetry breaking.',{}),('Round verdict','Circulation is a valid arrow carrier but not a strict arrow source.',{}),('Recommendation','Derive minimal timestamp experiment.',{})];emit(2757,names,rows)
def r5():
 c=2.0;n=100;names=['HoldingTimeLaw','ExposureVariable','ClockLikelihood','ClockMLE','ClockFisher','CramerRao','SyntheticPrecision','TimestampCalibration','StateSequenceInsufficiency','DurationRequirement','IndependentCustody','OAFields','DimensionConversion','RoundFiveVerdict','RoundFiveRecommendation']
 rows=[('Proven','At state x, T~Exp(c lambda_x).',{}),('Defined','u=lambda_x T has Exp(c).',{}),('Proven','logL=n log c-c sum u.',{}),('Proven','c_hat=n/sum u.',{}),('Proven','I_n(c)=n/c^2.',{'n':n,'c':c,'Fisher':n/c**2}),('Proven','Var>=c^2/n.',{'relative_sd_lower':1/math.sqrt(n)}),('Conditional','100 waits permit ~10 percent relative one-sigma scale.',{}),('Boundary','T requires calibrated external clock ticks.',{}),('No-go','Visited states alone give zero scale information.',{}),('Proven','Counts require known calibrated observation duration.',{}),('Boundary','Hashed timestamps do not create independent custody.',{}),('Executable spec','run,state_before,state_after,wait,timestamp,config,clock_calibration.',{'fields':7}),('No-go','Conversion to seconds remains CA.',{}),('Round verdict','Clock rate is statistically identifiable only after the missing calibrated time record is supplied.',{}),('Recommendation','Synthesize.',{})];emit(2772,names,rows)
def r6():
 gate=ROOT/'FIN_ST2787_ST2801_ClockSourceGate.json';g={'rows':[{'name':n,'pass':v} for n,v in [('rate-scale torsor theorem',True),('moment nonclosure theorem',True),('clock Fisher theorem',True),('strict spectral normalization',False),('strict timestamp calibration',False),('strict circulation polarity',False),('A-to-Q moment intertwiner',False),('physical seconds',False),('OA custody',False),('laboratory evidence',False)]]};gate.write_text(json.dumps(g,indent=2)+'\n')
 names=['ScaleTheorem','MomentTheorem','SpectralClockNoGo','ArrowNoGo','OperationalTheorem','PhysicalBoundary','Gate','GateScore','ProvenLedger','ConditionalLedger','RefutedLedger','StopRules','HighestValueNext','FinalInterpretation','CycleTrigger']
 rows=[('Proven','Q scaling invisible without time.',{}),('Proven','Ternary dynamics does not close to A moments.',{}),('Proven','Several natural spectral clocks.',{}),('Proven','Full D12 cancels odd circulation.',{}),('Proven','Timestamps identify c with Fisher n/c2.',{}),('No-go','Calibration/seconds absent.',{}),('Constructed','Ten rows.',{'file':gate.name}),('Result','Three mathematical passes.',{'passes':3,'rows':10}),('Ledger','Scale, hierarchy, Fisher.',{}),('Ledger','Selected spectral clock and OA.',{}),('Ledger','Strict dimensional time arrow.',{}),('Stop','Do not call eigenfrequency seconds or entropy arrow polarity.',{}),('Recommendation','Only an operational calibration event or strict scale-charged clock source can change verdict.',{}),('Final verdict','FIN supplies dimensionless temporal parameters and arrow carriers, not physical time calibration or arrow selection.',{'fundamental':False}),('Cycle complete','Release 11.14.',{'programs':90,'rounds':6,'range':'ST2712-ST2801','strict_ToE_closure':False,'gate_sha256':hashlib.sha256(gate.read_bytes()).hexdigest()})];emit(2787,names,rows)
def main():r1();r2();r3();r4();r5();r6()
if __name__=='__main__':main()
