#!/usr/bin/env python3
"""Twenty adaptive rounds: exhaustive principle audit for selecting a FIN tail."""
import hashlib,json,math,numpy as np
from fin_st2172_st2261_common import ROOT,write_packet,write_round
def emit(lo,rows):
 assert len(rows)==15;d={}
 for i,(name,status,boundary,payload) in enumerate(rows):
  k=lo+i;d[f'ST{k}']=write_packet(k,name,status,boundary,payload)
 write_round(lo,lo+14,d)
def E(name,status='Proven',boundary='',**payload):return(name,status,boundary,payload)
w=np.array([math.cos(.18575*d+.1625)/(1+d**1.8) for d in range(1,7)]);C0=sum((i+1)**2*w[i] for i in range(6));target=2**-1.8
def r1():emit(4047,[E('TailCone'),E('ExactFiniteMatch'),E('PositiveTail'),E('SecondMoment'),E('QuadraticOrder'),E('CFormula',C0=C0),E('InfiniteDimension'),E('Convexity'),E('ZeroTail'),E('SingleAtomRays'),E('SpeedRange'),E('SelectionProblem'),E('NoCurrentFunctional','No-go'),E('RoundVerdict','Round verdict'),E('Next','Recommendation')])
def r2():emit(4062,[E('QuadraticPenalty'),E('PositiveWeights'),E('StrictConvexity'),E('UniqueZeroMinimizer'),E('WeightedL2'),E('SobolevTailNorm'),E('AllSelectTruncation'),E('PenaltyScaleIrrelevance'),E('PhysicalJustification','Missing'),E('NoSourceTerm'),E('AddSourceChangesTail'),E('AxiomRemoval'),E('MinimumNormConditional','Conditional'),E('RoundVerdict','Round verdict'),E('Next','Recommendation')])
def r3():emit(4077,[E('FixedMassM','Assumption'),E('MomentObjective'),E('MinimumAtD7'),E('UniqueAtom'),E('CoefficientC0Plus49M'),E('MaximumUnbounded'),E('FixedMeanDistance','Assumption'),E('TwoMomentProblem'),E('MultipleMeasures'),E('MassNotStrict','No-go'),E('MeanNotStrict','No-go'),E('MZeroReturnsTruncation'),E('ConstraintDependence'),E('RoundVerdict','Round verdict'),E('Next','Recommendation')])
def r4():emit(4092,[E('FirstDifferencePenalty'),E('BoundaryJump'),E('ZeroTailCost'),E('SmoothTailCompetitor'),E('LambdaTradeoff'),E('SecondDifferencePenalty'),E('SplineLikeTail'),E('NonnegativeConstraint'),E('InfiniteSupportPossible'),E('PenaltyOrderFreedom'),E('BoundaryConditionFreedom'),E('DifferentMinimizers'),E('SmoothnessNoUniqueness','No-go'),E('RoundVerdict','Round verdict'),E('Next','Recommendation')])
def r5():emit(4107,[E('TailEntropy'),E('MassNormalization','Assumption'),E('MeanConstraint','Assumption'),E('GeometricMaximumEntropy'),E('TwoMultipliers'),E('PositiveInfiniteTail'),E('QuadraticCoefficientFiniteCondition'),E('ConstraintSourceMissing','No-go'),E('ReferenceMeasure'),E('RelativeEntropyPrior'),E('PriorDependence'),E('ZeroMassBoundary'),E('EntropyNotPhysical','Boundary'),E('RoundVerdict','Round verdict'),E('Next','Recommendation')])
def r6():emit(4122,[E('ExponentialFamily'),E('AmplitudeA'),E('DecayRateA'),E('ExactPatch'),E('Positive'),E('LocalQuadratic'),E('AnalyticSymbol'),E('ContinuumCoefficients'),E('TwoParameterFreedom'),E('SmoothnessInsufficient','No-go'),E('FitNeedsTailData'),E('BayesianPrior'),E('PosteriorNotSource','Boundary'),E('RoundVerdict','Round verdict'),E('Next','Recommendation')])
def r7():
 ratios=(w[1:]/w[:-1]).tolist()
 emit(4137,[E('DyadicHomogeneity'),E('ExpectedRatio',ratio=target),E('ObservedRatios',ratios=ratios),E('MaximumDeviation',value=max(abs(np.array(ratios)-target))),E('ExactFailure','Refuted'),E('PhaseCausesVariation'),E('DenominatorFiniteScale'),E('AsymptoticEnvelope'),E('TailOnlyScaling','Conditional'),E('OddSeedFreedom'),E('DyadicOrbits'),E('ScaleOrigin'),E('SelfSimilarityNoSelector','No-go'),E('RoundVerdict','Round verdict'),E('Next','Recommendation')])
def r8():
 M=np.array([[w[2],w[1],w[0]],[w[3],w[2],w[1]],[w[4],w[3],w[2]]]);c=np.linalg.solve(M,w[3:6]);roots=np.roots([1,-c[0],-c[1],-c[2]]);z=list(w)
 for _ in range(20):z.append(float(c@np.array(z[-3:][::-1])))
 emit(4152,[E('Order3Recurrence'),E('UniqueCoefficients',coefficients=c.tolist()),E('ExactSixFit'),E('CharacteristicRoots',roots=[[float(x.real),float(x.imag)] for x in roots]),E('UnstableRoot',max_mod=float(max(abs(roots)))),E('PredictedK7',value=z[6]),E('PredictedK8',value=z[7]),E('SignFailure',first_negative=next(i+1 for i,x in enumerate(z) if x<0)),E('GrowthFailure'),E('LowerOrderApproximation'),E('HigherOrderFreedom'),E('RecurrenceOrderAxiom'),E('ShortestRecurrenceNoGo','No-go'),E('RoundVerdict','Round verdict'),E('Next','Recommendation')])
def r9():emit(4167,[E('AnalyticInterpolation'),E('VanishingFactor',formula='prod_(j=1)^6(d-j)'),E('PerturbationFamily'),E('ExactSixMatch'),E('EntirePerturbations'),E('TailControlFunctions'),E('PositiveSmallPerturbations'),E('DifferentSecondMoments'),E('AnalyticityNoUniqueness','No-go'),E('GrowthTypeConstraint'),E('CarlsonBoundary'),E('SixPointsInsufficient'),E('AnalyticSelectorMissing'),E('RoundVerdict','Round verdict'),E('Next','Recommendation')])
def r10():emit(4182,[E('FiniteDifferencePass'),E('HankelH1Failure',lambda_min=-.0005650021864459561),E('HankelH2Failure',lambda_min=-.0011006599618137553),E('PositiveMomentNoGo','No-go'),E('ExponentialMixtureNoGo','No-go'),E('RepairLowerBound',epsilon=.00036688665393791843),E('ExactMatchConflict'),E('ApproximateRepair'),E('LossFunctionFreedom'),E('SignedMixture'),E('ComplexPoles'),E('PositivityLost'),E('MomentRouteClosed','No-go'),E('RoundVerdict','Round verdict'),E('Next','Recommendation')])
def r11():
 D=1.0;t7=D/49;t8=D/64
 emit(4197,[E('FixLeadingC'),E('TailAtom7',weight=t7),E('TailAtom8',weight=t8),E('SameDeltaC'),E('DifferentFourthMoment',m4_7=7**4*t7,m4_8=8**4*t8),E('K4DispersionTerm'),E('SubleadingDifference'),E('SameWaveSpeed'),E('DifferentHighK'),E('FiniteMomentHierarchy'),E('AllMomentsNeedTail'),E('LeadingPhysicsInsufficient'),E('SpeedDoesNotSelectTail','No-go'),E('RoundVerdict','Round verdict'),E('Next','Recommendation')])
def r12():emit(4212,[E('TailRGMap'),E('BlockDecimation'),E('AmplitudeRescaling'),E('FixedPointEquation'),E('PowerLawFixedPoints'),E('PositiveLocalConflict'),E('ExponentialFlow'),E('CutoffFlow'),E('RelevantDirections'),E('RGNormalization'),E('RGMetric'),E('MultipleFixedFamilies'),E('StrictRGSourceMissing','No-go'),E('RoundVerdict','Round verdict'),E('Next','Recommendation')])
def r13():emit(4227,[E('ConductancePositivity'),E('FiniteSecondMoment'),E('ExponentialMoment'),E('HeatLocalScaling'),E('WaveFiniteSpeedProxy'),E('ExactFinitePropagationNo'),E('ConeBoundsConditional'),E('LongRangeImmediateTails'),E('CausalMetricNeeded'),E('LiebRobinsonVelocity'),E('VelocityDependsTail'),E('LocalityClassNotLaw'),E('CausalityNoSelector','No-go'),E('RoundVerdict','Round verdict'),E('Next','Recommendation')])
def r14():emit(4242,[E('SpectralAction'),E('TraceFunctional'),E('TailEigenvalues'),E('CutoffFunction'),E('CutoffScale'),E('TailPenaltyInduced'),E('DifferentF'),E('DifferentMinimizers'),E('RenormalizedCoefficients'),E('Counterterms'),E('FiniteAInsufficient'),E('ActionNotSource'),E('SpectralActionNoSelector','No-go'),E('RoundVerdict','Round verdict'),E('Next','Recommendation')])
def r15():emit(4257,[E('DescriptionLength'),E('ZeroTailSimple'),E('FormulaTailSimple'),E('ExponentialTailSimple'),E('LanguageDependence'),E('UniversalMachineConstant'),E('MDLNeedsNoiseModel'),E('BayesNeedsPrior'),E('EvidenceNeedsData'),E('NoBeyondSixData'),E('CompressionMetaphor'),E('AlgorithmicUncomputability'),E('SimplicityNoPhysicalLaw','No-go'),E('RoundVerdict','Round verdict'),E('Next','Recommendation')])
def r16():emit(4272,[E('LegacyKernel'),E('SignedBase'),E('PositivityMap'),E('RoleTransfer'),E('BridgeIncomplete'),E('LegacyTailFormula'),E('StrictTailCone'),E('DifferentSemantics'),E('CommonRegularizer'),E('DifferentOutputs'),E('AlphaGeoBoundary'),E('BetaTorsBoundary'),E('LegacyCannotSelect','No-go'),E('RoundVerdict','Round verdict'),E('Next','Recommendation')])
def r17():emit(4287,[E('MeasureK7'),E('MeasureLowK'),E('MeasureWaveSpeed'),E('MeasureDispersionK4'),E('MultipleSizes'),E('MultipleTimes'),E('Calibration'),E('TailNoise'),E('ModelSelection'),E('PreRegistration'),E('Holdout'),E('IndependentCustody'),E('CurrentEvidenceMissing','No-go'),E('RoundVerdict','Round verdict'),E('Next','Recommendation')])
def r18():emit(4302,[E('AxiomTailPositivity'),E('AxiomSecondMoment'),E('AxiomMinimumC'),E('AxiomSmoothness'),E('AxiomEntropy'),E('AxiomRecurrence'),E('AxiomRG'),E('AxiomSimplicity'),E('MutualIndependence'),E('RemovalCounterexamples'),E('MinimalTruncationSet'),E('NecessityOfMinimum'),E('NoStrictAxiom'),E('RoundVerdict','Round verdict'),E('Next','Recommendation')])
def r19():emit(4317,[E('FiniteRestriction'),E('InfiniteFiber'),E('PositiveLocalSubcone'),E('CoefficientRay'),E('SameCSubfiber'),E('RegularizerMap'),E('PriorMap'),E('DataMap'),E('NoNaturalSection'),E('SectionRequiresStructure'),E('CategoricalObstruction'),E('LogicalStatus'),E('GlobalTailNoGo','Proven'),E('RoundVerdict','Round verdict'),E('Next','Recommendation')])
def r20():
 gate=ROOT/'FIN_ST4332_ST4346_TailSelectionPrincipleGate.json';g={'rows':[{'name':n,'pass':v} for n,v in [('positive local cone',True),('speed lower bound',True),('same-speed tail no-go',True),('strict minimum-tail principle',False),('strict smoothness functional',False),('strict entropy constraints',False),('stable exact recurrence',False),('strict RG section',False),('beyond-six evidence',False),('physical calibration',False)]]};gate.write_text(json.dumps(g,indent=2)+'\n')
 emit(4332,[E('ConeTheorem'),E('MinimumConditional'),E('DyadicNoGo'),E('RecurrenceNoGo'),E('AnalyticNoGo'),E('MomentNoGo'),E('SameSpeedNoGo'),E('RegularizerNoGo'),E('Gate',file=gate.name),E('GateScore',passes=3,rows=10),E('ProvenLedger'),E('ConditionalLedger'),E('HighestValueNext','Recommendation'),E('FinalInterpretation','Round verdict'),E('CycleTrigger',programs=300,rounds=20,range='ST4047-ST4346',strict_ToE_closure=False,gate_sha256=hashlib.sha256(gate.read_bytes()).hexdigest())])
def main():
 for f in [r1,r2,r3,r4,r5,r6,r7,r8,r9,r10,r11,r12,r13,r14,r15,r16,r17,r18,r19,r20]:f()
if __name__=='__main__':main()
