#!/usr/bin/env python3
"""FIN ST154--ST165: typed environments, constrained preparation, and operational closure."""

from __future__ import annotations

import csv
import hashlib
import itertools
import json
import math
import platform
from fractions import Fraction
from pathlib import Path
from typing import Any, Iterable

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import mpmath as mp
import numpy as np
import scipy
from scipy.optimize import minimize_scalar, root

from fin_st01_st15_research import N, strict_operator
from fin_st28_st45_research import dyadic_lift
from fin_st106_st117_research import plus_minus
from fin_st118_st129_research import bounds, ib, interval_left, interval_matvec, spectrum_intervals
from fin_st130_st141_research import parametric_chernoff_stationary, point_design_system
from fin_st132_center_isolation_replay import strict_interval_matrix
from fin_st142_st153_research import krawczyk_fold


ROOT = Path(__file__).resolve().parent
RESULTS = ROOT / "FIN_ST154_ST165_Results.json"
SUMMARY = ROOT / "FIN_ST154_ST165_Summary.csv"
PACK154 = ROOT / "FIN_ST154_Interaction_Generated_Algebras.json"
CERT155 = ROOT / "FIN_ST155_Fold_Neighborhood_Certificate.json"
PACK156 = ROOT / "FIN_ST156_Orthogonal_Unitary_Recovery.json"
PACK158 = ROOT / "FIN_ST158_Minimal_C12_Anisotropy.json"
CERT159 = ROOT / "FIN_ST159_Adaptive_Nuisance_Cover.json"
PACK160 = ROOT / "FIN_ST160_Refinement_Functor_Cohomology.json"
PACK162 = ROOT / "FIN_ST162_Hidden_HMM_Certificate.json"
PACK164 = ROOT / "FIN_ST164_Minimax_Extreme_Criterion.json"
PACK165 = ROOT / "FIN_ST165_Minimal_Operational_Tuple.json"
FIG_DIR = ROOT / "FIN_ST154_ST165_Figures"
SEED = 20260824


def native(x: Any) -> Any:
    if isinstance(x, dict): return {str(k): native(v) for k, v in x.items()}
    if isinstance(x, (list, tuple)): return [native(v) for v in x]
    if isinstance(x, np.ndarray): return native(x.tolist())
    if isinstance(x, (np.floating, np.integer)): return x.item()
    return x


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_packet(path: Path, data: dict) -> str:
    path.write_text(json.dumps(native(data), indent=2, sort_keys=True), encoding="utf-8")
    return sha(path)


def commutant_dimension(generators: Iterable[np.ndarray], tol: float = 1e-9) -> int:
    generators = [np.asarray(g, dtype=complex) for g in generators]
    d = generators[0].shape[0]
    eye = np.eye(d)
    equations = [np.kron(eye, g) - np.kron(g.T, eye) for g in generators]
    rank = np.linalg.matrix_rank(np.vstack(equations), tol=tol)
    return int(d * d - rank)


def st154_environment_superselection(a: np.ndarray) -> dict:
    q = np.diag(np.arange(N, dtype=float))
    ad = np.kron(a, np.eye(2))
    rows = [
        {"interaction_observables": "{A}", "fixed_observable_algebra_dimension": commutant_dimension([a]),
         "interpretation": "strict spectral commutant; degeneracies remain"},
        {"interaction_observables": "{Q_vertex}", "fixed_observable_algebra_dimension": commutant_dimension([q]),
         "interpretation": "vertex-diagonal pointer algebra; Q_vertex is supplied"},
        {"interaction_observables": "{A,Q_vertex}", "fixed_observable_algebra_dimension": commutant_dimension([a, q]),
         "interpretation": "only scalars survive; connected A plus simple Q acts irreducibly"},
        {"interaction_observables": "{A tensor I2}", "fixed_observable_algebra_dimension": commutant_dimension([ad]),
         "interpretation": "unlabeled doubled strict commutant"},
    ]
    packet = {
        "rows": rows,
        "theorem": (
            "For a finite-dimensional unital dephasing semigroup generated by Hermitian interaction observables L_k, "
            "the Heisenberg fixed algebra is the joint commutant of {H,L_k}. Consequently an environment can select an algebra "
            "without naming that algebra as output, but the interaction observables themselves are typed input. For the strict-only "
            "choice L=A the fixed algebra has dimension 22, not the desired M12 direct-sum C algebra."
        ),
    }
    digest = write_packet(PACK154, packet)
    return {"program": "ST154", "object": "Interaction-Generated Superselection Algebra Compiler",
            "packet_file": PACK154.name, "packet_sha256": digest, **packet,
            "status": "proven_fixed_algebra_classification_for_declared_interactions",
            "boundary": "Q_vertex, every environment coupling, and the Markovian dephasing law are supplied. Strict A alone does not generate the desired fine-blind algebra."}


def st155_fold_neighborhoods() -> dict:
    old = json.loads((ROOT / "FIN_ST142_ST153_Results.json").read_text(encoding="utf-8"))["ST144"]
    aiv, _, _ = strict_interval_matrix()
    radii = [1e-4, 3e-5, 1e-5, 3e-6, 1e-6, 3e-7, 1e-7, 3e-8, 1e-8, 3e-9, 1e-9, 3e-10, 1e-10]
    rows = []
    for idx, rr in enumerate(old["roots"]):
        center = np.asarray(rr["center"], dtype=float)
        trials = []
        for radius in radii:
            cert = krawczyk_fold(center, aiv, radius)
            trials.append(cert)
        passed = [x for x in trials if x["included"]]
        largest = max((x["radius"] for x in passed), default=None)
        rows.append({"cluster": idx, "u_norm": rr["u_norm"], "kappa": rr["kappa"],
                     "largest_tested_certified_radius": largest,
                     "certified": largest is not None,
                     "root_free_shell_from_1e-7": bool(largest is not None and largest > 1e-7),
                     "trials": trials})
    certified = [r for r in rows if r["certified"]]
    shell = [r for r in rows if r["root_free_shell_from_1e-7"]]
    packet = {
        "input_numerical_clusters": len(rows),
        "adaptively_certified_clusters": len(certified),
        "clusters_with_certified_outer_root_free_shell": len(shell),
        "rows": rows,
        "theorem": (
            "Every accepted Krawczyk box contains exactly one fold root. If the same center has the earlier radius-1e-7 existence box "
            "and a larger accepted box, uniqueness of the larger box proves the intervening max-norm shell contains no other root."
        ),
        "scope": "This is a union of certified neighborhoods around multistart representatives, not a cover of the full 15-dimensional filtered domain.",
    }
    digest = write_packet(CERT155, packet)
    return {"program": "ST155", "object": "Adaptive Fold-Neighborhood Inclusion and Exclusion Shells",
            "certificate_file": CERT155.name, "certificate_sha256": digest, **packet,
            "status": "proven_local_neighborhood_cover_without_global_domain_exhaustion",
            "boundary": "Uncovered parts of the 15-dimensional fold domain may contain additional roots; multistart representatives are not a topological domain cover."}


def st156_orthogonal_unitary_recovery() -> dict:
    m = 4
    probabilities = np.array([.55, .25, .15, .05])
    confusion = np.zeros((m, m))
    for error in range(m):
        confusion[error, error] = .78
        confusion[(error + 1) % m, error] = .12
        confusion[(error - 1) % m, error] = .07
        confusion[(error + 2) % m, error] = .03
    posterior_weights = confusion * probabilities[None, :]
    decisions = np.argmax(posterior_weights, axis=1)
    contributions = np.max(posterior_weights, axis=1)
    optimum = float(np.sum(contributions))
    phase = np.exp(2j * np.pi * np.arange(N) / N)
    unitaries = [np.diag(phase ** k) for k in range(m)]
    gram = np.array([[np.trace(u.conj().T @ v) / N for v in unitaries] for u in unitaries])
    packet = {
        "error_probabilities": probabilities.tolist(), "readout_confusion_y_given_error": confusion.tolist(),
        "hilbert_schmidt_gram_abs_max_offdiagonal": float(np.max(np.abs(gram - np.eye(m)))),
        "optimal_decisions_by_reported_syndrome": decisions.tolist(),
        "optimal_entanglement_fidelity": optimum,
        "no_syndrome_best_fidelity": float(np.max(probabilities)),
        "perfect_syndrome_fidelity": 1.0,
        "theorem": (
            "For any finite Hilbert-Schmidt-orthogonal unitary error family {U_a} with prior p_a and classical syndrome channel q(y|a), "
            "the inverse-unitary decision U_a^dagger chosen by maximum posterior p_a q(y|a) is optimal, and F_e^*=sum_y max_a p_a q(y|a)."
        ),
    }
    digest = write_packet(PACK156, packet)
    return {"program": "ST156", "object": "Optimal Recovery for a Finite Orthogonal Unitary Spectrum",
            "packet_file": PACK156.name, "packet_sha256": digest, **packet,
            "status": "proven_for_general_finite_HS_orthogonal_unitary_error_families",
            "boundary": "The unitary family, prior, syndrome coupling, pinching, and readout channel are supplied. Nonorthogonal unitary errors require a different optimization."}


def st157_preparation_action_cost() -> dict:
    rows = []
    for g in [.01, .05, .1, .25, .5]:
        displacement2 = 11 * g * g / 12
        for horizon in [.1, 1.0, 10.0]:
            rows.append({"gap": g, "preparation_horizon": horizon,
                         "minimum_quadratic_kinetic_action": displacement2 / (2 * horizon)})
    return {
        "program": "ST157", "object": "Sharp Finite-Time Preparation Action Bound",
        "rows": rows,
        "minimum_action_formula": "A_min=11 g^2/(24 T)",
        "power_limited_time_formula": "T_min=sqrt(11/12) g/sqrt(2 P_max)",
        "theorem": (
            "For absolutely continuous probability paths from the uniform distribution to any endpoint satisfying p0-pj>=g, "
            "the kinetic action (1/2) integral_0^T ||p_dot||_2^2 dt is at least 11g^2/(24T). The straight path to the symmetric "
            "least-asymmetric endpoint attains equality. Under pointwise kinetic power at most P_max, time is at least sqrt(11/12)g/sqrt(2P_max)."
        ),
        "status": "proven_sharp_for_declared_probability_simplex_metric",
        "boundary": "The Euclidean preparation metric, horizon, power interpretation, preferred outcome, and gap are supplied; this is not a strict physical action or energy theorem."
    }


def st158_minimal_anisotropy() -> dict:
    constant = Fraction(693, 256)
    angular = Fraction(3, 512)
    normalized_constant = constant / (6 ** 6)
    normalized_angular = angular / (6 ** 6)
    samples = []
    for degree in range(2, 13, 2):
        theta = np.linspace(0, 2 * np.pi, 721, endpoint=False)
        vals = np.array([sum(math.cos(t + 2 * math.pi * j / 12) ** degree for j in range(12)) for t in theta])
        samples.append({"even_degree": degree, "angular_range": float(np.max(vals) - np.min(vals))})
    packet = {
        "unnormalized_identity": "sum_j cos(theta+2pi j/12)^12 = 693/256 + (3/512) cos(12theta)",
        "constant_coefficient": str(constant), "cos12_coefficient": str(angular),
        "normalized_mode_constant_coefficient": str(normalized_constant),
        "normalized_mode_cos12_coefficient": str(normalized_angular),
        "local_coupling_to_ST147_map": "for (g/12) sum_j psi_j^12, epsilon = -3g/(512*6^6)",
        "degree_scan": samples,
        "theorem": (
            "On the normalized first real Fourier mode psi_j=(r/sqrt(6))cos(theta+2pi j/12), every local even monomial sum_j psi_j^(2m) "
            "with 2m<12 is angularly isotropic. Degree twelve is the first local even monomial that aliases to cos(12theta), with the exact coefficients shown."
        ),
    }
    digest = write_packet(PACK158, packet)
    return {"program": "ST158", "object": "Minimal Local Source Shape for C12 Anisotropy",
            "packet_file": PACK158.name, "packet_sha256": digest, **packet,
            "status": "proven_minimal_order_and_exact_projection_coefficient",
            "boundary": "C12 geometry fixes the anisotropy shape and projection factor but does not determine the coupling g, its sign, units, or dynamical origin."}


def parametric_data(a: np.ndarray):
    p, f = plus_minus()
    b0 = f.T @ dyadic_lift(a, 0) @ f
    ec = np.linalg.eigvalsh(a); ef = np.linalg.eigvalsh(b0)
    return ec, ef, spectrum_intervals(ec), spectrum_intervals(ef)


def local_param_krawczyk(eigc, eigf, nuisance_center, nuisance_halfwidth, center, rbeta=.003, rs=.008):
    q0c, q1c, dc = nuisance_center
    q0 = (q0c - nuisance_halfwidth, q0c + nuisance_halfwidth)
    q1 = (q1c - nuisance_halfwidth, q1c + nuisance_halfwidth)
    delta = (dc - nuisance_halfwidth, dc + nuisance_halfwidth)
    mp.iv.dps = 50
    f0, _, _ = parametric_chernoff_stationary(ib(float(center[0])), ib(float(center[1])), q0, q1, eigc, eigf, delta)
    flo = np.array([bounds(x)[0] for x in f0]); fhi = np.array([bounds(x)[1] for x in f0])
    _, jm, _ = parametric_chernoff_stationary(ib(float(center[0])), ib(float(center[1])), q0c, q1c, eigc, eigf, dc)
    jml = np.array([[bounds(x)[0] for x in row] for row in jm]); jmh = np.array([[bounds(x)[1] for x in row] for row in jm])
    c = np.linalg.inv((jml + jmh) / 2)
    _, ji, _ = parametric_chernoff_stationary(ib((center[0]-rbeta, center[0]+rbeta)), ib((center[1]-rs, center[1]+rs)), q0, q1, eigc, eigf, delta)
    jl = np.array([[bounds(x)[0] for x in row] for row in ji]); jh = np.array([[bounds(x)[1] for x in row] for row in ji])
    cglo, cghi = interval_matvec(c, c, flo, fhi)
    ylo = np.nextafter(center-cghi, -np.inf); yhi = np.nextafter(center-cglo, np.inf)
    cjlo, cjhi = interval_left(c, jl, jh); mlo, mhi = -cjhi, -cjlo
    for i in range(2):
        mlo[i, i] = np.nextafter(mlo[i, i] + 1, -np.inf)
        mhi[i, i] = np.nextafter(mhi[i, i] + 1, np.inf)
    rv = np.array([rbeta, rs]); mdlo, mdhi = interval_matvec(mlo, mhi, -rv, rv)
    klo = ylo + mdlo; khi = yhi + mdhi
    margin = float(min(np.min(klo-(center-rv)), np.min((center+rv)-khi)))
    return {"included": margin > 0, "margin": margin, "root_center": center.tolist(),
            "root_radii": [rbeta, rs], "nuisance_center": list(nuisance_center), "nuisance_halfwidth": nuisance_halfwidth}


def st159_adaptive_nuisance_cover(a: np.ndarray) -> dict:
    ec, ef, eigc, eigf = parametric_data(a)
    global_halfwidth = 5e-5
    subdivisions = 4
    local_halfwidth = global_halfwidth / subdivisions
    offsets = [-global_halfwidth + (2*i+1)*local_halfwidth for i in range(subdivisions)]
    rows = []
    for dq0, dq1, dd in itertools.product(offsets, repeat=3):
        nuisance = (.2+dq0, .7+dq1, .05+dd)
        center = root(lambda x: point_design_system(x, ec, ef, *nuisance), np.array([2.1862, .53983]), tol=1e-12).x
        cert = local_param_krawczyk(eigc, eigf, nuisance, local_halfwidth, center)
        rows.append(cert)
    passed = sum(r["included"] for r in rows)
    packet = {
        "global_nuisance_center": [.2, .7, .05], "global_halfwidth": global_halfwidth,
        "subdivisions_per_axis": subdivisions, "boxes": len(rows), "local_halfwidth": local_halfwidth,
        "passed_boxes": passed, "minimum_margin": min(r["margin"] for r in rows), "rows": rows,
        "theorem": (
            "The 4x4x4 partition covers the complete declared nuisance cube. Strict local Krawczyk inclusion in every cell proves a unique stationary root "
            "inside the cell-specific root box for every nuisance triple in the global cube."
        ),
    }
    digest = write_packet(CERT159, packet)
    return {"program": "ST159", "object": "Adaptive Interval Cover Beyond the Single-Box Boundary",
            "certificate_file": CERT159.name, "certificate_sha256": digest, **packet,
            "status": "proven_adaptive_uniform_cover" if passed == len(rows) else "partial_adaptive_cover",
            "boundary": "This disproves the ST148 single-box failure as a root-loss boundary, but it does not locate the maximal continuation domain or prove global beta optimality."}


def gf2_rank_bitrows(rows: list[int], ncols: int) -> int:
    rows = rows[:]; rank = 0
    for col in range(ncols):
        pivot = next((i for i in range(rank, len(rows)) if (rows[i] >> col) & 1), None)
        if pivot is None: continue
        rows[rank], rows[pivot] = rows[pivot], rows[rank]
        for i in range(len(rows)):
            if i != rank and ((rows[i] >> col) & 1): rows[i] ^= rows[rank]
        rank += 1
    return rank


def st160_refinement_functors() -> dict:
    # Fine diamond: 0->1,0->2,1->3,2->3.  Coherence is b01+b13=b02+b23.
    coherent = []
    for bits in itertools.product([0, 1], repeat=4):
        if bits[0] ^ bits[2] == bits[1] ^ bits[3]:
            coherent.append({"fine_twists": list(bits), "coarse_twist": bits[0] ^ bits[2]})
    fibers = {t: sum(x["coarse_twist"] == t for x in coherent) for t in [0, 1]}
    packet = {
        "fine_diamond_edges": 4, "fine_vertices": 4, "coherence_rank": 1,
        "coherent_assignments": len(coherent), "coarse_twist_fiber_sizes": fibers,
        "rows": coherent,
        "theorem": (
            "For a rooted all-odd refinement DAG in which every vertex is reachable, path-independent F2 twists are exactly vertex coboundaries b_uv=phi_u+phi_v, so the coherent space has dimension |V|-1. "
            "A coarse-graining retaining a subset of vertices pushes a coherent twist forward by restricting phi; it is surjective, and its kernel has dimension equal to the number of eliminated nonroot vertices. "
            "For mixed parity, equality of affine linear parts on every contracted path is an additional necessary obstruction."
        ),
    }
    digest = write_packet(PACK160, packet)
    return {"program": "ST160", "object": "Functorial Refinement Cohomology under Coarse-Graining",
            "packet_file": PACK160.name, "packet_sha256": digest, **packet,
            "status": "proven_for_connected_all_odd_DAGs_with_mixed_parity_obstruction",
            "boundary": "Refinement graphs, retained vertices, degree parities, and twist variables remain supplied; no strict fractal refinement law is derived."}


def algebra_span_dimension(generators: list[np.ndarray], tol=1e-9) -> int:
    d = generators[0].shape[0]
    basis = [np.eye(d, dtype=complex)]
    changed = True
    while changed:
        changed = False
        candidates = basis + [b @ g for b in basis for g in generators]
        new_basis = []
        for x in candidates:
            trial = new_basis + [x]
            rank = np.linalg.matrix_rank(np.column_stack([z.reshape(-1) for z in trial]), tol=tol)
            if rank > len(new_basis): new_basis.append(x)
        if len(new_basis) > len(basis): changed = True
        basis = new_basis
    return len(basis)


def st161_instrument_tomography() -> dict:
    x = np.array([[0, 1], [1, 0]], complex); z = np.diag([1, -1]).astype(complex); i2 = np.eye(2)
    left = [np.kron(x, i2), np.kron(z, i2)]
    right = [np.kron(i2, x), np.kron(i2, z)]
    incomplete = [np.kron(z, i2)]
    rng = np.random.default_rng(SEED + 161)
    q, _ = np.linalg.qr(rng.normal(size=(4, 4)) + 1j*rng.normal(size=(4, 4)))
    left_u = [q @ g @ q.conj().T for g in left]; right_u = [q @ g @ q.conj().T for g in right]
    rows = [
        {"table": "complete_labeled_left", "generated_algebra_dimension": algebra_span_dimension(left), "commutant_dimension": commutant_dimension(left)},
        {"table": "complete_labeled_right", "generated_algebra_dimension": algebra_span_dimension(right), "commutant_dimension": commutant_dimension(right)},
        {"table": "joined_complete", "generated_algebra_dimension": algebra_span_dimension(left + right), "commutant_dimension": commutant_dimension(left + right)},
        {"table": "global_unitary_conjugate", "generated_algebra_dimension": algebra_span_dimension(left_u + right_u), "commutant_dimension": commutant_dimension(left_u + right_u)},
        {"table": "incomplete_single_Z", "generated_algebra_dimension": algebra_span_dimension(incomplete), "commutant_dimension": commutant_dimension(incomplete)},
    ]
    return {"program": "ST161", "object": "Atomic Causal-Net Reconstruction from Instrument Tomography",
            "rows": rows,
            "theorem": (
                "If two labeled tomographically reconstructed instrument algebras are commuting full M2 factors, each equals the commutant of the other and together they generate M4. "
                "The tensor-factor net is then unique up to local unitaries; labels remove the remaining swap. A single abelian instrument has an eight-dimensional commutant and cannot identify the factor net."
            ),
            "status": "proven_exact_noiseless_reconstruction_criterion",
            "boundary": "Tomographic completeness, instrument labels, exact matrix data, and identification with physical regions are supplied. Robust noisy reconstruction remains open."}


def hmm_sequence_likelihoods(n: int, P: np.ndarray, pi: np.ndarray, emissions: np.ndarray) -> np.ndarray:
    # Rows are all binary strings in lexicographic recursion; columns are hidden-state forward weights.
    if n < 1:
        raise ValueError("n must be positive")
    forward = np.vstack([pi * emissions[:, 0], pi * emissions[:, 1]])
    for _ in range(1, n):
        pred = forward @ P
        forward = np.vstack([pred * emissions[:, 0], pred * emissions[:, 1]])
    return np.sum(forward, axis=1)


def hidden_pair_transfer(P, p0, p1, s=.5):
    t = np.zeros((4, 4)); initial = np.zeros(4)
    pi = np.array([2/3, 1/3])
    for z, zp in itertools.product(range(2), repeat=2):
        c0 = p0[z]**s * p1[zp]**(1-s) + (1-p0[z])**s * (1-p1[zp])**(1-s)
        initial[2*z+zp] = pi[z]**s * pi[zp]**(1-s) * c0
        for w, wp in itertools.product(range(2), repeat=2):
            c = p0[w]**s * p1[wp]**(1-s) + (1-p0[w])**s * (1-p1[wp])**(1-s)
            t[2*z+zp, 2*w+wp] = P[z, w]**s * P[zp, wp]**(1-s) * c
    return initial, t


def st162_hidden_hmm() -> dict:
    P = np.array([[.9, .1], [.2, .8]])
    pi = np.array([2/3, 1/3])
    p0 = np.array([.02, .08]); p1 = np.array([.92, .98])
    e0 = np.column_stack([1-p0, p0]); e1 = np.column_stack([1-p1, p1])
    initial, transfer = hidden_pair_transfer(P, p0, p1, .5)
    rho = float(max(abs(np.linalg.eigvals(transfer))))
    row_sum_bound = float(np.max(np.sum(transfer, axis=1)))
    rows = []
    for n in [1, 2, 4, 8, 12, 16, 18]:
        l0 = hmm_sequence_likelihoods(n, P, pi, e0)
        l1 = hmm_sequence_likelihoods(n, P, pi, e1)
        error = .5 * float(np.sum(np.minimum(l0, l1)))
        bound = .5 * float(initial @ np.linalg.matrix_power(transfer, n-1) @ np.ones(4))
        rows.append({"events": n, "exact_Bayes_error": error, "pair_path_Chernoff_upper_bound": min(.5, bound)})
    packet = {
        "transition_matrix": P.tolist(), "stationary_distribution": pi.tolist(),
        "hypothesis_0_emission_one_probabilities": p0.tolist(), "hypothesis_1_emission_one_probabilities": p1.tolist(),
        "tilted_pair_transfer_spectral_radius": rho, "maximum_row_sum_certificate": row_sum_bound,
        "certified_exponent_from_row_sum": float(-math.log(row_sum_bound)), "rows": rows,
        "theorem": (
            "For 0<s<1, subadditivity (sum a)^s <= sum a^s expands the observed HMM Chernoff coefficient into a positive four-state pair-path transfer bound. "
            "At s=1/2 every row sum is below one, proving a positive discrimination exponent even though no output symbol reveals the hidden availability state."
        ),
    }
    digest = write_packet(PACK162, packet)
    return {"program": "ST162", "object": "Certified Fully Hidden Non-Erasure HMM Discrimination",
            "packet_file": PACK162.name, "packet_sha256": digest, **packet,
            "status": "proven_positive_upper_error_exponent_for_declared_hidden_HMM",
            "boundary": "The transition law, stationary state, and strongly separated emissions are supplied; the pair-path exponent is a conservative bound, not the exact asymptotic Chernoff rate."}


def st163_local_bath_speed(a: np.ndarray) -> dict:
    beta = .8; eig = np.linalg.eigvalsh(a); gamma = np.exp(-beta*eig); gamma /= gamma.sum()
    gamma_min = float(np.min(gamma)); replacement_identity_distance = 2*(1-gamma_min)
    rows = []
    for epsilon in [0, .05, .1, .25, .5]:
        arg = max(0.0, min(1.0, (replacement_identity_distance-epsilon)/4))
        rows.append({"diamond_error_tolerance": epsilon,
                     "minimum_time_times_generator_norm": 2*math.asin(arg)})
    return {"program": "ST163", "object": "Finite-Time and Site-Local Bath Resource Bounds",
            "bath_dimension_lower_bound": N, "gibbs_minimum_probability": gamma_min,
            "replacement_vs_identity_diamond_lower_bound": replacement_identity_distance,
            "rows": rows, "two_site_SWAP_attaining_time_times_norm": math.pi/2,
            "theorem": (
                "If the total dilation generator has operator norm at most g and gt<=pi, then ||E_t-Id||_diamond<=4 sin(gt/2). "
                "Triangle inequality against the Gibbs replacement channel gives t >= (2/g)asin((2(1-gamma_min)-epsilon)/4) for epsilon-approximation. "
                "The exact isospectral two-qudit SWAP is site-local, has norm g, and completes at pi/(2g); bath dimension at least 12 remains necessary for exact reset."
            ),
            "status": "proven_general_speed_lower_bound_and_two_site_local_upper_construction",
            "boundary": "The bound constrains total generator norm and qudit-site locality. Microscopic qubit locality, Lieb-Robinson geometry, controls, beta, units, and apparatus remain supplied or open."}


def bell_number(n: int) -> int:
    bell = [0]*(n+1); bell[0] = 1
    for i in range(1, n+1):
        bell[i] = sum(math.comb(i-1, k)*bell[k] for k in range(i))
    return bell[n]


def extremality_constraint_rank(h: np.ndarray, tol=1e-9) -> tuple[int, int]:
    vals, vecs = np.linalg.eigh(h); keep = vals > tol
    v = vecs[:, keep] * np.sqrt(vals[keep])[None, :]
    r = v.shape[1]; pairs = [(i, i) for i in range(N)] + [(i, j) for i in range(N) for j in range(i+1, N) if abs(h[i, j]) < tol]
    cols = []
    for a in range(r):
        for b in range(a, r):
            col = []
            for i, j in pairs:
                value = v[i, a]*v[j, b]
                if a != b: value += v[i, b]*v[j, a]
                col.append(value)
            cols.append(col)
    rank = np.linalg.matrix_rank(np.array(cols).T, tol=tol) if cols else 0
    return r, int(rank)


def partition_matrix(blocks: list[list[int]]) -> np.ndarray:
    h = np.zeros((N, N))
    for block in blocks:
        for i in block:
            for j in block: h[i, j] = 1/N
    return h


def st164_extreme_criterion() -> dict:
    examples = []
    families = {
        "discrete_partition_I_over_12": [[i] for i in range(N)],
        "one_block_J_over_12": [list(range(N))],
        "six_pairs": [[2*i, 2*i+1] for i in range(6)],
        "three_blocks_of_four": [list(range(4*i, 4*i+4)) for i in range(3)],
    }
    for name, blocks in families.items():
        h = partition_matrix(blocks); r, constraint_rank = extremality_constraint_rank(h)
        examples.append({"name": name, "matrix_rank": r, "symmetric_range_dimension": r*(r+1)//2,
                         "extremality_constraint_rank": constraint_rank, "extreme": constraint_rank == r*(r+1)//2})
    packet = {
        "affine_dimension": N*(N-1)//2, "certified_partition_extreme_points": bell_number(N),
        "examples": examples,
        "criterion": (
            "Write H=VV^T with row vectors v_i in R^r and let Z be the zero off-diagonal positions. H is extreme iff the only R in Sym_r satisfying "
            "v_i^T R v_i=0 for every i and v_i^T R v_j=0 for every (i,j) in Z is R=0."
        ),
        "theorem": (
            "The optimizer set has affine dimension 66. The displayed linear criterion is necessary and sufficient for extremality. "
            "Every set partition of twelve labels yields one extreme block-correlation matrix, giving at least Bell(12)=4,213,597 distinct extreme points."
        ),
    }
    digest = write_packet(PACK164, packet)
    return {"program": "ST164", "object": "Dimension and Complete Linear Extremality Criterion for the Minimax Spectrahedron",
            "packet_file": PACK164.name, "packet_sha256": digest, **packet,
            "status": "proven_dimension_extremality_criterion_and_partition_family",
            "boundary": "The criterion is complete but the full extreme-point list beyond the partition family is not enumerated."}


def st165_operational_tuple() -> dict:
    atoms = [
        ("ALG", "typed observable algebra and system-composition embeddings", "identifies subsystems and admissible observables", "spectral commutant versus vertex pointer algebra"),
        ("GAUGE", "operational equivalence/gauge action", "defines carrier-independent equivalence classes", "trivial group versus strict commutant-unitary group"),
        ("PREP", "preparation family", "defines which states can actually be initialized", "uniform state versus a vertex preparation"),
        ("DYN", "dynamical channel family", "selects one of the many functions/channels of A", "unitary exp(-itA) versus heat exp(-tA)"),
        ("CLOCK", "clock/calibration map", "turns a channel parameter into an ordered measured duration", "t versus 2t calibration on the same dimensionless channel"),
        ("INST", "instrument family", "produces outcome probabilities and conditional post-measurement states", "spectral PVM versus vertex POVM"),
        ("ENV", "environment/bath and dilation", "types decoherence, loss, thermalization, and memory", "closed dynamics versus the isospectral Gibbs bath"),
        ("APP", "apparatus implementation and calibration", "connects abstract instruments to settings and detectors", "identity detector labeling versus a nontrivial calibration permutation"),
        ("SELECT", "initial/boundary/branch-selection datum", "realizes one member of a symmetry orbit", "any two of the twelve ST147 stable branches"),
        ("UNITS", "dimension and scale map", "maps dimensionless records to physical quantities", "scale map u versus c u for c>0"),
        ("RECORD", "event record with custody and hold-out rule", "makes a falsifiable history external to analysis", "empty record versus a frozen timestamped event string"),
    ]
    rows = [{"atom": a, "definition": d, "deletion_failure": f, "alternative_witness": w,
             "independent_of_strict_A": True} for a, d, f, w in atoms]
    packet = {
        "tuple": "O_FIN=(A_strict, ALG, GAUGE, PREP, DYN, CLOCK, INST, ENV, APP, SELECT, UNITS, RECORD)",
        "axiom_atoms": len(atoms), "rows": rows,
        "theorem": (
            "Relative to the eleven declared operational obligations, every typed atom has an independent deletion witness: the strict operator admits at least two inequivalent choices of that atom while the remaining mathematical core is unchanged. "
            "Therefore no atom can be inferred from A_strict by type alone, and deleting it removes its corresponding obligation."
        ),
        "minimality_scope": "signature-minimal relative to the listed obligations; not an absolute theorem that no alternative packaging can combine atoms",
    }
    digest = write_packet(PACK165, packet)
    return {"program": "ST165", "object": "Operational FIN Completion Tuple with Axiom Deletion",
            "packet_file": PACK165.name, "packet_sha256": digest, **packet,
            "status": "proven_relative_independence_map_and_conditional_operational_design",
            "boundary": "The tuple organizes missing physics but does not instantiate a laboratory, derive its atoms from strict FIN, or supply independent custody by code."}


def make_figures(d: dict):
    FIG_DIR.mkdir(exist_ok=True)
    fig, ax = plt.subplots(figsize=(7, 4)); rows = d["ST154"]["rows"]
    ax.bar(range(len(rows)), [r["fixed_observable_algebra_dimension"] for r in rows]); ax.set_xticks(range(len(rows)), [r["interaction_observables"] for r in rows], rotation=18); ax.set(ylabel="complex dimension", title="ST154: the interaction selects the fixed algebra"); fig.tight_layout(); fig.savefig(FIG_DIR/"st154_fixed_algebras.png", dpi=190); plt.close(fig)
    fig, ax = plt.subplots(figsize=(7, 4)); rows = d["ST155"]["rows"]
    ax.scatter([r["kappa"] for r in rows], [r["largest_tested_certified_radius"] or 1e-11 for r in rows], c=[r["certified"] for r in rows]); ax.set_yscale("log"); ax.set(xlabel="kappa", ylabel="largest tested certified radius", title="ST155: adaptive local fold neighborhoods"); fig.tight_layout(); fig.savefig(FIG_DIR/"st155_fold_neighborhoods.png", dpi=190); plt.close(fig)
    fig, ax = plt.subplots(figsize=(7, 4)); p = d["ST156"]["error_probabilities"]; ax.bar(np.arange(4)-.2, p, width=.4, label="prior"); ax.bar(np.arange(4)+.2, [max(np.array(d["ST156"]["readout_confusion_y_given_error"])[y]*np.array(p)) for y in range(4)], width=.4, label="winning posterior mass"); ax.set(xlabel="error/syndrome label", title="ST156: four-error syndrome recovery"); ax.legend(); fig.tight_layout(); fig.savefig(FIG_DIR/"st156_unitary_recovery.png", dpi=190); plt.close(fig)
    fig, ax = plt.subplots(figsize=(7, 4)); rows = [r for r in d["ST157"]["rows"] if r["preparation_horizon"] == 1]
    ax.loglog([r["gap"] for r in rows], [r["minimum_quadratic_kinetic_action"] for r in rows], "o-"); ax.set(xlabel="selector gap", ylabel="minimum action at T=1", title="ST157: a preparation metric makes selector cost positive"); fig.tight_layout(); fig.savefig(FIG_DIR/"st157_action_cost.png", dpi=190); plt.close(fig)
    fig, ax = plt.subplots(figsize=(7, 4)); rows = d["ST158"]["degree_scan"]
    ax.semilogy([r["even_degree"] for r in rows], [max(r["angular_range"], 1e-15) for r in rows], "o-"); ax.set(xlabel="local even degree", ylabel="angular range", title="ST158: degree 12 is the first C12 anisotropy"); fig.tight_layout(); fig.savefig(FIG_DIR/"st158_anisotropy_order.png", dpi=190); plt.close(fig)
    fig, ax = plt.subplots(figsize=(7, 4)); rows = d["ST159"]["rows"]
    ax.hist([r["margin"] for r in rows], bins=16); ax.set(xlabel="Krawczyk inclusion margin", ylabel="cell count", title="ST159: adaptive 64-cell nuisance cover"); fig.tight_layout(); fig.savefig(FIG_DIR/"st159_adaptive_cover.png", dpi=190); plt.close(fig)
    fig, ax = plt.subplots(figsize=(7, 4)); rows = d["ST162"]["rows"]
    ax.semilogy([r["events"] for r in rows], [r["exact_Bayes_error"] for r in rows], "o-", label="exact finite error"); ax.semilogy([r["events"] for r in rows], [r["pair_path_Chernoff_upper_bound"] for r in rows], "--", label="certified upper bound"); ax.set(xlabel="events", ylabel="Bayes error", title="ST162: fully hidden non-erasure HMM"); ax.legend(); fig.tight_layout(); fig.savefig(FIG_DIR/"st162_hidden_hmm.png", dpi=190); plt.close(fig)
    fig, ax = plt.subplots(figsize=(7, 4)); rows = d["ST163"]["rows"]
    ax.plot([r["diamond_error_tolerance"] for r in rows], [r["minimum_time_times_generator_norm"] for r in rows], "o-"); ax.axhline(d["ST163"]["two_site_SWAP_attaining_time_times_norm"], ls="--", color="red", label="SWAP upper construction"); ax.set(xlabel="diamond error tolerance", ylabel="time x norm", title="ST163: bounded-generator reset time"); ax.legend(); fig.tight_layout(); fig.savefig(FIG_DIR/"st163_bath_speed.png", dpi=190); plt.close(fig)
    fig, ax = plt.subplots(figsize=(7, 4)); rows = d["ST164"]["examples"]
    ax.bar([r["name"] for r in rows], [r["matrix_rank"] for r in rows]); ax.tick_params(axis="x", rotation=20); ax.set(ylabel="matrix rank", title="ST164: certified extreme partition matrices"); fig.tight_layout(); fig.savefig(FIG_DIR/"st164_extreme_partitions.png", dpi=190); plt.close(fig)


def main():
    _, a, _ = strict_operator()
    out = {"metadata": {"programs": "ST154-ST165", "date": "2026-08-11", "seed": SEED,
                        "python": platform.python_version(), "numpy": np.__version__, "scipy": scipy.__version__}}
    out["ST154"] = st154_environment_superselection(a)
    out["ST155"] = st155_fold_neighborhoods()
    out["ST156"] = st156_orthogonal_unitary_recovery()
    out["ST157"] = st157_preparation_action_cost()
    out["ST158"] = st158_minimal_anisotropy()
    out["ST159"] = st159_adaptive_nuisance_cover(a)
    out["ST160"] = st160_refinement_functors()
    out["ST161"] = st161_instrument_tomography()
    out["ST162"] = st162_hidden_hmm()
    out["ST163"] = st163_local_bath_speed(a)
    out["ST164"] = st164_extreme_criterion()
    out["ST165"] = st165_operational_tuple()
    out["recommended_next_programs"] = [
        {"id": "ST166", "priority": 1, "study": "define and falsify a carrier-change operational invariant under explicit encoding, decoding, and instrument functors"},
        {"id": "ST167", "priority": 2, "study": "derive an environment interaction observable from strict data or prove a strict-source obstruction"},
        {"id": "ST168", "priority": 3, "study": "interval-cover a compact symmetry-reduced fold domain with both inclusion and exclusion boxes"},
        {"id": "ST169", "priority": 4, "study": "solve nonorthogonal coherent-unitary recovery by primal-dual SDP certificates"},
        {"id": "ST170", "priority": 5, "study": "derive selector cost from a declared Lindbladian or information-geometric control law"},
        {"id": "ST171", "priority": 6, "study": "search for a strict source of the local twelfth-order coupling g or prove a coefficient no-go"},
        {"id": "ST172", "priority": 7, "study": "extend the adaptive nuisance cover until a certified geometric boundary or resource stop"},
        {"id": "ST173", "priority": 8, "study": "lift refinement cohomology to noisy approximate functors and multiscale compression"},
        {"id": "ST174", "priority": 9, "study": "certify atomic-net reconstruction under finite tomography noise"},
        {"id": "ST175", "priority": 10, "study": "compute a sharper hidden-HMM Chernoff rate with interval Lyapunov or transfer-operator methods"},
        {"id": "ST176", "priority": 11, "study": "derive reset bounds for microscopic k-local bath encodings and Lieb-Robinson geometry"},
        {"id": "ST177", "priority": 12, "study": "implement the ST165 operational tuple as an executable validator with frozen record and axiom-deletion tests"},
    ]
    out["central_verdict"] = (
        "A typed environment can generate a fixed observable algebra, but strict A alone selects its 22-dimensional commutant rather than the desired fine-blind algebra. "
        "The C12 lattice fixes the first possible local anisotropy shape at degree twelve but not its coupling. Adaptive subdivision extends the stationary-root theorem beyond the old single-box boundary. "
        "A fully hidden HMM can retain a certified positive exponent, and thermal reset carries independent dimension and time costs. The operational completion therefore requires explicit typed resources."
    )
    out["epistemic_boundary"] = "No strict environment coupling, strict fine algebra, QW-2191 discharge, strict anisotropy coefficient, dimensional unit, laboratory apparatus or record, legacy-to-strict completion or role transfer, Standard Model, gravity, L_total, physical projection theorem, or ToE closure is claimed."
    RESULTS.write_text(json.dumps(native(out), indent=2, sort_keys=True), encoding="utf-8")
    with SUMMARY.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle); writer.writerow(["program", "object", "status"])
        for k in range(154, 166): writer.writerow([f"ST{k}", out[f"ST{k}"]["object"], out[f"ST{k}"]["status"]])
    make_figures(out)
    print(json.dumps({"results": RESULTS.name, "programs": 12, "figures": 9}, indent=2))


if __name__ == "__main__":
    main()
