#!/usr/bin/env python3
"""Six rounds: exact prism RG map, fixed points and feedback classification."""
import hashlib,json,math,numpy as np
from fin_st2172_st2261_common import ROOT,write_packet,write_round
def emit(lo,names,rows):
 d={}
 for i,(s,b,p) in enumerate(rows):k=lo+i;d[f'ST{k}']=write_packet(k,names[i],s,b,p)
 write_round(lo,lo+14,d)
def old(t,q):
 A=math.exp(3*q)+3*math.exp(-q);B=3*math.exp(q)+math.exp(-3*q)
 return t+.5*math.log((math.exp(t)*A+math.exp(-t)*B)/(math.exp(-t)*A+math.exp(t)*B))
def rg(t,q):return t+math.atanh(math.tanh(q)**3*math.tanh(t))
def mrg(m,q):
 r=math.tanh(q)**3;return m*(1+r)/(1+r*m*m)
def r1():
 grid=[(t,q) for t in [-2,-.3,.1,1.5] for q in [-1,-.2,0,.4,1]];res=max(abs(old(t,q)-rg(t,q)) for t,q in grid)
 names=['OriginalMap','ABIdentities','RhoSimplification','ThetaMap','MagnetizationMap','GridReplay','OddTheta','OddQEffect','IdentityQZero','SignPreservation','Domain','SmallQExpansion','ExactClosureRestated','RoundOneVerdict','RoundOneRecommendation']
 rows=[('Reused','Prior exact prism marginal.',{}),('Proven algebra','A-B=8sinh(q)^3; A+B=8cosh(q)^3.',{}),('Proven','rho=(A-B)/(A+B)=tanh(q)^3.',{}),('Proven exact','theta prime=theta+atanh(tanh(q)^3 tanh(theta)).',{}),('Proven exact','m prime=m(1+r)/(1+r m^2).',{}),('Computed','Old/new formula agreement.',{'max_residual':res}),('Proven','Map preserves theta sign for finite q.',{}),('Proven','q sign controls increment sign.',{}),('Proven','q=0 gives identity.',{}),('Proven','No sign selection.',{}),('Proven','Finite theta,q map inside |m|<1.',{}),('Proven','increment=q^3 tanh(theta)+O(q^5).',{}),('Theorem','Closed one-dimensional conditional RG.',{}),('Round verdict','Prism RG is exactly a tanh-cubic feedback law.',{}),('Recommendation','Classify fixed points.',{})];emit(2892,names,rows)
def r2():
 names=['FixedEquation','ZeroFixedPoint','QZeroLine','BoundaryFixedPoints','FiniteNonzeroNoGo','PositiveQZeroStability','NegativeQZeroStability','DerivativeAtZero','DerivativeAtBoundary','NoFiniteResonance','TranslationSignPair','ThetaInfinityBoundary','FixedPointGate','RoundTwoVerdict','RoundTwoRecommendation']
 rows=[('Derived','m prime=m.',{}),('Proven','m=0 for all q.',{}),('Proven','Every finite m fixed when q=0.',{}),('Proven','m=+-1 boundary fixed.',{}),('Proven no-go','For q!=0 and |m|<1, no nonzero fixed point.',{}),('Proven','q>0 makes zero unstable.',{}),('Proven','q<0 makes zero stable.',{}),('Proven','F prime(0)=1+tanh(q)^3.',{}),('Boundary','Saturation stability depends side but stays boundary.',{}),('Refuted','No finite nonzero highest-resonance fixed state in this map.',{}),('Proven','+- branches paired.',{}),('Boundary','|m|=1 means |theta| infinite/perfect order.',{}),('Gate fail','No finite selected nonzero fixed point.',{}),('Round verdict','Only disorder, identity line, or infinite-order boundaries exist.',{}),('Recommendation','Classify feedback trajectories.',{})];emit(2907,names,rows)
def r3():
 names=['PositiveFeedback','NegativeFeedback','NeutralFeedback','MagnitudeMonotonicity','EntropyDirection','SmallQWeakness','LargeQBoundary','NoPolarity','InformationGainBoundary','ErasureBoundary','ParameterSource','LegacyBoundary','FeedbackGate','RoundThreeVerdict','RoundThreeRecommendation']
 rows=[('Proven','q>0 increases |m| for 0<|m|<1.',{}),('Proven','q<0 decreases |m|.',{}),('Proven','q=0 identity.',{}),('Proven','Strict monotonic inequalities.',{}),('Conditional','Positive q orders; negative q disorders.',{}),('Proven','First effect cubic in q.',{}),('Boundary','q->+-infinity gives r->+-1.',{}),('Proven','Both theta signs treated symmetrically.',{}),('Boundary','Ordering is not physical information creation without dynamics/resource.',{}),('Boundary','Attenuation is not thermodynamic destruction.',{}),('No-go','Strict FIN sources neither q sign nor magnitude.',{}),('Boundary','Signed legacy loops need separate completion.',{}),('Gate fail','Feedback type remains a sector input.',{}),('Round verdict','The exact map realizes positive/negative informational feedback conditionally.',{}),('Recommendation','Iterate multilevel.',{})];emit(2922,names,rows)
def r4():
 def it(t,q,n):
  for _ in range(n):t=rg(t,q)
  return t
 vals={str(q):[it(.3,q,n) for n in [1,5,20,100]] for q in [.2,-.2,.5,-.5]}
 names=['ConstantQIteration','PositiveLimit','NegativeLimit','NeutralLimit','NumericalTrajectories','RateDependence','LevelSequence','CompositionNonsemigroup','AlternatingQ','FineTuning','SaturationMeaning','ErasureMeaning','IterationGate','RoundFourVerdict','RoundFourRecommendation']
 rows=[('Constructed','theta_(n+1)=RG(theta_n,q).',{}),('Proven','q>0, nonzero theta tends in magnitude to infinity.',{}),('Proven','q<0 tends to zero.',{}),('Proven','q=0 constant.',{}),('Computed','Declared trajectories.',{'values':vals}),('Proven','Convergence depends q.',{}),('Boundary','Arbitrary q_n gives controlled nonautonomous flow.',{}),('Proven','RG maps do not reduce to addition of q.',{}),('Conditional','Signs can cancel/amplify across levels.',{}),('No-go','Maintaining finite nonzero theta needs selected q_n control.',{}),('Boundary','Infinite theta is perfect-order boundary, not finite physics.',{}),('Boundary','Zero theta is loss of ternary order, not Landauer heat.',{}),('Gate fail','No strict multilevel q sequence.',{}),('Round verdict','Nontrivial bounded hierarchy requires new level control.',{}),('Recommendation','Test inverse identification/source.',{})];emit(2937,names,rows)
def r5():
 t,q=.3,.2;tp=rg(t,q);r=math.tanh(tp-t)/math.tanh(t);qi=math.atanh(math.copysign(abs(r)**(1/3),r))
 names=['InverseFormula','QIdentifiability','ThetaZeroBlindness','ObservedTransition','InverseReplay','TargetTrajectory','ControlFreedom','FixedPointConstraint','SingleLawHypothesis','ThetaQCoupling','SourceVsInference','ClockIndependence','PhysicalBoundary','RoundFiveVerdict','RoundFiveRecommendation']
 rows=[('Proven','r=tanh(theta prime-theta)/tanh(theta), q=atanh(cuberoot r).',{}),('Conditional','q identifiable from nonzero theta transition.',{}),('Proven','At theta=0 every q gives theta prime=0.',{}),('Computed','Declared step.',{'theta':t,'q':q,'theta_prime':tp}),('Computed','Inverse recovers q.',{'q_recovered':qi,'residual':abs(qi-q)}),('Proven','Admissible target steps define q_n when |r|<1.',{}),('No-go','Inference/control does not source trajectory.',{}),('Proven','Scale-stationary finite nonzero theta forces q=0.',{}),('Refuted','RG does not derive both theta and q from one fixed-point law.',{}),('Conditional','A separate recurrence q(theta) could couple axes.',{}),('Boundary','Measured q is not ontological provenance.',{}),('Proven','RG relation does not fix kinetic clock c.',{}),('Boundary','No units/OA.',{}),('Round verdict','Exact RG reduces algebra but not source count.',{}),('Recommendation','Synthesize.',{})];emit(2952,names,rows)
def r6():
 gate=ROOT/'FIN_ST2967_ST2981_PrismRGFixedPointGate.json';g={'rows':[{'name':n,'pass':v} for n,v in [('exact tanh-cubic RG theorem',True),('complete fixed-point classification',True),('feedback trajectory theorem',True),('strict q source',False),('finite nonzero fixed point',False),('polarity selector',False),('bounded multilevel trajectory',False),('kinetic clock coupling',False),('physical units',False),('OA evidence',False)]]};gate.write_text(json.dumps(g,indent=2)+'\n')
 names=['RGTheorem','FixedPointTheorem','FeedbackTheorem','IterationTheorem','InverseTheorem','FiniteResonanceNoGo','SourceNoGo','Gate','GateScore','ProvenLedger','ConditionalLedger','RefutedLedger','HighestValueNext','FinalInterpretation','CycleTrigger']
 rows=[('Proven','theta prime exact tanh-cubic formula.',{}),('Proven','zero/qzero/boundary complete classification.',{}),('Proven','q sign orders/disorders.',{}),('Proven','constant-q asymptotics.',{}),('Proven conditional','q inferred from observed transition.',{}),('No-go','No finite nonzero fixed point for q nonzero.',{}),('No-go','q sequence/polarity/clock absent.',{}),('Constructed','Ten rows.',{'file':gate.name}),('Result','Three mathematical passes.',{'passes':3,'rows':10}),('Ledger','RG/fixed/feedback.',{}),('Ledger','Conditional controlled hierarchy.',{}),('Ledger','Strict finite resonance and physics.',{}),('Recommendation','Search for a strict q_n recurrence or accept q as independent refinement resource.',{}),('Final verdict','Prism gives exact feedback mathematics but no self-sourced nontrivial universe trajectory.',{'fundamental':False}),('Cycle complete','Release 11.16.',{'programs':90,'rounds':6,'range':'ST2892-ST2981','strict_ToE_closure':False,'gate_sha256':hashlib.sha256(gate.read_bytes()).hexdigest()})];emit(2967,names,rows)
def main():r1();r2();r3();r4();r5();r6()
if __name__=='__main__':main()
