#!/usr/bin/env python3
"""Build the archival English PDF source for FIN Programs P323--P336."""

from pathlib import Path
import re

from fin_english_reports_to_latex import COMMON_PACKAGES, COMMON_SETUP, common_body


SOURCE = Path("FIN_Programs_323_336_Exact_Resource_Report_EN.md")
TARGET = Path("FIN_Programs_323_336_Exact_Resource_Report_EN.tex")

FIGURES = {
    "p323_continuum_extremizer.png": (
        "The matching continuum signed-measure and dual-polynomial "
        "extremizers."
    ),
    "p324_p325_parent_phase.png": (
        "One legacy input with distinct target parents, and the exact "
        "QW-2030/QW-2038 phase-lattice genealogy."
    ),
    "p326_lossy_protocol.png": (
        "Detector-degraded fifth-percentile operational separation under the "
        "declared synthetic nuisance model."
    ),
    "p327_exact_chambers.png": (
        "Minimum positive weights for all 720 exact algebraic spectral-order "
        "witnesses."
    ),
    "p328_p329_channel_clock.png": (
        "Ideal one-time wave-channel diamond separation and the quartic-clock "
        "minimax design distribution."
    ),
    "p331_p333_transfer_carriers.png": (
        "Photonic transfer tolerance and noncyclic carrier commutator "
        "obstructions."
    ),
    "p334_p335_axioms_independence.png": (
        "Conditional electroweak parameter accounting and the five-resource "
        "independence cube."
    ),
}


PREAMBLE = COMMON_PACKAGES + r"""
\hypersetup{
  unicode=true,
  colorlinks=true,
  linkcolor=finblue,
  citecolor=fingreen,
  urlcolor=finblue,
  pdftitle={FIN Research Programs P323--P336},
  pdfauthor={Krzysztof Żuchowski},
  pdfsubject={Exact resource certificates, refreeze provenance, and operational transfer boundaries},
  pdfkeywords={FIN, signed moment, Jordan measure, phase lattice, refreeze provenance, exact spectral chambers, diamond distance, photonic transfer, resource independence}
}
\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\small FIN Programs P323--P336}
\fancyhead[R]{\small Release 10.29}
\fancyfoot[C]{\thepage}
""" + COMMON_SETUP + r"""
\begin{document}
\hypersetup{pageanchor=false}
\begin{titlepage}
\centering
\vspace*{7mm}
{\Large\bfseries FIN --- Release 10.29\par}
\vspace{9mm}
{\Huge\bfseries Research Programs P323--P336\par}
\vspace{6mm}
{\Large Exact resource certificates,\\
refreeze provenance,\\
and operational transfer boundaries\par}
\vspace{13mm}
{\Large Krzysztof \.Zuchowski\par}
\vspace{2mm}
{\normalsize Independent Researcher --- Fractal Information Theory Project\par}
\vspace{2mm}
{\normalsize ORCID:
\href{https://orcid.org/0009-0002-0909-3613}{0009-0002-0909-3613}\par}
\vspace{7mm}
{\large 30 July 2026\par}
{\normalsize Publication --- Preprint; Version 1.0.0\par}
\vfill
\begin{minipage}{0.92\textwidth}
\small
\textbf{Central result.}
A matching signed-measure/dual-polynomial certificate fixes the continuum
seven-moment negative path resource at
\(\mathcal N_{\rm path}=0.406706334692258\ldots\).

\medskip
\textbf{Phase provenance.}
The exact strict phase unit \(1/4000\) is the gcd lattice unit generated by
the QW-2030 center and QW-2038 grid steps.  This is a procedural provenance
theorem, not an internal physical source theorem.

\medskip
\textbf{Repository.}
\url{https://github.com/hyconiek/Fractal-Nadsoliton-Theory}

\textbf{License.} CC BY 4.0.
\end{minipage}
\vfill
\end{titlepage}
\hypersetup{pageanchor=true}
\pagenumbering{roman}
\chapter*{Publication statement}
\addcontentsline{toc}{chapter}{Publication statement}
This monograph reports all executed Programs P323--P336 and recommends
Programs P337--P350.  Mathematical proof, high-precision evaluation,
target-dependent construction, synthetic design, conditional axiom package,
and missing external evidence remain separate.  The legacy/strict split,
QW-2191, dimensional-source, role-transfer, laboratory, \(L_{\rm total}\),
Standard-Model/gravity, and Theory-of-Everything boundaries are preserved.

\tableofcontents
\clearpage
\pagenumbering{arabic}
"""


POSTAMBLE = r"""
\clearpage
\chapter*{Reproduction certificate}
\addcontentsline{toc}{chapter}{Reproduction certificate}
\begin{Verbatim}[fontsize=\small]
MPLCONFIGDIR=/tmp/mpl-fin \
python3 -m unittest -v test_fin_programs_323_336.py
\end{Verbatim}
Expected result: 18 tests passed, 0 failed.  The suite recompiles the
dependency-free Lean 4.28 source.  Detector, clock, coupling-error, and
finite-count assumptions are synthetic.  P330 and P336 admit no external
laboratory or hardware evidence.

\medskip
\noindent\textbf{Suggested citation:}

\.Zuchowski, K. (2026). \emph{FIN Research Programs P323--P336:
Exact Resource Certificates, Refreeze Provenance, and Operational Transfer
Boundaries} (Release 10.29; Version 1.0.0) [Preprint]. Zenodo.

\end{document}
"""


def main() -> None:
    text = SOURCE.read_text(encoding="utf-8")
    text = re.sub(
        r"^(#{1,4})\s+\d+(?:\.\d+)*\.\s+",
        lambda match: match.group(1) + " ",
        text,
        flags=re.MULTILINE,
    )
    body = common_body(
        text,
        FIGURES,
        "FIN_Programs_323_336_Figures",
    )
    body = body.replace(
        r"\section{Confidence convention}",
        r"\chapter*{Confidence convention}"
        "\n"
        r"\addcontentsline{toc}{chapter}{Confidence convention}",
    )
    TARGET.write_text(
        PREAMBLE + "\n" + body + "\n" + POSTAMBLE,
        encoding="utf-8",
    )
    print(TARGET)


if __name__ == "__main__":
    main()
