#!/usr/bin/env python3
"""Six rounds: metric-measure-energy compatibility on binary refinement."""
import hashlib,json,math,numpy as np
from fin_st2172_st2261_common import ROOT,write_packet,write_round
def emit(lo,names,rows):
 d={}
 for i,(s,b,p) in enumerate(rows):k=lo+i;d[f'ST{k}']=write_packet(k,names[i],s,b,p)
 write_round(lo,lo+14,d)
def treeL(N,rho):
 n=2**(N+1)-1;L=np.zeros((n,n))
 for child in range(1,n):
  parent=(child-1)//2;depth=int(math.floor(math.log2(child+1)));c=rho**depth
  L[child,child]+=c;L[parent,parent]+=c;L[child,parent]-=c;L[parent,child]-=c
 return L
def r1():
 vals={}
 for rho in [.5,1,2]:
  e=np.linalg.eigvalsh(treeL(6,rho));vals[str(rho)]={'gap':float(e[1]),'max':float(e[-1]),'trace':float(e.sum())}
 names=['TreeVertices','EdgeConductanceFamily','DirichletEnergy','Positivity','ConstantKernel','SameCantorBoundary','SameBernoulliMeasure','SpectralWitness','SpectralVariation','GapVariation','HighModeVariation','EnergyModulus','TopologyDynamicsSplit','RoundOneVerdict','RoundOneRecommendation']
 rows=[('Constructed','Depth N full binary tree.',{'N':6,'vertices':127}),('Defined','c_l=rho^l.',{}),('Defined','E=1/2 sum c_e(df)^2.',{}),('Proven','L_rho positive semidefinite.',{}),('Proven','Connected tree has one zero mode.',{}),('Proven','All rho>0 share boundary topology.',{}),('Proven','Uniform branch measure independent of rho.',{}),('Computed','rho=.5,1,2.',{'spectra':vals}),('Proven counterexample','Same metric/measure can have different spectra.',{}),('Computed','Gaps differ by >14x.',{}),('Computed','Maximum eigenvalues differ by >100x.',{}),('No-go','rho is independent energy modulus.',{}),('Proven','Topology+measure do not determine dynamics.',{}),('Round verdict','Cantor geometry admits a family of Dirichlet forms.',{}),('Recommendation','Test scale axioms.',{})];emit(3342,names,rows)
def r2():
 names=['LayerEnergy','ConstantLayerEnergy','RhoHalf','ConstantEdgeEnergy','RhoOne','IncreasingConductance','ResistanceMetric','ResistanceCompletion','AxiomConflict','RemovalAudit','MetricRIndependence','TimeScale','PhysicalBoundary','RoundTwoVerdict','RoundTwoRecommendation']
 rows=[('Proven','Total unit-jump layer energy scales as (2rho)^l.',{}),('Axiom','Require constant total layer energy.',{}),('Conditional theorem','Then rho=1/2.',{}),('Axiom','Require constant conductance per edge.',{}),('Conditional theorem','Then rho=1.',{}),('Alternative','Fine-scale stiffening rho>1.',{}),('Conditional','Effective resistance depends rho.',{}),('Boundary','Finite/infinite resistance requires separate criterion.',{}),('Proven','Natural energy normalizations select incompatible rho.',{}),('Proven','Removing chosen normalization restores rho continuum.',{}),('No-go','Neither condition selects ultrametric r.',{}),('No-go','Global multiplier of energy remains clock.',{}),('Boundary','No joules/seconds.',{}),('Round verdict','Energy compatibility requires a declared normalization axiom.',{}),('Recommendation','Exponent relation.',{})];emit(3357,names,rows)
def r3():
 names=['MetricScale','MeasureScale','EnergyScale','DimensionD','EnergyExponent','RhoRelation','ParameterCount','OneConstraint','ResidualModulus','WalkDimension','SpectralDimension','EinsteinRelation','CompatibilityGate','RoundThreeVerdict','RoundThreeRecommendation']
 rows=[('Defined','delta_l=r^-l.',{}),('Proven','mu_l=2^-l=delta_l^D.',{}),('Defined','c_l=rho^l=delta_l^-sigma.',{}),('Proven','D=log2/logr.',{}),('Proven','sigma=logrho/logr.',{}),('Proven','rho=r^sigma.',{}),('Proven','Metric-energy family has r,sigma plus overall scale.',{}),('No-go','One scaling relation cannot select both.',{}),('Proven','At least one dimensionless modulus remains.',{}),('Conditional','Needs definition of diffusion time scaling.',{}),('Conditional','d_s=2D/d_w after extra heat-kernel hypotheses.',{}),('Boundary','Relation adds rather than derives d_w.',{}),('Fail','Metric+measure+energy scaling not unique.',{}),('Round verdict','Compatibility reduces coordinates but not theory dimension.',{}),('Recommendation','Test eta assignments.',{})];emit(3372,names,rows)
def r4():
 eta=1.8;names=['EtaDatum','EtaAsD','EtaAsSigma','EtaAsWalkDimension','ThreeRoutes','RouteValues','NonEquivalence','SpectralConsequences','KernelTailBoundary','LayerEnergyBoundary','LegacyBoundary','SelectionGate','EtaNoGo','RoundFourVerdict','RoundFourRecommendation']
 rows=[('Proven','Strict eta=1.8.',{}),('Route','D=eta -> r=2^(1/eta).',{'r':2**(1/eta)}),('Route','sigma=eta -> rho=r^eta.',{}),('Route','d_w=eta.',{}),('Proven','At least three typed assignments.',{}),('Computed','With r=2, sigma=eta gives rho.',{'rho':2**eta}),('Proven','Assignments give different metrics/dynamics.',{}),('Proven','Tree spectra change with rho.',{}),('Guardrail','Spatial tail exponent is not automatically layer D.',{}),('Guardrail','No energy theorem transfers eta.',{}),('Guardrail','Legacy D_f roles remain separate.',{}),('Fail','No strict semantic selector.',{}),('No-go','Eta alone cannot close metric-measure-energy triple.',{}),('Round verdict','One exponent cannot fill three independent roles without theorem.',{}),('Recommendation','Observer/heat tests.',{})];emit(3387,names,rows)
def r5():
 names=['HeatSemigroup','InternalClock','GlobalEnergyScale','CoarseProjection','Lumpability','BoundaryProcess','HeatKernelDimension','FiniteDepth','ObserverResolution','RecordRequirements','Calibration','Inference','SourceBoundary','RoundFiveVerdict','RoundFiveRecommendation']
 rows=[('Constructed','exp(-tL_rho).',{}),('Boundary','t dimensionless until scale fixed.',{}),('No-go','L->cL,t->t/c invariance.',{}),('Defined','Prefix averaging.',{}),('Boundary','Projected tree walk not generally Markov without symmetry/lumpability.',{}),('Conditional','Boundary process needs trace/limit construction.',{}),('Conditional','Spectral dimension needs asymptotic theorem.',{}),('No-go','Finite N spectra cannot prove continuum dimension.',{}),('Proven','Prefix depth controls accessible modes.',{}),('Boundary','Need timestamps and child-resolved records.',{}),('No-go','No SI units.',{}),('Conditional','Records may estimate rho/r ratios.',{}),('No-go','Estimation is not source.',{}),('Round verdict','Dirichlet form supports internal diffusion, not physical spacetime.',{}),('Recommendation','Synthesize.',{})];emit(3402,names,rows)
def r6():
 gate=ROOT/'FIN_ST3417_ST3431_CantorDirichletGate.json';g={'rows':[{'name':n,'pass':v} for n,v in [('Cantor Dirichlet family',True),('spectral nonuniqueness theorem',True),('scaling exponent relations',True),('canonical rho',False),('canonical r',False),('eta semantic assignment',False),('continuum heat kernel',False),('physical clock/energy',False),('observer apparatus',False),('OA evidence',False)]]};gate.write_text(json.dumps(g,indent=2)+'\n')
 names=['FamilyTheorem','SpectralNoGo','ScalingTheorem','NormalizationNoGo','EtaNoGo','ContinuumBoundary','PhysicalBoundary','Gate','GateScore','ProvenLedger','ConditionalLedger','RefutedLedger','HighestValueNext','FinalInterpretation','CycleTrigger']
 rows=[('Proven','rho-family of positive tree forms.',{}),('Proven','Same metric/measure different spectra.',{}),('Proven','D and sigma formulas.',{}),('No-go','Natural normalizations conflict.',{}),('No-go','Eta has multiple roles.',{}),('Boundary','No heat-kernel limit theorem.',{}),('No-go','No clock/energy units.',{}),('Constructed','Ten rows.',{'file':gate.name}),('Result','Three mathematical passes.',{'passes':3,'rows':10}),('Ledger','Family/nonuniqueness/scaling.',{}),('Ledger','Chosen r,rho and internal diffusion.',{}),('Ledger','Unique physical fractal dynamics.',{}),('Recommendation','Seek a new variational or renormalization fixed-point principle jointly selecting r and rho; otherwise freeze metric-energy family.',{}),('Final verdict','FIN supplies a natural fractal state space but not a unique resistance form or diffusion physics.',{'fundamental':False}),('Cycle complete','Release 11.21.',{'programs':90,'rounds':6,'range':'ST3342-ST3431','strict_ToE_closure':False,'gate_sha256':hashlib.sha256(gate.read_bytes()).hexdigest()})];emit(3417,names,rows)
def main():r1();r2();r3();r4();r5();r6()
if __name__=='__main__':main()
