#!/usr/bin/env python3
"""Five follow-up rounds for the strict-shape ternary Gibbs candidate."""
import hashlib,itertools,json,math,numpy as np
from fin_st2442_st2531_common import ROOT,data,law,write_packet,write_round
def emit(lo,names,rows):
 d={}
 for i,(s,b,p) in enumerate(rows):k=lo+i;d[f'ST{k}']=write_packet(k,names[i],s,b,p)
 write_round(lo,lo+14,d)
def r2():
 a=law(.2);b=law(-.2);names=['D12TensorCovariance','ReflectionEvenness','GlobalFlip','ThetaPolarity','PartitionEvenness','MeanOddness','EntropyEvenness','FisherEvenness','ScalarSourceNoGo','SpontaneousPair','FiniteVolumeBoundary','InitialConditionBoundary','PolarityGate','RoundTwoVerdict','RoundTwoRecommendation']
 rows=[('Proven','tau is strict D12 invariant.',{'covariant':True}),('Proven','Spatial reflection permutes faces without changing tau.',{'chiral':False}),('Proven','x->-x sends S->-S.',{'theta_map':'theta->-theta'}),('No-go','Pair core is even under global flip.',{'sign_selected':False}),('Proven','Configuration bijection.',{'logZ_plus':a['logZ'],'logZ_minus':b['logZ'],'residual':abs(a['logZ']-b['logZ'])}),('Proven','Derivative of even logZ.',{'S_plus':a['S_mean'],'S_minus':b['S_mean']}),('Proven','Entropy depends on |theta|.',{'selects_sign':False}),('Proven','I=Var(S) is even.',{'I_plus':a['S_var'],'I_minus':b['S_var']}),('Proven no-go','Existing alpha_geo, beta, eta and spectra are flip-even.',{'strict_theta_sign':False}),('Conditional','A double well yields +-theta branches.',{'unique_branch':False}),('Proven','Finite positive Z is analytic; no genuine finite-volume spontaneous phase transition.',{'phase_transition_finite':False}),('Boundary','Prepared nonzero state transfers sign.',{'source':'preparation'}),('Gate fail','No nonpremise polarity.',{'QW2191':False}),('Round verdict','Tensor shape is strict; theta polarity is an added sector datum.',{'strict_law':False}),('Recommendation','Classify convex stationary family and coefficient identifiability.',{'next':'finite exponential-family theorem'})];emit(2457,names,rows)
def r3():
 tau,X,Y,S=data();vals=[law(t) for t in (-1,-.2,0,.2,1)];names=['FiniteExponentialFamily','LogPartitionConvexity','FisherPositivity','MomentMapMonotonicity','ThetaIdentifiability','NoFiniteSingularity','MaximumEntropyCharacterization','CoefficientScale','TemperatureCoupling','DNLSComparison','NegativeInformationComparison','StabilityMeaning','SourceVsFit','RoundThreeVerdict','RoundThreeRecommendation']
 rows=[('Proven','4096-state regular exponential family.',{'support':4096}),('Proven','d2 logZ=Var(S)>0.',{'variances':[v['S_var'] for v in vals]}),('Proven','S nonconstant.',{'minimum_variance':min(v['S_var'] for v in vals)}),('Proven','Strict convexity.',{'theta_to_mean_injective':True}),('Conditional positive','A supplied empirical mean uniquely estimates theta.',{'source_theta':False}),('Proven','Finite sum of exponentials is entire/positive on real theta.',{'critical_singularity':False}),('Proven','p_theta maximizes entropy at supplied <S>.',{'constraint_supplied':True}),('No-go','Rescaling tau can be absorbed into theta.',{'absolute_coupling_identifiable_without_normalization':False}),('Boundary','Gibbs form theta=beta J needs bath and energy.',{'beta_J_strict':False}),('Different class','DNLS quartic amplitude law is not this three-bit Gibbs family.',{'equivalent':False}),('Different class','Active g is not theta without bridge.',{'equivalent':False}),('Boundary','Convex statistical identifiability is not dynamical Lyapunov stability.',{'dynamics_needed':True}),('Proven','Target moment fitting estimates but does not derive law.',{'fit_is_source':False}),('Round verdict','Conditional state family is mathematically complete; provenance remains one coupling/constraint plus polarity.',{'strict':False}),('Recommendation','Test prism refinement closure.',{'next':'six-bit prism marginal'})];emit(2472,names,rows)
def prism_effect(theta=.3,q=.2):
 states=np.array(list(itertools.product((-1,1),repeat=6)),float);b=states[:,:3];t=states[:,3:];H=theta*(np.prod(b,1)+np.prod(t,1))+q*np.sum(b*t,1);w=np.exp(H);# marginal bottom
 m={tuple(z):0 for z in itertools.product((-1,1),repeat=3)}
 for z,ww in zip(map(tuple,b.astype(int)),w):m[z]+=ww
 keys=list(m);logw=np.array([math.log(m[z]) for z in keys]);M=np.array([[1,*z,z[0]*z[1],z[0]*z[2],z[1]*z[2],z[0]*z[1]*z[2]] for z in keys],float);coef=np.linalg.solve(M,logw)
 return coef
def r4():
 c=prism_effect();names=['PrismLift','IndependentLayerClosure','VerticalPairCoupling','ExactMarginalWalsh','GeneratedOneBody','GeneratedPairBody','RenormalizedThreeBody','FamilyClosure','RefinementParameterQ','TwoStepCoherence','CoarseBlindness','PrimitiveIncidenceBoundary','RefinementGate','RoundFourVerdict','RoundFourRecommendation']
 rows=[('Constructed','Two triangle bases.',{'variables':6}),('Proven','q=0 factorizes; marginal preserves bottom theta.',{'closed':True}),('Constructed','q sum_i b_i t_i.',{'q_strict':False}),('Computed exact finite','Walsh coefficients of log marginal.',{'coefficients':c.tolist()}),('Proven cancellation','Symmetry cancels one-body terms.',{'max_abs':float(abs(c[1:4]).max())}),('Proven cancellation','All pair Walsh terms vanish.',{'max_abs':float(abs(c[4:7]).max())}),('Computed','Only the cubic coefficient changes.',{'theta_effective':float(c[7])}),('Proven exact closure','Top marginal depends only on bottom parity.',{'pure_family_closed':True,'formula':'theta_eff=theta+0.5*log[(e^theta A+e^-theta B)/(e^-theta A+e^theta B)]'}),('No-go','q is an additional vertical source.',{'strict_q':False}),('Conditional RG law','Closure holds but every level needs q_n or a strict recurrence.',{'path_unique':False}),('Proven','Coarse records cannot reconstruct hidden q.',{'prior_no_go_applies':True}),('Conditional','Prism fixes cells and closure shape, not coefficients.',{'source_coefficients':False}),('Gate fail','No unique 12-24-48 transport without q_n law.',{'coherent_strict_transport':False}),('Round verdict','Symmetric prism marginalization exactly closes the ternary family; q remains unsourced.',{'single_missing_scalar_refuted':True,'closure_breakthrough':True}),('Recommendation','Audit dual dynamics and OA.',{'next':'channel realization'})];emit(2487,names,rows)
def r5():
 names=['UnitaryChannel','HeatChannel','GibbsStationarity','GlauberRealization','DetailedBalanceRates','BathRequirement','ParityInstrument','PairInstrumentNoGo','FiniteSampleSpec','RawRecord','DualDynamicsBoundary','TimeScale','PhysicalEnergy','RoundFiveVerdict','RoundFiveRecommendation']
 rows=[('Boundary','U_t acts on complex amplitudes, not this classical Gibbs law.',{'stationary_general':False}),('Boundary','P_t is vertex diffusion, not 12-bit configuration dynamics.',{'stationary_general':False}),('No-go','p_theta is not automatically stationary for either channel.',{'common_A_sufficient':False}),('Conditional construction','Single-bit-flip Glauber dynamics can realize p_theta.',{'generator_added':True}),('Conditional','Rates require theta and clock normalization.',{'strict_rates':False}),('Boundary','Thermodynamic Gibbs interpretation needs bath/temperature.',{'bath_strict':False}),('Proven','Joint triangle parity sees theta.',{'observable':'x_i x_j x_k'}),('Proven','Pair-only records lose irreducible information.',{'Fisher_at_zero_for_pair':0}),('Conditional','Shot bound depends on effect size and confidence.',{'calibration_needed':True}),('Executable spec','Keep run, three bits, face, layer, time, config.',{'fields':7}),('Proven','Shared A does not make U/P/Glauber identical.',{'dualism_preserved':True}),('No-go','Dimensionless rate does not supply seconds.',{'clock_strict':False}),('No-go','theta dimensionless does not supply joules.',{'energy_strict':False}),('Round verdict','An operational mathematical model exists only after a new configuration-space dynamics and apparatus.',{'physical_evidence':False}),('Recommendation','Synthesize gate.',{'next':'source theorem or no-go'})];emit(2502,names,rows)
def r6():
 gate=ROOT/'FIN_ST2517_ST2531_TernaryGibbsSourceGate.json';g={'rows':[{'name':n,'pass':v} for n,v in [('strict tau tensor',True),('finite nonGaussian family',True),('nonzero connected triangle response',True),('strict theta magnitude',False),('strict theta polarity',False),('unique refinement q law',False),('closure under coarse graining',False),('dual-channel realization',False),('physical units',False),('OA evidence',False)]]};gate.write_text(json.dumps(g,indent=2)+'\n')
 names=['CandidateObject','StrictContent','ConditionalContent','ThetaNoGo','PolarityNoGo','RefinementNoGo','ChannelNoGo','OperationalBoundary','Gate','GateScore','SingleScalarHypothesis','StopRules','HighestValueNext','FinalInterpretation','CycleTrigger']
 rows=[('Constructed','Strongest current ternary candidate.',{'law':'p proportional exp(theta sum tau_f Y_f)'}),('Proven','tau shape and D12 covariance.',{'strict':['tau']}),('Constructed','theta family and parity instrument.',{'conditional':['theta','state law','instrument']}),('No-go','No current scalar sources magnitude.',{'strict_theta':False}),('No-go','Global flip pairs signs.',{'strict_polarity':False}),('No-go','Prism q generates extra interactions.',{'unique_transport':False}),('No-go','U/P do not realize configuration Gibbs dynamics.',{'extra_generator':True}),('Boundary','No external record.',{'evidence':False}),('Gate constructed','Ten rows.',{'file':gate.name}),('Gate result','Three mathematical rows pass.',{'passes':3,'rows':10}),('Refuted','Theta is not the only missing object after refinement.',{'single_missing_scalar':False}),('Stop','Do not call conditional Gibbs law strict physics.',{'stop':['theta=alpha_geo','theta=eta','Gibbs=heat','prism=transport theorem']}),('Recommendation','A new strict configuration-space generator with sourced detailed-balance affinity and refinement closure is required.',{'next':'strict Markov generator source or impossibility theorem'}),('Final verdict','FIN pair tensor determines interaction shape, not statistical law, sign, refinement or physics.',{'fundamental_physics':False}),('Cycle complete','Release 11.11.',{'programs':90,'rounds':6,'range':'ST2442-ST2531','strict_ToE_closure':False,'gate_sha256':hashlib.sha256(gate.read_bytes()).hexdigest()})];emit(2517,names,rows)
def main():r2();r3();r4();r5();r6()
if __name__=='__main__':main()
