#!/usr/bin/env python3
"""Build the archival LaTeX source for the executed FIN Programs 21--30."""

from pathlib import Path
import re

import fin_monograph_to_latex as converter


SOURCE = Path("FIN_Programs_21_30_Executed_Monograph.md")
TARGET = Path("FIN_Programs_21_30_Executed_Monograph.tex")


PREAMBLE = r"""\documentclass[11pt,a4paper,openany]{report}

\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{microtype}
\usepackage{amsmath,amssymb,amsthm,mathtools,bm}
\usepackage{booktabs,array,longtable,tabularx}
\usepackage{xcolor}
\usepackage[margin=24mm,headheight=23pt]{geometry}
\usepackage{enumitem}
\usepackage{fancyhdr}
\usepackage{fancyvrb}
\usepackage{graphicx}
\usepackage{url}
\usepackage{hyperref}

\definecolor{finblue}{HTML}{1F5A99}
\definecolor{fingreen}{HTML}{19733A}
\definecolor{finorange}{HTML}{D55E00}
\definecolor{finred}{HTML}{A61B1B}
\definecolor{finviolet}{HTML}{6A3D9A}
\definecolor{fingray}{HTML}{4D4D4D}

\hypersetup{
  unicode=true,
  colorlinks=true,
  linkcolor=finblue,
  citecolor=fingreen,
  urlcolor=finblue,
  pdftitle={FIN Beyond the Spectral Core: Executed Programs 21--30},
  pdfauthor={Krzysztof Żuchowski},
  pdfsubject={Executed FIN Programs 21--30, operational falsification, and inverse reconstruction of an action from the strict kernel},
  pdfkeywords={FIN, process tensor, Dirichlet form, graph Dirac operator, reflection positivity, inverse action, operator theory, operational physics}
}

\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\small FIN Beyond the Spectral Core}
\fancyhead[R]{\small Release 10.2}
\fancyfoot[C]{\thepage}
\setlength{\parindent}{0pt}
\setlength{\parskip}{0.55em}
\setlist{nosep,leftmargin=2em}
\setcounter{tocdepth}{2}
\setcounter{secnumdepth}{3}
\emergencystretch=2em

\newcommand{\one}{\bm 1}
\newcommand{\C}{\mathbb C}
\newcommand{\R}{\mathbb R}
\newcommand{\Z}{\mathbb Z}
\newcommand{\statusProven}{\textcolor{fingreen}{[Proven]}}
\newcommand{\statusStrong}{\textcolor{finblue}{[Strong evidence]}}
\newcommand{\statusModerate}{\textcolor{finviolet}{[Moderate evidence]}}
\newcommand{\statusWeak}{\textcolor{fingray}{[Weak evidence]}}
\newcommand{\statusSpeculative}{\textcolor{finorange}{[Speculative]}}
\newcommand{\statusRefuted}{\textcolor{finred}{[Refuted]}}

\begin{document}
\hypersetup{pageanchor=false}
\begin{titlepage}
\centering
\vspace*{12mm}
{\Large\bfseries FIN Research Supplement --- Release 10.2\par}
\vspace{12mm}
{\Huge\bfseries FIN Beyond the Spectral Core\par}
\vspace{6mm}
{\Large Executed Programs 21--30, Operational Falsification, and Inverse Reconstruction of an Action from the Strict Kernel\par}
\vspace{18mm}
{\Large Krzysztof Żuchowski\par}
\vspace{2mm}
{\normalsize Independent Researcher --- Fractal Information Theory Project\par}
\vspace{2mm}
{\normalsize ORCID: \href{https://orcid.org/0009-0002-0909-3613}{0009-0002-0909-3613}\par}
\vspace{10mm}
{\large 19 July 2026\par}
{\normalsize Publication --- Preprint; record version 1.0.0\par}
\vfill
\begin{minipage}{0.88\textwidth}
\small
\textbf{Scope.} Ten executed mathematical and computational studies continuing the FIN theory synthesis. The report separates proof, numerical evidence, conjecture, and refutation. Synthetic tests are not represented as hardware experiments or evidence for fundamental physics.

\medskip
\textbf{Repository.} \url{https://github.com/hyconiek/Fractal-Nadsoliton-Theory}

\textbf{Reproducibility.} The release includes the deterministic numerical suite, JSON results, figures, Markdown source, LaTeX source, and checksums.

\textbf{License.} Creative Commons Attribution 4.0 International (CC BY 4.0).

\textbf{Zenodo DOI.} To be assigned to this record.
\end{minipage}
\vfill
\end{titlepage}
\hypersetup{pageanchor=true}

\pagenumbering{roman}
\chapter*{Publication statement}
\addcontentsline{toc}{chapter}{Publication statement}
This preprint executes Programs 21--30 from the preceding FIN roadmap and adds a rigorous inverse-action audit. It is self-contained: all finite operator definitions, assumptions, formulas, counterexamples, confidence labels, and reproducibility information required for the results are included here. It does not claim a legacy--strict bridge, selector closure, physical units, Lorentz symmetry, a physical quantum field theory, or a Theory of Everything.

\tableofcontents
\clearpage
\pagenumbering{arabic}
"""


POSTAMBLE = r"""
\clearpage
\chapter*{Archival note}
\addcontentsline{toc}{chapter}{Archival note}
The numerical record accompanying this report is \path{FIN_Programs_21_30_Results.json}. It is generated by \path{fin_programs_21_30_experiments.py}. The program uses explicit twelve-mode radial values and declared synthetic models; it does not import repository verdicts.

\medskip
\noindent\textbf{Suggested citation before DOI assignment:}

Żuchowski, K. (2026). \emph{FIN Beyond the Spectral Core: Executed Programs 21--30, Operational Falsification, and Inverse Reconstruction of an Action from the Strict Kernel} (FIN Research Supplement, Release 10.2; Version 1.0.0) [Preprint]. Zenodo. DOI to be assigned.

\end{document}
"""


FIGURES = {
    "FINFIGUREP21": (
        "FIN_Programs_21_30_Figures/program21_confusion.png",
        "Intervention-aware finite-shot classification for the four declared Program 21 models. Rows are true models and columns are maximum-likelihood predictions.",
    ),
    "FINFIGUREP22": (
        "FIN_Programs_21_30_Figures/program22_positive_refinement.png",
        "The raw strict analytic continuation changes sign, while the anchored exponential completion remains positive. Both agree on the twelve-mode anchors.",
    ),
    "FINFIGUREP23": (
        "FIN_Programs_21_30_Figures/program23_dirac_dispersion.png",
        "Positive incidence-Dirac dispersion compared with its low-momentum linear limit.",
    ),
    "FINFIGUREP28": (
        "FIN_Programs_21_30_Figures/program28_adaptive_jacobian.png",
        "Selected diagnostics of the finite-time covariance Jacobian. The large antisymmetric part obstructs an exact covariance potential.",
    ),
    "FINFIGUREACTION": (
        "FIN_Programs_21_30_Figures/inverse_action_residual.png",
        "Distance-resolved residual of the Frobenius-optimal contact-subtracted screened-resolvent fit.",
    ),
}


def figure_latex(filename: str, caption: str) -> str:
    return (
        "\\begin{figure}[htbp]\n"
        "\\centering\n"
        f"\\includegraphics[width=0.82\\textwidth]{{{filename}}}\n"
        f"\\caption{{{caption}}}\n"
        "\\end{figure}"
    )


def main() -> None:
    source = SOURCE.read_text(encoding="utf-8")
    # LaTeX supplies section numbers.  Remove the prose ordinals used by the
    # Markdown edition so that headings do not read, for example, "13.4 4.".
    source = re.sub(r"^(#{2,4})\s+\d+\.\s+", r"\1 ", source, flags=re.MULTILINE)
    # The shared structural converter accepts indented CommonMark code blocks.
    source = re.sub(
        r"```(?:text)?\n(.*?)```",
        lambda match: "\n".join("    " + line for line in match.group(1).rstrip().splitlines()),
        source,
        flags=re.DOTALL,
    )
    body = converter.body_from_markdown(source)
    body = body.replace(
        r"\section{Confidence convention}",
        r"\chapter*{Confidence convention}\addcontentsline{toc}{chapter}{Confidence convention}",
        1,
    )
    for token, (filename, caption) in FIGURES.items():
        if token not in body:
            raise ValueError(f"Missing figure token: {token}")
        body = body.replace(token, figure_latex(filename, caption))
    TARGET.write_text(PREAMBLE + "\n" + body + "\n" + POSTAMBLE, encoding="utf-8")
    print(f"wrote {TARGET} ({TARGET.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
