#!/usr/bin/env python3
"""Build the archival LaTeX source for FIN Programs 31--40."""

from pathlib import Path
import re

import fin_monograph_to_latex as converter


SOURCE = Path("FIN_Programs_31_40_Negative_Information_Coupling.md")
TARGET = Path("FIN_Programs_31_40_Negative_Information_Coupling.tex")


PREAMBLE = r"""\documentclass[11pt,a4paper,openany]{report}

\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{microtype}
\usepackage{amsmath,amssymb,amsthm,mathtools,bm}
\usepackage{booktabs,array,longtable,tabularx}
\usepackage{xcolor}
\usepackage[margin=24mm,headheight=23pt]{geometry}
\usepackage{enumitem}
\usepackage{fancyhdr}
\usepackage{fancyvrb}
\usepackage{graphicx}
\usepackage{url}
\usepackage{hyperref}

\definecolor{finblue}{HTML}{1F5A99}
\definecolor{fingreen}{HTML}{19733A}
\definecolor{finorange}{HTML}{D55E00}
\definecolor{finred}{HTML}{A61B1B}
\definecolor{finviolet}{HTML}{6A3D9A}
\definecolor{fingray}{HTML}{4D4D4D}

\hypersetup{
  unicode=true,
  colorlinks=true,
  linkcolor=finblue,
  citecolor=fingreen,
  urlcolor=finblue,
  pdftitle={FIN Negative Information Coupling: Executed Programs 31--40},
  pdfauthor={Krzysztof Żuchowski},
  pdfsubject={Negative information coupling, the legacy-to-strict bridge, operational loss, and executed FIN Programs 31--40},
  pdfkeywords={FIN, negative information coupling, legacy kernel, strict kernel, Markov semigroup, Lindblad dynamics, information loss, feedback, system identification}
}

\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\small FIN Negative Information Coupling}
\fancyhead[R]{\small Release 10.3}
\fancyfoot[C]{\thepage}
\setlength{\parindent}{0pt}
\setlength{\parskip}{0.55em}
\setlist{nosep,leftmargin=2em}
\setcounter{tocdepth}{2}
\setcounter{secnumdepth}{3}
\emergencystretch=2em

\newcommand{\one}{\bm 1}
\newcommand{\C}{\mathbb C}
\newcommand{\R}{\mathbb R}
\newcommand{\Z}{\mathbb Z}
\newcommand{\statusProven}{\textcolor{fingreen}{[Proven]}}
\newcommand{\statusStrong}{\textcolor{finblue}{[Strong evidence]}}
\newcommand{\statusModerate}{\textcolor{finviolet}{[Moderate evidence]}}
\newcommand{\statusWeak}{\textcolor{fingray}{[Weak evidence]}}
\newcommand{\statusSpeculative}{\textcolor{finorange}{[Speculative]}}
\newcommand{\statusRefuted}{\textcolor{finred}{[Refuted]}}

\begin{document}
\hypersetup{pageanchor=false}
\begin{titlepage}
\centering
\vspace*{10mm}
{\Large\bfseries FIN Research Supplement --- Release 10.3\par}
\vspace{11mm}
{\Huge\bfseries FIN Negative Information Coupling\par}
\vspace{6mm}
{\Large Executed Programs 31--40, the Legacy-to-Strict Bridge, and the Operational Meaning of Information Loss\par}
\vspace{17mm}
{\Large Krzysztof Żuchowski\par}
\vspace{2mm}
{\normalsize Independent Researcher --- Fractal Information Theory Project\par}
\vspace{2mm}
{\normalsize ORCID: \href{https://orcid.org/0009-0002-0909-3613}{0009-0002-0909-3613}\par}
\vspace{10mm}
{\large 19 July 2026\par}
{\normalsize Publication --- Preprint; record version 1.0.0\par}
\vfill
\begin{minipage}{0.88\textwidth}
\small
\textbf{Scope.} Ten executed mathematical and computational studies of a conditional negative-information-coupling extension. The report distinguishes static attenuation, stochastic contraction, open-system information transfer, feedback, and fundamental deletion.

\medskip
\textbf{Repository.} \url{https://github.com/hyconiek/Fractal-Nadsoliton-Theory}

\textbf{Guardrail.} The legacy kernel is treated as an intended intermediate precursor, not as an already proven identity with the strict kernel. No role transfer, selector closure, physical unit, or Theory-of-Everything claim is made.

\textbf{Reproducibility.} Code, JSON results, nine figures, Markdown, LaTeX, Zenodo description, and checksums accompany the PDF.

\textbf{License.} Creative Commons Attribution 4.0 International (CC BY 4.0).

\textbf{Zenodo DOI.} To be assigned to this record.
\end{minipage}
\vfill
\end{titlepage}
\hypersetup{pageanchor=true}

\pagenumbering{roman}
\chapter*{Publication statement}
\addcontentsline{toc}{chapter}{Publication statement}
This preprint executes Programs 31--40 and tests negative information coupling as a new conditional bridge component. It is self-contained and reports proofs, numerical evidence, counterexamples, identifiability limits, and reproducibility artifacts. It does not claim a completed legacy--strict bridge, transfer of legacy physical roles, a strict selector, physical units, fundamental information destruction, hardware validation, or a Theory of Everything.

\tableofcontents
\clearpage
\pagenumbering{arabic}
"""


POSTAMBLE = r"""
\clearpage
\chapter*{Archival note}
\addcontentsline{toc}{chapter}{Archival note}
The machine-readable record is \path{FIN_Programs_31_40_Negative_Information_Results.json}. It is generated by \path{fin_programs_31_40_negative_information.py}. All calculations are dimensionless and use declared finite models.

\medskip
\noindent\textbf{Suggested citation before DOI assignment:}

Żuchowski, K. (2026). \emph{FIN Negative Information Coupling: Executed Programs 31--40, the Legacy-to-Strict Bridge, and the Operational Meaning of Information Loss} (FIN Research Supplement, Release 10.3; Version 1.0.0) [Preprint]. Zenodo. DOI to be assigned.

\end{document}
"""


FIGURES = {
    "FINFIGUREP31": (
        "FIN_Programs_31_40_Figures/program31_loss_bridge.png",
        "Canonical legacy and strict radial rows. Positive attenuation preserves signs and therefore cannot supply the missing phase transformation.",
    ),
    "FINFIGUREP32": (
        "FIN_Programs_31_40_Figures/program32_legacy_spectrum.png",
        "Spectrum of the raw signed legacy Laplacian candidate on the twelve-cycle. Eleven nonconstant eigenvalues are negative.",
    ),
    "FINFIGUREP33": (
        "FIN_Programs_31_40_Figures/program33_hazard.png",
        "Exact legacy-to-strict envelope retention, fitted candidate laws, and the positive discrete hazard sequence.",
    ),
    "FINFIGUREP34": (
        "FIN_Programs_31_40_Figures/program34_stability_cone.png",
        "Markov-rate and spectral boundaries for exponential retention and linear subtraction.",
    ),
    "FINFIGUREP35": (
        "FIN_Programs_31_40_Figures/program35_information_ledger.png",
        "Reduced-system information, environment entropy, and mutual information for the explicit isometric dilation.",
    ),
    "FINFIGUREP36": (
        "FIN_Programs_31_40_Figures/program36_sign_gauge.png",
        "System and environment sign-discrimination diagnostics. Symmetric-bath system dynamics is exactly sign blind.",
    ),
    "FINFIGUREP38": (
        "FIN_Programs_31_40_Figures/program38_wave_diffusion.png",
        "Linear diffusive versus quadratic unitary escape and a phase-sensitive double-path record.",
    ),
    "FINFIGUREP39": (
        "FIN_Programs_31_40_Figures/program39_identifiability.png",
        "Profile likelihood for the signed coupling with and without a calibrated reference channel.",
    ),
    "FINFIGUREP40": (
        "FIN_Programs_31_40_Figures/program40_confusion.png",
        "Confusion matrix for the four-model blinded synthetic held-out challenge.",
    ),
}


def _normalize_promoted_math(expression: str) -> str:
    """Restore TeX commands lost in the historical parenthetical notation."""
    expression = re.sub(
        r"(?<!\\)\bmathcal\s+([A-Za-z])(?=_|\b)",
        r"\\mathcal{\1}",
        expression,
    )
    for name in (
        "alpha", "beta", "gamma", "delta", "epsilon", "eta", "theta",
        "lambda", "mu", "pi", "rho", "sigma", "tau", "phi", "psi", "omega",
    ):
        expression = re.sub(
            rf"(?<!\\)\b{name}(?=_|\b)",
            rf"\\{name}",
            expression,
        )
    return expression


def _looks_like_math(expression: str) -> bool:
    expression = expression.strip()
    if not expression or "%" in expression or expression.startswith(("http://", "https://")):
        return False
    if expression.startswith("mathcal "):
        return True
    if any(character in expression for character in ("\\", "_", "^", "=", "<", ">", "|")):
        return True
    if re.search(r"[+-]?\d+\.\d+", expression) and not re.search(r"[A-Za-z]{2,}", expression):
        return True
    if re.fullmatch(r"(?:[+-]\d+|\d+/\d+)", expression):
        return True
    return expression in {
        "0", "A", "B", "c", "d", "g", "h", "i", "j", "p", "q", "r", "t", "u",
        "gamma", "eta", "tau", "epsilon", "sigma", "delta", "alpha", "beta",
    }


def promote_parenthesized_math(source: str) -> str:
    """Convert the draft's ``(formula)`` convention to real inline TeX.

    Display equations are left untouched.  A function-form pass precedes the
    simple-parenthesis pass so expressions such as ``(K_ell(d))`` remain one
    mathematical span rather than acquiring nested delimiters.
    """
    function_pattern = re.compile(r"\(([^()\n]+?)\(([^()\n]*)\)\)")
    simple_pattern = re.compile(r"\(([^()\n]+)\)")
    lines: list[str] = []
    in_display = False

    def function_replacement(match: re.Match[str]) -> str:
        expression = f"{match.group(1)}({match.group(2)})"
        if not _looks_like_math(expression):
            return match.group(0)
        return r"\(" + _normalize_promoted_math(expression) + r"\)"

    def simple_replacement(match: re.Match[str]) -> str:
        expression = match.group(1)
        if not _looks_like_math(expression):
            return match.group(0)
        return r"\(" + _normalize_promoted_math(expression) + r"\)"

    for line in source.splitlines(keepends=True):
        stripped = line.strip()
        if stripped == r"\[":
            in_display = True
            lines.append(line)
            continue
        if stripped == r"\]":
            in_display = False
            lines.append(line)
            continue
        if in_display:
            lines.append(line)
            continue
        protected_manual: dict[str, str] = {}
        for raw, replacement in {
            r"((W_\ell)_{xy}\ge0)": r"\((W_\ell)_{xy}\ge0\)",
            r"((1+cd)^{-p})": r"\((1+cd)^{-p}\)",
            r"((1+bd^\eta)^{-1})": r"\((1+bd^\eta)^{-1}\)",
        }.items():
            if raw in line:
                token = f"FINMANUAL{len(protected_manual):04d}TOKEN"
                protected_manual[token] = replacement
                line = line.replace(raw, token)
        promoted_functions: dict[str, str] = {}

        def protect_function(match: re.Match[str]) -> str:
            replacement = function_replacement(match)
            if replacement == match.group(0):
                return replacement
            token = f"FININLINE{len(promoted_functions):04d}TOKEN"
            promoted_functions[token] = replacement
            return token

        line = function_pattern.sub(protect_function, line)
        line = simple_pattern.sub(simple_replacement, line)
        for token, replacement in promoted_functions.items():
            line = line.replace(token, replacement)
        for token, replacement in protected_manual.items():
            line = line.replace(token, replacement)
        lines.append(line)
    return "".join(lines)


def figure_latex(filename: str, caption: str) -> str:
    return (
        "\\begin{figure}[htbp]\n"
        "\\centering\n"
        f"\\includegraphics[width=0.82\\textwidth]{{{filename}}}\n"
        f"\\caption{{{caption}}}\n"
        "\\end{figure}"
    )


def main() -> None:
    source = SOURCE.read_text(encoding="utf-8")
    source = promote_parenthesized_math(source)
    source = re.sub(r"^(#{2,4})\s+\d+(?:\.\d+)*\.?\s+", r"\1 ", source, flags=re.MULTILINE)
    source = re.sub(
        r"```(?:text)?\n(.*?)```",
        lambda match: "\n".join("    " + line for line in match.group(1).rstrip().splitlines()),
        source,
        flags=re.DOTALL,
    )
    body = converter.body_from_markdown(source)
    body = body.replace(
        r"\section{Confidence convention}",
        r"\chapter*{Confidence convention}\addcontentsline{toc}{chapter}{Confidence convention}",
        1,
    )
    for token, (filename, caption) in FIGURES.items():
        if token not in body:
            raise ValueError(f"Missing figure token: {token}")
        body = body.replace(token, figure_latex(filename, caption))
    TARGET.write_text(PREAMBLE + "\n" + body + "\n" + POSTAMBLE, encoding="utf-8")
    print(f"wrote {TARGET} ({TARGET.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
