#!/usr/bin/env python3
"""Five rounds: positive exponential-mixture/Hausdorff moment obstruction."""
import hashlib,json,math,numpy as np
from fin_st2172_st2261_common import ROOT,write_packet,write_round
def emit(lo,names,rows):
 d={}
 for i,(s,b,p) in enumerate(rows):k=lo+i;d[f'ST{k}']=write_packet(k,names[i],s,b,p)
 assert len(rows)==15;write_round(lo,lo+14,d)
strict=np.array([math.cos(.18575*d+.1625)/(1+d**1.8) for d in range(1,7)])
H1=np.array([[strict[i+j] for j in range(3)] for i in range(3)])
H2=np.array([[strict[i+j+1] for j in range(3)] for i in range(3)])
e1=np.linalg.eigvalsh(H1);e2=np.linalg.eigvalsh(H2)
def r1():
 arrays=[];a=strict.copy()
 for k in range(6):arrays.append((((-1)**k)*a).tolist());a=np.diff(a)
 names=['StrictSequence','Monotone','FirstDifferences','SecondDifferences','ThirdDifferences','FourthDifferences','FifthDifference','FiniteCompleteMonotonicity','MinimumMargin','NaivePass','HausdorffRepresentation','NecessityOnly','ScreeningBoundary','RoundOneVerdict','RoundOneRecommendation']
 rows=[('Loaded','Six strict weights.',{'values':strict.tolist()}),('Proven','Strictly decreasing positive.',{}),('Computed','Positive alternating.',{'values':arrays[1]}),('Computed','Positive.',{'values':arrays[2]}),('Computed','Positive.',{'values':arrays[3]}),('Computed','Positive.',{'values':arrays[4]}),('Computed','Positive.',{'values':arrays[5]}),('Pass screening','All available alternating differences positive.',{}),('Computed','Smallest finite-difference margin.',{'margin':min(min(x) for x in arrays)}),('Warning','Finite difference screen suggests but does not prove extendibility.',{}),('Target','K(d)=integral x^d dmu, mu>=0.',{}),('Proven','Moment positivity conditions additionally necessary.',{}),('Boundary','Truncated sequence tests require Hankel/localizing matrices.',{}),('Round verdict','Elementary monotonicity does not decide the positive-mixture question.',{}),('Recommendation','Hankel test.',{})];emit(3822,names,rows)
def r2():
 names=['ShiftedHankel1','ShiftedHankel2','MomentGramMeaning','PSDRequirement','EigenvaluesH1','EigenvaluesH2','DeterminantH1','DeterminantH2','FirstObstruction','SecondObstruction','HausdorffNoGo','ExponentialMixtureNoGo','StieltjesBoundary','RoundTwoVerdict','RoundTwoRecommendation']
 rows=[('Constructed','[K(i+j+1)] i,j=0..2.',{'matrix':H1.tolist()}),('Constructed','[K(i+j+2)] i,j=0..2.',{'matrix':H2.tolist()}),('Proven','Would be Gram integrals of x powers.',{}),('Proven necessity','Both must be PSD for positive measure.',{}),('Computed high margin','H1.',{'eigenvalues':e1.tolist()}),('Computed high margin','H2.',{'eigenvalues':e2.tolist()}),('Computed','Negative.',{'det':float(np.linalg.det(H1))}),('Computed','Negative.',{'det':float(np.linalg.det(H2))}),('Proven numerical certificate','lambda min H1<0.',{'lambda_min':float(e1[0])}),('Proven numerical certificate','lambda min H2<0.',{'lambda_min':float(e2[0])}),('No-go','No positive measure on [0,1] matches six values.',{}),('No-go','No positive mixture of decaying exponentials matches exactly.',{}),('Boundary','Signed measures remain possible but lose positivity.',{}),('Round verdict','Strict six-point data already obstruct completely monotone positive tails.',{}),('Recommendation','Robustness/repair size.',{})];emit(3837,names,rows)
def r3():
 eps1=abs(e1[0])/3;eps2=abs(e2[0])/3
 names=['EntryPerturbation','OperatorNormBound','H1RepairLowerBound','H2RepairLowerBound','JointRepairBound','RelativeSmallWeight','RoundingRobustness','ParameterUncertainty','PSDProjection','FitTradeoff','ExactMatchConflict','ApproximateMixture','RepairNotDerivation','RoundThreeVerdict','RoundThreeRecommendation']
 rows=[('Defined','Every moment changes by at most epsilon.',{}),('Proven','3x3 matrix perturbation norm <=3epsilon.',{}),('Proven','Need epsilon>=|lambda_min(H1)|/3.',{'epsilon':eps1}),('Proven','Need epsilon>=|lambda_min(H2)|/3.',{'epsilon':eps2}),('Proven','Both require at least max lower bound.',{'epsilon':max(eps1,eps2)}),('Computed','Relative to K(6).',{'fraction':max(eps1,eps2)/strict[-1]}),('Proven','Ordinary floating/decimal rounding far below bound.',{}),('Boundary','Large model uncertainty could repair but changes frozen data.',{}),('Conditional','Nearest PSD moments define an approximation problem.',{}),('No-go','Objective/norm selects different repairs.',{}),('Proven','Exact strict match incompatible with positive mixture.',{}),('Conditional','Approximate exponential mixture possible after deformation.',{}),('Boundary','Fitting is not a source law.',{}),('Round verdict','Moment obstruction is quantitatively robust.',{}),('Recommendation','Legacy and signed alternatives.',{})];emit(3852,names,rows)
def r4():
 al=4*math.log(2);leg=np.array([al*math.cos(math.pi*d/4+math.pi/6)/(1+.01*d) for d in range(1,7)]);b=abs(leg);L1=np.array([[b[i+j] for j in range(3)] for i in range(3)]);L2=np.array([[b[i+j+1] for j in range(3)] for i in range(3)])
 names=['LegacySequence','LegacySignNoGo','AbsoluteLegacy','AbsoluteHankel1','AbsoluteHankel2','AbsoluteNoGo','SignedMeasure','JordanDecomposition','PositivityLoss','OscillatoryExponentials','ComplexPoles','StrictLegacySplit','NoRoleTransfer','RoundFourVerdict','RoundFourRecommendation']
 rows=[('Loaded','Canonical legacy d1..6.',{'values':leg.tolist()}),('Immediate no-go','Negative values cannot be positive moments.',{}),('Tested','Absolute values.',{}),('Computed','Still indefinite.',{'eigenvalues':np.linalg.eigvalsh(L1).tolist()}),('Computed','Still indefinite.',{'eigenvalues':np.linalg.eigvalsh(L2).tolist()}),('No-go','Absolute legacy also not positive Hausdorff moments.',{}),('Possible','Finite signed measure can fit moments.',{}),('Boundary','Positive-minus-negative parts nonunique.',{}),('No-go','Signed representation is not Markov/positive mixture.',{}),('Possible','Complex/signed exponentials encode oscillations.',{}),('Boundary','Not a positive relaxation spectrum.',{}),('Guardrail','Results differ but both positive-mixture routes fail.',{}),('Guardrail','No physical role transfer.',{}),('Round verdict','Legacy does not rescue a positive exponential-mixture foundation.',{}),('Recommendation','Synthesize continuation consequences.',{})];emit(3867,names,rows)
def r5():
 gate=ROOT/'FIN_ST3882_ST3896_HausdorffMomentGate.json';g={'rows':[{'name':n,'pass':v} for n,v in [('finite difference screen',True),('Hankel obstruction theorem',True),('robust repair lower bound',True),('exact positive measure',False),('exact positive exponential mixture',False),('strict Stieltjes tail',False),('legacy positive mixture',False),('unique approximate repair',False),('physical continuum selection',False),('OA evidence',False)]]};gate.write_text(json.dumps(g,indent=2)+'\n')
 names=['ScreeningResult','HankelTheorem','RobustnessTheorem','StrictNoGo','LegacyNoGo','SignedAlternative','ApproximateBoundary','Gate','GateScore','ProvenLedger','ConditionalLedger','RefutedLedger','HighestValueNext','FinalInterpretation','CycleTrigger']
 rows=[('Proven','Alternating differences all positive but insufficient.',{}),('Proven','Two shifted Hankel matrices indefinite.',{}),('Proven','Uniform repair at least 3.67e-4.',{}),('No-go','No exact positive Hausdorff/Stieltjes mixture.',{}),('No-go','Legacy/absolute legacy fail.',{}),('Conditional','Signed/complex mixtures possible.',{}),('Boundary','Approximate repair needs loss/prior.',{}),('Constructed','Ten rows.',{'file':gate.name}),('Result','Three mathematical passes.',{'passes':3,'rows':10}),('Ledger','Finite screen/Hankel/robustness.',{}),('Ledger','Deformed approximate mixtures.',{}),('Ledger','Exact positive spectral relaxation foundation.',{}),('Recommendation','Do not pursue positive exponential-mixture tails without modifying frozen weights; next test should classify positive local continuations under exact finite matching by a different principle.',{}),('Final verdict','The strict finite kernel is positive as a graph but not a truncated completely monotone moment sequence.',{'fundamental':False}),('Cycle complete','Release 11.25.',{'programs':75,'rounds':5,'range':'ST3822-ST3896','strict_ToE_closure':False,'gate_sha256':hashlib.sha256(gate.read_bytes()).hexdigest()})];emit(3882,names,rows)
def main():r1();r2();r3();r4();r5()
if __name__=='__main__':main()
