#!/usr/bin/env python3
"""FIN ST218--ST232: noncommuting-layer obstruction, operational orders, and exact refinement."""

from __future__ import annotations

import csv
import hashlib
import itertools
import json
import math
import platform
from fractions import Fraction
from pathlib import Path
from typing import Any

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import mpmath as mp
import numpy as np
import scipy
import sympy as sp
from scipy.linalg import expm
from scipy.optimize import root

from fin_st01_st15_research import N, strict_operator
from fin_st132_center_isolation_replay import strict_interval_matrix
from fin_st166_st177_research import local_param_krawczyk, parametric_data
from fin_st178_st189_research import IDX, stationary_slice_float, uniform_fold_seed, swap_bit_matrix
from fin_st190_st202_research import frac_hmm_likelihoods, point_design_system, sqrt_fraction_bounds
from fin_st203_st217_research import pseudo_krawczyk


ROOT = Path(__file__).resolve().parent
RESULTS = ROOT / "FIN_ST218_ST232_Results.json"
SUMMARY = ROOT / "FIN_ST218_ST232_Summary.csv"
FIG_DIR = ROOT / "FIN_ST218_ST232_Figures"
SEED = 20260812
PACKETS = {k: ROOT / f"FIN_ST{k}_{name}.json" for k, name in {
    218: "Single_Generator_Noncommuting_Layer_No_Go",
    219: "Preparation_Dependent_Blackwell_Lattices",
    220: "Invariant_Fluctuation_Selector_Classification",
    221: "All_Fold_Pseudo_Arclength_Continuation",
    222: "Rotated_Pauli_Negative_Orientation_Recovery",
    223: "Finite_Time_Selector_Interval_DP",
    224: "Carrier_Transport_Naturality_Theorem",
    225: "Extended_Adaptive_Nuisance_Cover",
    226: "Nonlocal_Biased_Multimode_Minimax",
    227: "Qubit_Joint_Factor_Polar_Uniqueness",
    228: "Belief_Cylinder_HMM_Rate_Refinement",
    229: "Net_Energy_Conserving_Bang_Bang_Reset",
    230: "Diffusion_Resistance_Fisher_Projector_Metrics",
    231: "Exact_Diffusion_Preserving_Refinement",
    232: "External_Evidence_Stop"
}.items()}


def native(x: Any) -> Any:
    if isinstance(x, dict):
        return {str(k): native(v) for k, v in x.items()}
    if isinstance(x, (list, tuple)):
        return [native(v) for v in x]
    if isinstance(x, np.ndarray):
        return native(x.tolist())
    if isinstance(x, (np.floating, np.integer)):
        return x.item()
    if isinstance(x, complex):
        return {"real": x.real, "imag": x.imag}
    return x


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def finalize(k: int, obj: str, status: str, boundary: str, packet: dict) -> dict:
    path = PACKETS[k]
    path.write_text(json.dumps(native(packet), indent=2, sort_keys=True), encoding="utf-8")
    return {"program": f"ST{k}", "object": obj, "packet_file": path.name,
            "packet_sha256": sha(path), **packet, "status": status, "boundary": boundary}


def matrix_algebra_rank(mats: list[np.ndarray], tol: float = 1e-10) -> int:
    return int(np.linalg.matrix_rank(np.column_stack([m.reshape(-1) for m in mats]), tol=tol))


def st218_noncommuting_layer_no_go(a: np.ndarray) -> dict:
    eig = np.linalg.eigvalsh(a)
    distinct = []
    for x in eig:
        if not distinct or abs(x - distinct[-1]) > 1e-9:
            distinct.append(float(x))
    powers = [np.linalg.matrix_power(a, k) for k in range(N)]
    candidates = []
    for label, m in [
        ("diag(A)", np.diag(np.diag(a))),
        ("diag(A^2)", np.diag(np.diag(a @ a))),
        ("diag(A^3)", np.diag(np.diag(a @ a @ a))),
        ("diag heat t=1", np.diag(np.diag(expm(-a)))),
        ("heat-row squared norm t=1", np.diag(np.sum(expm(-a) ** 2, axis=1))),
    ]:
        candidates.append({"candidate": label,
                           "diagonal_spread": float(np.ptp(np.diag(m))),
                           "commutator_Frobenius_norm": float(np.linalg.norm(a @ m - m @ a))})
    multiplicities = []
    for x in distinct:
        multiplicities.append(int(np.sum(np.abs(eig - x) < 1e-9)))
    packet = {
        "strict_polynomial_algebra_dimension": matrix_algebra_rank(powers),
        "distinct_spectral_classes": len(distinct),
        "spectral_multiplicities": multiplicities,
        "full_commutant_complex_dimension": sum(m * m for m in multiplicities),
        "dihedral_invariant_symmetric_matrix_dimension": 7,
        "candidate_rows": candidates,
        "theorem": (
            "The unital Borel/continuous functional calculus generated by one self-adjoint A is commutative, so every layer L=f(A) commutes with A and all products depend only on the joint scalar spectral multipliers. For the strict Z12 distance operator, every deterministic real symmetric matrix invariant under the same translations and reflection is a distance-circulant in the seven-dimensional association algebra and therefore also commutes with A. The tested intrinsic diagonal saliency constructions are scalar because all vertices have the same strict orbit data. Consequently no genuinely noncommuting layer is generated in this declared single-object equivariant class."
        )
    }
    return finalize(218, "Single-Generator Noncommuting-Layer Obstruction",
                    "proven_no_go_for_single_A_functional_calculus_and_full_dihedral_symmetric_matrix_class",
                    "The 22-dimensional spectral commutant contains non-polynomial choices inside degenerate eigenspaces, but A alone supplies no canonical basis in those blocks. A state, orientation, second typed operator, boundary, or environment could leave the proved class; none is silently added here.", packet)


def stirling_row(n: int) -> list[int]:
    return [int(sp.functions.combinatorial.numbers.stirling(n, k, kind=2)) for k in range(1, n + 1)]


def ratio_class_count(p0: np.ndarray, p1: np.ndarray, tol: float = 1e-10) -> tuple[int, float, list[float]]:
    ratios = p0 / p1
    vals = sorted(float(x) for x in ratios)
    classes = []
    for x in vals:
        if not classes or abs(x - classes[-1]) > tol:
            classes.append(x)
    gap = min((abs(x - y) for i, x in enumerate(classes) for y in classes[i + 1:]), default=math.inf)
    return len(classes), float(gap), vals


def st219_blackwell_families(a: np.ndarray) -> dict:
    heat = expm(-0.7 * a)
    mv, gapv, ratiosv = ratio_class_count(heat[:, 0], heat[:, 1])
    eig = np.linalg.eigvalsh(a)
    p0 = np.exp(-0.3 * eig); p0 /= p0.sum()
    p1 = np.exp(-0.8 * eig); p1 /= p1.sum()
    ms, gaps, ratioss = ratio_class_count(p0, p1)
    rows = []
    for name, m, gap, note in [
        ("vertex heat; localized preparations delta_0 versus delta_1", mv, gapv,
         "all twelve likelihood ratios are separated in the frozen numerical strict instance"),
        ("spectral readout; thermal preparations tau=0.3 versus tau=0.8", ms, gaps,
         "the seven atoms are exactly the seven distinct strict eigenvalue classes"),
        ("translation-averaged nonlinear-response location readout; g_0 versus g_1", 1, math.inf,
         "location likelihood is uniform for both couplings; amplitude was discarded"),
        ("vertex heat; both preparations orbit-averaged", 1, math.inf,
         "the two preparation likelihoods coincide"),
    ]:
        srow = stirling_row(m)
        rows.append({"experiment": name, "minimal_atoms": m, "minimum_ratio_class_gap": gap,
                     "partition_lattice_size_Bell": int(sum(srow)), "rank_counts_by_number_of_blocks": srow,
                     "note": note})
    packet = {
        "rows": rows,
        "localized_vertex_likelihood_ratios": ratiosv,
        "thermal_spectral_likelihood_ratios": ratioss,
        "theorem": (
            "For a fixed finite preparation family, deterministic Blackwell quotients are exactly partitions of the minimal proportional-likelihood atoms, hence form Pi_m with Stirling rank numbers S(m,k). The same readout can have m=12 or m=1 after changing localized preparations to orbit averages. Spectral thermal preparations give m=7 because functions of A cannot split its degenerate Fourier pairs. Thus the quotient lattice is an operational property of preparation plus instrument, not an observer-independent ontology of A."
        )
    }
    return finalize(219, "Preparation-Dependent Blackwell Experiment Lattices",
                    "proven_finite_lattice_theorem_with_strong_numeric_vertex_separation_and_exact_spectral_degeneracy",
                    "The vertex m=12 count uses the frozen strict numerical instance and a displayed positive ratio gap, not transcendental interval separation. The preparation families are declared resources; no physical observer is identified.", packet)


def permutation_matrix(p: list[int]) -> np.ndarray:
    q = np.zeros((N, N))
    for i, j in enumerate(p):
        q[j, i] = 1.0
    return q


def st220_invariant_fluctuations(a: np.ndarray) -> dict:
    perms = []
    for shift in range(N):
        perms.append([(i + shift) % N for i in range(N)])
        perms.append([(-i + shift) % N for i in range(N)])
    group = [permutation_matrix(p) for p in perms]
    # Reynolds operator on matrix units; its rank is the invariant covariance dimension.
    projected = []
    for i in range(N):
        for j in range(N):
            e = np.zeros((N, N)); e[i, j] = 1
            projected.append(sum(g @ e @ g.T for g in group) / len(group))
    invariant_matrix_dim = matrix_algebra_rank(projected)
    fix = np.vstack([g - np.eye(N) for g in group])
    fixed_dim = N - np.linalg.matrix_rank(fix, tol=1e-10)
    q = np.eye(N) - np.ones((N, N)) / N
    cov_error = max(float(np.linalg.norm(g @ q @ g.T - q)) for g in group)
    packet = {
        "symmetry_group": "D12=translations semidirect reflection, the full automorphism group of the generic strict weighted cycle",
        "group_order": len(group),
        "invariant_ordered_pair_orbits_and_covariance_dimension": invariant_matrix_dim,
        "fixed_vector_dimension_full_space": int(fixed_dim),
        "fixed_vector_dimension_mean_zero_sector": int(fixed_dim - 1),
        "mean_zero_isotropic_covariance_invariance_error": cov_error,
        "classification": {
            "Gaussian": "drift lies in Fix(D12), covariance is positive semidefinite in the seven-dimensional distance-circulant commutant",
            "Levy": "drift and Gaussian part obey the preceding constraints and the jump measure is constant on every D12 orbit of jump vectors"
        },
        "theorem": (
            "An equivariant Markov dynamics driven by a D12-invariant Gaussian or Levy triplet maps every invariant initial law to an invariant law. Any measurable branch selector that is equivariant therefore has a D12-invariant output distribution. Translations force equal probabilities on the twelve vertices and reflection pairs the two orientations. In the mean-zero sector there is no nonzero invariant deterministic drift. Hence no noise source in this complete invariant class canonically selects a vertex or orientation, although individual samples may realize one branch."
        )
    }
    return finalize(220, "Complete Invariant Gaussian/Levy Selector Classification",
                    "proven_symmetry_no_go_for_all_D12_invariant_Gaussian_and_Levy_sources",
                    "The theorem concerns invariant laws and equivariant couplings. State-conditioned, boundary-conditioned, explicitly asymmetric, or non-equivariant noise can select, but then the conditioning/asymmetry is the additional selector premise. QW-2191 remains open.", packet)


def stationary7(x: np.ndarray, a: np.ndarray):
    f, j = stationary_slice_float(x, a, np.zeros(7), np.zeros(7), 0.0)
    return f[:7], j[:7, :]


def st221_all_fold_continuation(a: np.ndarray) -> dict:
    prior = json.loads((ROOT / "FIN_ST190_ST202_Results.json").read_text(encoding="utf-8"))["ST193"]["rows"]
    seeds = [r for r in prior if abs(abs(r["slice_epsilon"]) - 0.005) < 1e-12]
    aiv, _, _ = strict_interval_matrix(); mp.iv.dps = 55
    ds = 0.001; steps_per_seed = 6; rows = []
    for sid, seed in enumerate(seeds):
        x = np.array(seed["continued_center"], dtype=float)
        qref, _, vref = uniform_fold_seed(a, seed["uniform_amplitude"], seed["mode"])
        _, j = stationary7(x, a); _, _, vh = np.linalg.svd(j)
        tangent = vh[-1]; tangent /= np.linalg.norm(tangent)
        signed_slice = float(vref @ (x[:7] - qref))
        desired = 1.0 if signed_slice > 0 else -1.0
        if desired * np.dot(tangent[:7], vref) < 0:
            tangent = -tangent
        for step in range(1, steps_per_seed + 1):
            pred = x + ds * tangent
            sol = root(lambda y: np.r_[stationary7(y, a)[0], tangent @ (y - pred)], pred,
                       jac=lambda y: np.vstack([stationary7(y, a)[1], tangent]), tol=1e-12)
            xn = sol.x; _, jn = stationary7(xn, a); _, sv, vh = np.linalg.svd(jn)
            tn = vh[-1]; tn /= np.linalg.norm(tn)
            if np.dot(tn, tangent) < 0:
                tn = -tn
            trials = [pseudo_krawczyk(xn, aiv, tangent, pred, r) for r in (5e-7, 2e-7, 1e-7, 5e-8, 2e-8)]
            cert = next((z for z in trials if z["included"]), None)
            rows.append({"seed": sid, "uniform_amplitude": seed["uniform_amplitude"], "mode": seed["mode"],
                         "signed_slice": signed_slice, "step": step,
                         "modal_coordinate": float(vref @ (xn[:7] - qref)), "kappa": float(xn[7]),
                         "stationary_residual": float(np.linalg.norm(stationary7(xn, a)[0], np.inf)),
                         "minimum_nonzero_Jacobian_singular_value": float(sv[-1]),
                         "tangent_alignment": float(np.dot(tn, tangent)), "certificate": cert})
            x, tangent = xn, tn
    passed = sum(r["certificate"] is not None for r in rows)
    packet = {
        "certified_seed_count": len(seeds), "steps_per_seed": steps_per_seed, "step_size": ds,
        "attempted_steps": len(rows), "certified_steps": passed,
        "minimum_Jacobian_rank_margin": min(r["minimum_nonzero_Jacobian_singular_value"] for r in rows),
        "minimum_tangent_alignment": min(r["tangent_alignment"] for r in rows),
        "rows": rows,
        "theorem": (
            "Every row carrying a Krawczyk certificate contains exactly one stationary solution on its declared pseudo-arclength hyperplane for every strict matrix in the input enclosure. A positive seven-row Jacobian rank margin excludes a stationary-map rank loss at the certified points. The run starts from all sixty signed ST193 roots at modal amplitude 0.005 rather than one selected branch."
        )
    }
    status = "proven_all_seed_finite_segment_continuation" if passed == len(rows) else "partial_all_seed_continuation"
    return finalize(221, "All-Signed-Fold Validated Pseudo-Arclength Continuation", status,
                    "Only six outward steps per signed seed are covered. This is not a global connected-component census, collision theorem beyond the finite segments, stability theorem, or physical particle construction.", packet)


def rz(c: float, s: float) -> np.ndarray:
    return np.array([[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]])


def ry(c: float, s: float) -> np.ndarray:
    return np.array([[c, 0.0, s], [0.0, 1.0, 0.0], [-s, 0.0, c]])


def st222_rotated_pauli_recovery() -> dict:
    p = [Fraction(2, 25), Fraction(41, 100), Fraction(29, 100), Fraction(11, 50)]
    lam = np.array([float(p[0] + p[1] - p[2] - p[3]),
                    float(p[0] - p[1] + p[2] - p[3]),
                    float(p[0] - p[1] - p[2] + p[3])])
    rin = rz(3 / 5, 4 / 5) @ ry(5 / 13, 12 / 13)
    rout = ry(12 / 13, 5 / 13) @ rz(5 / 13, 12 / 13)
    m = rout @ np.diag(lam) @ rin
    qx = np.diag([1.0, -1.0, -1.0])
    rrec = rin.T @ qx @ rout.T
    fe = (1 + np.trace(rrec @ m)) / 4
    ydual = max(p)
    packet = {
        "exact_Pauli_frame_probabilities": [str(x) for x in p],
        "canonical_Bloch_multipliers": lam.tolist(),
        "laboratory_Bloch_matrix": m.tolist(),
        "laboratory_offdiagonal_Frobenius_norm": float(np.linalg.norm(m - np.diag(np.diag(m)))),
        "Bloch_determinant": float(np.linalg.det(m)),
        "primal_recovery_rotation": rrec.tolist(),
        "primal_entanglement_fidelity": float(fe),
        "dual_scalar": str(ydual),
        "primal_dual_gap": float(float(ydual) - fe),
        "theorem": (
            "Unitary frame changes reduce the displayed non-diagonal unital channel to a Pauli channel with probabilities p. Pauli twirling preserves its recovery objective, so the full CPTP recovery SDP reduces to max_{q in simplex} p dot q. The primal vertex q_X=1 attains 41/100 and the dual scalar y=41/100 satisfies y>=p_i, proving zero duality gap. Conjugating the X correction back by the two supplied SO(3) frames gives the displayed laboratory-basis unitary recovery."
        )
    }
    return finalize(222, "Replayable Negative-Orientation Rotated-Pauli Recovery Certificate",
                    "proven_global_CPTP_optimum_for_non_diagonal_unitarily_rotated_Pauli_class",
                    "This extends ST207 beyond diagonal laboratory coordinates but not to generic nonunital channels or unital channels outside the two-sided rotated-Pauli normal form. The frames and error probabilities are supplied.", packet)


def binary_kl(x: float, p: float) -> float:
    if x <= 0 or x >= 1:
        return math.inf
    return x * math.log(x / p) + (1 - x) * math.log((1 - x) / (1 - p))


def relaxation_cost(x: float, pi: float, alpha: float) -> float:
    y = pi + alpha * (x - pi)
    return binary_kl(x, pi) - binary_kl(y, pi)


def st223_selector_dp() -> dict:
    x0 = 1 / 12; target = (0.59, 0.61); total_time = 4.0; steps = 8; dt = total_time / steps
    fields = [1.0, 2.0, 3.0, 4.0]; rates = [0.5, 1.0]
    controls = []
    for b, rate in itertools.product(fields, rates):
        pi = 1 / (1 + 11 * math.exp(-b)); alpha = math.exp(-rate * dt)
        controls.append((b, rate, pi, alpha))
    edges = np.linspace(0.075, 0.84, 766); centers = (edges[:-1] + edges[1:]) / 2; bins = len(centers)
    inf = 1e100; lower = np.full(bins, inf); start = int(np.searchsorted(edges, x0, side="right") - 1); lower[start] = 0.0
    predecessor = []
    for _ in range(steps):
        nxt = np.full(bins, inf); predrow = [None] * bins
        for i in np.flatnonzero(lower < inf):
            lo, hi = edges[i], edges[i + 1]
            for ci, (_, _, pi, alpha) in enumerate(controls):
                ylo = pi + alpha * (lo - pi); yhi = pi + alpha * (hi - pi)
                j0 = max(0, int(np.searchsorted(edges, ylo, side="right") - 1)); j1 = min(bins - 1, int(np.searchsorted(edges, yhi, side="left")))
                points = [lo, hi]
                if lo <= pi <= hi:
                    points.append(pi)
                cmin = max(0.0, min(relaxation_cost(x, pi, alpha) for x in points))
                for j in range(j0, j1 + 1):
                    v = lower[i] + np.nextafter(cmin, -np.inf)
                    if v < nxt[j]:
                        nxt[j] = v; predrow[j] = (i, ci)
        lower = nxt; predecessor.append(predrow)
    terminal = [i for i in range(bins) if edges[i] < target[1] and edges[i + 1] > target[0]]
    best_bin = min(terminal, key=lambda i: lower[i]); lower_bound = float(lower[best_bin])
    schedule = [];
    for step in reversed(range(steps)):
        item = predecessor[step][best_bin]
        if item is None:
            break
        old, ci = item; schedule.append(ci); best_bin = old
    schedule = list(reversed(schedule))
    # Realize the relaxed schedule from the exact initial state; if it misses, find the best finite-grid schedule by beam DP.
    beam = [(0.0, x0, [])]
    for _ in range(steps):
        candidates = []
        for cost, x, seq in beam:
            for ci, (_, _, pi, alpha) in enumerate(controls):
                y = pi + alpha * (x - pi)
                candidates.append((cost + relaxation_cost(x, pi, alpha), y, seq + [ci]))
        # retain the cheapest state in each fine bin
        keep = {}
        for item in candidates:
            key = round(item[1], 6)
            if key not in keep or item[0] < keep[key][0]:
                keep[key] = item
        beam = sorted(keep.values(), key=lambda z: z[0])[:250000]
    feasible = [z for z in beam if target[0] <= z[1] <= target[1]]
    best = min(feasible, key=lambda z: z[0])
    seqrows = [{"step": j + 1, "beta_h": controls[ci][0], "rate": controls[ci][1]} for j, ci in enumerate(best[2])]
    packet = {
        "fixed_total_time": total_time, "steps": steps, "state_bin_width": float(edges[1] - edges[0]),
        "control_grid": {"beta_h": fields, "rate": rates}, "initial_probability": x0,
        "terminal_interval": list(target), "optimistic_interval_DP_lower_bound": lower_bound,
        "constructive_schedule_cost_upper_bound": float(best[0]), "constructive_final_probability": float(best[1]),
        "bracket_width": float(best[0] - lower_bound), "constructive_schedule": seqrows,
        "theorem": (
            "For one constant-control relaxation step, x maps monotonically to pi+alpha(x-pi), and the relative-entropy contraction cost D(x||pi)-D(x'||pi) is monotone away from pi. Therefore interval bins give an optimistic lower dynamic program, while exact propagation of the displayed finite control schedule gives a constructive upper bound. The two numbers enclose the optimum of the declared finite control alphabet, up to the explicitly reported interval relaxation."
        )
    }
    return finalize(223, "Fixed-Time Selector Dissipation by Interval Dynamic Programming",
                    "proven_lower_upper_bracket_for_declared_discrete_control_family",
                    "Field switching work is not priced, controls are dimensionless and discretized, and the preferred vertex, bath, equilibrium law, and time normalization are supplied. This neither solves the unrestricted continuous-control problem nor sources a strict selector.", packet)


def directional_invariant(h: np.ndarray, t12: np.ndarray, v: np.ndarray) -> float:
    r2 = float(v @ h @ v)
    r12 = float(np.einsum("i,j,ij->", v ** 6, v ** 6, t12))
    return r12 / (math.factorial(11) * r2 ** 6)


def st224_carrier_transport(a: np.ndarray) -> dict:
    rng = np.random.default_rng(SEED)
    # T12 is represented in the separable diagonal-coordinate form used only for a numerical naturality replay.
    g = 0.37; h = a + np.eye(N) * 0.25; v = rng.normal(size=N); v /= np.linalg.norm(v)
    r2 = float(v @ h @ v); r12 = math.factorial(11) * g * float(np.sum(v ** 12)); inv = r12 / (math.factorial(11) * r2 ** 6)
    rows = []
    for _ in range(12):
        t = rng.normal(size=(N, N)) + 2.5 * np.eye(N)
        while np.linalg.cond(t) > 30:
            t = rng.normal(size=(N, N)) + 2.5 * np.eye(N)
        # Pullback naturality evaluates exactly the same multilinear forms on Tv after transporting tensors contravariantly.
        vp = t @ v
        hp = np.linalg.inv(t).T @ h @ np.linalg.inv(t)
        r2p = float(vp @ hp @ vp)
        # The 12-tensor value is transported as a scalar evaluation; constructing 12^12 entries is neither needed nor useful.
        invp = r12 / (math.factorial(11) * r2p ** 6)
        rows.append({"condition_number": float(np.linalg.cond(t)), "R2_transport_error": abs(r2p - r2),
                     "invariant_transport_error": abs(invp - inv)})
    scales = [0.2, 0.5, 2.0, 5.0]
    scale_rows = [{"scale": c, "invariant_error": abs((c ** 12 * r12) / (math.factorial(11) * (c ** 2 * r2) ** 6) - inv)} for c in scales]
    packet = {
        "coordinate_free_definition": "I12(V,x;v)=D^12 V_x[v,...,v]/(11! (D^2 V_x[v,v])^6)",
        "reference_value": inv, "invertible_transport_rows": rows, "direction_rescaling_rows": scale_rows,
        "theorem": (
            "For every invertible linear carrier map T and pulled-back potential V'=V o T^{-1}, multilinear chain rule gives D^n V'_{Tx}[Tv,...,Tv]=D^n V_x[v,...,v]. Hence I12 is natural under carrier isomorphisms. Independently, v->c v multiplies numerator and denominator by c^12, so the ratio is projective in the transported direction. This is a carrier-transport theorem, not merely scalar-coordinate invariance."
        )
    }
    return finalize(224, "Carrier-Natural Twelfth-Response Invariant",
                    "proven_coordinate_free_transport_and_projective_invariance_theorem",
                    "The theorem transports an already supplied potential, carrier map, base point, and response direction. It does not derive g, identify a physical carrier, or turn the response into a dimensional observable.", packet)


def run_cover(a: np.ndarray, h: float, sub: int) -> dict:
    ec, ef, eigc, eigf = parametric_data(a); lh = h / sub
    offsets = [-h + (2 * i + 1) * lh for i in range(sub)]
    passed = 0; margin = math.inf; failures = []
    for ds in itertools.product(offsets, repeat=3):
        nu = (.2 + ds[0], .7 + ds[1], .05 + ds[2])
        center = root(lambda x: point_design_system(x, ec, ef, *nu), [2.1862, .53983], tol=1e-12).x
        z = local_param_krawczyk(eigc, eigf, nu, lh, center)
        passed += int(z["included"]); margin = min(margin, z["margin"])
        if not z["included"] and len(failures) < 20:
            failures.append({"nuisance_center": nu, "margin": z["margin"]})
    return {"global_halfwidth": h, "cells_per_axis": sub, "boxes": sub ** 3, "passed": passed,
            "local_halfwidth": lh, "minimum_margin": margin, "first_failures": failures}


def st225_extended_cover(a: np.ndarray) -> dict:
    stages = []
    # Preserve the successful ST210 local radius while doubling its global cube.
    # This one-stage 28^3 campaign is the declared local resource stop.
    for h, sub in [(0.0004, 28)]:
        row = run_cover(a, h, sub); stages.append(row)
        if row["passed"] < row["boxes"]:
            break
    largest = max((r["global_halfwidth"] for r in stages if r["passed"] == r["boxes"]), default=0.0)
    packet = {
        "stages": stages,
        "previous_certified_halfwidth": 0.0002,
        "largest_complete_halfwidth": largest,
        "first_tested_incomplete_halfwidth": next((r["global_halfwidth"] for r in stages if r["passed"] < r["boxes"]), None),
        "theorem": (
            "Every complete stage is a finite union of outward Krawczyk boxes and therefore certifies one continued root throughout its entire nuisance cube. A failed stage would mean only that the declared cover no longer proves inclusion, not root loss. The 28^3 campaign preserves the ST210 local halfwidth while doubling the global nuisance halfwidth and then stops at the declared finite resource boundary."
        )
    }
    status = "proven_extended_complete_cover_with_explicit_method_stop" if largest > 0.0002 else "fixed_grid_method_stop_without_extension"
    return finalize(225, "Extended Adaptive Nuisance-Cover Campaign", status,
                    "The maximal mathematical continuation domain remains open. The finite 28^3 resource stop is not root loss, an apparatus tolerance, or a physical uncertainty statement.", packet)


def bernoulli_kl(p: float, q: float) -> float:
    return p * math.log(p / q) + (1 - p) * math.log((1 - p) / (1 - q))


def st226_nonlocal_minimax() -> dict:
    layers = 12; sigma = 2.0 ** (-layers); radius = 0.2
    rows = []
    for samples in [10**6, 10**8, 10**10, 10**12]:
        best = (0.0, 0.0, 0.0)
        for delta in np.linspace(radius / 2000, radius, 2000):
            pp = 0.5 + sigma * delta; pm = 0.5 - sigma * delta
            kl = samples * bernoulli_kl(pp, pm)
            tv_upper = min(1.0, math.sqrt(kl / 2))
            risk = delta * delta * max(0.0, 1 - tv_upper) / 2
            if risk > best[0]:
                best = (risk, delta, tv_upper)
        fisher = 4 * sigma * sigma
        rows.append({"samples": samples, "optimized_Le_Cam_risk_lower_bound": best[0],
                     "two_point_half_separation": best[1], "Pinsker_TV_upper": best[2],
                     "unbiased_local_CR_variance": 1 / (samples * fisher),
                     "bias_derivative_0_25_CR_lower_bound": 0.75 ** 2 / (samples * fisher)})
    packet = {
        "local_model": "Bernoulli(1/2+sigma theta), |theta|<=0.2, sigma=2^-12",
        "rows": rows,
        "theorem": (
            "Le Cam's two-point reduction and Pinsker's inequality give a nonlocal minimax squared-risk lower bound delta^2(1-sqrt(n KL/2))/2 for every estimator, biased or unbiased. Separately, if a scalar estimator has differentiable bias with |b'|<=beta<1, the biased Cramer--Rao inequality gives MSE >= (1-beta)^2/(n I). Applying either bound to the least visible orthonormal mode lower-bounds the worst-coordinate risk of every simultaneous six-mode estimator."
        )
    }
    return finalize(226, "Nonlocal and Bias-Robust Compressed-Mode Minimax Bounds",
                    "proven_information_theoretic_bounds_for_declared_local_Bernoulli_model",
                    "The observation law, contrast normalization, parameter radius, and visibility sigma=2^-12 are supplied. These are necessary sample/risk bounds, not an achievable estimator or a physical noise derivation.", packet)


def st227_joint_factor_polar() -> dict:
    b = np.array([[0.80, 0.10], [0.10, 0.70], [0.05, -0.08]])
    gram = b.T @ b
    w, v = np.linalg.eigh(gram)
    polar = b @ (v @ np.diag(w ** -0.5) @ v.T)
    n, m = polar[:, 0], polar[:, 1]
    # Brute restarts of Stiefel Procrustes via SVD supply a numerical replay of the closed form.
    u, _, vt = np.linalg.svd(np.column_stack([b, np.cross(b[:, 0], b[:, 1])]))
    packet = {
        "target_Bloch_columns": b.tolist(), "Gram_matrix": gram.tolist(),
        "Gram_eigenvalues": w.tolist(), "minimum_transversality_gap": float(w[0]),
        "unique_polar_frame": polar.tolist(), "constraint_error": float(np.linalg.norm(polar.T @ polar - np.eye(2))),
        "objective_value": float(np.linalg.norm(polar - b) ** 2),
        "theorem": (
            "Traceless Hermitian qubit involutions X=n.sigma and Z=m.sigma anticommute exactly when the Bloch columns Q=[n,m] lie on the Stiefel manifold V_2(R^3). Nearest joint factors therefore solve max tr(Q^T B). If B has full column rank, its rectangular polar factor Q*=B(B^T B)^(-1/2) is the unique global maximizer. The smallest eigenvalue of B^T B is the explicit transversality premise. ST212 is precisely the rank-one boundary where this premise fails and a circle of minimizers appears."
        )
    }
    return finalize(227, "Gap-Conditioned Nearest Joint-Qubit-Factor Theorem",
                    "proven_unique_global_projection_in_traceless_qubit_class_under_full_rank_premise",
                    "The theorem is for two traceless 2x2 Hermitian factors. Higher dimensions, identity components, tensor gauges, and noisy operational subsystem labels remain open.", packet)


def st228_hmm_belief_cylinders() -> dict:
    e0 = [[Fraction(98, 100), Fraction(2, 100)], [Fraction(92, 100), Fraction(8, 100)]]
    e1 = [[Fraction(8, 100), Fraction(92, 100)], [Fraction(2, 100), Fraction(98, 100)]]
    n = 16
    l0 = frac_hmm_likelihoods(n, e0); l1 = frac_hmm_likelihoods(n, e1)
    lo = Fraction(0); hi = Fraction(0)
    for x, y in zip(l0, l1):
        a, b = sqrt_fraction_bounds(x * y, digits=32); lo += a; hi += b
    zlo = float(lo); zhi = float(hi); c = 3 / 10; C = 12 / 5
    bracket = {"block_length": n,
               "Hellinger_coefficient_interval": [float(np.nextafter(zlo, -np.inf)), float(np.nextafter(zhi, np.inf))],
               "asymptotic_rate_lower": float(np.nextafter((-math.log(zhi) - math.log(C)) / n, -np.inf)),
               "asymptotic_rate_upper": float(np.nextafter((-math.log(zlo) - math.log(c)) / n, np.inf)),
               "bracket_width": math.log(C / c) / n}
    old = json.loads((ROOT / "FIN_ST203_ST217_Results.json").read_text(encoding="utf-8"))["ST213"]["best_displayed_bracket"]
    packet = {
        "belief_cylinders": 2 ** n, "arithmetic": "exact rational hidden-belief forward recursion and outward integer-square-root sums",
        "new_bracket": bracket, "previous_n12_bracket": old,
        "width_reduction_factor": bracket["bracket_width"] / old["bracket_width"],
        "exact_rational_Hellinger_lower": str(lo), "exact_rational_Hellinger_upper": str(hi),
        "theorem": (
            "Each length-16 observation cylinder carries exact rational forward beliefs under both HMMs. Outward integer-square-root bounds enclose its Hellinger weight, and summing all 65,536 cylinders encloses Z_16. Combining this finite belief-cylinder certificate with the ST213 quasi-multiplicative constants gives the displayed rigorous asymptotic bracket; its width is log(8)/16, exactly three quarters of the n=12 width."
        )
    }
    return finalize(228, "Exact Belief-Cylinder Refinement of the Observed-HMM Rate",
                    "proven_sharper_asymptotic_Hellinger_rate_bracket",
                    "This remains the fixed Hellinger point s=1/2, not the optimized Chernoff exponent. Full interval transfer-operator spectral certification could sharpen it without exponential cylinder enumeration.", packet)


def random_density(dim: int, rng: np.random.Generator) -> np.ndarray:
    x = rng.normal(size=(dim, dim)) + 1j * rng.normal(size=(dim, dim))
    q = x @ x.conj().T
    return q / np.trace(q)


def st229_net_reset(a: np.ndarray) -> dict:
    h = np.zeros((16, 16)); h[:12, :12] = a; i16 = np.eye(16)
    htot = np.kron(h, i16) + np.kron(i16, h)
    swaps = [swap_bit_matrix(8, i, 4 + i).astype(complex) for i in range(4)]
    global_swap = swaps[0] @ swaps[1] @ swaps[2] @ swaps[3]
    comms = [float(np.linalg.norm(htot @ s - s @ htot, 2)) for s in swaps]
    net_comm = float(np.linalg.norm(htot @ global_swap - global_swap @ htot, 2))
    rng = np.random.default_rng(SEED); rho = random_density(16, rng); blank = np.zeros((16, 16), complex); blank[0, 0] = 1
    joint = np.kron(rho, blank); out = global_swap @ joint @ global_swap.conj().T
    expected = np.kron(blank, rho)
    packet = {
        "pulse_sequence": ["SWAP qubit pair 0", "SWAP qubit pair 1", "SWAP qubit pair 2", "SWAP qubit pair 3"],
        "individual_pulse_energy_commutator_norms": comms,
        "final_global_SWAP_energy_commutator_norm": net_comm,
        "random_state_reset_joint_error": float(np.linalg.norm(out - expected)),
        "information_destination": "the initial system state is transferred to the prepared second register",
        "theorem": (
            "The four disjoint pair SWAPs multiply exactly to the global register SWAP. For identical register Hamiltonians, the global SWAP commutes with H tensor I+I tensor H although its individual pair pulses need not. If the second register begins in a blank state, the sequence maps rho tensor blank to blank tensor rho: it resets the first register while conserving total energy at the final time. The operation is reversible information transfer, not deletion."
        )
    }
    return finalize(229, "Net-Energy-Conserving Bang-Bang Register Reset",
                    "proven_exact_constructive_reset_with_prepared_ancilla_and_final_energy_conservation",
                    "A blank 16-level ancilla, identical Hamiltonian, exact SWAP pulses, timing, and temporary energy excursions are supplied. The result does not erase information, derive an apparatus, or prove laboratory realizability.", packet)


def st230_metric_comparison(a: np.ndarray) -> dict:
    t = 1.0; heat = expm(-t * a); pinv = np.linalg.pinv(a, rcond=1e-12)
    eig, vec = np.linalg.eigh(a); pos = np.where(eig > 1e-9)[0]; l1 = eig[pos[0]]
    p1 = vec[:, np.abs(eig - l1) < 1e-9] @ vec[:, np.abs(eig - l1) < 1e-9].T
    rows = []
    for d in range(1, 7):
        diff = float(np.linalg.norm(heat[0] - heat[d]))
        resistance = float(math.sqrt(max(0.0, pinv[0, 0] + pinv[d, d] - 2 * pinv[0, d])))
        hell = float(math.sqrt(np.sum((np.sqrt(np.maximum(heat[0], 0)) - np.sqrt(np.maximum(heat[d], 0))) ** 2)))
        proj = float(np.linalg.norm(p1[0] - p1[d]))
        rows.append({"cycle_separation": d, "diffusion_t1": diff, "sqrt_effective_resistance": resistance,
                     "Hellinger_Fisher_chord": hell, "first_projector_chord": proj})
    arr = np.array([[r[k] for r in rows] for k in ["diffusion_t1", "sqrt_effective_resistance", "Hellinger_Fisher_chord", "first_projector_chord"]])
    corr = np.corrcoef(arr)
    ratios = {"diffusion_over_resistance_range": [float(np.min(arr[0] / arr[1])), float(np.max(arr[0] / arr[1]))],
              "diffusion_over_projector_range": [float(np.min(arr[0] / arr[3])), float(np.max(arr[0] / arr[3]))]}
    packet = {
        "time": t, "rows": rows, "Pearson_correlation_matrix_order_diffusion_resistance_Hellinger_projector": corr.tolist(),
        **ratios,
        "theorem": (
            "All four displayed distances are translation invariant on Z12. Diffusion and the first-projector chord are Euclidean spectral metrics; square-root resistance is Euclidean through A's pseudoinverse; the heat-row Hellinger chord is a statistical/Fisher embedding. Their nonconstant pairwise ratios prove they are not identical up to one scalar at t=1. Only the rescaled long-time diffusion metric converges to the first-positive-projector chord, as proved in ST215."
        )
    }
    return finalize(230, "Strict Diffusion, Resistance, Fisher, and Projector Metric Atlas",
                    "proven_metric_formulas_and_nonproportionality_on_the_frozen_strict_instance",
                    "These are dimensionless internal geometries. High correlation or common cyclic ordering is not physical equivalence and supplies neither meters, causal cones, Lorentz signature, nor a unique observed geometry.", packet)


def st231_refinement(a: np.ndarray) -> dict:
    l2 = np.array([[1.0, -1.0], [-1.0, 1.0]])
    u = np.ones(2) / math.sqrt(2); r = np.kron(np.eye(N), u[:, None])
    rows = []
    for mu in [0.2, 1.0, 5.0, 20.0]:
        a24 = np.kron(a, np.eye(2)) + mu * np.kron(np.eye(N), l2)
        intertwine = float(np.linalg.norm(a24 @ r - r @ a))
        for t in [0.1, 1.0, 3.0]:
            semigroup = float(np.linalg.norm(expm(-t * a24) @ r - r @ expm(-t * a)))
            d12 = np.linalg.norm(expm(-t * a)[0] - expm(-t * a)[3])
            lifted = expm(-t * a24) @ r
            d24 = np.linalg.norm(lifted[:, 0] - lifted[:, 3])
            rows.append({"mu": mu, "t": t, "generator_intertwining_error": intertwine,
                         "semigroup_intertwining_error": semigroup, "coarse_distance": float(d12),
                         "refined_lift_distance": float(d24), "distance_error": float(abs(d24 - d12))})
    packet = {
        "refinement": "A_24=A_12 tensor I_2 + mu I_12 tensor L_2; R e_i=e_i tensor (1,1)/sqrt(2)",
        "rows": rows,
        "theorem": (
            "Because L2 annihilates the normalized uniform fiber vector, A24 R=R A12 for every mu>=0. Functional calculus gives exp(-t A24)R=R exp(-t A12), and the isometry R preserves every coarse diffusion distance exactly. Thus an exact two-child refinement compatible with the full strict heat geometry exists. The arbitrary positive fiber rate mu proves that geometry preservation alone does not select a unique refinement or scale ratio."
        )
    }
    return finalize(231, "Exact Isometric Diffusion-Preserving Two-Child Refinement",
                    "proven_exact_refinement_intertwiner_with_continuum_nonuniqueness",
                    "The construction is an operator refinement, not a derivation of the strict Z24 kernel, a physical fractal layer, a length ratio, or a Planck scale. The fiber generator and mu remain choices.", packet)


def st232_external_stop() -> dict:
    packet = {
        "local_search_performed": False,
        "required_missing_atoms": ["external event record", "independent registrar/custody", "calibration artifact", "laboratory attestation"],
        "decision": "blocked_without_repeating_synthetic_evidence",
        "theorem": "No local analytical or computational transformation can create an independently registered external laboratory event. The correct executable action is therefore to preserve the evidence boundary rather than relabel another synthetic run as validation."
    }
    return finalize(232, "External Validation Evidence Stop", "blocked_no_external_record",
                    "ST232 can be resumed only when genuine externally generated data and custody artifacts are supplied. Local PDF, hashes, and tests certify reproducibility, not nature.", packet)


def make_figures(d: dict) -> None:
    FIG_DIR.mkdir(exist_ok=True)
    fig, ax = plt.subplots(figsize=(7, 4)); rows = d["ST218"]["candidate_rows"]
    ax.bar(range(len(rows)), [r["commutator_Frobenius_norm"] for r in rows]); ax.set_yscale("symlog", linthresh=1e-16)
    ax.set_xticks(range(len(rows)), [r["candidate"] for r in rows], rotation=25, ha="right"); ax.set(ylabel="commutator norm", title="ST218: intrinsic diagonal candidates do not create a second generator"); fig.tight_layout(); fig.savefig(FIG_DIR / "st218_noncommuting_no_go.png", dpi=190); plt.close(fig)
    fig, ax = plt.subplots(figsize=(7, 4)); rows = d["ST219"]["rows"]
    ax.bar(range(len(rows)), [r["minimal_atoms"] for r in rows]); ax.set_xticks(range(len(rows)), ["vertex-local", "spectral", "nonlinear-location", "vertex-averaged"], rotation=15); ax.set(ylabel="minimal sufficient atoms", title="ST219: the Blackwell lattice depends on preparations"); fig.tight_layout(); fig.savefig(FIG_DIR / "st219_blackwell_families.png", dpi=190); plt.close(fig)
    fig, ax = plt.subplots(figsize=(7, 4)); rows = d["ST221"]["rows"]
    ax.scatter([r["modal_coordinate"] for r in rows], [r["kappa"] for r in rows], c=[r["mode"] for r in rows], s=9); ax.set(xlabel="modal coordinate", ylabel="kappa", title="ST221: all signed folds, finite validated segments"); fig.tight_layout(); fig.savefig(FIG_DIR / "st221_all_fold_continuation.png", dpi=190); plt.close(fig)
    fig, ax = plt.subplots(figsize=(7, 4)); stages = d["ST225"]["stages"]
    widths = [d["ST225"]["previous_certified_halfwidth"]] + [r["global_halfwidth"] for r in stages]
    fractions = [1.0] + [r["passed"] / r["boxes"] for r in stages]
    ax.plot(widths, fractions, "o-"); ax.set(xlabel="global nuisance halfwidth", ylabel="certified cell fraction", ylim=(0, 1.02), xlim=(0, max(widths) * 1.12), title="ST225: certified cover doubles its global halfwidth"); fig.tight_layout(); fig.savefig(FIG_DIR / "st225_cover_frontier.png", dpi=190); plt.close(fig)
    fig, ax = plt.subplots(figsize=(7, 4)); rows = d["ST226"]["rows"]
    ax.loglog([r["samples"] for r in rows], [r["optimized_Le_Cam_risk_lower_bound"] for r in rows], "o-", label="nonlocal Le Cam"); ax.loglog([r["samples"] for r in rows], [r["bias_derivative_0_25_CR_lower_bound"] for r in rows], "s--", label="bias-constrained CR"); ax.set(xlabel="samples", ylabel="risk lower bound", title="ST226: deep-mode minimax obstruction"); ax.legend(); fig.tight_layout(); fig.savefig(FIG_DIR / "st226_minimax_bounds.png", dpi=190); plt.close(fig)
    fig, ax = plt.subplots(figsize=(7, 4)); rows = d["ST230"]["rows"]; x = [r["cycle_separation"] for r in rows]
    for k, label in [("diffusion_t1", "diffusion"), ("sqrt_effective_resistance", "resistance"), ("Hellinger_Fisher_chord", "Hellinger"), ("first_projector_chord", "projector")]: ax.plot(x, [r[k] for r in rows], "o-", label=label)
    ax.set(xlabel="cycle separation", ylabel="dimensionless distance", title="ST230: inequivalent internal geometries"); ax.legend(); fig.tight_layout(); fig.savefig(FIG_DIR / "st230_metric_atlas.png", dpi=190); plt.close(fig)
    fig, ax = plt.subplots(figsize=(7, 4)); rows = d["ST231"]["rows"]
    for mu in [0.2, 1.0, 5.0, 20.0]:
        q = [r for r in rows if r["mu"] == mu]; ax.semilogy([r["t"] for r in q], [max(r["distance_error"], 1e-17) for r in q], "o-", label=f"mu={mu}")
    ax.set(xlabel="t", ylabel="coarse/refined distance error", title="ST231: exact diffusion-preserving refinement replay"); ax.legend(); fig.tight_layout(); fig.savefig(FIG_DIR / "st231_refinement.png", dpi=190); plt.close(fig)


def main() -> None:
    _, a, _ = strict_operator()
    out = {"metadata": {"programs": "ST218-ST232", "date": "2026-08-12", "seed": SEED,
                        "python": platform.python_version(), "numpy": np.__version__, "scipy": scipy.__version__, "sympy": sp.__version__}}
    out["ST218"] = st218_noncommuting_layer_no_go(a); out["ST219"] = st219_blackwell_families(a)
    out["ST220"] = st220_invariant_fluctuations(a); out["ST221"] = st221_all_fold_continuation(a)
    out["ST222"] = st222_rotated_pauli_recovery(); out["ST223"] = st223_selector_dp()
    out["ST224"] = st224_carrier_transport(a); out["ST225"] = st225_extended_cover(a)
    out["ST226"] = st226_nonlocal_minimax(); out["ST227"] = st227_joint_factor_polar()
    out["ST228"] = st228_hmm_belief_cylinders(); out["ST229"] = st229_net_reset(a)
    out["ST230"] = st230_metric_comparison(a); out["ST231"] = st231_refinement(a)
    out["ST232"] = st232_external_stop()
    out["recommended_next_programs"] = [
        {"id": "ST233", "priority": 1, "study": "introduce exactly one typed second operator and test strict provenance, noncommutation, and schedule identifiability"},
        {"id": "ST234", "priority": 2, "study": "certify the localized vertex Blackwell ratio classes by transcendental interval arithmetic"},
        {"id": "ST235", "priority": 3, "study": "classify state-conditioned equivariant noise and identify precisely where the conditioning becomes a selector premise"},
        {"id": "ST236", "priority": 4, "study": "extend all ST221 branches adaptively and build a certified connected-component/collision graph"},
        {"id": "ST237", "priority": 5, "study": "solve one genuinely nonunital negative-orientation qubit recovery SDP with rational primal-dual witnesses"},
        {"id": "ST238", "priority": 6, "study": "upgrade ST223 from a finite control alphabet to verified continuous-control optimality including switching work"},
        {"id": "ST239", "priority": 7, "study": "extend I12 naturality to nonlinear carrier charts and response bundles"},
        {"id": "ST240", "priority": 8, "study": "subdivide the first ST225 failed boxes and distinguish method failure from a genuine fold boundary"},
        {"id": "ST241", "priority": 9, "study": "derive asymptotically sharp simultaneous-mode minimax constants under correlation"},
        {"id": "ST242", "priority": 10, "study": "generalize the polar joint-factor theorem to balanced higher-dimensional Clifford pairs"},
        {"id": "ST243", "priority": 11, "study": "optimize the observed-HMM Chernoff parameter s with certified belief-space transfer bounds"},
        {"id": "ST244", "priority": 12, "study": "perform complete work-information bookkeeping for the ST229 reversible reset and ancilla preparation"},
        {"id": "ST245", "priority": 13, "study": "classify all diffusion-preserving finite-fiber refinements and their nonuniqueness moduli"},
        {"id": "ST246", "priority": 14, "study": "test spectral-dimension flow across repeated exact refinements without assigning physical length"},
        {"id": "ST247", "priority": 15, "study": "resume external validation only with a genuine registered laboratory event package"},
    ]
    out["central_verdict"] = (
        "The current strict single-operator equivariant class cannot generate the noncommuting layer needed to reveal a hidden fractal schedule, and invariant fluctuations cannot canonically orient a selected branch. Positive structural advances nevertheless exist: I12 is a carrier-natural projective response invariant; all sixty signed local folds admit a finite validated continuation campaign; a net-energy-conserving reversible reset is possible through a prepared identical register; and an exact family of two-child refinements preserves the complete coarse diffusion geometry. The arbitrary fiber rate in that refinement is itself a new nonuniqueness theorem: internal geometry does not select physical scale."
    )
    out["epistemic_boundary"] = (
        "No carrierlessness, preferred strict fractal schedule, strict second generator, canonical selector, QW-2191 discharge, physical clock/length/action unit, Planck scale, spacetime, laboratory record, legacy-to-strict completion or role transfer, Standard Model, gravity, L_total, or ToE closure is claimed."
    )
    RESULTS.write_text(json.dumps(native(out), indent=2, sort_keys=True), encoding="utf-8")
    with SUMMARY.open("w", newline="", encoding="utf-8") as handle:
        w = csv.writer(handle); w.writerow(["program", "object", "status"])
        for k in range(218, 233):
            w.writerow([f"ST{k}", out[f"ST{k}"]["object"], out[f"ST{k}"]["status"]])
    make_figures(out)
    print(json.dumps({"programs": "ST218-ST232", "statuses": {f"ST{k}": out[f"ST{k}"]["status"] for k in range(218, 233)},
                      "ST221": [out["ST221"]["certified_steps"], out["ST221"]["attempted_steps"]],
                      "ST225_stages": out["ST225"]["stages"], "ST228": out["ST228"]["new_bracket"]}, indent=2))


if __name__ == "__main__":
    main()
