#!/usr/bin/env python3
"""Six rounds: exact refinement maps versus dyadic layer-distance sampling."""
import hashlib,json,math,numpy as np
from fin_st2172_st2261_common import ROOT,strict_A_W,write_packet,write_round
def emit(lo,names,rows):
 d={}
 for i,(s,b,p) in enumerate(rows):k=lo+i;d[f'ST{k}']=write_packet(k,names[i],s,b,p)
 write_round(lo,lo+14,d)
A,W=strict_A_W();q=.2;B=np.array([[q,-q],[-q,q]]);A24=np.kron(A,np.eye(2))+np.kron(np.eye(12),B);u=np.ones(2)/math.sqrt(2);R=np.kron(np.eye(12),u[:,None])
def shift(n,k=1):
 P=np.zeros((n,n))
 for i in range(n):P[(i+k)%n,i]=1
 return P
def K(d):return math.cos(.18575*d+.1625)/(1+d**1.8)
def r1():
 names=['ProductRefinement','FiberGenerator','CoarseIsometry','GeneratorIntertwiner','HeatIntertwiner','UnitaryIntertwiner','UniformFiberKernel','FreeFiberRate','BlockLabels','CoverMap','BaseDistance','LayerDistance','ProductGeometry','RoundOneVerdict','RoundOneRecommendation']
 rows=[('Reconstructed','A24=A12 tensor I2+I12 tensor Bq.',{}),('Defined','Bq.',{'q':q}),('Proven','R e_i=e_i tensor uniform.',{'isometry_residual':float(np.linalg.norm(R.T@R-np.eye(12)))}),('Proven','A24 R=R A12.',{'residual':float(np.linalg.norm(A24@R-R@A))}),('Analytic consequence','Functional calculus.',{}),('Analytic consequence','Functional calculus.',{}),('Proven','Bq uniform=0.',{}),('Proven no-go','Every q>=0 preserves coarse dynamics.',{}),('Defined','(i,b) -> 2i+b in current Kronecker order.',{}),('Defined','Coarse projection forgets b.',{}),('Proven','Product base coordinate keeps d.',{}),('Proven','Fiber coordinate is separate.',{}),('Proven','Refinement is Z12 product two-point fiber, not Z24 cyclic subdivision.',{}),('Round verdict','Current exact refinement does not define d->2d kernel sampling.',{}),('Recommendation','Audit relabelings.',{})];emit(3162,names,rows)
def r2():
 S1=shift(24,1);S2=shift(24,2);names=['InterleavedLabels','HorizontalNumericDistance','VerticalNumericDistance','ShiftTwoSymmetry','ShiftOneFailure','NotC24Circulant','RelabelingInvariantPhysics','WeightInheritance','KernelResamplingDifference','DistanceTable','CoordinateArtifact','FiberUniformSubspace','EvenSupportSubspace','RoundTwoVerdict','RoundTwoRecommendation']
 diffs=[W[0,d]-K(2*d) for d in range(1,7)]
 rows=[('Defined','(i,b)->2i+b.',{}),('Proven','Same-fiber base separation d has numeric C24 distance 2d.',{}),('Proven','Fiber edge has numeric distance1.',{}),('Computed','A24 commutes with shift by2.',{'residual':float(np.linalg.norm(S2@A24-A24@S2))}),('Computed','Generic product A24 does not commute with shift by1.',{'residual':float(np.linalg.norm(S1@A24-A24@S1))}),('Proven','Product operator is not a distance-circulant Z24 kernel.',{}),('Proven','Labels do not change operator weights.',{}),('Proven','Horizontal weight remains W12(d).',{}),('Proven counterexample','W12(d) differs from K(2d).',{'differences':diffs,'max_abs':max(map(abs,diffs))}),('Computed','d=1..6.',{}),('No-go','Doubled label distance is not a derivation of doubled kernel argument.',{}),('Proven','R uses equal amplitudes on even/odd pair.',{}),('Proven','R is not injection supported only at even sites.',{}),('Round verdict','Interleaving creates visual distance doubling but no kernel resampling theorem.',{}),('Recommendation','Test true even embedding.',{})];emit(3177,names,rows)
def r3():
 names=['MetricTransport','WeightTransport','TwoNotions','InheritedConductance','ResampledConductance','EqualityCondition','StrictFailure','EnergyIntertwining','DistanceCovariance','HodgeBoundary','PhysicalLengthBoundary','ScaleOrigin','TransportGate','RoundThreeVerdict','RoundThreeRecommendation']
 rows=[('Classified','Numeric fine-cycle distance.',{}),('Classified','Operator conductance attached to product edge.',{}),('Proven','They are independent data in product refinement.',{}),('Proven','w_fine(horizontal d)=w_coarse(d).',{}),('Alternative','w_fine(2d)=K(2d).',{}),('Proven','Both agree only if K(2d)=K(d) on required d.',{}),('Computed','Strict kernel violates equality.',{}),('Proven','Inheritance, not resampling, gives exact coarse energy.',{}),('No-go','Metric coordinate covariance alone cannot replace intertwining.',{}),('Boundary','DEC measure transport remains separate.',{}),('No-go','Neither numeric label distance has metres.',{}),('No-go','No canonical a.',{}),('Fail','No layer-distance kernel law.',{}),('Round verdict','Exact refinement transports weights functorially, not by evaluating K at doubled labels.',{}),('Recommendation','Parity-subspace no-go.',{})];emit(3192,names,rows)
def r4():
 # naive C24 strict-form Laplacian
 n=24;Af=np.zeros((n,n));weights={d:K(d) for d in range(1,13)};s=2*sum(weights[d] for d in range(1,12))+weights[12]
 for i in range(n):
  for j in range(n):Af[i,j]=s if i==j else -weights[min((i-j)%n,(j-i)%n)]
 E=np.zeros((24,12))
 for i in range(12):E[2*i,i]=1
 leak=float(np.linalg.norm((np.eye(24)-E@E.T)@Af@E))
 names=['EvenEmbedding','EvenSubspace','NaiveC24Kernel','ParityLeakage','LeakageWitness','OddDistanceCondition','DisconnectedRepair','FiberCouplingConflict','PairUniformEmbedding','InvariantSubspaceTheorem','CirculantNoGo','AlternativeInterpolation','EvenGate','RoundFourVerdict','RoundFourRecommendation']
 rows=[('Defined','E e_i=e_(2i).',{}),('Defined','Vectors supported on even vertices.',{}),('Constructed','Apply strict formula on all C24 distances.',{}),('Computed','Fine Laplacian leaks to odd sites.',{'residual':leak}),('Proven','Any nonzero odd-distance weight causes leakage.',{}),('Theorem','Even subspace invariant iff all odd-distance couplings vanish.',{}),('Boundary','Removing odd weights splits parity components.',{}),('No-go','Vertical distance-one q edge also mixes parity.',{}),('Proven','Correct coarse space is pair-uniform, not even-supported.',{}),('Proven','Product Bq annihilates pair uniform vector.',{}),('No-go','Connected generic C24 circulant cannot realize E intertwiner.',{}),('Conditional','Interpolation including odd sites is extra map.',{}),('Fail','Even group embedding is not operator intertwiner.',{}),('Round verdict','Group-label injection does not supply the FIN refinement dynamics.',{}),('Recommendation','Reassess dyadic recurrence.',{})];emit(3207,names,rows)
def r5():
 names=['DyadicRecurrenceReview','NaturalRatio','MissingDistanceLaw','ProductQRole','KernelWeightRole','SemanticMismatch','ConditionalModel','FinitePrefix','ConvergenceSurvives','ProvenanceFails','PossibleNewAxiom','AxiomConsequence','RecurrenceGate','RoundFiveVerdict','RoundFiveRecommendation']
 rows=[('Reviewed','q_n=K(2^n).',{}),('Positive','Binary fibers motivate ratio2.',{}),('No-go','They do not map fiber level to base distance.',{}),('Proven','q is vertical relative-fiber rate.',{}),('Proven','K(d) is horizontal/base conductance.',{}),('No-go','Equating q_n and K(distance) crosses typed roles.',{}),('Conditional','May be adopted as new layer-distance axiom.',{}),('Proven','d=1,2,4 are strict values.',{}),('Proven','Mathematical summability unchanged.',{}),('Fail','Strict recurrence source not upgraded.',{}),('Axiom','Declare layer n corresponds to physical/base distance a2^n.',{}),('Conditional','Then prior dyadic theorem applies.',{}),('Fail strict','Axiom not current export.',{}),('Round verdict','Dyadic recurrence remains useful conditional model, not recovered strict theorem.',{}),('Recommendation','Synthesize.',{})];emit(3222,names,rows)
def r6():
 gate=ROOT/'FIN_ST3237_ST3251_LayerDistanceEmbeddingGate.json';g={'rows':[{'name':n,'pass':v} for n,v in [('exact product refinement',True),('coarse functional-calculus intertwining',True),('distance/weight distinction theorem',True),('even embedding intertwiner',False),('C24 strict circulant refinement',False),('layer-to-distance map',False),('q_n=K(2^n) strict source',False),('physical layer spacing',False),('clock/units',False),('OA evidence',False)]]};gate.write_text(json.dumps(g,indent=2)+'\n')
 names=['ProductTheorem','LabelTheorem','TransportTheorem','EvenNoGo','DyadicBoundary','TypedRoleNoGo','PhysicalBoundary','Gate','GateScore','ProvenLedger','ConditionalLedger','RefutedLedger','HighestValueNext','FinalInterpretation','CycleTrigger']
 rows=[('Proven','A tensor I+I tensor Bq exact.',{}),('Proven','Interleaving doubles labels only.',{}),('Proven','Weights inherited, not K(2d).',{}),('Proven','Even support leaks for connected C24 kernel.',{}),('Boundary','Recurrence stable but conditional.',{}),('No-go','Vertical q and horizontal K are different typed objects.',{}),('No-go','No length/clock.',{}),('Constructed','Ten rows.',{'file':gate.name}),('Result','Three mathematical passes.',{'passes':3,'rows':10}),('Ledger','Product/intertwining/transport.',{}),('Ledger','New layer-distance axiom.',{}),('Ledger','Recovered strict dyadic law.',{}),('Recommendation','Either derive an explicit typed layer-distance axiom from a new geometry or keep q_n independent of K(d).',{}),('Final verdict','Existing refinement actively contradicts the inference that binary layer labels force kernel argument doubling.',{'fundamental':False}),('Cycle complete','Release 11.19.',{'programs':90,'rounds':6,'range':'ST3162-ST3251','strict_ToE_closure':False,'gate_sha256':hashlib.sha256(gate.read_bytes()).hexdigest()})];emit(3237,names,rows)
def main():r1();r2();r3();r4();r5();r6()
if __name__=='__main__':main()
