#!/usr/bin/env python3
"""FIN ST130--ST141: strict-source no-go, robust recovery, and typed physics tests."""

from __future__ import annotations

import csv
import hashlib
import itertools
import json
import math
import platform
from pathlib import Path
from typing import Any

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import mpmath as mp
import numpy as np
import scipy
from scipy.optimize import minimize_scalar, root

from fin_st01_st15_research import N, strict_operator
from fin_st28_st45_research import dyadic_lift
from fin_st106_st117_research import plus_minus
from fin_st118_st129_research import (
    bounds, detected_probability_jet, ib, interval_left, interval_matvec,
    spectrum_intervals,
)
from fin_st132_center_isolation_replay import run as run_center_isolation, strict_interval_matrix


ROOT = Path(__file__).resolve().parent
RESULTS = ROOT / "FIN_ST130_ST141_Results.json"
SUMMARY = ROOT / "FIN_ST130_ST141_Summary.csv"
PACK131 = ROOT / "FIN_ST131_Diagonal_Noncirculant_Face.json"
CERT132 = ROOT / "FIN_ST132_Independent_Center_Isolation_Certificate.json"
CERT136 = ROOT / "FIN_ST136_Parametric_Design_Certificate.json"
PACK137 = ROOT / "FIN_ST137_Refinement_Diagram_Cohomology.json"
PACK140 = ROOT / "FIN_ST140_Matched_Gap_Bath_Dilation.json"
PACK141 = ROOT / "FIN_ST141_Noisy_Nondiagonal_Minimax.json"
FIG_DIR = ROOT / "FIN_ST130_ST141_Figures"
SEED = 20260822


def native(x: Any) -> Any:
    if isinstance(x, dict): return {str(k): native(v) for k, v in x.items()}
    if isinstance(x, (list, tuple)): return [native(v) for v in x]
    if isinstance(x, np.ndarray): return native(x.tolist())
    if isinstance(x, (np.floating, np.integer)): return x.item()
    return x


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def st130_functional_calculus_no_gauge(a: np.ndarray) -> dict:
    vals = np.linalg.eigvalsh(a)
    groups = []
    for value in vals:
        if not groups or abs(value-groups[-1][0]) > 1e-9: groups.append([float(value), 1])
        else: groups[-1][1] += 1
    mult = [g[1] for g in groups]
    mp.iv.dps=60; _,weights,siv=strict_interval_matrix(); spectral_intervals=[]
    for k in range(7):
        lam=siv-2*sum((weights[d]*mp.iv.cos(2*mp.iv.pi*k*d/N) for d in range(1,6)),ib(0))-weights[6]*mp.iv.cos(mp.iv.pi*k)
        spectral_intervals.append(bounds(lam))
    spectral_intervals.sort(key=lambda x:(x[0]+x[1])/2)
    certified_gap=min(spectral_intervals[j+1][0]-spectral_intervals[j][1] for j in range(6))
    return {
        "program": "ST130", "object": "Strict Functional-Calculus Fine-Gauge No-Go",
        "distinct_spectral_values": len(groups), "spectral_multiplicities": mult,
        "functional_calculus_complex_dimension": len(groups),
        "commutant_complex_dimension": sum(m*m for m in mult),
        "desired_fine_gauge_real_dimension": N*N,
        "spectral_class_intervals_k0_to_k6": spectral_intervals,
        "minimum_certified_separation_between_distinct_classes": certified_gap,
        "theorem": (
            "C*(A) is the seven-dimensional abelian algebra generated by the seven spectral projectors of the non-scalar strict operator. "
            "On a doubled copy, the strict dynamics is A direct-sum A.  A transformation I direct-sum U is a symmetry for every U in U(12) "
            "only if UAU*=A for every U, which would force A to be scalar.  It is not.  Therefore Borel/continuous functional calculus, "
            "finite direct sums, and covariance under the strict dynamical symmetries cannot generate the full fine U(12) gauge used in ST118."
        ),
        "status": "proven_no_fine_U12_source_in_declared_strict_functional_calculus_class",
        "boundary": (
            "This is not a universal impossibility theorem. A new dilation, state-dependent redundancy, environment, instrument, or operational "
            "quotient can leave the class, but then supplies additional structure. QW-2191 is not discharged."
        ),
    }


def st131_diagonal_face(a: np.ndarray) -> dict:
    rng = np.random.default_rng(SEED+131); checks = []
    for support_size in [0, 1, 2, 6, 12]:
        t = np.zeros(N)
        if support_size:
            idx = rng.choice(N, support_size, replace=False); t[idx] = rng.uniform(.02, .8, support_size)
        b = a + np.diag(t)
        checks.append({"support_size": support_size, "minimum_eigenvalue": float(np.min(np.linalg.eigvalsh(b))),
                       "rank": int(np.linalg.matrix_rank(b, tol=1e-10)), "circulant": bool(np.max(abs(t-t[0])) < 1e-14)})
    packet = {
        "face": "F_diag={A+Diag(t): t in R_+^12}", "dimension": 12, "face_count": 2**N,
        "vertex_count": 1, "extreme_rays": N, "rank_at_vertex": N-1,
        "rank_for_every_nonzero_t": N, "sample_checks": checks,
        "theorem": (
            "Fixing every off-diagonal graph inequality at its lower endpoint exposes a twelve-dimensional face of the complete lift fiber. "
            "It is affinely the nonnegative orthant, hence has 2^12 faces, one vertex A, and rays E_ii.  Since the strict graph is connected, "
            "x*(A+Diag(t))x=0 implies x is constant and every supported t_i x_i^2 vanishes. Thus every nonzero t makes the block positive definite. "
            "Consequently this face contains no nontrivial low-rank stratum beyond its rank-eleven vertex."
        ),
    }
    PACK131.write_text(json.dumps(native(packet), indent=2, sort_keys=True), encoding="utf-8")
    return {"program": "ST131", "object": "Diagonal Noncirculant Face and Rank-Jump Classification",
            "packet_file": PACK131.name, "packet_sha256": sha(PACK131), **packet,
            "status": "proven_exact_twelve_dimensional_noncirculant_face_and_low_rank_no_go",
            "boundary": "The remaining noncirculant bounded faces of the full 78-dimensional spectrahedron are not enumerated."}


def st132_center_isolation() -> dict:
    cert = run_center_isolation(True)
    return {"program": "ST132", "object": "Independent Fold-Center Discovery and Interval Isolation",
            "certificate_file": CERT132.name, "certificate_sha256": sha(CERT132), **cert,
            "status": "proven_local_root_isolation_without_prior_center_input" if cert["accepted"] else "blocked_center_isolation",
            "boundary": cert["boundary"]}


def st133_noisy_recovery() -> dict:
    rows = []
    for eps in [0, .01, .05, .1, .25, .5, 1.0]:
        fe = 1-eps+eps/N**2
        favg = 1-eps*(N-1)/N
        rows.append({"epsilon": eps, "optimal_entanglement_fidelity": fe, "optimal_average_fidelity": favg})
    return {
        "program": "ST133", "object": "Optimal Recovery after Depolarizing Noisy Pinching",
        "channel": "N_epsilon=(1-epsilon) Pi_cf + epsilon D_24, D_24(X)=Tr(X)I_24/24",
        "logical_channel_after_ST121_recovery": "(1-epsilon)Id_12+epsilon D_12",
        "rows": rows,
        "theorem": (
            "Every maximal ST121 graph code is recovered perfectly on the pinching branch. The completely depolarizing branch carries no input "
            "information and is mapped to I_12/12. Hence the optimal entanglement fidelity is 1-epsilon+epsilon/144 and the optimal average "
            "fidelity is 1-11 epsilon/12. No recovery can improve the depolarizing branch, so the displayed recovery is globally optimal."
        ),
        "status": "proven_optimal_recovery_for_declared_depolarizing_pinching_noise",
        "boundary": "Coherent leakage, sector-dependent noise, correlated uses, and a physical implementation are not covered.",
    }


def relative_entropy_vertex_mixture(eps: float) -> float:
    p0 = (1+11*eps)/12; p = (1-eps)/12
    ans = p0*math.log(12*p0)
    if p > 0: ans += 11*p*math.log(12*p)
    return ans


def st134_symmetry_breaking_cost() -> dict:
    rows = []
    for eps in [1e-6, 1e-4, .01, .1, .5, 1.0]:
        rows.append({"epsilon": eps, "trace_distance_to_twirl": 11*eps/12,
                     "relative_entropy_asymmetry_nats": relative_entropy_vertex_mixture(eps)})
    return {
        "program": "ST134", "object": "Minimal-Rank Symmetry-Breaking State and Vanishing Source-Cost Infimum",
        "family": "rho_epsilon=(1-epsilon)I/12+epsilon|0><0|",
        "density_rank_at_epsilon_1": 1, "orbit_size_at_epsilon_positive": 12,
        "pure_vertex_trace_distance_to_twirl": 11/12, "pure_vertex_relative_entropy_asymmetry": math.log(12),
        "rows": rows,
        "theorem": (
            "A rank-one vertex state is the minimum possible nonzero density rank and breaks C12 completely. Its group twirl is I/12, giving "
            "trace-distance asymmetry 11/12 and relative-entropy asymmetry ln 12. However rho_epsilon has a unique preferred vertex for every "
            "epsilon>0 while both costs tend to zero. Therefore no positive minimum symmetry-breaking source cost follows from state space alone."
        ),
        "status": "proven_rank_one_sufficiency_and_zero_cost_infimum",
        "boundary": "The family supplies a noninvariant preparation. It does not derive a strict selector or discharge QW-2191.",
    }


def st135_pumped_strict_modes(a: np.ndarray) -> dict:
    vals = np.linalg.eigvalsh(a); distinct = []
    for value in vals:
        if not distinct or abs(value-distinct[-1][0]) > 1e-9: distinct.append([float(value), 1])
        else: distinct[-1][1] += 1
    gamma, nu, kappa, g = .35, .2, 1.0, .55
    rows = []
    for r, (lam, mult) in enumerate(distinct):
        mu = g-gamma-nu*lam
        rows.append({"spectral_class": r, "lambda": lam, "multiplicity": mult,
                     "threshold_g": gamma+nu*lam, "growth_mu_at_g": mu,
                     "stable_orbit_radius": math.sqrt(max(mu, 0)/kappa),
                     "radial_exponent_on_nonzero_orbit": -2*mu if mu > 0 else None})
    return {
        "program": "ST135", "object": "Pumped Strict-Mode Orbital Stability and Degeneracy Obstruction",
        "equation": "z_dot=[g-gamma-nu lambda_r+i lambda_r]z-kappa||z||^2 z on each eigenspace",
        "parameters": {"g": g, "gamma": gamma, "nu": nu, "kappa": kappa}, "rows": rows,
        "theorem": (
            "For mu_r=g-gamma-nu lambda_r<=0 the zero mode is stable. For mu_r>0 the sphere ||z||=sqrt(mu_r/kappa) is orbitally "
            "stable with radial exponent -2mu_r and neutral phase/group tangents. On the mean-zero subspace the first threshold belongs to a "
            "twofold strict eigenspace, so pumping selects a degenerate orbit, not a unique orientation or localized soliton."
        ),
        "status": "proven_orbital_stability_for_constructed_decoupled_mode_model_and_selection_obstruction",
        "boundary": "Pump, loss, nonlinear saturation, clock, and mode decoupling are supplied. No physical gain or strict soliton theorem follows.",
    }


def parametric_chernoff_stationary(beta, s, q0, q1, eigc, eigf, delta):
    a, ap, app = detected_probability_jet(beta, q0, eigc, eigf, delta)
    b, bp, bpp = detected_probability_jet(beta, q1, eigc, eigf, delta)
    Bs=ib(0); Bb=ib(0); Bss=ib(0); Bsb=ib(0); Bbb=ib(0); B=ib(0)
    for x,xp,xpp,y,yp,ypp in [(a,ap,app,b,bp,bpp),(1-a,-ap,-app,1-b,-bp,-bpp)]:
        lx=mp.iv.log(x); ly=mp.iv.log(y); term=mp.iv.exp(s*lx+(1-s)*ly)
        hs=lx-ly; hb=s*xp/x+(1-s)*yp/y
        hsb=xp/x-yp/y
        hbb=s*(xpp/x-(xp/x)**2)+(1-s)*(ypp/y-(yp/y)**2)
        B += term; Bs += term*hs; Bb += term*hb
        Bss += term*hs**2; Bsb += term*(hb*hs+hsb); Bbb += term*(hb**2+hbb)
    return [Bs,Bb], [[Bss,Bsb],[Bsb,Bbb]], B


def point_design_system(x, ec, ef, q0=.2, q1=.7, delta=.05):
    beta, ss = x
    def jet(q):
        tc=np.exp(-beta*ec); tf=np.exp(-beta*ef); zc=tc.sum(); zf=tf.sum()
        mc=(ec*tc).sum()/zc; mf=(ef*tf).sum()/zf
        vc=(ec**2*tc).sum()/zc-mc**2; vf=(ef**2*tf).sum()/zf-mf**2
        lr=np.exp(-2*beta*q)*zf/zc; p=1/(1+lr); lp=-2*q-mf+mc; lpp=vf-vc
        dp=-p*(1-p)*lp; ddp=p*(1-p)*((1-2*p)*lp**2-lpp); c=1-2*delta
        return delta+c*p,c*dp,c*ddp
    a,ap,app=jet(q0); b,bp,bpp=jet(q1); Bs=Bb=0.0
    for xx,xp,xpp,yy,yp,ypp in [(a,ap,app,b,bp,bpp),(1-a,-ap,-app,1-b,-bp,-bpp)]:
        term=xx**ss*yy**(1-ss); Bs += term*math.log(xx/yy)
        Bb += term*(ss*xp/xx+(1-ss)*yp/yy)
    return np.array([Bs,Bb])


def st136_parametric_design(a: np.ndarray) -> dict:
    p, f = plus_minus(); b0 = f.T@dyadic_lift(a, 0)@f
    ec = np.linalg.eigvalsh(a); ef = np.linalg.eigvalsh(b0)
    eigc, eigf = spectrum_intervals(ec), spectrum_intervals(ef)
    center = root(lambda x: point_design_system(x, ec, ef), np.array([2.18,.54]), tol=1e-12).x
    q0box=(.19999,.20001); q1box=(.69999,.70001); deltabox=(.04999,.05001)
    mp.iv.dps=60
    f0,j0,_=parametric_chernoff_stationary(ib(float(center[0])),ib(float(center[1])),q0box,q1box,eigc,eigf,deltabox)
    flo=np.array([bounds(x)[0] for x in f0]); fhi=np.array([bounds(x)[1] for x in f0])
    # Point-parameter midpoint inverse is only a preconditioner; proof images use full parameter intervals.
    _,jmid,_=parametric_chernoff_stationary(ib(float(center[0])),ib(float(center[1])),.2,.7,eigc,eigf,.05)
    jml=np.array([[bounds(x)[0] for x in row] for row in jmid]); jmh=np.array([[bounds(x)[1] for x in row] for row in jmid])
    c=np.linalg.inv((jml+jmh)/2); attempts=[]; accepted=None
    for rbeta,rs in [(3e-3,8e-3),(2e-3,6e-3),(1e-3,5e-3),(5e-4,4e-3),(3e-3,6e-3),(4e-3,8e-3)]:
        rvec=np.array([rbeta,rs])
        _,ji,_=parametric_chernoff_stationary(ib((center[0]-rbeta,center[0]+rbeta)),ib((center[1]-rs,center[1]+rs)),q0box,q1box,eigc,eigf,deltabox)
        jl=np.array([[bounds(x)[0] for x in row] for row in ji]); jh=np.array([[bounds(x)[1] for x in row] for row in ji])
        cglo,cghi=interval_matvec(c,c,flo,fhi); ylo=np.nextafter(center-cghi,-np.inf); yhi=np.nextafter(center-cglo,np.inf)
        cjlo,cjhi=interval_left(c,jl,jh); mlo,mhi=-cjhi,-cjlo
        for i in range(2): mlo[i,i]=np.nextafter(mlo[i,i]+1,-np.inf); mhi[i,i]=np.nextafter(mhi[i,i]+1,np.inf)
        mdlo,mdhi=interval_matvec(mlo,mhi,-rvec,rvec); klo=ylo+mdlo; khi=yhi+mdhi
        margin=float(min(np.min(klo-(center-rvec)),np.min((center+rvec)-khi)))
        row={"beta_radius":rbeta,"s_radius":rs,"minimum_strict_inclusion_margin":margin,"included":margin>0,
             "Krawczyk_box":[klo.tolist(),khi.tolist()]}; attempts.append(row)
        if accepted is None and margin>0: accepted=row
    cert={"nominal_center":{"beta":float(center[0]),"s":float(center[1])},"q0_interval":q0box,"q1_interval":q1box,
          "detector_flip_interval":deltabox,"attempts":attempts,"accepted":accepted,
          "scope":"Uniform local Krawczyk existence/uniqueness for every nuisance triple in the displayed box; spectra are outward-enclosed binary64 values.",
          "boundary":"The nuisance box is local and no global beta-optimum theorem or laboratory calibration follows."}
    CERT136.write_text(json.dumps(native(cert),indent=2,sort_keys=True),encoding="utf-8")
    return {"program":"ST136","object":"Parametric Chernoff Stationary-Design Certificate","certificate_file":CERT136.name,
            "certificate_sha256":sha(CERT136),**cert,
            "status":"proven_uniform_local_stationary_root_over_declared_nuisance_box" if accepted else "blocked_parametric_interval_inclusion",
            "boundary":cert["boundary"]}


def affine_compose(second, first):
    a2,b2=second; a1,b1=first
    return ((a2*a1)%2,(a2*b1+b2)%2)


def diamond_count(degrees):
    coherent=[]
    for twists in itertools.product([0,1],repeat=4):
        edges=[(degrees[i]%2,twists[i]) for i in range(4)]
        left=affine_compose(edges[1],edges[0]); right=affine_compose(edges[3],edges[2])
        if left==right: coherent.append(twists)
    return {"degrees":degrees,"coherent_twists":len(coherent),"total_twists":16,
            "examples":[list(x) for x in coherent[:4]]}


def st137_refinement_diagrams() -> dict:
    examples=[diamond_count([2,3,3,2]),diamond_count([3,3,3,3]),diamond_count([2,3,3,3])]
    packet={"affine_transport":"x_target=(m mod 2)x_source+tau over F2","diamond_examples":examples,
            "theorem":(
                "Every twisted Z2 refinement edge is an affine endomorphism (a,b) of F2 with a=m mod 2. Path transport is affine composition. "
                "A twist assignment is path independent exactly when the affine pairs agree for every pair of parallel paths. If their degree-parity "
                "products differ, no twist can repair the diagram for both input holonomies; if they agree, the remaining equations are linear cocycle equations over F2."
            )}
    PACK137.write_text(json.dumps(native(packet),indent=2,sort_keys=True),encoding="utf-8")
    return {"program":"ST137","object":"Finite Refinement-Diagram Affine-Cohomology Classification","packet_file":PACK137.name,
            "packet_sha256":sha(PACK137),**packet,"status":"proven_general_path_independence_criterion_and_finite_diamond_exhaustion",
            "boundary":"Degrees and twists are categorical input data; no strict spin or topology source is generated."}


def st138_conditional_independence_no_selection() -> dict:
    return {
        "program":"ST138","object":"Conditional Independence Cannot Select Its Own Gauge Algebra",
        "counterexample":"M2 tensor M2 with normalized trace; E1=id tensor tau and E2=tau tensor id",
        "fixed_algebra_dimensions":[4,4],"expectations_distinct":True,
        "theorem":(
            "Both E1 and E2 are faithful trace-preserving conditional expectations. They satisfy the same product-state conditional-independence "
            "and commuting-square identities, yet their ranges M2 tensor I and I tensor M2 are distinct. Unitary conjugation produces a continuum "
            "of further examples. Therefore an abstract causal/conditional-independence axiom cannot identify the conditioning algebra or the FIN fine sector without a supplied net, region assignment, or instrument class."
        ),
        "status":"proven_finite_counterexample_to_gauge_selection_by_untyped_conditional_independence",
        "boundary":"A physically typed causal net could remove the ambiguity, but that net is additional operational structure.",
    }


def binomial_bayes_error(k,p0,p1):
    error=0.0
    for j in range(k+1):
        b0=math.comb(k,j)*p0**j*(1-p0)**(k-j)
        b1=math.comb(k,j)*p1**j*(1-p1)**(k-j)
        error += .5*min(b0,b1)
    return error


def st139_dependent_counts() -> dict:
    p0,p1,m=.72,.94,5
    opt=minimize_scalar(lambda ss:p0**ss*p1**(1-ss)+(1-p0)**ss*(1-p1)**(1-ss),bounds=(0,1),method="bounded")
    c=-math.log(opt.fun); rows=[]
    for n in [5,10,25,50,100,250,500]:
        k=n//m
        rows.append({"raw_events":n,"independent_blocks":k,"exact_Bayes_error":binomial_bayes_error(k,p0,p1),
                     "Chernoff_upper_bound":.5*math.exp(-k*c)})
    return {
        "program":"ST139","object":"Finite-Count Bounds under Certified Finite-Range Dependence",
        "model":"blocks of m=5 identical detector events; blocks mutually independent","p0":p0,"p1":p1,"block_length":m,
        "one_block_Chernoff_information":c,"per_raw_event_exponent":c/m,"rows":rows,
        "theorem":(
            "The complete n=km record is statistically equivalent to k independent Bernoulli samples. Its Bayes error is the displayed exact "
            "binomial overlap and obeys P_e<=exp(-k C)/2. Thus a positive count exponent is recovered after a certified finite dependence length, "
            "but it is reduced from C to C/m per raw event."
        ),
        "status":"proven_exact_finite_count_law_for_declared_m_dependent_block_model",
        "boundary":"The block partition, stationarity surrogate, p0, p1, and correlation length are supplied; arbitrary hidden Markov drift remains open.",
    }


def st140_matched_gap_bath(a: np.ndarray) -> dict:
    vals=np.linalg.eigvalsh(a); unique=[]
    for value in vals:
        if not unique or abs(value-unique[-1])>1e-9: unique.append(float(value))
    gap=unique[1]-unique[0]; beta=.8; excited=math.exp(-beta*gap)/(1+math.exp(-beta*gap)); ground=1-excited
    # Basis |00>,|01>,|10>,|11>; SWAP is exactly energy conserving for matched gaps.
    swap=np.array([[1,0,0,0],[0,0,1,0],[0,1,0,0],[0,0,0,1]],dtype=complex)
    htot=np.diag([0,gap,gap,2*gap]); comm=float(np.linalg.norm(swap@htot-htot@swap))
    rows=[]
    for theta in [0,math.pi/8,math.pi/4,3*math.pi/8,math.pi/2]:
        r=math.sin(theta)**2
        rows.append({"theta":theta,"exchange_probability":r,"up_probability_from_ground":excited*r,
                     "down_probability_from_excited":ground*r,"detailed_balance_ratio":excited/ground})
    packet={"strict_selected_gap":gap,"beta":beta,"bath_populations":[ground,excited],"energy_commutator_norm":comm,
            "rows":rows,"full_swap_resets_selected_two_level_subsystem":True,
            "theorem":(
                "For a bath qubit with the same gap Delta, the excitation-exchange unitary commutes with H_S+H_B. Its up/down probabilities are "
                "b_1 sin^2(theta) and b_0 sin^2(theta), with ratio exp(-beta Delta). At theta=pi/2 the selected two-level subsystem is reset exactly "
                "to the bath Gibbs state. On the twelve-level strict system, one qubit leaves all unaddressed energy populations invariant and therefore cannot implement a global Gibbs reset."
            )}
    PACK140.write_text(json.dumps(native(packet),indent=2,sort_keys=True),encoding="utf-8")
    return {"program":"ST140","object":"Matched-Gap Qubit Thermal Dilation","packet_file":PACK140.name,"packet_sha256":sha(PACK140),
            **packet,"status":"proven_exact_selected_gap_dilation_and_full_system_no_go_for_one_bath_qubit",
            "boundary":"The bath Hamiltonian, beta, interaction time, selected eigenvectors, clock, and energy scale are supplied."}


def st141_nondiagonal_minimax(a: np.ndarray) -> dict:
    weights=np.array([-a[0,d] for d in range(1,7)]); tmax=4*float(np.min(weights))
    rng=np.random.default_rng(SEED+141); random_responses=[]
    for _ in range(1000):
        x=rng.random(N); x/=np.linalg.norm(x); rho=np.outer(x,x)
        h=rng.random((N,N)); h=h@h.T; h/=np.trace(h)
        random_responses.append(float(np.trace(h@rho)))
    packet={"adversary":("trace-one PSD matrices Delta with entrywise nonnegative entries; A+t Delta remains graph-feasible "
                          "for every 0<=t<=4 min_d w_d"),
            "safe_lift_amplitude":tmax,"detector_budget":"H>=0, Tr(H)=1",
            "depolarizing_measurement_noise":"H_delta=(1-delta)H+delta I/12","minimax_value":1/N,
            "uniform_detector":"I/12","random_response_range":[min(random_responses),max(random_responses)],
            "worst_additive_calibration_error_formula":"max(0,1/12-epsilon)",
            "theorem":(
                "The adversary contains every coordinate projector E_ii, so min_Delta Tr(H Delta)<=min_i H_ii<=1/12. "
                "The uniform detector I/12 returns 1/12 for every trace-one Delta and is fixed by depolarizing measurement noise. "
                "Hence the minimax value remains 1/12 for every declared noise strength. An independent worst additive response error epsilon reduces the certified guarantee to max(0,1/12-epsilon)."
            )}
    PACK141.write_text(json.dumps(native(packet),indent=2,sort_keys=True),encoding="utf-8")
    return {"program":"ST141","object":"Noisy Minimax Observation on a Non-Diagonal Graph-Feasible Perturbation Class",
            "packet_file":PACK141.name,"packet_sha256":sha(PACK141),**packet,
            "status":"proven_exact_minimax_value_for_declared_nondiagonal_face_and_noise",
            "boundary":"The uncertainty cone, fine access, normalization, and noise law are supplied; uniqueness of all optimal detectors and laboratory realization are open."}


def make_figures(d):
    FIG_DIR.mkdir(exist_ok=True)
    fig,ax=plt.subplots(figsize=(7,4)); ax.bar(range(7),d["ST130"]["spectral_multiplicities"]); ax.set(xticks=range(7),xlabel="distinct spectral class",ylabel="multiplicity",title="ST130: strict C12 spectrum has seven certified classes"); fig.tight_layout(); fig.savefig(FIG_DIR/"st130_algebra_dimensions.png",dpi=190); plt.close(fig)
    fig,ax=plt.subplots(figsize=(7,4)); rows=d["ST132"]["Newton_history"]; ax.semilogy([r["iteration"] for r in rows],[max(r["residual_inf"],1e-18) for r in rows],"o-"); ax.set(xlabel="Newton iteration",ylabel="infinity-norm residual",title="ST132: center generated without prior certificate"); fig.tight_layout(); fig.savefig(FIG_DIR/"st132_center_isolation.png",dpi=190); plt.close(fig)
    fig,ax=plt.subplots(figsize=(7,4)); rows=d["ST133"]["rows"]; ax.plot([r["epsilon"] for r in rows],[r["optimal_average_fidelity"] for r in rows],"o-"); ax.set(xlabel="noise epsilon",ylabel="optimal average fidelity",ylim=(0,1.02),title="ST133: exact noisy-pinch recovery law"); fig.tight_layout(); fig.savefig(FIG_DIR/"st133_noisy_recovery.png",dpi=190); plt.close(fig)
    fig,ax=plt.subplots(figsize=(7,4)); rows=d["ST134"]["rows"]; ax.loglog([r["epsilon"] for r in rows],[r["trace_distance_to_twirl"] for r in rows],"o-",label="trace distance"); ax.loglog([r["epsilon"] for r in rows],[max(r["relative_entropy_asymmetry_nats"],1e-18) for r in rows],"s-",label="relative entropy"); ax.set(xlabel="symmetry-breaking epsilon",ylabel="asymmetry cost",title="ST134: no positive minimum source cost"); ax.legend(); fig.tight_layout(); fig.savefig(FIG_DIR/"st134_asymmetry_cost.png",dpi=190); plt.close(fig)
    fig,ax=plt.subplots(figsize=(7,4)); rows=d["ST135"]["rows"]; ax.scatter([r["lambda"] for r in rows],[r["threshold_g"] for r in rows],s=[35*r["multiplicity"] for r in rows]); ax.set(xlabel="strict eigenvalue",ylabel="pump threshold",title="ST135: modal thresholds and degeneracy"); fig.tight_layout(); fig.savefig(FIG_DIR/"st135_mode_thresholds.png",dpi=190); plt.close(fig)
    fig,ax=plt.subplots(figsize=(7,4)); rows=d["ST139"]["rows"]; ax.semilogy([r["raw_events"] for r in rows],[r["exact_Bayes_error"] for r in rows],"o-",label="exact"); ax.semilogy([r["raw_events"] for r in rows],[r["Chernoff_upper_bound"] for r in rows],"--",label="Chernoff bound"); ax.set(xlabel="raw events",ylabel="Bayes error",title="ST139: finite-range dependence retains a reduced exponent"); ax.legend(); fig.tight_layout(); fig.savefig(FIG_DIR/"st139_dependent_counts.png",dpi=190); plt.close(fig)
    fig,ax=plt.subplots(figsize=(7,4)); rows=d["ST140"]["rows"]; ax.plot([r["theta"] for r in rows],[r["up_probability_from_ground"] for r in rows],"o-",label="up"); ax.plot([r["theta"] for r in rows],[r["down_probability_from_excited"] for r in rows],"s-",label="down"); ax.set(xlabel="exchange angle",ylabel="transition probability",title="ST140: matched-gap thermal exchange"); ax.legend(); fig.tight_layout(); fig.savefig(FIG_DIR/"st140_matched_gap_bath.png",dpi=190); plt.close(fig)
    fig,ax=plt.subplots(figsize=(7,4)); eps=np.linspace(0,.1,100); ax.plot(eps,np.maximum(0,1/N-eps)); ax.axhline(1/N,color="black",ls="--",label="depolarizing-noise value"); ax.set(xlabel="additive calibration error",ylabel="guaranteed response",title="ST141: exact minimax guarantee"); ax.legend(); fig.tight_layout(); fig.savefig(FIG_DIR/"st141_minimax_noise.png",dpi=190); plt.close(fig)


def main():
    _,a,_=strict_operator()
    out={"metadata":{"programs":"ST130-ST141","date":"2026-08-11","seed":SEED,"python":platform.python_version(),"numpy":np.__version__,"scipy":scipy.__version__}}
    out["ST130"]=st130_functional_calculus_no_gauge(a); out["ST131"]=st131_diagonal_face(a); out["ST132"]=st132_center_isolation(); out["ST133"]=st133_noisy_recovery()
    out["ST134"]=st134_symmetry_breaking_cost(); out["ST135"]=st135_pumped_strict_modes(a); out["ST136"]=st136_parametric_design(a); out["ST137"]=st137_refinement_diagrams()
    out["ST138"]=st138_conditional_independence_no_selection(); out["ST139"]=st139_dependent_counts(); out["ST140"]=st140_matched_gap_bath(a); out["ST141"]=st141_nondiagonal_minimax(a)
    out["recommended_next_programs"]=[
        {"id":"ST142","priority":1,"study":"classify natural operational quotients beyond strict functional calculus without pre-naming the fine sector"},
        {"id":"ST143","priority":2,"study":"enumerate bounded noncirculant face adjacencies outside the diagonal orthant face"},
        {"id":"ST144","priority":3,"study":"perform exhaustive multibasin fold-root isolation on a declared compact state domain"},
        {"id":"ST145","priority":4,"study":"solve optimal recovery for coherent leakage and asymmetric sector misclassification"},
        {"id":"ST146","priority":5,"study":"add an explicit preparation-resource constraint and seek a positive symmetry-breaking cost theorem"},
        {"id":"ST147","priority":6,"study":"analyze equivariant nonlinear coupling and orbital stability on the first degenerate strict eigenspace"},
        {"id":"ST148","priority":7,"study":"widen the ST136 nuisance box and certify or locate its first bifurcation boundary"},
        {"id":"ST149","priority":8,"study":"implement affine-cohomology path-independence certification for arbitrary finite refinement DAGs"},
        {"id":"ST150","priority":9,"study":"type a causal region net and test whether minimality removes the ST138 algebra ambiguity"},
        {"id":"ST151","priority":10,"study":"derive finite-count bounds for stationary hidden-Markov detector drift with certified contraction"},
        {"id":"ST152","priority":11,"study":"build a multi-gap bath ladder and prove bath-dimension bounds for approximate global Gibbs reset"},
        {"id":"ST153","priority":12,"study":"classify all optimal minimax detectors on the graph-feasible nonnegative-entry cone"},
    ]
    out["central_verdict"]=(
        "The strict functional-calculus class cannot generate the fine U(12) gauge: the projection layer remains irreducibly additional in that class. "
        "The fold certificate can now discover its own local center, exact noisy recovery and finite-dependence count laws are available, and a matched-gap bath qubit realizes thermalization of one selected transition. "
        "Symmetry breaking can be made arbitrarily cheap in unconstrained state space, so a positive selector cost requires a preparation resource theory."
    )
    out["epistemic_boundary"]="No strict fine-gauge source, QW-2191 discharge, dimensional clock/unit, laboratory apparatus or record, legacy-to-strict completion or role transfer, Standard Model, gravity, L_total, physical projection theorem, or ToE closure is claimed."
    RESULTS.write_text(json.dumps(native(out),indent=2,sort_keys=True),encoding="utf-8")
    with SUMMARY.open("w",newline="",encoding="utf-8") as handle:
        writer=csv.writer(handle); writer.writerow(["program","object","status"])
        for k in range(130,142): writer.writerow([f"ST{k}",out[f"ST{k}"]["object"],out[f"ST{k}"]["status"]])
    make_figures(out)
    print(json.dumps({"results":RESULTS.name,"programs":12,"figures":8},indent=2))


if __name__ == "__main__": main()
