#!/usr/bin/env python3
"""Ten rounds: finite-kernel tail continuation and continuum-class no-go."""
import hashlib,json,math,numpy as np
from fin_st2172_st2261_common import ROOT,write_packet,write_round
def emit(lo,names,rows):
 d={}
 for i,(s,b,p) in enumerate(rows):k=lo+i;d[f'ST{k}']=write_packet(k,names[i],s,b,p)
 assert len(rows)==15;write_round(lo,lo+14,d)
eta=1.8;om=.18575;ph=.1625
def raw(d):return math.cos(om*d+ph)/(1+d**eta)
def symbols(N=1000000):
 n=np.arange(1,N+1,dtype=float);base=np.cos(om*n+ph)/(1+n**eta);ab=np.abs(base);tr=np.where(n<=6,base,0)
 ks=np.logspace(-4,-1.3,15)
 def L(w):return np.array([2*np.sum(w*(1-np.cos(k*n))) for k in ks])
 return ks,L(base),L(ab),L(tr)
KS,LS,LA,LT=symbols()
def slope(v,a=2,b=10):return float(np.polyfit(np.log(KS[a:b]),np.log(abs(v[a:b])),1)[0])
def r1():
 names=['RestrictionMap','FrozenCoordinates','TailKernel','InfiniteKernel','AffineFiber','FiniteRangeWitness','SignedWitness','AbsoluteWitness','PositivePartWitness','ExponentialWitness','ExactAgreement','DistinctAsymptotics','IdentifiabilityNoGo','RoundOneVerdict','RoundOneRecommendation']
 rows=[('Defined','Restrict sequences to d=1..6.',{}),('Proven','Strict A depends only six weights.',{}),('Proven','Any sequence supported d>=7 lies in kernel.',{}),('Proven','Infinite-dimensional.',{}),('Theorem','All continuations form K0+ker restriction.',{}),('Constructed','Set tail zero.',{}),('Constructed','Continue analytic cosine formula.',{}),('Constructed','Use absolute cosine tail.',{}),('Constructed','Use positive part tail.',{}),('Constructed','Attach arbitrary positive exponential tail.',{}),('Proven','All patched rules match d<=6.',{}),('Proven','They have different locality/symbol classes.',{}),('No-go','Finite A cannot identify tail.',{}),('Round verdict','Continuum completion is infinitely nonunique.',{}),('Recommendation','Literal signed tail.',{})];emit(3672,names,rows)
def r2():
 coef=float(LS[0]/KS[0]**2);names=['SignedFormula','FirstSignCrossing','ShiftedSingularities','ZeroNeighborhood','QuadraticFit','QuadraticCoefficient','NegativeSymbol','PSDNoGo','MarkovNoGo','WaveInstability','FiniteC12Positivity','DomainProtection','AnalyticityBenefit','RoundTwoVerdict','RoundTwoRecommendation']
 rows=[('Defined','cos(omega d+phi)/(1+d^eta) all d.',{}),('Computed','First negative integer d.',{'d':next(d for d in range(1,100) if raw(d)<0)}),('Proven','Power singularities shifted near k=+-omega.',{}),('Proven','k=0 lies away from shifted singularity.',{}),('Computed','Small-k absolute slope.',{'slope':slope(LS,0,6)}),('Computed','lambda/k2.',{'coefficient':coef}),('Proven/Computed','Coefficient negative.',{}),('No-go','Signed conductances fail positive Dirichlet form.',{}),('No-go','Not a Markov heat generator.',{}),('Boundary','Negative low modes give unstable wave/heat interpretations.',{}),('Proven','d<=6 weights remain positive.',{}),('Interpretation','Finite cutoff stops before sign change.',{}),('Positive','Literal formula is smooth/analytic in d.',{}),('Round verdict','Literal infinite strict formula is locally quadratic but spectrally negative.',{}),('Recommendation','Positive absolute tail.',{})];emit(3687,names,rows)
def r3():
 names=['AbsoluteContinuation','ExactFiniteMatch','Positivity','TailEnvelope','FractionalOrder','NumericalSlope','SpectralDimension','WalkExponent','WaveSpeed','NondifferentiableZeros','AnalyticityLoss','AlternativePositivePart','FractionalUniversality','RoundThreeVerdict','RoundThreeRecommendation']
 rows=[('Defined','|cos|/(1+d^eta).',{}),('Proven','Cos positive for d=1..6.',{}),('Proven','All conductances nonnegative.',{}),('Proven','Periodic mean times d^-eta.',{}),('Proven','alpha=eta-1=.8.',{}),('Computed','Small-k fit.',{'slope':slope(LA,4,12)}),('Proven','d_s=2/.8=2.5 in 1D.',{}),('Proven','d_w=.8.',{}),('No-go','Wave group speed diverges.',{}),('Boundary','Absolute value creates cusps in continuous d formula.',{}),('No-go','Cannot keep literal analyticity.',{}),('Constructed','max(K,0) also positive and finite-matching.',{}),('Proven','Many positive periodic tails share alpha=.8.',{}),('Round verdict','Positivity can be restored but does not select one tail or causal physics.',{}),('Recommendation','Finite-range tail.',{})];emit(3702,names,rows)
def r4():
 names=['TruncatedContinuation','ExactMatch','PositiveConductances','FiniteRange','QuadraticSymbol','NumericalSlope','PositiveCoefficient','NormalWalk','FiniteWaveSpeed','SpeedValue','CutoffChoice','RefinementBoundary','SmoothTailAlternative','RoundFourVerdict','RoundFourRecommendation']
 rows=[('Defined','K(d)=0 for d>6.',{}),('Proven','Matches all strict weights.',{}),('Proven','d<=6 positive.',{}),('Proven','Compact support.',{}),('Proven','lambda~Ck2.',{}),('Computed','Small-k fit.',{'slope':slope(LT,0,6)}),('Computed','lambda/k2.',{'coefficient':float(LT[0]/KS[0]**2)}),('Proven','d_w=2 in 1D.',{}),('Conditional','Wave speed sqrt(C).',{}),('Computed','Dimensionless only.',{'c_hat':math.sqrt(float(LT[0]/KS[0]**2))}),('No-go','Why cutoff exactly6 remains finite-carrier premise.',{}),('Boundary','Growing refinements need cutoff law.',{}),('Constructed','Positive exponential tails give analytic k and quadratic order too.',{}),('Round verdict','A positive local continuum exists but is not unique.',{}),('Recommendation','Classify incompatible desiderata.',{})];emit(3717,names,rows)
def r5():
 names=['Desiderata','LiteralAnalyticity','ConductancePositivity','ExactFiniteMatch','InfiniteSupport','LocalQuadratic','FractionalTail','SignedFailure','AbsoluteTradeoff','TruncationTradeoff','NoAllUnique','PositiveClassSplit','SelectionAxiom','RoundFiveVerdict','RoundFiveRecommendation']
 rows=[('Classified','Exact match, positivity, literal formula, locality, smoothness.',{}),('Passed by signed','Literal analyticity holds but positivity fails.',{}),('Passed by positive classes','Absolute, truncated and other positive tails.',{}),('Passed','All patched constructions match d<=6.',{}),('Passed by several','Signed, absolute and exponential tails have infinite support.',{}),('Passed by local classes','Truncated/exponential and signed formally have quadratic order.',{}),('Passed by nonlocal classes','Absolute/positive periodic tails have fractional order.',{}),('Proven','Literal formula and conductance positivity are incompatible after d=7.',{}),('Boundary','Absolute value keeps magnitude but loses analytic sign.',{}),('Boundary','Truncation imports a cutoff.',{}),('No-go','Current premises do not choose a unique maximal set.',{}),('Proven','At least local and fractional positive subclasses survive.',{}),('Missing','Need a continuum-selection principle.',{}),('Round verdict','Positivity narrows but does not close the continuation.',{}),('Recommendation','Causality/dual dynamics.',{})];emit(3732,names,rows)
def r6():
 names=['LocalClass','FractionalClass','HeatPropagationLocal','HeatPropagationFractional','WaveConeLocal','WaveConeFractional','UnitaryTails','LiebRobinsonBoundary','ClockScaling','SignedClassRejected','PhysicalCausality','ContinuumFork','PredictionNoGo','RoundSixVerdict','RoundSixRecommendation']
 rows=[('Defined','Quadratic finite/exponential tail.',{}),('Defined','Positive power tail alpha=.8.',{}),('Proven','Diffusive infinite support but Gaussian scaling.',{}),('Proven','Stable Levy jumps/nonlocal tails.',{}),('Conditional','Finite-range wave admits finite speed proxy/bounds.',{}),('No-go','Fractional wave has divergent low-k speed.',{}),('Boundary','Both unitary classes spread differently.',{}),('Conditional','Finite exponential moments needed for exponential cone bounds.',{}),('Proven','Local heat/unitary and wave use distinct clocks.',{}),('Proven','Literal signed tail not positive.',{}),('No-go','Finite A alone cannot select causal class.',{}),('Proven','Operational predictions differ.',{}),('No-go','No unique propagation law.',{}),('Round verdict','Continuum choice is physically consequential and unsourced.',{}),('Recommendation','Selection principles.',{})];emit(3747,names,rows)
def r7():
 names=['MinimalChange','AnalyticContinuation','MaximumEntropyTail','CompleteMonotonicity','StieltjesTail','PositivityProjection','ShortestSupport','SmoothestTail','RegularizationDependence','PriorDependence','AxiomRemoval','CrossValidationBoundary','StrictSourceAudit','RoundSevenVerdict','RoundSevenRecommendation']
 rows=[('Axiom','Minimize tail norm -> truncation.',{}),('Axiom','Literal formula -> signed unstable tail.',{}),('Axiom','Entropy needs reference/constraints.',{}),('Axiom','Positive mixtures restrict oscillations.',{}),('Axiom','May select a positive resolvent class, not strict cosine.',{}),('Axiom','Absolute/positive part choices.',{}),('Axiom','Truncation.',{}),('Axiom','Exponential/analytic optimization.',{}),('Proven','Different penalties select different tails.',{}),('No-go','Every inference requires a prior.',{}),('Proven','Removing prior restores infinite fiber.',{}),('Boundary','No held-out beyond-d6 data.',{}),('Fail','No current strict selection functional.',{}),('Round verdict','Standard regularizers do not become physical laws automatically.',{}),('Recommendation','Dimension/product consequences.',{})];emit(3762,names,rows)
def r8():
 names=['FiniteAsymptoticDimension','LocalBaseDs','FractionalBaseDs','SignedNoDs','CantorFiberFamily','ProductLocal','ProductFractional','TargetFourLocal','TargetFourFractional','MultipleRho','RelativeScale','Crossover','NoUniqueDimension','RoundEightVerdict','RoundEightRecommendation']
 rows=[('Proven','C12 alone d_s=0 asymptotically.',{}),('Conditional','Local 1D base d_s=1.',{}),('Conditional','Fractional base d_s=2.5.',{}),('Rejected','Signed negative operator.',{}),('Conditional','d_s,f=2ln2/ln2rho.',{}),('Proven','Total=1+d_f.',{}),('Proven','Total=2.5+d_f.',{}),('Conditional','Need d_f=3.',{}),('Conditional','Need d_f=1.5.',{}),('Proven','Different rho realize both.',{}),('No-go','Gamma remains.',{}),('Boundary','Finite windows mimic plateaus.',{}),('No-go','Continuation fork propagates to dimension fork.',{}),('Round verdict','No strict four-dimensional prediction.',{}),('Recommendation','Operational discrimination.',{})];emit(3777,names,rows)
def r9():
 names=['BeyondSixData','SmallKData','SignTest','PropagationTailTest','WaveSpeedTest','SizeScaling','HeatTraceTest','CutoffVariation','TailPriorAudit','Calibration','FiniteSample','SyntheticLimits','ExternalRecord','RoundNineVerdict','RoundNineRecommendation']
 rows=[('Required','Measure/derive couplings d>=7.',{}),('Required','Large-N low-k eigenvalues.',{}),('Decisive','Literal signed tail predicts negative low modes.',{}),('Decisive','Fractional vs local spatial tails.',{}),('Decisive','Finite vs divergent group speed.',{}),('Required','Multiple N.',{}),('Required','Multiple t.',{}),('Required','Test stability under truncation.',{}),('Required','Declare regularizer/prior.',{}),('No-go','Length/time calibration absent.',{}),('Boundary','Long-range slopes need large range.',{}),('No-go','Current local computation is not evidence.',{}),('Missing','No independently registered tail record.',{}),('Round verdict','Classes are falsifiably distinct but untested externally.',{}),('Recommendation','Final synthesis.',{})];emit(3792,names,rows)
def r10():
 gate=ROOT/'FIN_ST3807_ST3821_TailContinuationGate.json';g={'rows':[{'name':n,'pass':v} for n,v in [('restriction-fiber theorem',True),('literal-tail sign theorem',True),('positive-class bifurcation theorem',True),('unique positive continuation',False),('strict cutoff law',False),('strict long-range law',False),('unique causal class',False),('unique continuum dimension',False),('physical calibration',False),('OA evidence',False)]]};gate.write_text(json.dumps(g,indent=2)+'\n')
 names=['RestrictionTheorem','SignedTailTheorem','PositiveForkTheorem','LiteralNoGo','LocalBranch','FractionalBranch','SelectionNoGo','Gate','GateScore','ProvenLedger','ConditionalLedger','RefutedLedger','HighestValueNext','FinalInterpretation','CycleTrigger']
 rows=[('Proven','Restriction fiber infinite-dimensional.',{}),('Proven','Literal tail quadratic with negative symbol.',{}),('Proven','Abs tail fractional; truncation local.',{}),('No-go','Literal formula not positive Dirichlet.',{}),('Conditional','Positive finite-range physics.',{}),('Conditional','Positive fractional physics.',{}),('No-go','No strict selector.',{}),('Constructed','Ten rows.',{'file':gate.name}),('Result','Three mathematical passes.',{'passes':3,'rows':10}),('Ledger','Tail classification and signs.',{}),('Ledger','Two positive continuum classes.',{}),('Ledger','Unique strict continuum.',{}),('Recommendation','Derive one beyond-d6 coupling or a tail variational law from independent strict structure; otherwise freeze the continuum fork.',{}),('Final verdict','Finite FIN mathematics does not determine its infinite continuum completion; different completions make incompatible physical predictions.',{'fundamental':False}),('Cycle complete','Release 11.24.',{'programs':150,'rounds':10,'range':'ST3672-ST3821','strict_ToE_closure':False,'gate_sha256':hashlib.sha256(gate.read_bytes()).hexdigest()})];emit(3807,names,rows)
def main():r1();r2();r3();r4();r5();r6();r7();r8();r9();r10()
if __name__=='__main__':main()
