#!/usr/bin/env python3
"""Ten rounds: logarithmic-mean Onsager mobility from Shannon plus strict heat."""
import hashlib,json,math,numpy as np
from fin_st2172_st2261_common import ROOT,strict_A_W,write_packet,write_round
def emit(lo,names,rows):
 d={};assert len(rows)==15
 for i,(s,b,p) in enumerate(rows):k=lo+i;d[f'ST{k}']=write_packet(k,names[i],s,b,p)
 write_round(lo,lo+14,d)
A,W=strict_A_W();p0=np.arange(1,13,dtype=float);p0/=p0.sum()
def lm(a,b):return a if a==b else (a-b)/(math.log(a)-math.log(b))
def mobility(p,A=A,W=W):
 n=len(p);K=np.zeros((n,n))
 for i in range(n):
  for j in range(i+1,n):
   c=W[i,j]*lm(p[i],p[j]);K[i,i]+=c;K[j,j]+=c;K[i,j]-=c;K[j,i]-=c
 return K
K0=mobility(p0);res=float(np.linalg.norm(K0@np.log(p0)-A@p0,np.inf))
def r1():
 names=['ProbabilitySimplex','ShannonEntropy','EntropyGradient','LogarithmicMean','DiagonalExtension','EdgeMobility','OnsagerOperator','Symmetry','MassKernel','Positivity','StrictWeights','StateDependence','ConstructedMobility','RoundOneVerdict','RoundOneRecommendation']
 rows=[('Defined','p_i>0,sum p=1.',{}),('Defined','H=sum p log p.',{}),('Proven','grad H=log p+1.',{}),('Defined','Lambda(a,b)=(a-b)/(loga-logb).',{}),('Proven','Lambda(a,a)=a.',{}),('Constructed','c_ij=W_ij Lambda(p_i,p_j).',{}),('Constructed','K_p graph Laplacian of c.',{}),('Proven','Symmetric.',{}),('Proven','K_p 1=0.',{}),('Proven','K_p>=0.',{}),('Proven','Uses strict W only.',{}),('Proven','Mobility depends on state p.',{}),('Positive result','A canonical candidate exists.',{}),('Round verdict','Shannon and W generate a positive local Onsager mobility.',{}),('Recommendation','Prove heat identity.',{})];emit(8397,names,rows)
def r2():
 names=['MeanIdentity','EdgeFluxIdentity','OperatorIdentity','GradientFlow','HeatEquation','NumericalReplay','Residual','MassConservation','EntropyDissipation','DirichletEntropyProduction','StationaryUniform','StrictConvexityOnSimplex','FiniteGlobalFlow','RoundTwoVerdict','RoundTwoRecommendation']
 rows=[('Proven','Lambda(a,b)(loga-logb)=a-b.',{}),('Proven','c_ij gradient difference=W_ij(p_i-p_j).',{}),('Proven','K_p logp=A p.',{}),('Proven','p_dot=-K_p gradH.',{}),('Proven','Equals p_dot=-A p.',{}),('Computed','Nonuniform 12-state p.',{}),('Computed','Infinity residual.',{'residual':res}),('Proven','1^T p constant.',{}),('Proven','dH/dt=-(logp)^T A p<=0.',{'witness':float(np.log(p0)@A@p0)}),('Proven','Sum W_ij(p_i-p_j)(logp_i-logp_j)/2.',{}),('Proven','Connected graph.',{}),('Proven','Unique entropy minimum uniform.',{}),('Proven','Heat semigroup preserves simplex.',{}),('Round verdict','Strict heat is exactly Shannon gradient flow in this metric.',{}),('Recommendation','Uniqueness.',{})];emit(8412,names,rows)
def r3():
 names=['EdgeLocalClass','SymmetricMean','HeatMatching','FunctionalEquation','UniqueSolution','DiagonalLimit','NoAlternativeMean','OverallMultiplier','ClockRescaling','GraphAssembly','D12Naturality','UniquenessScope','AxiomRemoval','RoundThreeVerdict','RoundThreeRecommendation']
 rows=[('Declared','Edge-local mobility W_ij M(a,b).',{}),('Required','M(a,b)=M(b,a)>0.',{}),('Required','M(a,b)(loga-logb)=a-b.',{}),('Derived','Pointwise equation.',{}),('Theorem','M=Lambda for a!=b.',{}),('Proven','Continuity gives M(a,a)=a.',{}),('Proven','No other continuous edge mean in class.',{}),('Boundary','Multiplying K by c changes heat to cA.',{}),('No-go','Physical clock scale remains.',{}),('Proven','Edge uniqueness yields operator uniqueness.',{}),('Proven','Inherited from W.',{}),('Boundary','Requires Shannon, locality and exact heat matching.',{}),('Proven','Removing any premise admits alternatives.',{}),('Round verdict','Mobility shape is uniquely derived in the declared class.',{}),('Recommendation','Boundary/positivity dynamics.',{})];emit(8427,names,rows)
def r4():
 names=['BoundaryBehavior','LogMeanAtZero','InwardFlux','SimplexInvariance','EntropyLyapunov','DetailedBalance','Reversibility','MetricTensor','DegenerateZeroMode','ConvergenceRate','SpectralGap','NoBlowup','NegativeInformationSign','RoundFourVerdict','RoundFourRecommendation']
 rows=[('Boundary','Lambda(a,0)->0.',{}),('Proven','Continuous nonnegative extension.',{}),('Proven','Heat equation has inward positive flux at empty vertex.',{}),('Proven','P_t stochastic for conductance A.',{}),('Proven','H decreases.',{}),('Proven','Uniform stationary law.',{}),('Proven','A symmetric.',{}),('Constructed','K_p on tangent space.',{}),('Proven','Constants are kernel.',{}),('Conditional','Controlled by strict spectral gap.',{}),('Known finite','Gap positive.',{}),('Proven','Linear heat globally bounded.',{}),('No-go','Reversing entropy gradient gives backward heat/instability.',{}),('Round verdict','Candidate is globally well-posed for the finite heat channel.',{}),('Recommendation','Alternative entropies.',{})];emit(8442,names,rows)
def r5():
 names=['GeneralEntropy','GeneralGradient','GeneralMean','HeatIdentity','Convexity','Family','ShannonSpecialization','QuadraticEntropy','PowerEntropy','MetricDependence','EntropyChoice','InformationAxiom','UniquenessConditional','RoundFiveVerdict','RoundFiveRecommendation']
 rows=[('Defined','F_phi=sum phi(p_i).',{}),('Proven','grad=phi prime(p).',{}),('Defined','M_phi(a,b)=(a-b)/(phi prime(a)-phi prime(b)).',{}),('Proven','K_phi gradF=A p.',{}),('Required','Strict convex phi gives positive mean.',{}),('Proven','Every convex entropy gives its own metric.',{}),('Proven','phi=xlogx yields log mean.',{}),('Example','phi=x2/2 gives M=1.',{}),('Example','Power entropies give power means.',{}),('No-go','Heat flow alone does not select entropy-metric pair.',{}),('Boundary','Shannon must be independently privileged.',{}),('Positive','FIN informational ontology motivates but does not mathematically force phi.',{}),('Classified','Unique after Shannon is fixed.',{}),('Round verdict','Cross-fibre theorem closes mobility only conditional on entropy choice.',{}),('Recommendation','Dual dynamics.',{})];emit(8457,names,rows)
def r6():
 names=['HeatChannel','UnitaryChannel','CommonA','GradientCharacter','HamiltonianCharacter','EntropyChangeHeat','EntropyChangeUnitary','NoSingleMetric','WaveChannel','GibbsState','ObserverParadox','OperationalChoice','DualismPreserved','RoundSixVerdict','RoundSixRecommendation']
 rows=[('Proven','P_t=e^-tA.',{}),('Proven','U_t=e^-itA.',{}),('Proven','Same spectrum.',{}),('Proven','Heat is Shannon gradient flow.',{}),('Proven','Unitary is Hamiltonian/isometric.',{}),('Proven','Classical Shannon generally increases under doubly stochastic P.',{}),('Proven','Von Neumann entropy invariant under U.',{}),('No-go','One dissipative Onsager metric does not generate U.',{}),('Boundary','Second-order wave needs phase-space symplectic structure.',{}),('Boundary','Requires beta/state choice.',{}),('Resolved','Different channels are operational choices, not contradiction.',{}),('Missing','Preparation/instrument selects channel.',{}),('Proven','Common A organizes duality without identifying dynamics.',{}),('Round verdict','Mobility theorem closes only the heat shadow.',{}),('Recommendation','Refinement compatibility.',{})];emit(8472,names,rows)
def r7():
 q=.2;B=np.array([[q,-q],[-q,q]]);A24=np.kron(A,np.eye(2))+np.kron(np.eye(12),B);names=['ProductRefinement','FineWeights','FineLogMean','FineHeatIdentity','CoarseIntertwiner','HeatCompatibility','StateFactorization','PrismBoundary','FiberRate','PerLevelQ','MetricTransport','CantorLimit','RefinementClock','RoundSevenVerdict','RoundSevenRecommendation']
 rows=[('Constructed','A24 product.',{}),('Proven','Positive conductances.',{}),('Constructed','Log mean on every fine edge.',{}),('Proven','K_p^24 logp=A24 p.',{}),('Proven','A24 R=R A12.',{}),('Proven','Heat semigroups intertwine.',{}),('Boundary','Coarse/fine probability maps must be declared.',{}),('Boundary','Stationary prism RG separate configuration model.',{}),('No-go','q remains free.',{}),('No-go','q_n sequence remains free.',{}),('Positive','Mobility construction is functorial once A24 is supplied.',{}),('Boundary','Limit needs selected rho/rates.',{}),('No-go','Overall/per-level clock remains.',{}),('Round verdict','Mobility transports through refinement but does not select refinement.',{}),('Recommendation','Configuration-state boundary.',{})];emit(8487,names,rows)
def r8():
 names=['VertexStateSpace','ConfigurationSpace','DimensionMismatch','VertexEntropy','ConfigurationEntropy','LogMeanVertex','LogMeanConfiguration','TernaryGibbs','DifferentGenerators','MomentProjection','Nonclosure','NoCanonicalLift','ScopeBoundary','RoundEightVerdict','RoundEightRecommendation']
 rows=[('Defined','12 probabilities.',{}),('Defined','4096 binary configurations.',{}),('Proven','Different algebras/dimensions.',{}),('Defined','sum_i p_i logp_i.',{}),('Defined','sum_x pi_x logpi_x.',{}),('Proven','Derives vertex heat mobility.',{}),('Conditional','Derives configuration heat only after configuration graph/energy supplied.',{}),('Boundary','Theta law still conditional.',{}),('No-go','A does not uniquely determine Q.',{}),('Boundary','Configuration moments project to vertex data.',{}),('Proven','Ternary hierarchy does not close first moments.',{}),('No-go','Vertex mobility does not source configuration kinetics.',{}),('Classified','Finite heat channel only.',{}),('Round verdict','Cross-fibre closure is substantial but not total dynamics.',{}),('Recommendation','Physical scale/OA.',{})];emit(8502,names,rows)
def r9():
 names=['InternalTime','RateMultiplier','PhysicalClock','LengthScale','Temperature','KB','EnergyScale','EntropyUnits','Preparation','Instrument','WaitingTimes','Calibration','Evidence','RoundNineVerdict','RoundNineRecommendation']
 rows=[('Proven','Heat parameter t dimensionless.',{}),('No-go','cK_p gives cA and free rate scale.',{}),('Missing','Seconds.',{}),('Missing','Metres.',{}),('Missing','Kelvin/bath.',{}),('Missing','Boltzmann conversion.',{}),('Missing','Joules.',{}),('Boundary','Shannon nats are dimensionless.',{}),('Missing','Physical state preparation.',{}),('Missing','Vertex-resolving instrument.',{}),('Conditional','Timed transitions estimate c.',{}),('No-go','Calibration not internal.',{}),('No-go','No laboratory record.',{}),('Round verdict','Mathematical mobility does not create dimensional physics.',{}),('Recommendation','Synthesis.',{})];emit(8517,names,rows)
def r10():
 gate=ROOT/'FIN_ST8532_ST8546_LogMeanMobilityGate.json';g={'rows':[{'name':n,'pass':v} for n,v in [('log-mean mobility construction',True),('exact Shannon heat-gradient identity',True),('edge-local uniqueness theorem',True),('entropy Lyapunov theorem',True),('refinement functoriality conditional on A24',True),('strict Shannon selection theorem',False),('strict refinement q law',False),('configuration kinetics closure',False),('physical clock/temperature',False),('OA evidence',False)]]};gate.write_text(json.dumps(g,indent=2)+'\n')
 names=['MobilityTheorem','HeatGradientTheorem','UniquenessTheorem','LyapunovTheorem','RefinementTheorem','EntropyChoiceBoundary','ScopeNoGo','PhysicalNoGo','Gate','GateScore','ProvenLedger','ConditionalLedger','HighestValueNext','FinalInterpretation','CycleTrigger']
 rows=[('Proven','K_p from logarithmic mean.',{}),('Proven','K_p logp=A p.',{}),('Proven','Unique in Shannon edge-local heat-matching class.',{}),('Proven','Entropy decreases globally.',{}),('Conditional','Functorial for supplied refined A.',{}),('No-go','Other convex entropies yield other metrics.',{}),('No-go','Does not source Q/continuum/selector.',{}),('No-go','Clock/temperature/OA absent.',{}),('Constructed','Ten rows.',{'file':gate.name}),('Result','Five mathematical passes.',{'passes':5,'rows':10}),('Ledger','Finite heat mobility now closed conditionally on Shannon.',{}),('Ledger','Other channels and physical conversion remain.',{}),('Recommendation','Test whether Shannon is uniquely selected by composability, locality and information additivity within FIN; otherwise label mobility theorem Shannon-conditional.',{}),('Final verdict','FIN gains a canonical frenetic geometry for its heat channel once Shannon entropy is fixed, but not complete physical dynamics.',{'fundamental':False}),('Cycle complete','Release 11.29.',{'programs':150,'rounds':10,'range':'ST8397-ST8546','strict_ToE_closure':False,'gate_sha256':hashlib.sha256(gate.read_bytes()).hexdigest()})];emit(8532,names,rows)
def main():r1();r2();r3();r4();r5();r6();r7();r8();r9();r10()
if __name__=='__main__':main()
