#!/usr/bin/env python3
"""Six rounds: literal dyadic kernel recurrence as q_n source candidate."""
import hashlib,json,math
from fin_st2172_st2261_common import ROOT,write_packet,write_round
def emit(lo,names,rows):
 d={}
 for i,(s,b,p) in enumerate(rows):k=lo+i;d[f'ST{k}']=write_packet(k,names[i],s,b,p)
 write_round(lo,lo+14,d)
w,ph,eta=.18575,.1625,1.8
def K(d):return math.cos(w*d+ph)/(1+d**eta)
def rg(t,q):return t+math.atanh(math.tanh(q)**3*math.tanh(t))
def run(fun,a=1,r=2,N=50,t=.3):
 s=0;qs=[]
 for n in range(N):q=fun(a*r**n);qs.append(q);s+=abs(math.tanh(q)**3);t=rg(t,q)
 return t,s,qs
def r1():
 t,s,qs=run(K,N=50);tr,_,_=run(K,N=3)
 names=['DyadicCandidate','StrictSamples','SignOscillation','CubicSum','ThetaLimit','FiniteDomainTruncation','TailEffect','PositiveEarlyFeedback','SignedTail','SignPreservation','NoTarget','ParameterFreeShape','CandidatePass','RoundOneVerdict','RoundOneRecommendation']
 rows=[('Constructed','q_n=K_strict(2^n).',{}),('Computed','First 12.',{'q':qs[:12]}),('Proven/Computed','Sign becomes mixed from d=8.',{}),('Computed','Absolute cubic sum.',{'sum':s}),('Computed','theta0=.3.',{'theta_inf':t}),('Computed','Use only d=1,2,4 inside finite domain.',{'theta_3':tr}),('Computed','Infinite extension correction.',{'difference':t-tr}),('Observed','First three positive q amplify.',{}),('Observed','Later signed tail nearly cancels/vanishes.',{}),('Proven','Every step preserves theta sign.',{}),('Positive','No target theta inserted.',{}),('Boundary','Uses formula extension.',{}),('Candidate','Mathematically bounded recurrence.',{}),('Round verdict','Literal dyadic sampling gives a concrete bounded hierarchy.',{}),('Recommendation','Prove tail summability.',{})];emit(3072,names,rows)
def r2():
 ratio=2**(-3*eta);bound=ratio/(1-ratio)
 names=['EnvelopeBound','TanhBound','DyadicMajorant','GeometricSeries','AbsoluteSummability','ThetaConvergence','TailBound','EtaThreshold','OscillationIrrelevance','FinitePrefixDominance','RobustPerturbations','CertifiedClass','SummabilityGate','RoundTwoVerdict','RoundTwoRecommendation']
 rows=[('Proven','|K(d)|<=1/(1+d^eta)<=d^-eta.',{}),('Proven','|tanh x|<=|x|.',{}),('Proven','|tanh K(2^n)|^3<=2^(-3eta n).',{}),('Proven','Exact geometric majorant.',{'ratio':ratio,'sum_from_n1_bound':bound}),('Proven','For every eta>0.',{}),('Proven','Prior summability theorem applies.',{}),('Proven','Tail N bound proportional 2^(-3eta N)/(1-ratio).',{}),('Proven','Any positive eta suffices dyadically.',{}),('Proven','Cosine signs do not affect absolute convergence.',{}),('Proven','Limit controlled mostly by low n.',{}),('Proven','Envelope-preserving tail perturbations remain convergent.',{}),('Theorem','Dyadic strict-form extension belongs to bounded hierarchy class.',{}),('Pass mathematical','Convergence unconditional after extension.',{}),('Round verdict','Tail stability is rigorous and does not need numerical cancellation.',{}),('Recommendation','Audit extension domain.',{})];emit(3087,names,rows)
def r3():
 names=['FrozenDomain','BeyondSix','FormulaVsOperator','InfiniteExtension','CyclicDistance','RefinementMap','DistanceScale','PhaseAtLargeD','StrictProvenanceGate','ConditionalTheorem','FinitePrefixTheorem','TailIndependenceBoundary','DomainNoGo','RoundThreeVerdict','RoundThreeRecommendation']
 rows=[('Proven','Strict A uses cyclic distances 1..6.',{}),('Boundary','Dyadic n>=3 evaluates d>=8.',{}),('Proven','An analytic formula can be evaluated without being an exported operator law.',{}),('Extra premise','Assume same kernel on unbounded distances.',{'strict':False}),('No-go','Z12 cyclic distance never equals 8,16,...',{}),('Missing','No strict theorem maps layer n to distance 2^n.',{}),('Missing','No physical lattice spacing.',{}),('Boundary','Oscillatory phase extrapolation unvalidated.',{}),('Fail','Infinite recurrence is not strict-provenance complete.',{}),('Positive','If extension is assumed, convergence theorem is exact.',{}),('Strict finite result','First three q values are genuine strict weights.',{}),('Proven','Small tail effect does not convert premise into theorem.',{}),('No-go','Numerical harmlessness is not provenance.',{}),('Round verdict','Candidate is robust but conditional at the domain bridge.',{}),('Recommendation','Compare legacy separately.',{})];emit(3102,names,rows)
def r4():
 alpha=4*math.log(2);wl=math.pi/4;pl=math.pi/6;beta=.01
 def L(d):return alpha*math.cos(wl*d+pl)/(1+beta*d)
 vals={str(a):run(L,a=a,N=30)[:2] for a in [1,2,3]}
 names=['LegacySequence','LegacyEnvelope','LegacySummability','LegacyLimits','EarlyStrongCoupling','SignedPattern','StrictComparison','KernelSplit','AmplitudeRole','BetaRole','NoTransfer','ConditionalCommonClass','LegacyGate','RoundFourVerdict','RoundFourRecommendation']
 rows=[('Constructed conditional','q_n=K_legacy(2^n).',{}),('Proven','Tail O(2^-n).',{}),('Proven','Cubic dyadic sum converges.',{}),('Computed','Origins 1,2,3.',{'limits_and_sums':vals}),('Observed','alpha_geo makes early q large.',{}),('Observed','Oscillations drive mixed feedback.',{}),('Proven','Legacy and strict limits differ strongly.',{}),('Guardrail','No identity or role transfer.',{}),('Boundary','alpha_geo explicit only legacy.',{}),('Boundary','beta_tors tail differs from strict eta.',{}),('No-go','Cannot use legacy recurrence as strict source.',{}),('Proven','Both fall in summable dyadic class.',{}),('Fail physical','Shared convergence class is not bridge completion.',{}),('Round verdict','Legacy comparison supports mathematical universality only.',{}),('Recommendation','Audit origin/refinement ratio.',{})];emit(3117,names,rows)
def r5():
 origins={str(a):run(K,a=a,N=40)[0] for a in [.5,1,2,3,4,5,6]};ratios={str(r):run(K,a=1,r=r,N=40)[0] for r in [1.5,2,3,4]}
 names=['GeneralSampling','OriginFreedom','OriginResults','RatioFreedom','RatioResults','AllRGreaterOne','SameSummability','DifferentLimits','ScaleSection','TranslationBoundary','RefinementConvention','Identifiability','OriginGate','RoundFiveVerdict','RoundFiveRecommendation']
 rows=[('Defined','q_n=K(a r^n).',{}),('No-go','a not strict-selected.',{}),('Computed','Limits.',{'limits':origins}),('No-go','r not strict-selected.',{}),('Computed','Limits.',{'limits':ratios}),('Proven','Every r>1 with eta>0 is summable.',{}),('Proven','Boundedness common.',{}),('Proven','Output trajectory differs.',{}),('Boundary','Choosing a is a calibration section.',{}),('Boundary','Phase makes origin material.',{}),('Boundary','Binary refinement suggests r=2 but does not derive distance sampling.',{}),('Conditional','Observed layers could fit a,r.',{}),('Gate fail','No canonical a/r map.',{}),('Round verdict','Dyadic choice is natural but not unavoidable.',{}),('Recommendation','Synthesize.',{})];emit(3132,names,rows)
def r6():
 gate=ROOT/'FIN_ST3147_ST3161_DyadicKernelRecurrenceGate.json';g={'rows':[{'name':n,'pass':v} for n,v in [('explicit dyadic recurrence',True),('absolute summability theorem',True),('bounded theta hierarchy',True),('strict beyond-Z12 domain',False),('strict layer-distance map',False),('canonical scale origin a',False),('canonical ratio r',False),('legacy-strict bridge',False),('physical layer scale',False),('OA evidence',False)]]};gate.write_text(json.dumps(g,indent=2)+'\n')
 names=['CandidateTheorem','SummabilityTheorem','NumericalLimit','DomainObstruction','ScaleObstruction','LegacyBoundary','UniversalityBoundary','Gate','GateScore','ProvenLedger','ConditionalLedger','RefutedLedger','HighestValueNext','FinalInterpretation','CycleTrigger']
 rows=[('Conditional','q_n=K_strict(2^n) explicit.',{}),('Proven','Dyadic tail bounded for eta>0.',{}),('Computed','theta_inf=.32668864347458015.',{}),('No-go','n>=3 outside frozen Z12 distances.',{}),('No-go','a,r and physical layer mapping absent.',{}),('Guardrail','Legacy comparison no role transfer.',{}),('No-go','Convergence class does not select recurrence.',{}),('Constructed','Ten rows.',{'file':gate.name}),('Result','Three mathematical passes.',{'passes':3,'rows':10}),('Ledger','Recurrence/convergence/boundedness.',{}),('Ledger','Infinite extension and dyadic map.',{}),('Ledger','Strict/physical hierarchy source.',{}),('Recommendation','Derive a typed layer-to-distance embedding from FIN refinement; otherwise retain recurrence as conditional model.',{}),('Final verdict','Strict kernel shape can regularize a dyadic hierarchy, but does not define the hierarchy domain or scale map.',{'fundamental':False}),('Cycle complete','Release 11.18.',{'programs':90,'rounds':6,'range':'ST3072-ST3161','strict_ToE_closure':False,'gate_sha256':hashlib.sha256(gate.read_bytes()).hexdigest()})];emit(3147,names,rows)
def main():r1();r2();r3();r4();r5();r6()
if __name__=='__main__':main()
