#!/usr/bin/env python3
"""FIN ST142--ST153: natural quotients, constrained selectors, and bath bounds."""

from __future__ import annotations

import csv
import hashlib
import itertools
import json
import math
import platform
from pathlib import Path
from typing import Any

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import mpmath as mp
import numpy as np
import scipy
from scipy.optimize import brentq, minimize_scalar, root

from fin_st01_st15_research import N, strict_operator
from fin_st28_st45_research import dyadic_lift
from fin_st106_st117_research import plus_minus
from fin_st118_st129_research import bounds, ib, interval_left, interval_matvec, spectrum_intervals
from fin_st130_st141_research import parametric_chernoff_stationary, point_design_system
from fin_st132_center_isolation_replay import (
    float_system_jacobian, interval_system, run as run_st132, strict_interval_matrix,
)


ROOT=Path(__file__).resolve().parent
RESULTS=ROOT/"FIN_ST142_ST153_Results.json"
SUMMARY=ROOT/"FIN_ST142_ST153_Summary.csv"
PACK143=ROOT/"FIN_ST143_Noncirculant_Edge_Star.json"
CERT144=ROOT/"FIN_ST144_Multibasin_Fold_Certificate.json"
PACK145=ROOT/"FIN_ST145_Coherent_Syndrome_Recovery.json"
CERT148=ROOT/"FIN_ST148_Nuisance_Continuation_Certificate.json"
PACK149=ROOT/"FIN_ST149_Refinement_DAG_Certificate.json"
PACK151=ROOT/"FIN_ST151_Markov_Modulated_Count_Certificate.json"
PACK152=ROOT/"FIN_ST152_Multigap_Bath_Dimension_Bounds.json"
PACK153=ROOT/"FIN_ST153_Complete_Minimax_Detector_Classification.json"
FIG_DIR=ROOT/"FIN_ST142_ST153_Figures"
SEED=20260823


def native(x:Any)->Any:
    if isinstance(x,dict): return {str(k):native(v) for k,v in x.items()}
    if isinstance(x,(list,tuple)): return [native(v) for v in x]
    if isinstance(x,np.ndarray): return native(x.tolist())
    if isinstance(x,(np.floating,np.integer)): return x.item()
    return x


def sha(path:Path)->str: return hashlib.sha256(path.read_bytes()).hexdigest()


def spectrum_groups(a):
    vals=np.linalg.eigvalsh(a); groups=[]
    for x in vals:
        if not groups or abs(x-groups[-1][0])>1e-9: groups.append([float(x),1])
        else: groups[-1][1]+=1
    return groups


def st142_natural_quotient_no_go(a:np.ndarray)->dict:
    mult=[m for _,m in spectrum_groups(a)]
    doubled=[2*m for m in mult]
    return {
        "program":"ST142","object":"Automorphism-Natural Operational Quotient No-Go",
        "base_multiplicities":mult,"doubled_multiplicities":doubled,
        "doubled_commutant_complex_dimension":sum(m*m for m in doubled),
        "full_automorphism_fixed_algebra_complex_dimension":len(mult),
        "desired_fine_blind_algebra_complex_dimension":N*N+1,
        "theorem":(
            "Let the only doubled datum be (H tensor C2,A tensor I2), with no named copy, coarse sector, fine sector, or instrument. "
            "Its full dynamical automorphism group is the unitary group of the commutant, with blocks U(2m_r). Any quotient/expectation "
            "natural under all these automorphisms has range contained in their fixed algebra, the seven-dimensional center generated by the "
            "spectral projectors. The desired M12 direct-sum C algebra has dimension 145 and is not invariant under automorphisms mixing the copy multiplicities."
        ),
        "status":"proven_no_fine_blind_quotient_in_full_automorphism_natural_class",
        "boundary":(
            "Naming layers, regions, preparations, instruments, an environment, or a smaller automorphism group evades the theorem by adding typing. "
            "This is not a universal no-go and does not discharge QW-2191."
        ),
    }


def st143_edge_star(a:np.ndarray)->dict:
    weights=np.array([-a[0,d] for d in range(1,7)])
    rows=[]
    for d in range(1,7):
        count=12 if d<6 else 6; tmax=2*weights[d-1]
        b=a.copy(); b[0,d]+=tmax; b[d,0]+=tmax
        rows.append({"distance":d,"edge_count":count,"segment_length":float(tmax),
                     "endpoint_minimum_eigenvalue":float(np.min(np.linalg.eigvalsh(b))),
                     "endpoint_rank":int(np.linalg.matrix_rank(b,tol=1e-10))})
    packet={"bounded_offdiagonal_segments":66,"unbounded_diagonal_rays":12,"total_incident_coordinate_faces":78,
            "distance_orbits":rows,
            "theorem":(
                "For every unordered pair i<j, fixing the other 77 coordinate inequalities at their lower endpoints leaves the exact segment "
                "B(t)=A+t(E_ij+E_ji), 0<=t<=-2A_ij. Throughout the segment the absolute off-diagonal row sums do not exceed s, so B(t) is PSD. "
                "For 0<t<-2A_ij irreducible diagonal dominance is strict in two rows; at the sign-flipped endpoint the signed complete graph is unbalanced. "
                "Hence every t>0 is positive definite. These 66 bounded edges plus the 12 diagonal rays form the complete coordinate-edge star at A."
            )}
    PACK143.write_text(json.dumps(native(packet),indent=2,sort_keys=True),encoding="utf-8")
    return {"program":"ST143","object":"Complete Coordinate-Edge Star at the Lift Vertex",
            "packet_file":PACK143.name,"packet_sha256":sha(PACK143),**packet,
            "status":"proven_exact_66_segment_plus_12_ray_coordinate_edge_star",
            "boundary":"Non-coordinate curved faces and adjacency away from A remain unclassified."}


def krawczyk_fold(center,aiv,radius=1e-7):
    g0lo,g0hi,j0lo,j0hi=interval_system(center,0.0,aiv); c=np.linalg.inv(.5*(j0lo+j0hi))
    _,_,jlo,jhi=interval_system(center,radius,aiv)
    cglo,cghi=interval_matvec(c,c,g0lo,g0hi); ylo=np.nextafter(center-cghi,-np.inf); yhi=np.nextafter(center-cglo,np.inf)
    cjlo,cjhi=interval_left(c,jlo,jhi); mlo,mhi=-cjhi,-cjlo
    for i in range(15): mlo[i,i]=np.nextafter(mlo[i,i]+1,-np.inf); mhi[i,i]=np.nextafter(mhi[i,i]+1,np.inf)
    mdlo,mdhi=interval_matvec(mlo,mhi,np.full(15,-radius),np.full(15,radius)); klo=ylo+mdlo; khi=yhi+mdhi
    margin=float(min(np.min(klo-(center-radius)),np.min((center+radius)-khi)))
    return {"radius":radius,"margin":margin,"included":margin>0,"max_half_width":float(np.max((khi-klo)/2))}


def cluster_points(points,tol=2e-5):
    clusters=[]
    for x in points:
        if not any(np.linalg.norm(x-y)<tol for y in clusters): clusters.append(x)
    return clusters


def st144_multibasin_fold(a:np.ndarray)->dict:
    rng=np.random.default_rng(SEED+144); candidates=[]; attempts=64
    # Structured seeds pay the known symmetry orbit but do not import a root center.
    base=np.array([2.5,.2,.08,.03,.015,.008,.004,.02,0,-1,0,0,0,0,0],float)
    seeds=[base.copy()]
    for su,sv in itertools.product([-1,1],repeat=2):
        x=base.copy(); x[:7]*=su; x[8:]*=sv; seeds.append(x)
    for _ in range(attempts):
        q=np.r_[rng.uniform(-3,3),rng.uniform(-.8,.8,6)]; k=rng.uniform(-.24,.08)
        v=rng.normal(size=7); v/=np.linalg.norm(v); seeds.append(np.r_[q,k,v])
    converged=0
    for seed in seeds:
        try:
            sol=root(lambda x:float_system_jacobian(x,a)[0],seed,jac=lambda x:float_system_jacobian(x,a)[1],method="lm",
                     options={"ftol":1e-12,"xtol":1e-12,"gtol":1e-12,"maxiter":600}).x
            res=float(np.linalg.norm(float_system_jacobian(sol,a)[0],ord=np.inf))
        except (ValueError,np.linalg.LinAlgError,FloatingPointError): continue
        if res<2e-8 and abs(np.linalg.norm(sol[8:])-1)<2e-6 and -3.2<=sol[0]<=3.2 and np.max(abs(sol[1:7]))<=1.2 and -.3<=sol[7]<=.12:
            candidates.append(sol); converged+=1
    clusters=cluster_points(candidates); aiv,_,_=strict_interval_matrix()
    rows=[]; certified=0
    for x in clusters:
        # Refine once from the cluster representative before interval testing.
        x=root(lambda y:float_system_jacobian(y,a)[0],x,jac=lambda y:float_system_jacobian(y,a)[1],method="lm",
               options={"ftol":1e-14,"xtol":1e-14,"gtol":1e-14,"maxiter":3000}).x
        cert=krawczyk_fold(x,aiv,1e-7) if len(rows)<32 else {"radius":1e-7,"margin":None,"included":False,"max_half_width":None,"reason":"local_certificate_budget_32"}
        if cert["included"]: certified+=1
        rows.append({"center":x.tolist(),"residual_inf":float(np.linalg.norm(float_system_jacobian(x,a)[0],ord=np.inf)),
                     "u_norm":float(np.linalg.norm(x[:7])),"kappa":float(x[7]),"certificate":cert})
    rows.sort(key=lambda r:(round(r["u_norm"],7),r["kappa"],r["center"][8]))
    certified_centers=[np.array(r["center"]) for r in rows if r["certificate"]["included"]]
    minimum_distance=min((np.linalg.norm(x-y) for i,x in enumerate(certified_centers) for y in certified_centers[i+1:]),default=None)
    result={"random_starts":attempts,"total_seeds":len(seeds),"converged_runs":converged,"distinct_numerical_clusters":len(rows),
            "local_certificate_budget":32,"locally_interval_certified_clusters":certified,
            "minimum_distance_between_certified_centers":minimum_distance,
            "domain_filter":{"q0":[-3.2,3.2],"q1_to_q6_abs_max":1.2,"kappa":[-.3,.12]},
            "roots":rows,"symmetries":"(u,v)->(-u,v) and (u,v)->(u,-v)",
            "scope":"Each accepted Krawczyk box proves a local unique root. Multistart coverage is deterministic numerical evidence, not an interval cover of the full domain.",
            "boundary":"No exhaustive compact-domain root count is claimed unless every domain box is covered or excluded."}
    CERT144.write_text(json.dumps(native(result),indent=2,sort_keys=True),encoding="utf-8")
    return {"program":"ST144","object":"Multibasin Fold Search with Local Interval Certificates",
            "certificate_file":CERT144.name,"certificate_sha256":sha(CERT144),**result,
            "status":"proven_multiple_local_roots_with_strong_nonexhaustive_multistart_map",
            "boundary":result["boundary"]}


def st145_coherent_syndrome_recovery()->dict:
    rows=[]; delta0,delta1=.08,.17
    for theta in np.linspace(0,math.pi/2,13):
        p=math.sin(theta)**2
        y0=max((1-p)*(1-delta0),p*delta1)
        y1=max((1-p)*delta0,p*(1-delta1))
        rows.append({"theta":float(theta),"unitary_error_probability":p,"optimal_entanglement_fidelity":y0+y1,
                     "identity_only_fidelity":1-p,"U_only_fidelity":p})
    packet={"logical_involution":"U=diag(I6,-I6), Tr(U)=0","readout_errors":{"delta0":delta0,"delta1":delta1},"rows":rows,
            "formula":"F_e*=max((1-p)(1-delta0),p delta1)+max((1-p)delta0,p(1-delta1)), p=sin^2(theta)",
            "theorem":(
                "A coherent system-syndrome coupling cos(theta)I+i sin(theta)U tensor X followed by syndrome pinching yields orthogonal Choi errors I and U. "
                "For each reported syndrome, maximum-likelihood application of I or U is optimal. The two posterior maxima give the displayed exact fidelity, including asymmetric readout errors."
            )}
    PACK145.write_text(json.dumps(native(packet),indent=2,sort_keys=True),encoding="utf-8")
    return {"program":"ST145","object":"Optimal Recovery for Coherent Involution Leakage with Asymmetric Syndrome Readout",
            "packet_file":PACK145.name,"packet_sha256":sha(PACK145),**packet,
            "status":"proven_optimal_recovery_for_declared_coherent_syndrome_model",
            "boundary":"The involution, syndrome coupling, pinching, and readout-error probabilities are supplied; generic coherent leakage remains open."}


def asymmetry_entropy(g):
    p0=(1+(N-1)*g)/N; p=(1-g)/N
    ans=p0*math.log(N*p0)
    if p>0: ans+=(N-1)*p*math.log(N*p)
    return ans


def st146_constrained_selector_cost()->dict:
    rows=[]
    for g in [1e-4,.001,.01,.05,.1,.25,.5,1.0]:
        rows.append({"robust_probability_gap":g,"minimum_trace_distance_to_uniform":(N-1)*g/N,
                     "minimum_relative_entropy_asymmetry_nats":asymmetry_entropy(g)})
    return {"program":"ST146","object":"Positive Selector Cost under a Robust Preparation Gap",
            "constraint":"p0-pj>=g for every j!=0 in a declared vertex POVM","rows":rows,
            "minimizer":"p0=(1+11g)/12, pj=(1-g)/12",
            "theorem":(
                "For a required operational gap g>0, permutation averaging over the eleven losing outcomes and convexity show that the least-asymmetric "
                "probability vector has all constraints tight. It has total-variation distance 11g/12 and relative entropy "
                "[(1+11g)/12]log(1+11g)+11[(1-g)/12]log(1-g). Data processing transfers these as lower bounds for quantum states."
            ),"status":"proven_positive_cost_conditional_on_robust_preparation_gap",
            "boundary":"The gap g, preferred outcome, and vertex POVM are supplied resources; no strict selector or QW-2191 discharge follows."}


def st147_equivariant_bifurcation()->dict:
    mu,kappa,eps,xi=.2,1.0,.05,.05
    def poly(y,cosine=1): return -mu+kappa*y-eps*cosine*y**5+xi*y**6
    y=brentq(lambda z:poly(z,1),0,2); r=math.sqrt(y)
    yu=brentq(lambda z:poly(z,-1),0,2); ru=math.sqrt(yu)
    fprime=kappa-5*eps*y**4+6*xi*y**5
    rows=[]
    for n in range(24):
        theta=n*math.pi/12; cosine=round(math.cos(12*theta))
        radius=r if cosine>0 else ru; angular=12*eps*radius**12*cosine
        rows.append({"branch":n,"theta":theta,"radius":radius,"cos12theta":cosine,"angular_Hessian":angular,
                     "classification":"stable_angle" if angular>0 else "unstable_angle"})
    return {"program":"ST147","object":"C12-Equivariant Nonlinear Mode Bifurcation",
            "potential":"V=-mu r^2/2+kappa r^4/4-epsilon r^12 cos(12theta)/12+xi r^14/14",
            "parameters":{"mu":mu,"kappa":kappa,"epsilon":eps,"xi":xi},"stable_radius":r,"unstable_angle_radius":ru,
            "radial_monotonicity_lower_bound":1-.25*(5/6)**4,"radial_derivative_at_root":fprime,
            "stable_branches":12,"unstable_angular_branches":12,"rows":rows,
            "theorem":(
                "The potential is bounded below and C12/reflection invariant. Its radial stationarity polynomial is strictly increasing: for y<=5/6, "
                "F'(y)>=1-(1/4)(5/6)^4>0, and for y>=5/6 the last two terms are nonnegative. Hence one positive radius exists. "
                "The angular Hessian selects twelve stable and twelve unstable alternating directions. All twelve minima remain symmetry-equivalent."
            ),"status":"proven_constructed_C12_equivariant_twelve_branch_bifurcation",
            "boundary":"The twelfth-order anisotropy and coefficients are supplied; initial condition/noise is still required to realize one branch."}


def param_krawczyk(a,center,h,rbeta,rs):
    p,f=plus_minus(); b0=f.T@dyadic_lift(a,0)@f
    ec=np.linalg.eigvalsh(a); ef=np.linalg.eigvalsh(b0); eigc=spectrum_intervals(ec); eigf=spectrum_intervals(ef)
    q0=(.2-h,.2+h); q1=(.7-h,.7+h); delta=(.05-h,.05+h); mp.iv.dps=55
    f0,_,_=parametric_chernoff_stationary(ib(float(center[0])),ib(float(center[1])),q0,q1,eigc,eigf,delta)
    flo=np.array([bounds(x)[0] for x in f0]); fhi=np.array([bounds(x)[1] for x in f0])
    _,jm,_=parametric_chernoff_stationary(ib(float(center[0])),ib(float(center[1])),.2,.7,eigc,eigf,.05)
    jml=np.array([[bounds(x)[0] for x in row] for row in jm]); jmh=np.array([[bounds(x)[1] for x in row] for row in jm]); c=np.linalg.inv((jml+jmh)/2)
    _,ji,_=parametric_chernoff_stationary(ib((center[0]-rbeta,center[0]+rbeta)),ib((center[1]-rs,center[1]+rs)),q0,q1,eigc,eigf,delta)
    jl=np.array([[bounds(x)[0] for x in row] for row in ji]); jh=np.array([[bounds(x)[1] for x in row] for row in ji])
    cglo,cghi=interval_matvec(c,c,flo,fhi); ylo=np.nextafter(center-cghi,-np.inf); yhi=np.nextafter(center-cglo,np.inf)
    cjlo,cjhi=interval_left(c,jl,jh); mlo,mhi=-cjhi,-cjlo
    for i in range(2): mlo[i,i]=np.nextafter(mlo[i,i]+1,-np.inf); mhi[i,i]=np.nextafter(mhi[i,i]+1,np.inf)
    rv=np.array([rbeta,rs]); mdlo,mdhi=interval_matvec(mlo,mhi,-rv,rv); klo=ylo+mdlo; khi=yhi+mdhi
    margin=float(min(np.min(klo-(center-rv)),np.min((center+rv)-khi)))
    return {"halfwidth":h,"beta_radius":rbeta,"s_radius":rs,"margin":margin,"included":margin>0}


def st148_nuisance_boundary(a:np.ndarray)->dict:
    p,f=plus_minus(); b0=f.T@dyadic_lift(a,0)@f; ec=np.linalg.eigvalsh(a); ef=np.linalg.eigvalsh(b0)
    center=root(lambda x:point_design_system(x,ec,ef),np.array([2.18,.54]),tol=1e-12).x
    scan=[]
    for h in [1e-5,2e-5,5e-5,1e-4,2e-4,5e-4,1e-3,2e-3,5e-3]:
        corner_roots=[]
        for dq0,dq1,dd in itertools.product([-h,h],repeat=3):
            rr=root(lambda x:point_design_system(x,ec,ef,.2+dq0,.7+dq1,.05+dd),center,tol=1e-11).x
            corner_roots.append(rr)
        shift=np.max(abs(np.array(corner_roots)-center),axis=0)
        candidates=[]
        # The interval Chernoff formula has strong dependency in the exponent
        # coordinate, so use the empirically certified ST136 aspect ratio and
        # enlarge it systematically.  Corner roots are recorded as a separate
        # floating diagnostic, never as the proof box.
        base_b=max(3e-3,300*h); base_s=max(8e-3,800*h)
        for factor in [1,2,4]:
            candidates.append(param_krawczyk(a,center,h,factor*base_b,factor*base_s))
        accepted=next((x for x in candidates if x["included"]),None)
        scan.append({"halfwidth":h,"corner_root_max_shift":shift.tolist(),"attempts":candidates,"accepted":accepted})
    accepted_h=[x["halfwidth"] for x in scan if x["accepted"]]; failed_h=[x["halfwidth"] for x in scan if not x["accepted"]]
    low=max(accepted_h) if accepted_h else None; high=min((x for x in failed_h if low is None or x>low),default=None); refinement=[]
    if low is not None and high is not None:
        for _ in range(10):
            h=(low+high)/2; base_b=max(3e-3,300*h); base_s=max(8e-3,800*h)
            attempts=[param_krawczyk(a,center,h,factor*base_b,factor*base_s) for factor in [1,2,4]]
            accepted=next((x for x in attempts if x["included"]),None)
            refinement.append({"halfwidth":h,"attempts":attempts,"accepted":accepted})
            if accepted: low=h
            else: high=h
    result={"nominal_center":center.tolist(),"scan":scan,"boundary_refinement":refinement,
            "largest_certified_halfwidth":low,"first_uncertified_halfwidth":high,
            "scope":"A passed row is a uniform local Krawczyk theorem for every q0,q1,delta in the common symmetric halfwidth box.",
            "boundary":"Failure is a certificate-method boundary, not proof that the stationary root ceases to exist. Global beta optimality remains open."}
    CERT148.write_text(json.dumps(native(result),indent=2,sort_keys=True),encoding="utf-8")
    return {"program":"ST148","object":"Nuisance-Box Continuation and First Certification Boundary",
            "certificate_file":CERT148.name,"certificate_sha256":sha(CERT148),**result,
            "status":"proven_uniform_continuation_through_largest_passed_box_with_method_boundary",
            "boundary":result["boundary"]}


def all_paths(n,edges,source=0):
    incoming=[[] for _ in range(n)]
    for e,(u,v,m) in enumerate(edges): incoming[v].append((u,e,m%2))
    paths=[[] for _ in range(n)]; paths[source]=[(1,0)]
    for v in range(source+1,n):
        for u,e,aedge in incoming[v]:
            for a,mask in paths[u]: paths[v].append((aedge*a,(aedge*mask)^(1<<e)))
    return paths


def gf2_rank(rows,ncols):
    rows=list(rows); rank=0
    for col in range(ncols):
        pivot=next((i for i in range(rank,len(rows)) if (rows[i]>>col)&1),None)
        if pivot is None: continue
        rows[rank],rows[pivot]=rows[pivot],rows[rank]
        for i in range(len(rows)):
            if i!=rank and ((rows[i]>>col)&1): rows[i]^=rows[rank]
        rank+=1
    return rank


def dag_certificate(n,edges):
    paths=all_paths(n,edges); equations=[]; parity_obstruction=[]
    for node,plist in enumerate(paths):
        if not plist: continue
        a0,m0=plist[0]
        for a,m in plist[1:]:
            if a!=a0: parity_obstruction.append(node)
            else: equations.append(m^m0)
    rank=gf2_rank([x for x in equations if x],len(edges))
    return {"nodes":n,"edges":[list(x) for x in edges],"path_counts":[len(x) for x in paths],
            "parity_obstruction_nodes":sorted(set(parity_obstruction)),"linear_equations":len([x for x in equations if x]),
            "GF2_rank":rank,"coherent_twist_count":0 if parity_obstruction else 2**(len(edges)-rank)}


def st149_refinement_dag()->dict:
    edges=[(0,1,3),(0,2,3),(1,3,3),(2,3,3),(1,4,3),(2,4,3),(3,5,3),(4,5,3)]
    good=dag_certificate(6,edges); bad_edges=list(edges); bad_edges[2]=(1,3,2); bad=dag_certificate(6,bad_edges)
    packet={"coherent_example":good,"parity_obstructed_example":bad,
            "algorithm":(
                "Propagate for every source-to-node path its affine parity a and a bit mask encoding the linear twist expression b. "
                "Unequal a values give an immediate obstruction. Equal a values give XOR equations; Gaussian elimination over F2 returns rank r and 2^(E-r) coherent assignments."
            ),"theorem":"The algorithm is necessary and sufficient for path independence on every finite topologically ordered refinement DAG."}
    PACK149.write_text(json.dumps(native(packet),indent=2,sort_keys=True),encoding="utf-8")
    return {"program":"ST149","object":"Executable Affine-Cohomology Certificate for Finite Refinement DAGs",
            "packet_file":PACK149.name,"packet_sha256":sha(PACK149),**packet,
            "status":"proven_algorithm_and_exact_two_DAG_certificates","boundary":"The graph, degrees, and edge-twist variables are supplied; no strict refinement law is derived."}


def st150_typed_causal_net()->dict:
    return {"program":"ST150","object":"Atomic Causal-Net Sufficiency and Minimality Boundary",
            "typed_net":"A({1})=M2 tensor I, A({2})=I tensor M2, A({1,2})=M4, with labeled singleton regions",
            "theorem":(
                "For labeled commuting full matrix factors that generate M4, each factor is the commutant of the other and the normalized-trace conditional expectation onto each is unique. "
                "Thus the atomic region net selects the two conditioning algebras. Removing singleton labels leaves the swap ambiguity; removing the factor subalgebras and retaining only trace/product-independence restores the continuum of ST138 conjugate choices."
            ),"status":"proven_typed_atomic_net_sufficiency_and_two_necessity_tests",
            "boundary":"The net and its identification with physical regions or FIN coarse/fine sectors are supplied operational structure."}


def binomial_error(k,p0,p1):
    return .5*sum(min(math.comb(k,j)*p0**j*(1-p0)**(k-j),math.comb(k,j)*p1**j*(1-p1)**(k-j)) for j in range(k+1))


def markov_count_distribution(n,P,pi):
    # State 0 is erasure/bad; state 1 is informative/good.
    dp=np.zeros((2,n+1)); dp[0,0]=pi[0]; dp[1,1]=pi[1]
    for _ in range(1,n):
        new=np.zeros_like(dp)
        for z in range(2):
            for k in range(n+1):
                if dp[z,k]==0: continue
                for zp in range(2): new[zp,k+zp]+=dp[z,k]*P[z,zp]
        dp=new
    return dp.sum(axis=0)


def st151_markov_counts()->dict:
    P=np.array([[.9,.1],[.2,.8]]); pi=np.array([2/3,1/3]); p0,p1=.72,.94
    opt=minimize_scalar(lambda s:p0**s*p1**(1-s)+(1-p0)**s*(1-p1)**(1-s),bounds=(0,1),method="bounded")
    b=float(opt.fun); C=-math.log(b); tilted=P@np.diag([1,b]); rho=max(abs(np.linalg.eigvals(tilted)))
    rows=[]
    for n in [1,2,5,10,20,50,100,200]:
        dist=markov_count_distribution(n,P,pi); err=sum(dist[k]*binomial_error(k,p0,p1) for k in range(n+1))
        bound=.5*float(pi@np.diag([1,b])@np.linalg.matrix_power(tilted,n-1)@np.ones(2))
        rows.append({"events":n,"exact_Bayes_error":float(err),"Chernoff_upper_bound":bound,"expected_good_events":float(sum(k*dist[k] for k in range(n+1)))})
    packet={"transition_matrix":P.tolist(),"stationary_distribution":pi.tolist(),"Dobrushin_contraction":.7,
            "good_state_probabilities":{"p0":p0,"p1":p1},"bad_state_output":"erasure","one_good_event_Chernoff":C,
            "tilted_spectral_radius":float(rho),"asymptotic_bound_exponent":float(-math.log(rho)),"rows":rows,
            "theorem":(
                "The common hidden availability state is a stationary two-state Markov chain; a bad state emits an erasure and a good state emits one Bernoulli sample. "
                "Conditional on K good events the exact error is the K-sample binomial overlap. Averaging its Chernoff bound gives a two-by-two tilted transfer matrix, "
                "whose spectral radius is below one and therefore proves a positive finite-count exponent."
            )}
    PACK151.write_text(json.dumps(native(packet),indent=2,sort_keys=True),encoding="utf-8")
    return {"program":"ST151","object":"Exact Counts for Markov-Modulated Detector Availability",
            "packet_file":PACK151.name,"packet_sha256":sha(PACK151),**packet,
            "status":"proven_exact_finite_count_law_and_positive_tilted_exponent",
            "boundary":"The transition matrix, stationary law, erasure observability, and emissions are supplied; a fully hidden non-erasure HMM remains open."}


def st152_bath_dimension(a:np.ndarray)->dict:
    beta=.8; vals=np.linalg.eigvalsh(a); gamma=np.exp(-beta*vals); gamma/=gamma.sum()
    choi=np.repeat(gamma/N,N); choi=np.sort(choi)[::-1]
    rows=[]
    for m in [1,2,3,4,6,8,10,11,12]:
        rank_cap=m*m; tail=float(np.sum(choi[min(rank_cap,N*N):]))
        rows.append({"bath_dimension":m,"maximum_channel_Kraus_rank":rank_cap,
                     "minimum_entangled_input_trace_distance_lower_bound":tail})
    packet={"system_dimension":N,"beta":beta,"strict_Gibbs_probabilities":gamma.tolist(),"rows":rows,
            "attaining_construction":"a 12-level bath with H_B=A, Gibbs state gamma, and full SWAP",
            "theorem":(
                "An exact full-rank replacement channel rho->gamma has Choi rank d^2. A unitary implementation with a bath of dimension m and initial bath rank at most m has Kraus rank at most m^2, so m>=d is necessary. "
                "A d-level isospectral Gibbs bath and SWAP attain the bound and commute with total energy. For m<d, the trace-distance error on a maximally entangled input is at least the tail beyond the largest m^2 eigenvalues of I/d tensor gamma."
            )}
    PACK152.write_text(json.dumps(native(packet),indent=2,sort_keys=True),encoding="utf-8")
    return {"program":"ST152","object":"Sharp Bath-Dimension Bound for Global Gibbs Reset",
            "packet_file":PACK152.name,"packet_sha256":sha(PACK152),**packet,
            "status":"proven_exact_minimum_bath_dimension_and_approximation_lower_bounds",
            "boundary":"The strict spectrum is treated as a dimensionless Hamiltonian; beta, bath preparation, SWAP time, energy scale, and apparatus are supplied."}


def st153_all_minimax_detectors()->dict:
    examples=[]
    for c in [0,.25,.5,.75,1.0]:
        h=((1-c)*np.eye(N)+c*np.ones((N,N)))/N
        examples.append({"c":c,"rank":int(np.linalg.matrix_rank(h,tol=1e-10)),"minimum_eigenvalue":float(np.min(np.linalg.eigvalsh(h)))})
    packet={"optimal_set":"H>=0, Tr(H)=1, H_ii=1/12 for all i, and H_ij>=0 for i!=j","examples":examples,
            "theorem":(
                "Optimality first forces every diagonal entry to equal 1/12 because the adversary contains E_ii. Write K=H-I/12. If some K_ij<0, "
                "a normalized rank-one adversary proportional to (e_i+epsilon e_j)(e_i+epsilon e_j)^T lowers the response below 1/12 for small epsilon. "
                "Conversely nonnegative off-diagonal K pairs nonnegatively with every entrywise-nonnegative adversary. These conditions are therefore necessary and sufficient."
            ),"depolarizing_noise_action":"H_delta=(1-delta)H+delta I/12 preserves the complete optimizer set"}
    PACK153.write_text(json.dumps(native(packet),indent=2,sort_keys=True),encoding="utf-8")
    return {"program":"ST153","object":"Complete Classification of Non-Diagonal Minimax Detectors",
            "packet_file":PACK153.name,"packet_sha256":sha(PACK153),**packet,
            "status":"proven_complete_optimizer_set_for_declared_adversary_cone",
            "boundary":"The adversary cone, detector normalization, fine access, and depolarizing noise law remain supplied."}


def make_figures(d):
    FIG_DIR.mkdir(exist_ok=True)
    fig,ax=plt.subplots(figsize=(7,4)); ax.bar(["natural fixed algebra","desired fine-blind algebra"],[d["ST142"]["full_automorphism_fixed_algebra_complex_dimension"],d["ST142"]["desired_fine_blind_algebra_complex_dimension"]]); ax.set(ylabel="complex dimension",title="ST142: full naturality selects the spectral center"); fig.tight_layout(); fig.savefig(FIG_DIR/"st142_natural_quotient.png",dpi=190); plt.close(fig)
    fig,ax=plt.subplots(figsize=(7,4)); rows=d["ST143"]["distance_orbits"]; ax.bar([r["distance"] for r in rows],[r["segment_length"] for r in rows]); ax.set(xlabel="cyclic distance",ylabel="bounded edge length",title="ST143: 66 bounded coordinate edges in six orbits"); fig.tight_layout(); fig.savefig(FIG_DIR/"st143_edge_star.png",dpi=190); plt.close(fig)
    fig,ax=plt.subplots(figsize=(7,4)); rows=d["ST144"]["roots"]; ax.scatter([r["kappa"] for r in rows],[r["u_norm"] for r in rows],c=[1 if r["certificate"]["included"] else 0 for r in rows]); ax.set(xlabel="kappa",ylabel="norm of stationary state",title="ST144: numerical fold clusters and local certificates"); fig.tight_layout(); fig.savefig(FIG_DIR/"st144_multibasin.png",dpi=190); plt.close(fig)
    fig,ax=plt.subplots(figsize=(7,4)); rows=d["ST145"]["rows"]; ax.plot([r["theta"] for r in rows],[r["optimal_entanglement_fidelity"] for r in rows],"o-"); ax.set(xlabel="coherent coupling angle",ylabel="optimal entanglement fidelity",title="ST145: asymmetric syndrome recovery"); fig.tight_layout(); fig.savefig(FIG_DIR/"st145_recovery.png",dpi=190); plt.close(fig)
    fig,ax=plt.subplots(figsize=(7,4)); rows=d["ST146"]["rows"]; ax.loglog([r["robust_probability_gap"] for r in rows],[r["minimum_trace_distance_to_uniform"] for r in rows],"o-",label="trace distance"); ax.loglog([r["robust_probability_gap"] for r in rows],[r["minimum_relative_entropy_asymmetry_nats"] for r in rows],"s-",label="relative entropy"); ax.set(xlabel="required selector gap",ylabel="minimum asymmetry cost",title="ST146: robustness restores positive selector cost"); ax.legend(); fig.tight_layout(); fig.savefig(FIG_DIR/"st146_selector_cost.png",dpi=190); plt.close(fig)
    fig,ax=plt.subplots(subplot_kw={"projection":"polar"},figsize=(5,5)); stable=[r["theta"] for r in d["ST147"]["rows"] if r["classification"]=="stable_angle"]; ax.scatter(stable,[d["ST147"]["stable_radius"]]*len(stable)); ax.set(title="ST147: twelve symmetry-equivalent stable branches"); fig.tight_layout(); fig.savefig(FIG_DIR/"st147_branches.png",dpi=190); plt.close(fig)
    fig,ax=plt.subplots(figsize=(7,4)); scan=d["ST148"]["scan"]; ax.semilogx([r["halfwidth"] for r in scan],[1 if r["accepted"] else 0 for r in scan],"o-"); ax.set(xlabel="common nuisance halfwidth",ylabel="certificate accepted",yticks=[0,1],title="ST148: continuation and method boundary"); fig.tight_layout(); fig.savefig(FIG_DIR/"st148_continuation.png",dpi=190); plt.close(fig)
    fig,ax=plt.subplots(figsize=(7,4)); rows=d["ST151"]["rows"]; ax.semilogy([r["events"] for r in rows],[r["exact_Bayes_error"] for r in rows],"o-",label="exact"); ax.semilogy([r["events"] for r in rows],[r["Chernoff_upper_bound"] for r in rows],"--",label="tilted bound"); ax.set(xlabel="events",ylabel="Bayes error",title="ST151: Markov-modulated availability"); ax.legend(); fig.tight_layout(); fig.savefig(FIG_DIR/"st151_markov_counts.png",dpi=190); plt.close(fig)
    fig,ax=plt.subplots(figsize=(7,4)); rows=d["ST152"]["rows"]; ax.plot([r["bath_dimension"] for r in rows],[r["minimum_entangled_input_trace_distance_lower_bound"] for r in rows],"o-"); ax.axvline(N,color="red",ls="--"); ax.set(xlabel="bath dimension",ylabel="certified reset-error lower bound",title="ST152: exact reset requires bath dimension at least 12"); fig.tight_layout(); fig.savefig(FIG_DIR/"st152_bath_bound.png",dpi=190); plt.close(fig)


def main():
    _,a,_=strict_operator(); out={"metadata":{"programs":"ST142-ST153","date":"2026-08-11","seed":SEED,"python":platform.python_version(),"numpy":np.__version__,"scipy":scipy.__version__}}
    out["ST142"]=st142_natural_quotient_no_go(a); out["ST143"]=st143_edge_star(a); out["ST144"]=st144_multibasin_fold(a); out["ST145"]=st145_coherent_syndrome_recovery()
    out["ST146"]=st146_constrained_selector_cost(); out["ST147"]=st147_equivariant_bifurcation(); out["ST148"]=st148_nuisance_boundary(a); out["ST149"]=st149_refinement_dag()
    out["ST150"]=st150_typed_causal_net(); out["ST151"]=st151_markov_counts(); out["ST152"]=st152_bath_dimension(a); out["ST153"]=st153_all_minimax_detectors()
    out["recommended_next_programs"]=[
        {"id":"ST154","priority":1,"study":"classify environment-induced superselection quotients with a typed interaction but without a predeclared fine algebra"},
        {"id":"ST155","priority":2,"study":"interval-cover the reduced fold domain around every ST144 cluster and certify exclusion boxes"},
        {"id":"ST156","priority":3,"study":"derive coherent-leakage recovery for a general unitary spectrum rather than a balanced involution"},
        {"id":"ST157","priority":4,"study":"derive selector-cost bounds from action, energy, or finite-time preparation budgets"},
        {"id":"ST158","priority":5,"study":"couple the C12 anisotropy coefficient to a strict-derived state or prove a source obstruction"},
        {"id":"ST159","priority":6,"study":"certify the true ST148 continuation boundary with adaptive interval subdivision"},
        {"id":"ST160","priority":7,"study":"classify refinement-DAG cohomology under composition and coarse-graining functors"},
        {"id":"ST161","priority":8,"study":"test whether an atomic causal net can be reconstructed from a supplied instrument tomography table"},
        {"id":"ST162","priority":9,"study":"remove the observable erasure flag in ST151 and certify a genuinely hidden HMM exponent"},
        {"id":"ST163","priority":10,"study":"derive minimal bath resources for approximate reset under locality and bounded interaction strength"},
        {"id":"ST164","priority":11,"study":"classify extreme points and dimensions of the complete ST153 optimizer spectrahedron"},
        {"id":"ST165","priority":12,"study":"integrate gauge, preparation, clock, bath, apparatus, and record into one minimal operational tuple and re-run axiom deletion"},
    ]
    out["central_verdict"]=(
        "Full automorphism naturality strengthens the fine-gauge obstruction: without named operational typing it selects only the seven-dimensional spectral center. "
        "Robust selector cost becomes positive only after a probability-gap resource is supplied, while a C12-equivariant nonlinear potential produces twelve equivalent stable branches but still no realized branch. "
        "A typed atomic causal net resolves algebra ambiguity, Markov-modulated availability restores a certified exponent, and an exact global Gibbs reset requires bath dimension at least twelve."
    )
    out["epistemic_boundary"]="No strict fine-gauge source, QW-2191 discharge, strict anisotropy source, dimensional clock/unit, laboratory apparatus or record, legacy-to-strict completion or role transfer, Standard Model, gravity, L_total, physical projection theorem, or ToE closure is claimed."
    RESULTS.write_text(json.dumps(native(out),indent=2,sort_keys=True),encoding="utf-8")
    with SUMMARY.open("w",newline="",encoding="utf-8") as h:
        w=csv.writer(h); w.writerow(["program","object","status"])
        for k in range(142,154): w.writerow([f"ST{k}",out[f"ST{k}"]["object"],out[f"ST{k}"]["status"]])
    make_figures(out); print(json.dumps({"results":RESULTS.name,"programs":12,"figures":9},indent=2))


if __name__=="__main__": main()
