#!/usr/bin/env python3
"""Six rounds: Haar hierarchical Laplacian and spectral-dimension closures."""
import hashlib,json,math
from fin_st2172_st2261_common import ROOT,write_packet,write_round
def emit(lo,names,rows):
 d={}
 for i,(s,b,p) in enumerate(rows):k=lo+i;d[f'ST{k}']=write_packet(k,names[i],s,b,p)
 write_round(lo,lo+14,d)
def r1():
 names=['HaarBasis','LevelMultiplicity','HierarchicalEigenlaw','PositiveOperator','ZeroMode','EigenGrowth','CompactResolvent','CriticalRho','SubcriticalFailure','HeatTrace','TraceClassCriterion','FiniteDepthTruncation','OperatorFamily','RoundOneVerdict','RoundOneRecommendation']
 rows=[('Constructed','Cantor Haar wavelets.',{}),('Proven','Level l multiplicity 2^l.',{}),('Defined','lambda_l=lambda0(2rho)^l.',{}),('Proven','rho,lambda0 positive.',{}),('Proven','Constants zero mode.',{}),('Proven','Eigenvalues diverge iff 2rho>1.',{}),('Proven','Finite multiplicities plus divergence iff rho>1/2.',{}),('Boundary','rho=1/2 flat levels.',{}),('No-go','rho<1/2 eigenvalues collapse.',{}),('Defined','sum_l 2^l exp(-t lambda_l).',{}),('Proven','Finite for all t>0 iff rho>1/2.',{}),('Boundary','Finite trees hide infinite-depth failure.',{}),('Constructed','One-parameter spectral family rho>1/2.',{}),('Round verdict','Compact spectral geometry excludes rho<=1/2 but not a unique rho.',{}),('Recommendation','Derive dimensions.',{})];emit(3432,names,rows)
def r2():
 names=['CountingFunction','LevelCutoff','SpectralDimension','MetricScale','HausdorffDimension','WalkExponent','EinsteinRelation','RIndependenceOfDs','RhoDependenceOfDs','RhoInversion','DimensionRange','CriticalDivergence','LargeRhoLimit','RoundTwoVerdict','RoundTwoRecommendation']
 rows=[('Defined','N(Lambda).',{}),('Proven','l~log Lambda/log(2rho).',{}),('Proven','d_s=2log2/log(2rho).',{}),('Defined','delta_l=r^-l.',{}),('Proven','D=log2/logr.',{}),('Proven','d_w=log(2rho)/logr.',{}),('Proven','d_s=2D/d_w.',{}),('Proven','d_s independent of r.',{}),('Proven','d_s strictly decreases with rho.',{}),('Proven','rho=2^(2/d_s-1).',{}),('Proven','rho in (1/2,infty) gives d_s in (infty,0).',{}),('Boundary','rho->1/2+ gives d_s->infty.',{}),('Boundary','rho->infty gives d_s->0.',{}),('Round verdict','A target spectral dimension selects rho but target is additional.',{}),('Recommendation','Conditional eta closures.',{})];emit(3447,names,rows)
def r3():
 eta=1.8;r=2**(1/eta);rho=2**(2/eta-1)
 names=['ClosureA','ClosureB','JointClosure','SelectedR','SelectedRho','SelectedD','SelectedDw','SelectedDs','Consistency','Compactness','ParameterFreeGivenEta','PremiseAudit','StrictGate','RoundThreeVerdict','RoundThreeRecommendation']
 rows=[('Axiom','Set Hausdorff dimension D=eta.',{}),('Axiom','Set normal walk exponent d_w=2.',{}),('Conditional theorem','Together with binary branching.',{}),('Computed','r=2^(1/eta).',{'r':r}),('Computed','rho=r^2/2.',{'rho':rho}),('Computed','D.',{'D':eta}),('Computed','d_w.',{'d_w':math.log(2*rho)/math.log(r)}),('Computed','d_s.',{'d_s':2*math.log(2)/math.log(2*rho)}),('Proven','d_s=D under d_w=2.',{}),('Proven','rho>1/2.',{}),('Conditional','No new continuous parameter after eta.',{}),('No-go','D=eta and d_w=2 are not strict-derived.',{}),('Fail strict','Numerical closure is axiom-augmented.',{}),('Round verdict','A small two-axiom bridge yields a coherent fractal diffusion.',{}),('Recommendation','Compare alternative closures.',{})];emit(3462,names,rows)
def r4():
 eta=1.8;alts={'ds=eta':2**(2/eta-1),'ds=2':1.0,'ds=4':2**-.5,'rho=1':1.0,'layer_energy':.5}
 names=['AlternativeDsEta','AlternativeDs2','AlternativeDs4','RhoOne','LayerEnergyRhoHalf','CompactnessFilter','MultipleSurvivors','DifferentSpectra','DifferentWalkDimensions','EtaRoleAmbiguity','AxiomRemoval','UniquenessGate','ConditionalRanking','RoundFourVerdict','RoundFourRecommendation']
 rows=[('Conditional','Set d_s=eta.',{'rho':alts['ds=eta']}),('Conditional','Set d_s=2.',{'rho':alts['ds=2']}),('Conditional','Set d_s=4.',{'rho':alts['ds=4']}),('Conditional','Constant edge conductance.',{'rho':1}),('Rejected by compactness','rho=1/2.',{}),('Proven','Only removes rho<=1/2.',{}),('Proven','Continuum rho>1/2 remains.',{}),('Proven','Distinct d_s.',{}),('Proven','Depends r,rho.',{}),('No-go','Eta can target D,ds,dw,sigma.',{}),('Proven','Removing either joint-closure axiom restores modulus.',{}),('Fail','Current strict data select no survivor.',{}),('Strategic','Joint D=eta,dw=2 is economical but not proven.',{}),('Round verdict','Compactness strengthens but does not uniquely close geometry.',{}),('Recommendation','Finite heat-trace falsification.',{})];emit(3477,names,rows)
def r5():
 def heat(rho,t,L=24):return sum(2**l*math.exp(-t*(2*rho)**l) for l in range(L))
 table={str(rho):[heat(rho,t) for t in [.01,.1,1]] for rho in [.51,2**(2/1.8-1),1,2]}
 names=['HeatTraceReplay','CandidateTable','NearCriticalGrowth','EtaClosureTrace','RhoOneTrace','RhoTwoTrace','FiniteDepthBias','AsymptoticFit','ResolutionRequirement','ObserverCutoff','TraceNormalization','ClockScale','EmpiricalBoundary','RoundFiveVerdict','RoundFiveRecommendation']
 rows=[('Computed','24 Haar levels.',{'table':table}),('Constructed','rho candidates.',{}),('Observed','rho=.51 needs extreme depth for asymptotic regime.',{}),('Computed','Axiom closure rho.',{}),('Computed','d_s=2.',{}),('Computed','d_s=1.',{}),('Proven','Finite depth truncates divergence and biases dimension.',{}),('Conditional','Log counting slope estimates d_s.',{}),('Boundary','Need many resolved layers.',{}),('Boundary','Internal observer has finite prefix.',{}),('No-go','Heat trace amplitude/cutoff conventions remain.',{}),('No-go','t scale remains free.',{}),('Boundary','No raw multilevel record.',{}),('Round verdict','Finite numerical spectra cannot select the asymptotic closure.',{}),('Recommendation','Synthesize.',{})];emit(3492,names,rows)
def r6():
 gate=ROOT/'FIN_ST3507_ST3521_HierarchicalSpectralGate.json';g={'rows':[{'name':n,'pass':v} for n,v in [('compact-resolvent criterion',True),('spectral dimension formula',True),('Einstein scaling relation',True),('unique rho',False),('unique r',False),('strict D=eta axiom',False),('strict dw=2 axiom',False),('physical clock/length',False),('continuum evidence',False),('OA record',False)]]};gate.write_text(json.dumps(g,indent=2)+'\n')
 names=['CompactnessTheorem','DimensionTheorem','EinsteinTheorem','CriticalNoGo','ConditionalClosure','AxiomBoundary','PhysicalBoundary','Gate','GateScore','ProvenLedger','ConditionalLedger','RefutedLedger','HighestValueNext','FinalInterpretation','CycleTrigger']
 rows=[('Proven','rho>1/2 iff compact resolvent/finite heat trace.',{}),('Proven','d_s=2ln2/ln(2rho).',{}),('Proven','d_s=2D/d_w.',{}),('Proven','rho<=1/2 rejected.',{}),('Conditional','D=eta,dw=2 selects r,rho.',{}),('No-go','Two axioms not strict.',{}),('No-go','No units/OA.',{}),('Constructed','Ten rows.',{'file':gate.name}),('Result','Three mathematical passes.',{'passes':3,'rows':10}),('Ledger','Compactness/dimensions/scaling.',{}),('Ledger','Economical eta closure.',{}),('Ledger','Unique strict physical geometry.',{}),('Recommendation','Test whether strict heat/dual dynamics can derive normal walk exponent d_w=2 and whether kernel data can derive D=eta.',{}),('Final verdict','A coherent two-axiom fractal diffusion exists, but inevitability is unproved.',{'fundamental':False}),('Cycle complete','Release 11.22.',{'programs':90,'rounds':6,'range':'ST3432-ST3521','strict_ToE_closure':False,'gate_sha256':hashlib.sha256(gate.read_bytes()).hexdigest()})];emit(3507,names,rows)
def main():r1();r2();r3();r4();r5();r6()
if __name__=='__main__':main()
