#!/usr/bin/env python3
"""Ten rounds: falsify/condition dimension bridges from eta and dual dynamics."""
import hashlib,json,math,numpy as np
from fin_st2172_st2261_common import ROOT,write_packet,write_round
def emit(lo,names,rows):
 d={}
 for i,(s,b,p) in enumerate(rows):k=lo+i;d[f'ST{k}']=write_packet(k,names[i],s,b,p)
 assert len(rows)==15;write_round(lo,lo+14,d)
eta=1.8;alpha=eta-1;ds_lr=2/alpha
def r1():
 names=['HeatSemigroupFamily','RhoContinuum','WalkExponentFormula','DwRange','HeatExistence','MarkovProperty','CompactnessOnly','Dw2Condition','Dw2RhoRelation','RFreedom','Counterexamples','FiniteTreeWitness','StrictHeatGate','RoundOneVerdict','RoundOneRecommendation']
 rows=[('Proven','Every rho>1/2 gives heat semigroup.',{}),('Proven','Continuum remains.',{}),('Proven','d_w=log(2rho)/logr.',{}),('Proven','Varies with r,rho.',{}),('No-go','Semigroup existence does not imply d_w=2.',{}),('No-go','Markov positivity does not imply d_w=2.',{}),('Proven','Compactness gives rho>1/2 only.',{}),('Conditional','Normal diffusion axiom.',{}),('Proven','d_w=2 iff 2rho=r^2.',{}),('No-go','Relation leaves r free.',{}),('Constructed','Many r with rho=r^2/2.',{}),('Prior witness','Same tree different spectra.',{}),('Fail','Strict P_t does not select d_w.',{}),('Round verdict','d_w=2 is an extra scaling axiom.',{}),('Recommendation','Analyze spatial tail symbol.',{})];emit(3522,names,rows)
def r2():
 n=np.arange(1,200001,dtype=float);ks=np.logspace(-3,-1.2,12);lam=np.array([2*np.sum(n**(-eta)*(1-np.cos(k*n))) for k in ks]);slope=float(np.polyfit(np.log(ks[4:11]),np.log(lam[4:11]),1)[0])
 names=['LongRangeContinuation','SymbolFormula','FractionalOrder','Eta18Order','NumericalReplay','SlopeResidual','FiniteRangeAlternative','FiniteRangeOrder','ContinuationNonuniqueness','HeatScaling','WalkExponentLR','SpectralDimensionLR','FiniteC12Boundary','RoundTwoVerdict','RoundTwoRecommendation']
 rows=[('Conditional','J(n)~n^-eta on Z.',{}),('Proven','lambda(k)=2sum J(n)(1-cos kn).',{}),('Proven','For 1<eta<3, lambda~|k|^(eta-1).',{}),('Computed','alpha=.8.',{'alpha':alpha}),('Computed','200000 terms.',{'slope':slope}),('Computed','Against .8.',{'residual':abs(slope-alpha)}),('Conditional','Finite-range continuation.',{}),('Proven','lambda~k^2.',{}),('No-go','Same finite C12 data admit both classes.',{}),('Proven','Stable heat scaling x~t^(1/alpha).',{}),('Proven','d_w=alpha=.8 in long-range class.',{}),('Proven','d_s=2/alpha=2.5.',{'d_s':ds_lr}),('No-go','Finite C12 has no k->0 sequence.',{}),('Round verdict','Eta=1.8 implies fractional order .8, not spatial dimension 1.8, in the literal long-range class.',{}),('Recommendation','Dual wave/unitary consequences.',{})];emit(3537,names,rows)
def r3():
 names=['HeatDispersion','UnitaryDispersion','WaveDispersion','HeatWalkScaling','UnitaryGroupVelocity','WaveGroupVelocity','Eta18Divergence','FiniteSpeedCriterion','FiniteRangeRecovery','ClockScalingHeat','ClockScalingWave','OneClockNoGo','LorentzBoundary','RoundThreeVerdict','RoundThreeRecommendation']
 rows=[('Proven','lambda~|k|^alpha.',{}),('Proven','omega_U=lambda.',{}),('Proven','omega_W=sqrt(lambda)~|k|^(alpha/2).',{}),('Proven','d_w=alpha.',{}),('Proven','v_U~|k|^(alpha-1).',{}),('Proven','v_W~|k|^(alpha/2-1).',{}),('Proven','Both diverge as k->0 for alpha=.8.',{}),('Proven','Finite nonzero wave speed requires alpha=2.',{}),('Conditional','Finite-range quadratic symbol.',{}),('Proven','Diffusive scaling a^-2.',{}),('Proven','Wave scaling a^-1.',{}),('Proven','Shared finite A does not imply one continuum clock.',{}),('No-go','No Lorentz cone from fractional continuation.',{}),('Round verdict','Dual dynamics falsifies automatic normal diffusion/light speed.',{}),('Recommendation','Type eta versus dimension.',{})];emit(3552,names,rows)
def r4():
 names=['TailExponentType','HausdorffType','DimensionIndependence','GeneralDFormula','AlphaRelation','SameEtaDifferentD','SameDDifferentEta','EtaEqualsDTest','StrictFiniteBoundary','LegacyBoundary','InformationDimension','SemanticSelector','BridgeNoGo','RoundFourVerdict','RoundFourRecommendation']
 rows=[('Typed','Decay exponent of pair coupling.',{}),('Typed','Metric covering exponent.',{}),('Proven','No general identity.',{}),('Proven','Fractional kernel in D dimensions scales |x-y|^-(D+alpha).',{}),('Proven','Tail exponent=D+alpha in that class.',{}),('Counterexample','Fix eta and vary ambient D where admissible.',{}),('Counterexample','Fix D and vary alpha.',{}),('Refuted','Eta=D is not a theorem of long-range operators.',{}),('No-go','C12 cannot estimate Hausdorff dimension.',{}),('Guardrail','Legacy D_f not transferred.',{}),('Boundary','Information dimension needs measure+metric.',{}),('No-go','No strict role assignment.',{}),('Proven','D_H=eta remains an independent axiom.',{}),('Round verdict','Kernel tail and fractal dimension are different mathematical types.',{}),('Recommendation','Reassess two-axiom closure.',{})];emit(3567,names,rows)
def r5():
 r=2**(1/eta);rho=2**(2/eta-1)
 names=['PriorClosure','AxiomD','AxiomDw','SelectedPair','InternalConsistency','LongRangeConflict','FiniteRangeCompatibility','TwoContinuationFork','StrictSelection','AxiomCount','AlternativeDsClosure','Compactness','ConditionalValue','RoundFiveVerdict','RoundFiveRecommendation']
 rows=[('Reviewed','D=eta,d_w=2.',{}),('Still axiom','No derivation.',{}),('Still axiom','Heat does not force it.',{}),('Computed','r,rho.',{'r':r,'rho':rho}),('Proven','d_s=D=1.8 inside hierarchy.',{}),('Proven','Literal long-range base has d_w=.8.',{}),('Conditional','Finite-range base can have d_w=2.',{}),('No-go','Finite strict data select neither.',{}),('Fail','No promotion to strict.',{}),('Proven','At least two semantic/dynamic premises.',{}),('Alternative','Set d_s=eta directly.',{'rho':rho}),('Proven','Selected rho>1/2.',{}),('Positive','Coherent conditional model retained.',{}),('Round verdict','Closure survives only as one branch among inequivalent continuations.',{}),('Recommendation','Product spectral dimensions.',{})];emit(3582,names,rows)
def r6():
 ds_f_needed=4-ds_lr;rho4=2**(2/ds_f_needed-1);rho18=2**(2/eta-1)
 names=['KroneckerHeatProduct','TraceFactorization','DimensionAddition','BaseLongRangeDs','FiberEtaClosureDs','Total43','TargetFour','RequiredFiberDs','RequiredRho','AlternativeFiniteRangeBase','RequiredFiberDs3','RequiredRho3','TargetImportBoundary','RoundSixVerdict','RoundSixRecommendation']
 rows=[('Proven','L=L_base tensor I+I tensor L_fiber.',{}),('Proven','Tr exp(-tL)=product traces.',{}),('Proven','d_s,total=d_s,base+d_s,fiber under asymptotics.',{}),('Conditional','Long-range base.',{'d_s':ds_lr}),('Conditional','Fiber d_s=eta.',{'d_s':eta}),('Computed','Total.',{'d_s_total':ds_lr+eta}),('Axiom','Demand total spectral dimension4.',{}),('Computed','Fiber must be1.5.',{'d_s_fiber':ds_f_needed}),('Computed','rho=2^(2/ds-1).',{'rho':rho4}),('Conditional','Finite-range 1D base d_s=1.',{}),('Computed','Fiber must be3.',{}),('Computed','rho.',{'rho':2**(2/3-1)}),('No-go','Four is an external target until spacetime derived.',{}),('Round verdict','Dimension four can be engineered through multiple decompositions.',{}),('Recommendation','Crossover/relative-scale audit.',{})];emit(3597,names,rows)
def r7():
 names=['RelativeScaleGamma','ProductOperator','HeatTraceGamma','AsymptoticDimension','FiniteWindowDimension','CrossoverShift','PlateauEngineering','CutoffDependence','FiniteBase','FiniteFiber','OrderOfLimits','ObserverWindow','UniversalityNoGo','RoundSevenVerdict','RoundSevenRecommendation']
 rows=[('Defined','L=L_b+gamma L_f.',{}),('Constructed','Relative energy scale.',{}),('Proven','Fiber trace evaluated at gamma t.',{}),('Proven','True ideal exponent unchanged for fixed gamma.',{}),('Boundary','Finite-window effective dimension depends gamma.',{}),('Proven','Gamma moves crossover.',{}),('No-go','A target plateau can be tuned.',{}),('No-go','Cutoffs alter it.',{}),('Boundary','C12 contributes dimension zero at t->0.',{}),('Boundary','Finite depth truncates fiber.',{}),('Proven','N->infty and t->0 order matters.',{}),('Conditional','Internal observer sees finite window.',{}),('No-go','Finite plateau is not unique continuum dimension.',{}),('Round verdict','Dimensional flow is informative but scale/cutoff dependent.',{}),('Recommendation','Alternative decompositions.',{})];emit(3612,names,rows)
def r8():
 names=['DecompositionFamily','BaseDsParameter','FiberDsParameter','SumConstraint','ContinuumSolutions','RhoFamily','RFamily','EtaAssignments','Example25Plus15','Example1Plus3','Example22Plus18','AllCompact','PredictionNoGo','RoundEightVerdict','RoundEightRecommendation']
 rows=[('Defined','d_total=d_b+d_f.',{}),('Free','Continuation class.',{}),('Free','rho.',{}),('Conditional','Set total=4.',{}),('Proven','One-dimensional continuum of positive splits.',{}),('Proven','Each d_f>0 gives rho.',{}),('No-go','r still independent unless D supplied.',{}),('No-go','Eta may label several slots.',{}),('Constructed','2.5+1.5.',{}),('Constructed','1+3.',{}),('Constructed','2.2+1.8.',{}),('Proven','Corresponding rho>1/2.',{}),('No-go','Target sum alone not predictive.',{}),('Round verdict','Even dimension-four closure is nonunique.',{}),('Recommendation','Operational falsification.',{})];emit(3627,names,rows)
def r9():
 names=['RequiredSizes','RequiredTimes','HeatTraceRecord','ModeCountingRecord','BaseContinuationTest','FiberScalingTest','RelativeScaleTest','CutoffTest','NoiseSensitivity','FiniteBias','Calibration','IndependentRecord','SyntheticBoundary','RoundNineVerdict','RoundNineRecommendation']
 rows=[('Required','Multiple N/depth.',{}),('Required','Multiple calibrated t.',{}),('Required','Trace or randomized estimator.',{}),('Required','Eigenvalue counting.',{}),('Required','Distinguish fractional vs quadratic symbol.',{}),('Required','Estimate rho scaling.',{}),('Required','Estimate gamma crossover.',{}),('Required','Vary resolution/cutoff.',{}),('Boundary','Small-k and deep-level estimates fragile.',{}),('Proven','Single finite size cannot identify asymptotic dimension.',{}),('No-go','Seconds/length absent.',{}),('Boundary','Needs external custody.',{}),('No-go','Local simulations are not evidence.',{}),('Round verdict','Competing closures are distinguishable only with multiscale operational data.',{}),('Recommendation','Final synthesis.',{})];emit(3642,names,rows)
def r10():
 gate=ROOT/'FIN_ST3657_ST3671_DimensionBridgeGate.json';g={'rows':[{'name':n,'pass':v} for n,v in [('fractional-order theorem',True),('dual-dispersion theorem',True),('product-dimension theorem',True),('strict dw=2',False),('strict D=eta',False),('unique base continuation',False),('unique dimension-four split',False),('relative scale gamma',False),('physical units',False),('OA evidence',False)]]};gate.write_text(json.dumps(g,indent=2)+'\n')
 names=['FractionalTheorem','DualTheorem','TypeNoGo','PriorClosureStatus','ProductTheorem','FourDimensionalNoGo','ScaleNoGo','Gate','GateScore','ProvenLedger','ConditionalLedger','RefutedLedger','HighestValueNext','FinalInterpretation','CycleTrigger']
 rows=[('Proven','eta=1.8 tail -> alpha=.8, ds=2.5 in 1D LR class.',{}),('Proven','Wave speed diverges unless alpha=2.',{}),('Proven','Eta tail not Hausdorff dimension.',{}),('Conditional','D=eta,dw=2 branch retained.',{}),('Proven','Spectral dimensions add.',{}),('No-go','Many base/fiber splits yield4.',{}),('No-go','Gamma/cutoff/units free.',{}),('Constructed','Ten rows.',{'file':gate.name}),('Result','Three mathematical passes.',{'passes':3,'rows':10}),('Ledger','Fractional/dual/product mathematics.',{}),('Ledger','Axiom-augmented fractal diffusion.',{}),('Ledger','Strict 3+1 physical spacetime.',{}),('Recommendation','The decisive local theorem is a continuum-selection principle choosing finite-range versus long-range base and assigning eta to one typed dimension; absent it preserve the fork.',{}),('Final verdict','Current FIN supports several inequivalent continuum universality classes and does not uniquely derive dimensional physics.',{'fundamental':False}),('Cycle complete','Release 11.23.',{'programs':150,'rounds':10,'range':'ST3522-ST3671','strict_ToE_closure':False,'gate_sha256':hashlib.sha256(gate.read_bytes()).hexdigest()})];emit(3657,names,rows)
def main():r1();r2();r3();r4();r5();r6();r7();r8();r9();r10()
if __name__=='__main__':main()
