#!/usr/bin/env python3
"""FIN ST1062--ST1076: falsification and annihilation countermodels."""
import math

import numpy as np
from scipy.linalg import expm

from fin_total_nadsoliton_common import N, STRICT_A, write_packet, write_round


LO, HI = 1062, 1076
NAMES = [
    "Falsification_ModelClass_Lattice", "ClosedNormalized_NoKill",
    "SubMarkov_Killing", "StochasticCemetery_Hazard",
    "FiniteTimeCollapse", "TopologicalProtection_GapFailure",
    "NormalizationCanHideSurvivalLoss", "ProjectiveAmplitudeBlindness",
    "Totality_ExternalEmbeddingCountermodel", "InternalPairAnnihilation_GlobalCharge",
    "HeatMixing_NotKilling", "SurvivalObservable_Requirement",
    "ModelDiscrimination_Table", "ProtectionPremise_StressTest",
    "RoundFive_Recommendation",
]


def packet(k, status, boundary, payload):
    return write_packet(k, NAMES[k - LO], status, boundary, payload)


def main():
    x = {}
    x["ST1062"] = packet(1062, "constructed_six_model_falsification_lattice",
        "Models are alternatives for logic testing, not claims about nature.", {
        "classes": ["closed normalized flow", "sub-Markov killing", "stochastic cemetery jump",
                    "finite-time boundary collapse", "topological sector with gap", "externally embedded subsystem"],
    })
    p = np.zeros(N); p[0] = 1.0
    t = 5.0
    closed = expm(-t*STRICT_A)@p
    x["ST1063"] = packet(1063, "proven_closed_strict_heat_has_unit_survival_mass",
        "Probability embedding and exact generator required.", {
        "time": t, "total_mass": float(closed.sum()), "minimum_probability": float(closed.min()),
        "cemetery_probability": 0.0,
    })
    gamma = 0.3
    killed = expm(-t*(STRICT_A+gamma*np.eye(N)))@p
    x["ST1064"] = packet(1064, "proven_submarkov_extension_loses_survival_mass",
        "Uniform killing gamma is a new term, not generated by strict A.", {
        "gamma": gamma, "survival_mass": float(killed.sum()),
        "expected_survival": math.exp(-gamma*t), "cemetery_mass": float(1-killed.sum()),
    })
    hazard = 0.17
    times = [0.0,1.0,2.0,5.0,10.0]
    survival = [math.exp(-hazard*q) for q in times]
    x["ST1065"] = packet(1065, "proven_stochastic_annihilation_requires_hazard_and_cemetery_state",
        "Classical jump countermodel.", {
        "hazard": hazard, "times": times, "survival_curve": survival,
        "generator_extension": "L_hat includes x->dagger at rate hazard",
    })
    x["ST1066"] = packet(1066, "proven_finite_time_collapse_requires_loss_of_lipschitz_or_manifold_invariance",
        "Scalar x_dot=-sqrt(x) countermodel.", {
        "x0": 1.0, "hitting_time": 2.0,
        "regularity_at_zero": "not locally Lipschitz", "complete_normalized_flow": False,
    })
    x["ST1067"] = packet(1067, "proven_topological_label_can_change_when_admissibility_gap_closes",
        "General homotopy limitation; FIN has no strict amplitude-gap theorem.", {
        "protected_if": "path stays in M_gap", "failure_event": "amplitude zero / singularity / branch-cut crossing",
        "strict_gap_protected": False,
    })
    unnormalized = np.array([math.exp(-gamma*t),0.0])
    conditional = unnormalized/unnormalized.sum()
    x["ST1068"] = packet(1068, "proven_renormalization_can_hide_extinction_probability",
        "Essential critique of normalized-state arguments.", {
        "unnormalized_mass": float(unnormalized.sum()), "conditional_state": conditional.tolist(),
        "conditional_norm_l1": float(conditional.sum()),
        "lesson": "normalization proves persistence only when normalization is dynamically conserved, not imposed after loss",
    })
    x["ST1069"] = packet(1069, "proven_projective_state_is_blind_to_absolute_survival_amplitude",
        "Ray semantics alone cannot distinguish psi from c psi for nonzero c.", {
        "same_ray": "[psi]=[c psi], c!=0", "missing_observable": "survival weight / trace",
        "zero_limit_not_a_ray": True,
    })
    x["ST1070"] = packet(1070, "proven_external_embedding_can_turn_totality_into_subsystem_decay",
        "This countermodel contradicts the stated ontology if the embedding is called more fundamental.", {
        "model": "M FIN embedded in M_big and amplitude transfers to complement",
        "lesson": "persistence depends on whether 'total' is a formal axiom or merely a label",
    })
    x["ST1071"] = packet(1071, "proven_internal_pair_annihilation_can_preserve_global_charge_information",
        "Kinematic charge bookkeeping only; no FIN particle/collision law.", {
        "example": "opposite local charges/excitations disappear into neutral radiation/correlations",
        "local_particle_number_change": True, "total_closed_state_disappears": False,
    })
    x["ST1072"] = packet(1072, "proven_strict_heat_mixing_is_not_killing",
        "Finite irreducible Laplacian-like model.", {
        "long_time_state": "uniform mass-one distribution", "zero_state_limit": False,
        "pattern_contrast_limit": 0.0,
    })
    x["ST1073"] = packet(1073, "constructed_survival_observable_requirement",
        "Operational candidate; apparatus and record remain absent.", {
        "observable": "s(t)=Tr rho_t or total mass before conditional renormalization",
        "closed_prediction": "s(t)=1", "killed_prediction": "s(t)<1",
        "warning": "if the total carrier vanishes, no internal detector remains to read s afterward",
    })
    x["ST1074"] = packet(1074, "proven_model_classes_are_distinguishable_only_before_total_event",
        "Direct total-nothing observation remains impossible internally.", {
        "diagnostics": {
            "closed": "constant trace and complete flow",
            "killed": "subnormalized trace",
            "finite_collapse": "boundary approach and regularity failure",
            "topological": "quantized label until gap closure",
        },
    })
    x["ST1075"] = packet(1075, "proven_no_protection_premise_survives_removal_unconditionally",
        "Falsification result for the proposed theorem schema.", {
        "stress_test": {
            "normalization_without_conservation": "postselection hides loss",
            "fixed_point_without_stability": "unstable",
            "topology_without_gap": "unwinds",
            "flow_without_completeness": "hits boundary",
            "totality_without_no_embedding": "becomes a subsystem",
        },
    })
    x["ST1076"] = packet(1076, "recommended_ST1077_ST1091",
        "Final round will state the exact no-go, rank axioms, and expose the remaining FIN derivation problem.", {
        "next": ["total-state annihilation no-go theorem", "unitary and heat corollaries", "axiom-removal proof",
                 "strict-versus-conditional status", "research roadmap ST1092 onward"],
    })
    write_round(LO, HI, x)


if __name__ == "__main__":
    main()
