#!/usr/bin/env python3
"""Six rounds: binary refinement boundary, ultrametric and layer geometry."""
import hashlib,itertools,json,math
from fin_st2172_st2261_common import ROOT,write_packet,write_round
def emit(lo,names,rows):
 d={}
 for i,(s,b,p) in enumerate(rows):k=lo+i;d[f'ST{k}']=write_packet(k,names[i],s,b,p)
 write_round(lo,lo+14,d)
def lcp(a,b):
 k=0
 while k<min(len(a),len(b)) and a[k]==b[k]:k+=1
 return k
def dist(a,b,r):return 0 if a==b else r**(-lcp(a,b))
def r1():
 N=8;X=list(itertools.product((0,1),repeat=N));viol=0
 for a,b,c in itertools.product(X[:32],repeat=3):viol=max(viol,dist(a,c,2)-max(dist(a,b,2),dist(b,c,2)))
 names=['BinaryTree','DepthNLeaves','PrefixLength','PrefixDistance','MetricPositivity','Symmetry','UltrametricInequality','FiniteReplay','Completion','CantorBoundary','SelfSimilarity','TopologyIndependence','MetricParameter','RoundOneVerdict','RoundOneRecommendation']
 rows=[('Constructed','Rooted binary refinement tree.',{}),('Proven','2^N leaves.',{'N':N,'leaves':len(X)}),('Defined','Longest common prefix.',{}),('Defined','d_r(x,y)=r^-lcp, r>1.',{}),('Proven','Metric axioms.',{}),('Proven','Fiber swaps act isometrically.',{}),('Proven','d(x,z)<=max(d(x,y),d(y,z)).',{}),('Computed exhaustive subset','No violation.',{'max_violation':viol}),('Proven','Infinite sequence completion.',{}),('Proven','Boundary homeomorphic to Cantor space.',{}),('Proven','Each cylinder has two scaled copies.',{}),('Proven','All r>1 give same topology.',{}),('No-go','Refinement topology does not select r.',{}),('Round verdict','A canonical topological layer space exists with a metric modulus.',{}),('Recommendation','Measure/dimension.',{})];emit(3252,names,rows)
def r2():
 names=['FiberSwapMeasure','CylinderMass','MeasureUniqueness','BallCylinder','LocalDimension','HausdorffDimension','R2Case','Sqrt2Case','EtaDimensionCase','DimensionModulus','MeasureMetricSplit','EntropyPrefix','InfiniteEntropyBoundary','CompressionBoundary','RoundTwoRecommendation']
 D=lambda r:math.log(2)/math.log(r)
 rows=[('Proven','Swap-invariant product measure is Bernoulli half at each branch.',{}),('Proven','Depth n cylinder mass 2^-n.',{}),('Conditional uniqueness','Requires independent identical branching.',{}),('Proven','Radius r^-n ball is prefix cylinder.',{}),('Proven','log mass/log radius.',{}),('Proven','D_H=log2/log r.',{}),('Computed','r=2.',{'D':D(2)}),('Computed','r=sqrt2.',{'D':D(math.sqrt(2))}),('Computed','r=2^(1/1.8).',{'D':D(2**(1/1.8))}),('No-go','Any positive D selected by choosing r.',{}),('Proven','Uniform measure does not select metric.',{}),('Proven','Observed prefix n carries n bits under uniform law.',{}),('Boundary','Infinite independent sequence has unbounded prefix entropy.',{}),('No-go','Self-similarity alone does not store an arbitrary universe in finite bits.',{}),('Recommendation','Layered observer/product carrier.',{})];emit(3267,names,rows)
def r3():
 names=['ProductCarrier','FiniteLayerStates','Projection','SigmaAlgebra','ObserverPrefix','HiddenTail','ConditionalExpectation','Martingale','ExactBlindness','FineInstrument','BaseCycleIndependence','LayerMetric','CombinedMetric','PhysicalObserverBoundary','RoundThreeRecommendation']
 rows=[('Constructed','Z12 times binary boundary.',{}),('Proven','At depth n: 12*2^n cells.',{}),('Defined','Forget tail bits.',{}),('Proven','Depth-m observables form nested sigma algebras.',{}),('Constructed','Internal observer restricted to prefix m.',{}),('Proven','n-m hidden bits per base label at depth n.',{}),('Proven','Coarse record is conditional expectation over tail.',{}),('Proven','Prefix expectations form a martingale.',{}),('Proven','Tail-odd observables average to zero.',{}),('Conditional','Child-resolving measurement accesses next bit.',{}),('Proven','Z12 coordinate and tree depth are separate typed factors.',{}),('Proven','Tree depth supplies layer distance without base d doubling.',{}),('Conditional','max or sum metric needs relative scale.',{}),('Boundary','Mathematical filtration is not an actual apparatus/observer.',{}),('Recommendation','Depth-decay q_n.',{})];emit(3282,names,rows)
def r4():
 names=['MetricScaleDelta','PowerDepthLaw','GeometricQ','CubicSummability','AllPositiveAlpha','ThetaBoundedness','MetricInterpretation','ConductanceDimension','Q0Freedom','AlphaFreedom','RFreedom','SameSequenceDegeneracy','RefinementOperatorBoundary','RoundFourVerdict','RoundFourRecommendation']
 rows=[('Defined','delta_n=r^-n.',{}),('Constructed','q_n=q0 delta_n^alpha.',{}),('Proven','q_n=q0 r^-alpha n.',{}),('Proven','sum |q_n|^3 converges for alpha>0,r>1.',{}),('Proven','No alpha=1/3 threshold for exponential depth.',{}),('Proven','Prior hierarchy theorem gives finite theta limit.',{}),('Positive','Correctly typed as interlayer-depth decay.',{}),('Boundary','Calling q conductance needs a Hodge/operator law.',{}),('No-go','q0 remains free.',{}),('No-go','alpha remains free.',{}),('No-go','r remains free.',{}),('Proven','Only product alpha log r controls the geometric sequence.',{}),('Boundary','Exact A tensor I refinements still allow arbitrary q_n.',{}),('Round verdict','Ultrametric depth organizes q_n but does not select it.',{}),('Recommendation','Eta/dimension identifiability.',{})];emit(3297,names,rows)
def r5():
 names=['EtaCandidate','EtaAsAlpha','EtaAsDimension','MutualIncompatibility','ProductDegeneracy','DimensionObservation','DecayObservation','JointIdentification','ScaleOrigin','PhysicalLength','LegacyDfBoundary','AlphaGeoBoundary','NoSilentTransfer','RoundFiveVerdict','RoundFiveRecommendation']
 rows=[('Conditional','Use strict eta=1.8.',{}),('Route A','Set decay exponent alpha=eta.',{}),('Route B','Set Hausdorff dimension D=eta, hence r=2^(1/eta).',{}),('Proven','Routes impose different equations and are not equivalent.',{}),('Proven','q sequence sees alpha log r only.',{}),('Conditional','Independent metric ball scaling can estimate D.',{}),('Conditional','q_n ratios estimate alpha log r.',{}),('Proven','Both records could identify alpha and r conditionally.',{}),('No-go','Overall length ell0 remains free.',{}),('No-go','Meters absent.',{}),('Guardrail','Legacy fractal dimension claims do not transfer.',{}),('Guardrail','alpha_geo is an information amplitude, not D_H.',{}),('No-go','No theorem chooses Route A or B.',{}),('Round verdict','Eta compatibility creates alternatives rather than a unique bridge.',{}),('Recommendation','Synthesize.',{})];emit(3312,names,rows)
def r6():
 gate=ROOT/'FIN_ST3327_ST3341_CantorLayerGeometryGate.json';g={'rows':[{'name':n,'pass':v} for n,v in [('binary boundary topology',True),('prefix ultrametric family',True),('uniform cylinder measure',True),('canonical r',False),('canonical Hausdorff dimension',False),('strict q depth law',False),('eta bridge',False),('physical length scale',False),('observer apparatus',False),('OA evidence',False)]]};gate.write_text(json.dumps(g,indent=2)+'\n')
 names=['BoundaryTheorem','MetricTheorem','MeasureTheorem','ObserverFiltration','QHierarchy','MetricModulus','EtaNoGo','Gate','GateScore','ProvenLedger','ConditionalLedger','RefutedLedger','HighestValueNext','FinalInterpretation','CycleTrigger']
 rows=[('Proven','Binary refinement defines Cantor boundary.',{}),('Proven','Ultrametric d_r family.',{}),('Proven conditional','Uniform Bernoulli measure.',{}),('Constructed','Prefix observer/conditional expectations.',{}),('Conditional','q_n=q0 r^-alpha n bounded.',{}),('No-go','r,alpha,q0,ell0 free.',{}),('No-go','Eta has inequivalent possible roles.',{}),('Constructed','Ten rows.',{'file':gate.name}),('Result','Three mathematical passes.',{'passes':3,'rows':10}),('Ledger','Topology/metric family/measure.',{}),('Ledger','Typed layer geometry and bounded q.',{}),('Ledger','Unique physical fractal.',{}),('Recommendation','Seek a strict metric-measure-energy compatibility theorem selecting r and alpha; otherwise retain a Cantor-family geometry.',{}),('Final verdict','FIN refinement naturally yields an ultrametric information space, but not its metric scale or physical interpretation.',{'fundamental':False}),('Cycle complete','Release 11.20.',{'programs':90,'rounds':6,'range':'ST3252-ST3341','strict_ToE_closure':False,'gate_sha256':hashlib.sha256(gate.read_bytes()).hexdigest()})];emit(3327,names,rows)
def main():r1();r2();r3();r4();r5();r6()
if __name__=='__main__':main()
