#!/usr/bin/env python3
"""Build archival LaTeX for FIN Programs 41--50 / K_legacy^* monograph."""

from pathlib import Path

import fin_monograph_to_latex as converter

SOURCE = Path("FIN_Programs_41_50_Legacy_Star_Monograph.md")
TARGET = Path("FIN_Programs_41_50_Legacy_Star_Monograph.tex")

PREAMBLE = r"""\documentclass[11pt,a4paper,openany]{report}

\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{microtype}
\usepackage{amsmath,amssymb,amsthm,mathtools,bm}
\usepackage{booktabs,array,longtable,tabularx}
\usepackage{xcolor}
\usepackage[margin=24mm,headheight=23pt]{geometry}
\usepackage{enumitem}
\usepackage{fancyhdr}
\usepackage{fancyvrb}
\usepackage{graphicx}
\usepackage{url}
\usepackage{hyperref}

\definecolor{finblue}{HTML}{1F5A99}
\definecolor{fingreen}{HTML}{19733A}
\definecolor{finorange}{HTML}{D55E00}
\definecolor{finred}{HTML}{A61B1B}
\definecolor{finviolet}{HTML}{6A3D9A}
\definecolor{fingray}{HTML}{4D4D4D}

\hypersetup{
  unicode=true,
  colorlinks=true,
  linkcolor=finblue,
  citecolor=fingreen,
  urlcolor=finblue,
  pdftitle={FIN Reconstructed Legacy Kernel: Programs 41--50},
  pdfauthor={Krzysztof \.Zuchowski},
  pdfsubject={Program 42a methodology audit and Programs 41--50 on K^*_legacy},
  pdfkeywords={FIN, legacy kernel, dual dynamics, selector, units, Programs 41-50}
}

\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\small FIN Reconstructed Legacy Kernel}
\fancyhead[R]{\small Release 10.4}
\fancyfoot[C]{\thepage}
\setlength{\parindent}{0pt}
\setlength{\parskip}{0.55em}
\setlist{nosep,leftmargin=2em}
\setcounter{tocdepth}{2}
\setcounter{secnumdepth}{3}
\emergencystretch=2em

\newcommand{\one}{\bm 1}
\newcommand{\C}{\mathbb C}
\newcommand{\R}{\mathbb R}
\newcommand{\Z}{\mathbb Z}
\newcommand{\statusProven}{\textcolor{fingreen}{[Proven]}}
\newcommand{\statusStrong}{\textcolor{finblue}{[Strong evidence]}}
\newcommand{\statusModerate}{\textcolor{finviolet}{[Moderate evidence]}}
\newcommand{\statusWeak}{\textcolor{fingray}{[Weak evidence]}}
\newcommand{\statusSpeculative}{\textcolor{finorange}{[Speculative]}}
\newcommand{\statusRefuted}{\textcolor{finred}{[Refuted]}}

\begin{document}
\hypersetup{pageanchor=false}
\begin{titlepage}
\centering
\vspace*{10mm}
{\Large\bfseries FIN Research Supplement --- Release 10.4\par}
\vspace{11mm}
{\Huge\bfseries FIN Reconstructed Legacy Kernel\par}
\vspace{6mm}
{\Large Program 42a Methodology Audit and Executed Programs 41--50 on \(K^*_{\mathrm{legacy}}\)\par}
\vspace{17mm}
{\Large Krzysztof \.Zuchowski\par}
\vspace{2mm}
{\normalsize Independent Researcher --- Fractal Information Theory Project\par}
\vspace{2mm}
{\normalsize ORCID: \href{https://orcid.org/0009-0002-0909-3613}{0009-0002-0909-3613}\par}
\vspace{10mm}
{\large 19 July 2026\par}
{\normalsize Publication --- Preprint; record version 1.0.0\par}
\vfill
\begin{minipage}{0.88\textwidth}
\small
\textbf{Scope.} Algebraic reconstruction of the historical legacy kernel, rejection of a double-damped product candidate, dual-dynamics audits, and ten executed programs (41--50) on the corrected class \(K^*\).

\medskip
\textbf{Guardrail.} No silent legacy--strict identification, no role transfer, no selector closure, no physical unit export, no Theory-of-Everything claim.

\medskip
\textbf{Reproducibility.} \path{fin_programs_41_50_legacy_star.py}, \path{FIN_Programs_41_50_Legacy_Star_Results.json}, figures, Markdown, LaTeX.

\medskip
\textbf{License.} Creative Commons Attribution 4.0 International (CC BY 4.0).
\end{minipage}
\vfill
\end{titlepage}
\hypersetup{pageanchor=true}

\pagenumbering{roman}
\chapter*{Publication statement}
\addcontentsline{toc}{chapter}{Publication statement}
This preprint freezes the path-transformed reconstructed legacy class
\[
K^*_{\mathrm{legacy}}(d)=A\frac{\cos(\pi d/4+\pi/6)}{1+\beta d}
\]
after Program~42a, executes Programs~41--50, and records that units, selector, and symmetry-breaking leaf-cuts remain open under current artifacts.

\tableofcontents
\clearpage
\pagenumbering{arabic}
"""

POSTAMBLE = r"""
\clearpage
\chapter*{Archival note}
\addcontentsline{toc}{chapter}{Archival note}
Machine-readable results: \path{FIN_Programs_41_50_Legacy_Star_Results.json}, generated by \path{fin_programs_41_50_legacy_star.py}. Program~42a report: \path{program_42a_legacy_kernel_reconstruction_report.json}.

\medskip
\noindent\textbf{Suggested citation before DOI assignment:}

\.Zuchowski, K. (2026). \emph{FIN Reconstructed Legacy Kernel: Program 42a Methodology Audit and Executed Programs 41--50 on \(K^*_{\mathrm{legacy}}\)} (FIN Research Supplement, Release 10.4; Version 1.0.0) [Preprint].

\end{document}
"""

FIGURES = {
    "FINFIGUREP44": (
        "FIN_Programs_41_50_Figures/program44_information_flow.png",
        "Relative information under Markov heat flow versus unitary Born populations for the abs-repaired historical \(K^*\) generator.",
    ),
    "FINFIGUREP50": (
        "FIN_Programs_41_50_Figures/program50_profiles.png",
        "Preregistered kernel profiles on \(d=1..12\): historical \(K^*\), \(\mathbb Z_{12}\) \(K^*\), classical frozen legacy, rejected product (scaled), and strict.",
    ),
}


def main() -> None:
    # Inject figure anchors into a working copy if markdown uses image links.
    import re

    text = SOURCE.read_text(encoding="utf-8")
    text = text.replace(
        "![Program 44 information flow](FIN_Programs_41_50_Figures/program44_information_flow.png)",
        "\n\nFINFIGUREP44\n\n",
    )
    text = text.replace(
        "![Program 50 profiles](FIN_Programs_41_50_Figures/program50_profiles.png)",
        "\n\nFINFIGUREP50\n\n",
    )
    # Converter does not support fenced/inline code; flatten to plain text.
    text = re.sub(r"```[a-zA-Z]*\n(.*?)```", r"\1", text, flags=re.DOTALL)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    # Drop markdown tables that may confuse parser if needed — keep as-is.
    body = converter.body_from_markdown(text)
    for token, (path, caption) in FIGURES.items():
        fig = (
            "\\begin{figure}[htbp]\n"
            "\\centering\n"
            f"\\includegraphics[width=0.92\\textwidth]{{{path}}}\n"
            f"\\caption{{{caption}}}\n"
            "\\end{figure}\n"
        )
        body = body.replace(token, fig)
    for plain, macro in [
        ("[Proven]", r"\statusProven{}"),
        ("[Strong evidence]", r"\statusStrong{}"),
        ("[Moderate evidence]", r"\statusModerate{}"),
        ("[Weak evidence]", r"\statusWeak{}"),
        ("[Speculative]", r"\statusSpeculative{}"),
        ("[Refuted]", r"\statusRefuted{}"),
    ]:
        body = body.replace(plain, macro)
    # Escape leftover figure tokens if any
    TARGET.write_text(PREAMBLE + "\n" + body + "\n" + POSTAMBLE, encoding="utf-8")
    print("Wrote", TARGET)


if __name__ == "__main__":
    main()
