#!/usr/bin/env python3
"""Ten rounds: positive local tail cone and continuum speed nonuniqueness."""
import hashlib,json,math,numpy as np
from fin_st2172_st2261_common import ROOT,write_packet,write_round
def emit(lo,names,rows):
 d={}
 for i,(s,b,p) in enumerate(rows):k=lo+i;d[f'ST{k}']=write_packet(k,names[i],s,b,p)
 assert len(rows)==15;write_round(lo,lo+14,d)
w=np.array([math.cos(.18575*d+.1625)/(1+d**1.8) for d in range(1,7)]);C0=sum((d+1)**2*w[d] for d in range(6));c0=math.sqrt(C0)
def r1():
 names=['PositiveTailCone','FiniteSecondMoment','ExactFiniteMatch','SymbolFormula','CosineExpansion','DominatedLimit','QuadraticCoefficient','BaseCoefficient','TailContribution','LocalClass','Convexity','ConeDimension','ZeroTailVertex','RoundOneVerdict','RoundOneRecommendation']
 rows=[('Defined','t_d>=0 for d>=7.',{}),('Required','sum d^2 t_d finite.',{}),('Proven','First six weights fixed.',{}),('Defined','lambda=2sum w_d(1-cos kd).',{}),('Proven','2(1-cos kd)/k2->d2.',{}),('Proven','Finite second moment permits limit exchange.',{}),('Theorem','C=C0+sum d2 t_d.',{}),('Computed','Strict truncated value.',{'C0':C0}),('Proven','Nonnegative.',{}),('Proven','Every member has alpha=2.',{}),('Proven','Tail set convex.',{}),('Proven','Infinite-dimensional.',{}),('Defined','Truncation t=0.',{}),('Round verdict','Local positive continuations share order but not coefficient.',{}),('Recommendation','Classify coefficient range.',{})];emit(3897,names,rows)
def r2():
 names=['CoefficientLowerBound','Attainment','ArbitraryTargetC','SingleAtomWitness','CoefficientRange','SpeedDefinition','SpeedLowerBound','SpeedRange','NoUpperBound','SameDimension','DifferentDynamics','StrictPredictionNoGo','RayStructure','RoundTwoVerdict','RoundTwoRecommendation']
 rows=[('Proven','C>=C0.',{'C0':C0}),('Proven','Equality iff zero tail.',{}),('Proven','For any Cstar>=C0.',{}),('Constructed','t7=(Cstar-C0)/49.',{}),('Theorem','Exact range [C0,infinity).',{}),('Defined','c_hat=sqrt(C).',{}),('Computed','c>=sqrtC0.',{'c_min':c0}),('Theorem','[sqrtC0,infinity).',{}),('Proven','One distant/sufficient atom.',{}),('Proven','All have base spectral dimension1.',{}),('Proven','Wave speeds arbitrary above bound.',{}),('No-go','Finite strict data give lower bound only.',{}),('Proven','One-dimensional coefficient image of infinite cone.',{}),('Round verdict','Locality fixes exponent, not propagation coefficient.',{}),('Recommendation','Tail-mass constraints.',{})];emit(3912,names,rows)
def r3():
 names=['FixedTailMass','SecondMomentAsExpectation','MinimumDistance','MassLowerBound','NoUpperBound','MassBudget','BudgetStillUnbounded','FiniteSupportR','SupportBounds','MeanDistanceConstraint','VarianceFreedom','MomentHierarchy','ConstraintCount','RoundThreeVerdict','RoundThreeRecommendation']
 rows=[('Assume','sum t_d=M.',{}),('Proven','DeltaC=M E[d2].',{}),('Proven','d>=7.',{}),('Proven','DeltaC>=49M.',{}),('Proven','Move mass to arbitrarily large d.',{}),('Assume','sum t_d<=B.',{}),('Proven','Tiny mass at huge d gives arbitrary DeltaC.',{}),('Assume','Tail support d<=R.',{}),('Proven','49M<=DeltaC<=R2M.',{}),('Conditional','Fix first tail moment.',{}),('No-go','Second moment still variable.',{}),('Proven','Each moment constraint leaves higher freedom.',{}),('No-go','Finite constraints cannot identify infinite tail generally.',{}),('Round verdict','Simple mass budgets do not select speed without support/moment laws.',{}),('Recommendation','Minimum principles.',{})];emit(3927,names,rows)
def r4():
 names=['MinimumCPrinciple','UniqueMinimizer','TruncationSelected','MinimumTailNorm','L1Minimum','L2Minimum','MaximumEntropyFailure','NoReferenceTail','PhysicalMeaning','CausalityBenefit','AxiomRemoval','AlternativePenalty','RegularizationDependence','RoundFourVerdict','RoundFourRecommendation']
 rows=[('Axiom','Minimize C over positive tail cone.',{}),('Proven','Unique t=0.',{}),('Conditional','Yields C0 and c0.',{}),('Axiom','Minimize any strictly positive tail norm.',{}),('Proven','Also selects zero.',{}),('Proven','Also selects zero.',{}),('Boundary','Entropy of zero tail ill-posed without mass.',{}),('No-go','Need reference/constraint.',{}),('No-go','Why nature minimizes propagation coefficient not derived.',{}),('Positive','Selects finite-range/local wave.',{}),('Proven','Remove minimization and full cone returns.',{}),('Counterexample','Smoothness/analytic penalties prefer nonzero tails.',{}),('No-go','Selection depends objective.',{}),('Round verdict','Truncation is unique only under an added minimum-tail axiom.',{}),('Recommendation','Exponential local tails.',{})];emit(3942,names,rows)
def r5():
 names=['ExponentialTail','Parameters','FiniteSecondMoment','CoefficientFormula','AmplitudeFreedom','DecayFreedom','ZeroAmplitudeBoundary','AnalyticSymbol','ExactFiniteMatch','SpeedFamily','SmoothnessSelection','FitBoundary','NoUniqueAB','RoundFiveVerdict','RoundFiveRecommendation']
 rows=[('Constructed','t_d=A exp[-a(d-6)], d>=7.',{}),('Defined','A>=0,a>0.',{}),('Proven','All moments finite.',{}),('Proven','DeltaC=A sum d2 exp[-a(d-6)].',{}),('No-go','A free.',{}),('No-go','a free.',{}),('Proven','A=0 truncation.',{}),('Proven','Quadratic analytic near k=0.',{}),('Proven','Patch leaves d<=6 exact.',{}),('Proven','Continuum of C values.',{}),('Boundary','A smooth-tail axiom still leaves parameters.',{}),('Boundary','Beyond-six data could fit A,a.',{}),('No-go','No strict A,a source.',{}),('Round verdict','Analytic positive local tails do not restore uniqueness.',{}),('Recommendation','Finite-range cutoff family.',{})];emit(3957,names,rows)
def r6():
 names=['FiniteRangeTail','CutoffR','WeightSimplex','CoefficientInterval','R6Truncation','R7Extension','GrowingR','RefinementCutoff','SupportSelection','GraphLocality','ConeBounds','LimitRInfinity','CutoffGate','RoundSixVerdict','RoundSixRecommendation']
 rows=[('Constructed','t_d>=0 for 7<=d<=R.',{}),('Parameter','Integer R>=6.',{}),('Proven','Finite-dimensional positive orthant.',{}),('Proven','C=C0+weighted sum.',{}),('Boundary','R=6 zero tail.',{}),('Constructed','One t7 parameter.',{}),('Proven','Degrees grow with R.',{}),('No-go','Refinement needs R_N law.',{}),('No-go','Finite C12 does not select R.',{}),('Positive','Every fixed R admits finite-range cone bounds.',{}),('Boundary','Speed still variable for weights.',{}),('Proven','Approaches infinite cone.',{}),('Fail','No strict cutoff source.',{}),('Round verdict','Finite range is a family, not one continuum.',{}),('Recommendation','Legacy comparison.',{})];emit(3972,names,rows)
def r7():
 al=4*math.log(2);leg=np.array([al*math.cos(math.pi*d/4+math.pi/6)/(1+.01*d) for d in range(1,7)]);names=['LegacyWeights','SignFailure','LegacyLaplacian','PositiveProjection','AbsoluteLegacy','TruncatedAbsolute','Coefficient','RoleMismatch','StrictLowerBound','NoTransfer','DifferentDomains','CommonTailCone','BridgeBoundary','RoundSevenVerdict','RoundSevenRecommendation']
 rows=[('Loaded','Canonical legacy.',{'values':leg.tolist()}),('Proven','Negative base weights.',{}),('No-go','Not conductance-positive without transformation.',{}),('Axiom','Take positive part/absolute value.',{}),('Constructed','Changes semantics.',{}),('Constructed','Positive local model.',{}),('Computed','Depends chosen projection.',{}),('Guardrail','Legacy oscillatory kernel not strict conductance W.',{}),('Proven','C0 bound is strict-only representation.',{}),('No-go','No physical role transfer.',{}),('Boundary','Legacy finite domain/parameters differ.',{}),('Conditional','After positivity map similar tail freedom returns.',{}),('Fail','No bridge completion.',{}),('Round verdict','Legacy cannot select strict local speed cone.',{}),('Recommendation','Physical scale.',{})];emit(3987,names,rows)
def r8():
 names=['DimensionlessSpeed','LengthUnit','TimeUnit','PhysicalC','CalibrationOrbit','MatchToObservedC','ArbitraryConversion','WaveEquation','HeatClock','UnitaryClock','TwoClockNoGo','CMinMeaning','PhysicalLowerBoundNoGo','RoundEightVerdict','RoundEightRecommendation']
 rows=[('Proven','c_hat=sqrtC dimensionless.',{}),('Missing','ell_star.',{}),('Missing','tau_star.',{}),('Defined','c_phys=(ell_star/tau_star)c_hat.',{}),('Proven','Scale torsor leaves dimensionless records.',{}),('No-go','Can fit any c_hat by unit ratio.',{}),('Proven','Conversion is free without calibration.',{}),('Conditional','Second-order wave uses c_hat.',{}),('Boundary','Heat scaling differs.',{}),('Boundary','Unitary phase scaling differs.',{}),('Proven','Shared A not one refinement clock.',{}),('Interpretation','Minimum only inside chosen positive local class.',{}),('No-go','Not a physical lower bound in m/s.',{}),('Round verdict','Even a selected C would not supply physical light speed.',{}),('Recommendation','Operational tail test.',{})];emit(4002,names,rows)
def r9():
 names=['LowKMeasurement','MultipleSizes','SecondMomentEstimate','PropagationFront','TailMassProbe','BeyondSixCouplings','CutoffTest','ExponentialFit','ModelSelection','TimestampCalibration','NuisanceParameters','Holdout','SyntheticBoundary','RoundNineVerdict','RoundNineRecommendation']
 rows=[('Required','Estimate lambda/k2.',{}),('Required','N growth.',{}),('Conditional','Infer C.',{}),('Conditional','Infer c_hat.',{}),('Required','Direct long-distance response.',{}),('Decisive','Measure d>=7.',{}),('Required','Vary effective range.',{}),('Conditional','Fit A,a.',{}),('Boundary','Needs preregistered candidate classes.',{}),('Missing','Physical time.',{}),('Boundary','Finite-size and detector errors.',{}),('Required','Prevent tail retuning.',{}),('No-go','Local simulations are not evidence.',{}),('Round verdict','Positive local cone is experimentally distinguishable but currently unobserved.',{}),('Recommendation','Synthesis.',{})];emit(4017,names,rows)
def r10():
 gate=ROOT/'FIN_ST4032_ST4046_PositiveLocalTailGate.json';g={'rows':[{'name':n,'pass':v} for n,v in [('positive local cone theorem',True),('coefficient/speed range theorem',True),('minimum-tail conditional theorem',True),('strict tail minimization law',False),('strict cutoff',False),('strict exponential parameters',False),('unique dimensionless speed',False),('physical speed calibration',False),('legacy role transfer',False),('OA evidence',False)]]};gate.write_text(json.dumps(g,indent=2)+'\n')
 names=['ConeTheorem','RangeTheorem','MinimumTheorem','MassNoGo','ExponentialNoGo','CutoffNoGo','PhysicalNoGo','Gate','GateScore','ProvenLedger','ConditionalLedger','RefutedLedger','HighestValueNext','FinalInterpretation','CycleTrigger']
 rows=[('Proven','Positive finite-second-moment tails.',{}),('Proven','C range [C0,infinity), speed [sqrtC0,infinity).',{}),('Conditional','Minimum C uniquely truncates.',{}),('No-go','Tail mass budgets insufficient.',{}),('No-go','A,a free.',{}),('No-go','R_N free.',{}),('No-go','No units/calibration.',{}),('Constructed','Ten rows.',{'file':gate.name}),('Result','Three mathematical passes.',{'passes':3,'rows':10}),('Ledger','Cone/range/lower bound.',{}),('Ledger','Minimum-tail local model.',{}),('Ledger','Unique physical propagation.',{}),('Recommendation','Seek a strict variational reason for minimum tail or one beyond-six datum; otherwise report only c_hat>=1.95328 within the positive local class.',{}),('Final verdict','Positive locality yields a sharp lower bound but no prediction of continuum speed.',{'fundamental':False}),('Cycle complete','Release 11.26.',{'programs':150,'rounds':10,'range':'ST3897-ST4046','strict_ToE_closure':False,'gate_sha256':hashlib.sha256(gate.read_bytes()).hexdigest()})];emit(4032,names,rows)
def main():r1();r2();r3();r4();r5();r6();r7();r8();r9();r10()
if __name__=='__main__':main()
