#!/usr/bin/env python3
"""Second-generation FIN puzzle atlas.

This script exhausts all singles, pairs and triples of C01..C12 under an
explicit finite construction grammar.  A grammar hit is only a candidate
construction.  Independent numerical identities are reported separately.
"""

from __future__ import annotations

import csv
import itertools
import json
import math
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np
from scipy.linalg import expm

import fin_nadsoliton_puzzle_atlas as first


HERE = Path(__file__).resolve().parent
FIG = HERE / "FIN_Second_Generation_Atlas_Figures"
FIG.mkdir(exist_ok=True)

BASE = {row[0]: {"name": row[1], "tags": row[2]} for row in first.CHARACTERISTICS}


RULES = [
    {
        "required": {"C03", "C05"},
        "object": "Quadratic Green Action",
        "operation": "operator inversion followed by stationary-action reconstruction",
        "space": "quadratic forms on the zero-mode quotient or a regulated Hilbert space",
        "observable": "source response and on-shell quadratic value",
        "dynamics": "gradient flow or Hamiltonian flow only after an explicit temporal rule",
        "status": "[Proven]",
    },
    {
        "required": {"C03", "C04"},
        "object": "Dual Spectral Ray",
        "operation": "holomorphic/Borel functional calculus of one positive generator",
        "space": "commutative operator algebra generated by A",
        "observable": "spectral response along real and imaginary time rays",
        "dynamics": "unitary group plus heat semigroup",
        "status": "[Proven]",
    },
    {
        "required": {"C03", "C07"},
        "object": "Static Schur Effective Generator",
        "operation": "Kron/Schur elimination of hidden vertices",
        "space": "positive graph Laplacians on retained contexts",
        "observable": "static boundary response",
        "dynamics": "not exact dynamically unless memory vanishes",
        "status": "[Proven]",
    },
    {
        "required": {"C04", "C10"},
        "object": "Operational Dual Process",
        "operation": "insert preparations and instruments into two functional-calculus rays",
        "space": "multi-time probability/process objects",
        "observable": "intervention-conditioned records",
        "dynamics": "wave and diffusion records with separate environments",
        "status": "[Proven]",
    },
    {
        "required": {"C06", "C12"},
        "object": "Asymmetry Resource Receiver",
        "operation": "pair an inversion-odd observable with a prepared state",
        "space": "reflection-asymmetry resource preorder",
        "observable": "signed current/bispectrum/cocycle response",
        "dynamics": "covariant channels cannot create the missing mode",
        "status": "[Proven]",
    },
    {
        "required": {"C10", "C11"},
        "object": "Operational Calibration Torsor",
        "operation": "quotient simultaneous generator-time rescaling",
        "space": "principal positive-scale orbit of (A,tau)",
        "observable": "projective spectrum before an external section is supplied",
        "dynamics": "same transition operator on every scale-orbit representative",
        "status": "[Proven]",
    },
    {
        "required": {"C04", "C09"},
        "object": "Heat Information Metric",
        "operation": "construct diffusion distances from heat-kernel rows",
        "space": "dimensionless metric family indexed by heat time",
        "observable": "multi-scale distinguishability",
        "dynamics": "contractive geometry under the heat semigroup",
        "status": "[Proven]",
    },
    {
        "required": {"C08", "C10"},
        "object": "Adaptive Process Estimator",
        "operation": "update an operator model from intervention-conditioned records",
        "space": "operator-valued state space with apparatus memory",
        "observable": "held-out process likelihood or residual",
        "dynamics": "nonlinear learning coupled to process dynamics",
        "status": "[Moderate evidence]",
    },
    {
        "required": {"C01", "C11"},
        "object": "Projective Spectral Fingerprint",
        "operation": "quotient positive generator rescaling",
        "space": "ordered eigenvalue-ratio simplex",
        "observable": "scale-free spectral ratios",
        "dynamics": "none beyond the inferred dimensionless generator ray",
        "status": "[Proven]",
    },
    {
        "required": {"C01", "C02"},
        "object": "Legacy-Strict Completion Defect",
        "operation": "compare a declared completion map with strict projective shape",
        "space": "residual/obstruction space between kernel families",
        "observable": "completion residual and role-safe mismatch",
        "dynamics": "none unless a typed completion flow is supplied",
        "status": "[Proven]",
    },
    {
        "required": {"C03", "C05", "C07"},
        "object": "Dynamic Spectral Compression Kernel (DSCK)",
        "operation": "frequency-dependent block resolvent and Schur elimination",
        "space": "positive operator-valued Stieltjes functions Sigma_E(z)",
        "observable": "self-energy, memory kernel and projected composition defect",
        "dynamics": "exact non-Markovian reduced heat/wave dynamics",
        "status": "[Proven]",
    },
    {
        "required": {"C03", "C06", "C12"},
        "object": "Chiral Spectral Response Bundle",
        "operation": "collect inversion-odd spectral receivers under one resource monotone",
        "space": "bundle of signed observables over reflection-asymmetric states",
        "observable": "current, bispectrum and cocycle responses with common sign covariance",
        "dynamics": "covariant spectral dynamics transports but does not source the sign",
        "status": "[Strong evidence]",
    },
    {
        "required": {"C04", "C07", "C10"},
        "object": "Dual-Ray Reduced Process Tensor",
        "operation": "project wave/heat propagators and retain intermediate interventions",
        "space": "context-indexed multi-time process maps",
        "observable": "intervention-dependent memory witness",
        "dynamics": "coherent and diffusive reduced processes with hidden excursions",
        "status": "[Strong evidence]",
    },
    {
        "required": {"C03", "C04", "C09"},
        "object": "Heat-Spectral Geometry Tower",
        "operation": "spectral calculus followed by diffusion/Fisher geometry",
        "space": "one-parameter family of intrinsic finite geometries",
        "observable": "diffusion distances and spectral dimensions",
        "dynamics": "metric contraction along heat time",
        "status": "[Proven]",
    },
    {
        "required": {"C06", "C09", "C12"},
        "object": "Spectral Asymmetry Transport Cost",
        "operation": "minimize information-geometric cost over symmetry-covariant channels",
        "space": "resource-conversion metric space",
        "observable": "minimum cost of a signed receiver target",
        "dynamics": "resource monotone under free channels",
        "status": "[Moderate evidence]",
    },
    {
        "required": {"C04", "C09", "C10"},
        "object": "Information Contraction Ledger",
        "operation": "apply data processing to operational heat records",
        "space": "pairs of probability measures modulo the process channel",
        "observable": "lost relative distinguishability",
        "dynamics": "monotone contraction without dimensional energy interpretation",
        "status": "[Proven]",
    },
    {
        "required": {"C05", "C07", "C10"},
        "object": "Resolvent Context Presheaf",
        "operation": "assign Schur-effective resolvents to nested observation contexts",
        "space": "contravariant diagram of effective operator pencils",
        "observable": "context-to-context self-energy and gluing residual",
        "dynamics": "contextual memory under refinement/coarsening",
        "status": "[Proven]",
    },
    {
        "required": {"C06", "C07", "C10"},
        "object": "Chiral Memory Susceptibility",
        "operation": "differentiate context self-energy with respect to an oriented flux twist",
        "space": "inversion-odd tangent operators over the context diagram",
        "observable": "Xi_E(z)=partial_theta Sigma_E(z,theta)|_0",
        "dynamics": "signed linear response of hidden-node memory",
        "status": "[Strong evidence]",
    },
    {
        "required": {"C07", "C08", "C10"},
        "object": "Adaptive Multiscale Memory Flow",
        "operation": "couple context self-energies to a record-driven update law",
        "space": "trajectories of operator-valued Stieltjes functions",
        "observable": "held-out change in memory spectrum",
        "dynamics": "nonlinear adaptive non-Markovian flow",
        "status": "[Speculative]",
    },
    {
        "required": {"C05", "C07", "C08"},
        "object": "Multiscale Memory Functor",
        "operation": "iterate resolvent self-energies through a nested reduction hierarchy",
        "space": "scale-indexed diagram of operator-valued Stieltjes functions",
        "observable": "memory spectrum and Schur-composition residual at each depth",
        "dynamics": "hierarchical fading memory; adaptation remains an added law",
        "status": "[Strong evidence]",
    },
    {
        "required": {"C01", "C02", "C07"},
        "object": "Multiscale Completion-Defect Tower",
        "operation": "transport the legacy-strict residual through nested reductions",
        "space": "scale-indexed obstruction diagram",
        "observable": "whether bridge defect contracts, persists or grows",
        "dynamics": "reduction-index flow, not physical time",
        "status": "[Moderate evidence]",
    },
    {
        "required": {"C08", "C09", "C10"},
        "object": "Adaptive Memory Geometry Flow",
        "operation": "couple Fisher/heat geometry to record-driven operator learning",
        "space": "product of probability manifold and operator-memory manifold",
        "observable": "geometric learning dissipation and predictive error",
        "dynamics": "coupled gradient/process flow",
        "status": "[Speculative]",
    },
    {
        "required": {"C10", "C11", "C12"},
        "object": "Two-Torsor Physicalization Bundle",
        "operation": "keep scale calibration and orientation resource as separate sections",
        "space": "product of a positive-scale torsor and an orientation torsor over operational contexts",
        "observable": "calibrated signed record only after both sections are supplied",
        "dynamics": "conditional physicalization map; no internal source theorem",
        "status": "[Strong evidence]",
    },
]


LARGE_GROUPS = [
    ("C03", "C04", "C05", "C07"),
    ("C03", "C04", "C07", "C10"),
    ("C03", "C05", "C06", "C07", "C12"),
    ("C03", "C04", "C08", "C09", "C10"),
    ("C01", "C02", "C03", "C05", "C07", "C11"),
    ("C03", "C04", "C05", "C07", "C09", "C10"),
    ("C04", "C06", "C09", "C10", "C11", "C12"),
]


DERIVED_OBJECTS = [
    ("O01", "Dynamic Spectral Compression Kernel", "C03+C05+C07", "Sigma_E(z)=A_EH(zI+A_HH)^(-1)A_HE", 4, 5, 5, 5, 2, "[Proven]"),
    ("O02", "Frequency-Dependent Effective Action", "C03+C05+C07", "S_z[x]=1/2<x,(zI+A_EE-Sigma_E(z))x>-<j,x>", 3, 5, 5, 5, 2, "[Proven]"),
    ("O03", "Resolvent Context Presheaf", "C05+C07+C10", "E maps to Schur_E(zI+A), inclusions map to nested Schur restrictions", 4, 5, 4, 5, 2, "[Proven]"),
    ("O04", "Chiral Spectral Response Bundle", "C03+C06+C12", "(M_R(rho), Lambda(rho,A), C_chi(rho), Im B(rho))", 3, 4, 5, 5, 3, "[Strong evidence]"),
    ("O05", "Chiral Memory Susceptibility", "C06+C07+C10", "Xi_E(z)=partial_theta Sigma_E(z,theta)|_0", 4, 4, 4, 5, 3, "[Strong evidence]"),
    ("O06", "Heat Information Metric Tower", "C03+C04+C09", "D_t(x,y)^2=sum_z |P_t(x,z)-P_t(y,z)|^2/pi_z", 2, 5, 4, 4, 3, "[Proven]"),
    ("O07", "Operational Calibration Torsor", "C10+C11", "(A,tau)~(cA,tau/c)", 2, 5, 5, 5, 2, "[Proven]"),
    ("O08", "Projective Spectral Fingerprint", "C01+C03+C11", "(lambda_1/lambda_max,...,lambda_11/lambda_max)", 2, 5, 5, 5, 2, "[Proven]"),
    ("O09", "Information Contraction Ledger", "C04+C09+C10", "L_t(p,q)=D(p||q)-D(P_t p||P_t q)", 2, 5, 4, 5, 4, "[Proven]"),
    ("O10", "Dual-Ray Reduced Process Tensor", "C04+C07+C10", "T_r[M_1,...,M_r] on projected U and P rays", 3, 3, 5, 5, 3, "[Moderate evidence]"),
    ("O11", "Adaptive Memory Geometry Flow", "C08+C09+C10", "(dot A,dot q)=(-grad_A L,-grad_F L) with process-memory likelihood", 4, 2, 3, 3, 5, "[Speculative]"),
    ("O12", "Multiscale Memory Functor", "C05+C07+C08", "nested Sigma^(n)(z) with associative Schur composition", 4, 4, 4, 4, 3, "[Strong evidence]"),
    ("O13", "Legacy-Strict Completion-Defect Tower", "C01+C02+C07", "Delta_n=K_strict^(n)-C_n[K_legacy^(n)]", 3, 4, 5, 5, 2, "[Moderate evidence]"),
    ("O14", "Spectral Asymmetry Transport Cost", "C06+C09+C12", "inf_{Phi covariant, Phi(rho)=sigma} Cost(Phi)", 3, 3, 4, 4, 4, "[Moderate evidence]"),
    ("O15", "Two-Torsor Physicalization Bundle", "C10+C11+C12", "scale torsor x orientation torsor with separate operational sections", 2, 4, 5, 5, 2, "[Strong evidence]"),
]


GENERATION3 = [
    ("G01", "O01+O02", "Dynamic Effective Action Bundle", "A Stieltjes self-energy plus its exact source-response action", "[Proven]"),
    ("G02", "O01+O03+O12", "Stieltjes-Schur Context Functor", "A context diagram whose reductions compose and whose self-energies are completely monotone", "[Proven]"),
    ("G03", "O04+O05+O14", "Chiral Memory Resource Bundle", "An inversion-odd tangent response with an explicit asymmetry budget; still no source sign", "[Strong evidence]"),
    ("G04", "O06+O12", "Memory-Diffusion Geometry Tower", "Intrinsic geometry indexed jointly by diffusion time and hidden-layer depth", "[Moderate evidence]"),
    ("G05", "O07+O08", "Calibrated Fingerprint Bundle", "A scale-free prediction plus an explicitly external calibration section", "[Proven]"),
    ("G06", "O09+O10", "Operational Information-Balance Tensor", "Multi-time record distinguishability with a channel-by-channel contraction ledger", "[Moderate evidence]"),
    ("G07", "O01+O11", "Adaptive Self-Energy Flow", "A learned trajectory in operator-valued Stieltjes space", "[Speculative]"),
    ("G08", "O12+O13", "Dynamic Completion-Defect Tower", "Tests whether a bridge obstruction is static or persists through exact memory reduction", "[Moderate evidence]"),
    ("G09", "O03+O14+O15", "Equivariant Context-Resource Diagram", "Separate context restrictions, scale sections and orientation resources; no automatic global section", "[Speculative]"),
    ("G10", "O05+O09", "Signed Information-Loss Susceptibility", "Derivative of operational information contraction under a chiral flux perturbation", "[Speculative]"),
]


def matched_rules(combo: tuple[str, ...]) -> list[dict[str, Any]]:
    ids = set(combo)
    matches = [rule for rule in RULES if rule["required"] <= ids]
    if not matches:
        return []
    width = max(len(rule["required"]) for rule in matches)
    return [rule for rule in matches if len(rule["required"]) == width]


def combination_row(combo: tuple[str, ...], selected_large: bool = False) -> dict[str, Any]:
    matches = matched_rules(combo)
    names = " + ".join(BASE[cid]["name"] for cid in combo)
    if len(combo) == 1:
        return {
            "size": 1,
            "combination": "+".join(combo),
            "base_puzzles": names,
            "common_operation": "base object only",
            "derived_candidate": "No derivative at generation 1",
            "object_space": "declared base characteristic",
            "new_observable": "none beyond the base puzzle",
            "new_dynamics": "none beyond the base puzzle",
            "status": "[Proven]",
            "screening_verdict": "Input inventory item",
        }
    if not matches:
        return {
            "size": len(combo),
            "combination": "+".join(combo),
            "base_puzzles": names,
            "common_operation": "no typed common operation in the declared finite grammar",
            "derived_candidate": "No admitted derivative",
            "object_space": "not constructed",
            "new_observable": "not constructed",
            "new_dynamics": "not constructed",
            "status": "[Refuted]",
            "screening_verdict": "Visual juxtaposition alone was rejected",
        }
    inherited = all(rule["required"] != set(combo) for rule in matches)
    return {
        "size": len(combo),
        "combination": "+".join(combo),
        "base_puzzles": names,
        "common_operation": " | ".join(rule["operation"] for rule in matches),
        "derived_candidate": " | ".join(rule["object"] for rule in matches),
        "object_space": " | ".join(rule["space"] for rule in matches),
        "new_observable": " | ".join(rule["observable"] for rule in matches),
        "new_dynamics": " | ".join(rule["dynamics"] for rule in matches),
        "status": " | ".join(sorted({rule["status"] for rule in matches})),
        "screening_verdict": (
            "Selected 4--6 puzzle coupling"
            if selected_large
            else (
                "Inherited lower-order object; no new irreducible coupling"
                if inherited
                else "Typed derivative generated"
            )
        ),
    }


def write_csv(name: str, rows: list[dict[str, Any]]) -> None:
    with (HERE / name).open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def strict_matrices() -> tuple[np.ndarray, np.ndarray]:
    w = np.zeros((first.N, first.N), dtype=float)
    for x in range(first.N):
        for y in range(first.N):
            delta = abs(x - y) % first.N
            d = min(delta, first.N - delta)
            if d:
                w[x, y] = first.K[d - 1]
    return w, w[0].sum() * np.eye(first.N) - w


def schur_keep(matrix: np.ndarray, keep: list[int]) -> np.ndarray:
    remove = [i for i in range(matrix.shape[0]) if i not in keep]
    if not remove:
        return matrix.copy()
    mkk = matrix[np.ix_(keep, keep)]
    mkr = matrix[np.ix_(keep, remove)]
    mrk = matrix[np.ix_(remove, keep)]
    mrr = matrix[np.ix_(remove, remove)]
    return mkk - mkr @ np.linalg.solve(mrr, mrk)


def twisted_generator(theta: float, w: np.ndarray, a: np.ndarray) -> np.ndarray:
    n = len(a)
    identity = np.eye(n, dtype=complex)
    result_w = np.zeros((n, n), dtype=complex)
    for d in range(1, n // 2):
        shift = np.zeros((n, n), dtype=complex)
        for x in range(n):
            shift[x, (x + d) % n] = 1.0
        result_w += first.K[d - 1] * (
            np.exp(1j * d * theta) * shift
            + np.exp(-1j * d * theta) * shift.conj().T
        )
    antipodal = np.zeros((n, n), dtype=complex)
    for x in range(n):
        antipodal[x, (x + n // 2) % n] = 1.0
    result_w += first.K[-1] * np.cos((n // 2) * theta) * antipodal
    return float(w[0].sum()) * identity - result_w


def density(phi: float, eta: float, time: float, a: np.ndarray) -> np.ndarray:
    eigenvalues, vectors = np.linalg.eigh(a)
    unitary = (vectors * np.exp(-1j * time * eigenvalues)) @ vectors.T
    basis = np.eye(len(a))
    ket_a, ket_b = basis[:, 10], basis[:, 2]
    rho0 = 0.5 * (
        np.outer(ket_a, ket_a)
        + np.outer(ket_b, ket_b)
        + eta * np.exp(-1j * phi) * np.outer(ket_a, ket_b)
        + eta * np.exp(+1j * phi) * np.outer(ket_b, ket_a)
    )
    return unitary @ rho0 @ unitary.conj().T


def kl(p: np.ndarray, q: np.ndarray) -> float:
    return float(np.sum(p * np.log(p / q)))


def numerical_certificates() -> dict[str, Any]:
    w, a = strict_matrices()
    n = len(a)
    even = list(range(0, n, 2))
    odd = list(range(1, n, 2))
    z = 0.2

    # O01/O02: DSCK and its exact effective action.
    aee = a[np.ix_(even, even)]
    aeh = a[np.ix_(even, odd)]
    ahe = a[np.ix_(odd, even)]
    ahh = a[np.ix_(odd, odd)]
    sigma = aeh @ np.linalg.solve(z * np.eye(len(odd)) + ahh, ahe)
    beff = z * np.eye(len(even)) + aee - sigma
    rng = np.random.default_rng(20260728)
    source = rng.normal(size=len(even))
    stationary = np.linalg.solve(beff, source)
    action_residual = float(np.linalg.norm(beff @ stationary - source))

    # O03: direct versus nested context restriction.
    bfull = z * np.eye(n) + a
    context1 = [0, 1, 2, 3, 4, 6, 8, 10]
    context2 = even
    direct = schur_keep(bfull, context2)
    first_stage = schur_keep(bfull, context1)
    context2_local = [context1.index(x) for x in context2]
    nested = schur_keep(first_stage, context2_local)
    context_associativity = float(np.linalg.norm(direct - nested, 2))

    # Complete monotonicity samples for the operator-valued Stieltjes kernel.
    stieltjes_min_eigenvalues: dict[str, float] = {}
    for order in range(5):
        signed_derivative = (
            math.factorial(order)
            * aeh
            @ np.linalg.matrix_power(z * np.eye(len(odd)) + ahh, -(order + 1))
            @ ahe
        )
        stieltjes_min_eigenvalues[str(order)] = float(
            np.linalg.eigvalsh((signed_derivative + signed_derivative.T) / 2).min()
        )

    # O04/O05: flux-current identity and inversion-odd memory tangent.
    h = 1e-6
    aprime = (twisted_generator(h, w, a) - twisted_generator(-h, w, a)) / (2 * h)
    rho = density(0.7, 1.0, 1.5525, a)
    current = 2.0 * w * np.imag(rho.T)
    c_chi = float(
        sum(d * current[x, (x + d) % n] for x in range(n) for d in range(1, n // 2))
    )
    flux_response = float(np.real(np.trace(rho @ aprime)))
    flux_identity_residual = abs(flux_response - c_chi)

    def sigma_theta(theta: float) -> np.ndarray:
        at = twisted_generator(theta, w, a)
        ee = at[np.ix_(even, even)]
        eh = at[np.ix_(even, odd)]
        he = at[np.ix_(odd, even)]
        hh = at[np.ix_(odd, odd)]
        del ee  # the self-energy uses only coupling and hidden block
        return eh @ np.linalg.solve(z * np.eye(len(odd)) + hh, he)

    xi = (sigma_theta(h) - sigma_theta(-h)) / (2 * h)
    reflection = np.zeros((n, n))
    for x in range(n):
        reflection[x, (-x) % n] = 1.0
    reflection_even = reflection[np.ix_(even, even)]
    chiral_covariance_residual = float(
        np.linalg.norm(reflection_even @ xi @ reflection_even + xi, 2)
    )

    # O07/O08: calibration-orbit and projective-spectrum invariance.
    tau, scale = 0.37, 7.25
    calibration_residual = float(
        np.linalg.norm(expm(-tau * a) - expm(-(tau / scale) * (scale * a)), 2)
    )
    eig = np.linalg.eigvalsh(a)
    eig_scaled = np.linalg.eigvalsh(scale * a)
    fingerprint = eig[1:] / eig[-1]
    fingerprint_scaled = eig_scaled[1:] / eig_scaled[-1]
    fingerprint_residual = float(np.max(np.abs(fingerprint - fingerprint_scaled)))

    # O09: data-processing contraction on a deterministic random audit family.
    heat = expm(-0.6 * a)
    losses = []
    for _ in range(1000):
        p = rng.dirichlet(np.ones(n))
        q = rng.dirichlet(np.ones(n))
        losses.append(kl(p, q) - kl(heat @ p, heat @ q))

    # O06: maximum pair diffusion distance contracts over the chosen time grid.
    diffusion_max: dict[str, float] = {}
    pi = np.full(n, 1.0 / n)
    for time in [0.1, 0.25, 0.5, 1.0]:
        ptime = expm(-time * a)
        values = []
        for x, y in itertools.combinations(range(n), 2):
            values.append(float(np.sum((ptime[x] - ptime[y]) ** 2 / pi)))
        diffusion_max[str(time)] = max(values)

    return {
        "effective_action_stationarity_residual": action_residual,
        "context_schur_associativity_residual": context_associativity,
        "operator_stieltjes_signed_derivative_min_eigenvalues_orders_0_to_4": stieltjes_min_eigenvalues,
        "flux_current_identity": {
            "C_chi": c_chi,
            "energy_twist_derivative": flux_response,
            "residual": flux_identity_residual,
        },
        "chiral_memory_susceptibility": {
            "operator_norm": float(np.linalg.norm(xi, 2)),
            "inversion_odd_covariance_residual": chiral_covariance_residual,
        },
        "calibration_torsor_heat_invariance_residual": calibration_residual,
        "projective_fingerprint_scaling_residual": fingerprint_residual,
        "information_contraction_1000_pairs": {
            "minimum_loss": min(losses),
            "median_loss": float(np.median(losses)),
            "maximum_loss": max(losses),
            "negative_count_below_minus_1e_12": sum(loss < -1e-12 for loss in losses),
        },
        "maximum_diffusion_distance_squared": diffusion_max,
    }


def make_figures(counts: dict[str, int]) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(12.5, 4.8))
    labels = ["singles", "pairs", "triples", "groups 4--6"]
    values = [
        counts["singles"],
        counts["pairs"],
        counts["triples"],
        counts["selected_groups_4_to_6"],
    ]
    axes[0].bar(labels, values, color=["#4c78a8", "#72b7b2", "#f2cf5b", "#e45756"])
    axes[0].set_ylabel("number screened")
    axes[0].set_title("Exhaustive finite combination coverage")
    axes[0].tick_params(axis="x", rotation=20)
    outcome_labels = ["base inputs", "typed derivatives", "rejected joins"]
    outcome_values = [
        counts["singles"],
        counts["typed_derivative_rows"],
        counts["rejected_visual_juxtapositions"],
    ]
    axes[1].barh(outcome_labels, outcome_values, color=["#4c78a8", "#54a24b", "#e45756"])
    axes[1].set_xlabel("combination rows")
    axes[1].set_title("Construction-grammar outcome")
    for axis in axes:
        axis.grid(axis="y", alpha=0.2)
    fig.tight_layout()
    fig.savefig(FIG / "combination_search_coverage.png", dpi=190)
    plt.close(fig)

    score_matrix = np.array([row[4:9] for row in DERIVED_OBJECTS], dtype=float)
    fig, ax = plt.subplots(figsize=(9.8, 8.2))
    image = ax.imshow(score_matrix, vmin=0, vmax=5, cmap="magma", aspect="auto")
    ax.set_xticks(
        range(5),
        ["novelty", "rigor", "FIN link", "falsifiability", "overinterpretation risk"],
        rotation=25,
        ha="right",
    )
    ax.set_yticks(range(len(DERIVED_OBJECTS)), [row[0] for row in DERIVED_OBJECTS])
    ax.set_title("Second-generation derived-object audit scores")
    for i in range(score_matrix.shape[0]):
        for j in range(score_matrix.shape[1]):
            ax.text(
                j,
                i,
                str(int(score_matrix[i, j])),
                ha="center",
                va="center",
                color="white" if score_matrix[i, j] < 2 or score_matrix[i, j] > 4 else "black",
                fontsize=8,
            )
    fig.colorbar(image, ax=ax, label="score 0--5")
    fig.tight_layout()
    fig.savefig(FIG / "derived_object_score_matrix.png", dpi=190)
    plt.close(fig)

    # A compact generation map. It intentionally omits cross-domain analogy
    # arrows so that construction inputs are not confused with equivalence.
    fig, ax = plt.subplots(figsize=(14, 8.5))
    ax.axis("off")
    o_positions: dict[str, tuple[float, float]] = {}
    g_positions: dict[str, tuple[float, float]] = {}
    for i, row in enumerate(DERIVED_OBJECTS):
        y = 0.94 - i * 0.062
        o_positions[row[0]] = (0.28, y)
        ax.text(
            0.28,
            y,
            f"{row[0]}  {row[1]}",
            ha="center",
            va="center",
            fontsize=8,
            bbox={"boxstyle": "round,pad=0.25", "fc": "#e8f1fa", "ec": "#4c78a8"},
        )
    for i, row in enumerate(GENERATION3):
        y = 0.90 - i * 0.088
        g_positions[row[0]] = (0.76, y)
        ax.text(
            0.76,
            y,
            f"{row[0]}  {row[2]}",
            ha="center",
            va="center",
            fontsize=8,
            bbox={"boxstyle": "round,pad=0.28", "fc": "#edf7e8", "ec": "#54a24b"},
        )
        for source in row[1].split("+"):
            if source in o_positions:
                x0, y0 = o_positions[source]
                x1, y1 = g_positions[row[0]]
                ax.annotate(
                    "",
                    xy=(x1 - 0.12, y1),
                    xytext=(x0 + 0.12, y0),
                    arrowprops={"arrowstyle": "->", "lw": 0.7, "color": "#888888", "alpha": 0.65},
                )
    ax.text(0.28, 0.995, "Generation 2: O objects", ha="center", va="top", fontsize=12, weight="bold")
    ax.text(0.76, 0.995, "Generation 3: coupled objects", ha="center", va="top", fontsize=12, weight="bold")
    ax.set_title("Construction map (arrows mean input dependency, not physical equivalence)", pad=20)
    fig.tight_layout()
    fig.savefig(FIG / "generation2_generation3_map.png", dpi=190)
    plt.close(fig)


def main() -> None:
    combinations: list[dict[str, Any]] = []
    ids = sorted(BASE)
    for size in [1, 2, 3]:
        combinations.extend(combination_row(combo) for combo in itertools.combinations(ids, size))
    combinations.extend(combination_row(tuple(combo), True) for combo in LARGE_GROUPS)
    write_csv("FIN_Second_Generation_Combination_Search.csv", combinations)

    object_fields = [
        "object_id",
        "derived_object",
        "source_combination",
        "mathematical_form",
        "novelty_0_5",
        "mathematical_rigor_0_5",
        "FIN_relation_0_5",
        "falsifiability_0_5",
        "overinterpretation_risk_0_5",
        "status",
    ]
    object_rows = [dict(zip(object_fields, row)) for row in DERIVED_OBJECTS]
    write_csv("FIN_Second_Generation_Derived_Objects.csv", object_rows)

    generation_fields = [
        "generation3_id",
        "inputs",
        "higher_object",
        "mechanism",
        "status",
    ]
    generation_rows = [dict(zip(generation_fields, row)) for row in GENERATION3]
    write_csv("FIN_Second_Generation_Generation3.csv", generation_rows)

    certificates = numerical_certificates()
    counts = {
        "singles": len(list(itertools.combinations(ids, 1))),
        "pairs": len(list(itertools.combinations(ids, 2))),
        "triples": len(list(itertools.combinations(ids, 3))),
        "selected_groups_4_to_6": len(LARGE_GROUPS),
        "total_combinations_screened": len(combinations),
        "generation2_objects": len(DERIVED_OBJECTS),
        "generation3_objects": len(GENERATION3),
        "typed_derivative_rows": sum(
            row["derived_candidate"] not in {"No derivative at generation 1", "No admitted derivative"}
            for row in combinations
        ),
        "rejected_visual_juxtapositions": sum(
            row["derived_candidate"] == "No admitted derivative" for row in combinations
        ),
    }
    payload = {
        "methodological_warning": (
            "Construction-grammar hits and cross-domain analogies are candidate "
            "generators, not equivalence or physical evidence."
        ),
        "coverage": counts,
        "numerical_certificates": certificates,
        "highest_level_candidate": {
            "name": "Stieltjes-Schur Context Functor",
            "definition": (
                "A context-indexed contravariant diagram E -> Schur_E(zI+A) "
                "whose restrictions compose and whose hidden-sector self-energies "
                "are positive operator-valued completely monotone functions."
            ),
            "status": "[Proven] as finite operator algebra; [Speculative] as a physical ontology",
        },
    }
    (HERE / "FIN_Second_Generation_Atlas_Results.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    make_figures(counts)
    print(json.dumps(counts, indent=2))
    print(json.dumps(certificates, indent=2))


if __name__ == "__main__":
    main()
