#!/usr/bin/env python3
"""
QW-2110: deterministic strict sidecar-template builder for QW-2109.

Purpose:
- generate strict-ready metadata template files with computed payload hashes,
- standardize evidence-sidecar structure for external T3/T4 inputs.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List


ROOT = Path(__file__).resolve().parent

DEFAULT_HZ_CSV = ROOT / "external_hz_nodes_qw2099.csv"
DEFAULT_HZ_META = ROOT / "external_hz_nodes_qw2099.metadata.json"
DEFAULT_G_JSON = ROOT / "external_gnewton_bridge_qw2101.json"
DEFAULT_G_META = ROOT / "external_gnewton_bridge_qw2101.metadata.json"

OUT_HZ = ROOT / "external_hz_nodes_qw2099.metadata.strict.template.json"
OUT_G = ROOT / "external_gnewton_bridge_qw2101.metadata.strict.template.json"


def _load_json(path: Path) -> Dict:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            chunk = f.read(1024 * 1024)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def _read_hz_header_rows(path: Path) -> tuple[List[str], int]:
    with path.open("r", encoding="utf-8", newline="") as f:
        r = csv.DictReader(f)
        header = list(r.fieldnames or [])
        n = 0
        for _ in r:
            n += 1
    return header, n


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def _base_from_existing(meta: Dict) -> Dict:
    return {
        "source_dataset_name": meta.get("source_dataset_name", ""),
        "citation": meta.get("citation", ""),
        "reference_url": meta.get("reference_url", ""),
        "source_version": meta.get("source_version", ""),
        "provenance_anchor_free": bool(meta.get("provenance_anchor_free", False)),
        "seeded_from_registry": bool(meta.get("seeded_from_registry", False)),
    }


def main() -> None:
    p = argparse.ArgumentParser(description="QW-2110 strict sidecar-template builder")
    p.add_argument("--hz-csv", default=str(DEFAULT_HZ_CSV), help="H(z) CSV artifact.")
    p.add_argument("--hz-meta", default=str(DEFAULT_HZ_META), help="Existing H(z) metadata.")
    p.add_argument("--g-json", default=str(DEFAULT_G_JSON), help="G bridge JSON artifact.")
    p.add_argument("--g-meta", default=str(DEFAULT_G_META), help="Existing G metadata.")
    args = p.parse_args()

    hz_csv = Path(args.hz_csv).resolve()
    hz_meta_path = Path(args.hz_meta).resolve()
    g_json_path = Path(args.g_json).resolve()
    g_meta_path = Path(args.g_meta).resolve()

    if not hz_csv.exists():
        raise FileNotFoundError(f"Missing H(z) CSV: {hz_csv}")
    if not g_json_path.exists():
        raise FileNotFoundError(f"Missing G JSON: {g_json_path}")

    hz_existing = _load_json(hz_meta_path)
    g_existing = _load_json(g_meta_path)
    g_payload = _load_json(g_json_path)

    hz_header, hz_rows = _read_hz_header_rows(hz_csv)
    hz_sha = _sha256_file(hz_csv)
    g_sha = _sha256_file(g_json_path)
    now_utc = _utc_now_iso()

    hz_template = {
        **_base_from_existing(hz_existing),
        "acquired_utc": now_utc,
        "artifact_sha256": hz_sha,
        "acquisition_protocol": "external_dataset_snapshot_with_manifest",
        "acquisition_command": "FILL_WITH_EXACT_COMMAND_USED_TO_PRODUCE_THIS_FILE",
        "analyst": "FILL_WITH_NAME_OR_ORCID",
        "data_license": "FILL_WITH_LICENSE",
        "columns_schema": hz_header,
        "record_count": hz_rows,
        "notes": "Strict template generated by QW-2110. Fill all FILL_* fields before strict use.",
    }

    g_template = {
        **_base_from_existing(g_existing),
        "acquired_utc": now_utc,
        "artifact_sha256": g_sha,
        "acquisition_protocol": "external_dataset_snapshot_with_manifest",
        "acquisition_command": "FILL_WITH_EXACT_COMMAND_USED_TO_PRODUCE_THIS_FILE",
        "analyst": "FILL_WITH_NAME_OR_ORCID",
        "data_license": "FILL_WITH_LICENSE",
        "json_keys": sorted(g_payload.keys()),
        "bridge_observable_origin": g_existing.get(
            "bridge_observable_origin",
            "FILL_WITH_external_dimensionless_observable_OR_backsolved_from_g_si",
        ),
        "notes": "Strict template generated by QW-2110. Fill all FILL_* fields before strict use.",
    }

    OUT_HZ.write_text(json.dumps(hz_template, ensure_ascii=False, indent=2), encoding="utf-8")
    OUT_G.write_text(json.dumps(g_template, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"[QW-2110] Saved: {OUT_HZ.name}")
    print(f"[QW-2110] Saved: {OUT_G.name}")
    print(f"[QW-2110] hz_sha256={hz_sha}")
    print(f"[QW-2110] g_sha256={g_sha}")


if __name__ == "__main__":
    main()
