#include <bits/stdc++.h>
using namespace std; constexpr int Q=12,D=7; const double u=1.0/Q;
struct State{array<int8_t,Q>a{};bool operator==(State const&o)const{return a==o.a;}};struct Hash{size_t operator()(State const&s)const noexcept{uint64_t h=1469598103934665603ULL;for(auto v:s.a){h^=(uint8_t)(v+8);h*=1099511628211ULL;}return h;}};struct Poly{double c[3]{0,0,0};};
static inline Poly mulp(const Poly&a,const Poly&b){Poly z;for(int i=0;i<3;i++)for(int j=0;i+j<3;j++)z.c[i+j]+=a.c[i]*b.c[j];return z;}
double E[Q][D],PV[Q][Q],PH[Q][Q],Aop[Q][Q],lam[7];
void init(){double W[Q][Q]{},L[Q][Q]{};for(int i=0;i<Q;i++)for(int j=0;j<Q;j++)if(i!=j){int d=abs(i-j);d=min(d,Q-d);W[i][j]=cos(.18575*d+.1625)/(1+pow((double)d,1.8));}for(int i=0;i<Q;i++){double s=0;for(int j=0;j<Q;j++)s+=W[i][j];for(int j=0;j<Q;j++)L[i][j]=(i==j?s:0)-W[i][j];}for(int k=0;k<=6;k++){double s=0;for(int j=0;j<Q;j++)s+=L[0][j]*cos(2*M_PI*k*j/Q);lam[k]=s;}int c=0;for(int k:{3,4,5}){for(int j=0;j<Q;j++)E[j][c]=sqrt(2.0/Q)*cos(2*M_PI*k*j/Q);c++;for(int j=0;j<Q;j++)E[j][c]=sqrt(2.0/Q)*sin(2*M_PI*k*j/Q);c++;}for(int j=0;j<Q;j++)E[j][c]=(j%2?-1:1)/sqrt((double)Q);for(int i=0;i<Q;i++)for(int j=0;j<Q;j++){double s=0;for(int r=0;r<D;r++)s+=E[i][r]*E[j][r];PV[i][j]=s;PH[i][j]=(i==j)-1.0/Q-s;}double ad[D]={lam[3],lam[3],lam[4],lam[4],lam[5],lam[5],lam[6]};for(int i=0;i<Q;i++)for(int j=0;j<Q;j++){double s=0;for(int r=0;r<D;r++)s+=E[i][r]*ad[r]*E[j][r];Aop[i][j]=s;}}
struct Co{double v[Q]{},w[Q]{},aa[Q]{},maa=0;};Co cf(State const&s){Co o;for(int i=0;i<Q;i++)for(int j=0;j<Q;j++){o.v[i]+=PV[i][j]*s.a[j];o.aa[i]+=Aop[i][j]*s.a[j];}for(int i=0;i<Q;i++){for(int j=0;j<Q;j++)o.w[i]+=6*PH[i][j]*o.v[j]*o.v[j];o.maa+=o.aa[i]*o.aa[i]/Q;}return o;}Poly rate(State const&s,bool cl,int hr,int i,int j,Co const&c){Poly z;double p1=cl?c.v[i]:s.a[i],p2=cl?c.w[i]:0;if(hr==0)z.c[0]=u*u;else if(hr==1){z.c[0]=p1*u;z.c[1]=u*c.aa[j]/Q;}else{z.c[0]=p2*u;z.c[1]=p1*c.aa[j]/Q;z.c[2]=u*(c.aa[j]*c.aa[j]-c.maa)/(2*Q);}return z;}using Map=unordered_map<State,Poly,Hash>;Map apply(Map const&m,bool cl,int hr){Map out;out.reserve(m.size()*8+100);for(auto const&kv:m){Co c=cf(kv.first);for(int i=0;i<Q;i++)for(int j=0;j<Q;j++)if(i!=j){Poly cp=mulp(kv.second,rate(kv.first,cl,hr,i,j,c));State t=kv.first;t.a[i]--;t.a[j]++;auto&x=out[t];auto&y=out[kv.first];for(int g=0;g<3;g++){x.c[g]+=cp.c[g];y.c[g]-=cp.c[g];}}}return out;}Map seqmeasure(bool cl,array<int,3>ss){State z{};Map m;m[z].c[0]=1;for(int r:ss)m=apply(m,cl,r);return m;}
void enumA(int rem,int pos,array<int,D>&a,vector<array<int,D>>&o){if(pos==D-1){a[pos]=rem;o.push_back(a);return;}for(int x=0;x<=rem;x++){a[pos]=x;enumA(rem-x,pos+1,a,o);}}double fac(int n){double r=1;for(int i=2;i<=n;i++)r*=i;return r;}
int main(){init();vector<array<int,3>> seq={{2,0,0},{0,2,0},{0,0,2},{1,1,0},{1,0,1},{0,1,1}};vector<array<int,D>> aa;array<int,D>x{};enumA(4,0,x,aa);cout<<setprecision(17);
 for(auto ss:seq){auto F=seqmeasure(false,ss),C=seqmeasure(true,ss);for(auto&kv:C){auto&o=F[kv.first];for(int g=0;g<3;g++)o.c[g]-=kv.second.c[g];}vector<array<double,3>> T(aa.size());for(auto const&kv:F){double z[D]{};for(int r=0;r<D;r++)for(int i=0;i<Q;i++)z[r]+=E[i][r]*kv.first.a[i];for(size_t m=0;m<aa.size();m++){double v=fac(4);for(int r=0;r<D;r++){v/=fac(aa[m][r]);if(aa[m][r])v*=pow(z[r],aa[m][r]);}for(int g=0;g<3;g++)T[m][g]+=kv.second.c[g]*v;}}
  for(size_t m=0;m<aa.size();m++){cout<<ss[0]<<ss[1]<<ss[2];for(int r=0;r<D;r++)cout<<","<<aa[m][r];cout<<" "<<T[m][0]<<" "<<T[m][1]<<" "<<T[m][2]<<"\n";}
 }
}
