#!/usr/bin/env python3
import os
import json, math, pathlib, sys
import numpy as np
from scipy.optimize import root
from mpmath import iv, mp
mp.dps=80; iv.dps=70
RROOT=pathlib.Path(os.environ.get('R7P_ROOT','/mnt/data/r7p_source/unpacked/fin_rank7_followup'))
cert=json.load(open(RROOT/'certificates/R7P-036_stationary_index2_witness.json'))

def ratmp(s):
    a,b=s.split('/') if '/' in s else (s,'1'); return mp.mpf(a)/mp.mpf(b)
def pbox(key):
    a,b=cert['spectral_inputs'][key]; return iv.mpf([str(ratmp(a)),str(ratmp(b))])
L3,L4,L5,L6=[pbox('lambda'+str(k)) for k in (3,4,5,6)]
# midpoint floats for navigation
lm=[float((mp.mpf(x.a)+mp.mpf(x.b))/2) for x in (L3,L4,L5,L6)]
l3,l4,l5,l6=lm

def xy_np(J,K):
    q=np.exp(-2*K); C=np.cosh(J); S=np.sinh(J); D=C+q
    return S/D,(C-q)/D

def fun_np(z):
    J,K,g=z; x,y=xy_np(J,K)
    delta=(1/g-l4/12)*(1/g-l5/12)-l4*l5*x*x/144
    return np.array([J-g*l3*x/6,K-g*l6*y/12,delta])
sol=root(fun_np,[0.0384,0.1853,5.17184],tol=1e-12)
x0=sol.x
if np.linalg.norm(fun_np(x0))>1e-10: raise SystemExit('navigation root failed')
# numerical Jacobian for preconditioner
def jac_np(z):
    J,K,g=z; q=np.exp(-2*K); C=np.cosh(J); S=np.sinh(J); D=C+q
    x=S/D; y=(C-q)/D
    xJ=(1+C*q)/(D*D); xK=2*q*S/(D*D); yJ=xK; yK=4*q*C/(D*D)
    return np.array([[1-g*l3*xJ/6,-g*l3*xK/6,-l3*x/6],
                     [-g*l6*yJ/12,1-g*l6*yK/12,-l6*y/12],
                     [-l4*l5*x*xJ/72,-l4*l5*x*xK/72,-(2/g-l4/12-l5/12)/(g*g)]])
R=np.linalg.inv(jac_np(x0))
# choose tight box
r=np.array([2e-7,2e-7,2e-7])
X=[iv.mpf([str(x0[i]-r[i]),str(x0[i]+r[i])]) for i in range(3)]
X0=[iv.mpf(str(x0[i])) for i in range(3)]

def xy_iv(J,K):
    q=iv.exp(-2*K); eJ=iv.exp(J); emJ=iv.exp(-J); C=(eJ+emJ)/2; S=(eJ-emJ)/2; D=C+q
    x=S/D; y=(C-q)/D
    xJ=(1+C*q)/(D*D); xK=2*q*S/(D*D); yJ=xK; yK=4*q*C/(D*D)
    return x,y,xJ,xK,yJ,yK

def F_iv(z):
    J,K,g=z; x,y,*_=xy_iv(J,K)
    return [J-g*L3*x/6,
            K-g*L6*y/12,
            (1/g-L4/12)*(1/g-L5/12)-L4*L5*x*x/144]
def J_iv(z):
    J,K,g=z; x,y,xJ,xK,yJ,yK=xy_iv(J,K)
    return [[1-g*L3*xJ/6,-g*L3*xK/6,-L3*x/6],
            [-g*L6*yJ/12,1-g*L6*yK/12,-L6*y/12],
            [-L4*L5*x*xJ/72,-L4*L5*x*xK/72,-(2/g-L4/12-L5/12)/(g*g)]]
F0=F_iv(X0); JX=J_iv(X)
# Krawczyk intervals
Kraw=[]
for i in range(3):
    base=X0[i]-sum(iv.mpf(str(R[i,j]))*F0[j] for j in range(3))
    corr=iv.mpf(0)
    for j in range(3):
        coeff=(iv.mpf(1) if i==j else iv.mpf(0))-sum(iv.mpf(str(R[i,k]))*JX[k][j] for k in range(3))
        corr += coeff*(X[j]-X0[j])
    Kraw.append(base+corr)

def flo(x): return float(x.a)
def fhi(x): return float(x.b)
inclusion=all(flo(Kraw[i])>flo(X[i]) and fhi(Kraw[i])<fhi(X[i]) for i in range(3))
# transversality derivative of delta along branch using implicit J,K derivatives wrt g
A2=jac_np(x0)[:2,:2]; bg=jac_np(x0)[:2,2]; dzdg=-np.linalg.solve(A2,bg)
row3=jac_np(x0)[2]; ddelta_dg=float(row3[:2]@dzdg+row3[2])
# rigorous interval version on X: invert the 2x2 branch Jacobian explicitly
A00,A01=JX[0][0],JX[0][1]; A10,A11=JX[1][0],JX[1][1]
b0,b1=JX[0][2],JX[1][2]
detA=A00*A11-A01*A10
# q=-A^{-1} b
qJ=-(A11*b0-A01*b1)/detA
qK=-(-A10*b0+A00*b1)/detA
ddelta_iv=JX[2][0]*qJ+JX[2][1]*qK+JX[2][2]
# symmetry: stabilizer generated by T4 and reflection. Critical complex coordinate gets omega under T4.
out={
 'task':'MP7-039',
 'scientific_state':'PROVED_INTERVAL_ASSISTED_LOCAL_TRANSVERSE_CROSSING' if inclusion else 'NUMERICAL_EVIDENCE',
 'navigation_root':x0.tolist(),
 'navigation_residual_norm':float(np.linalg.norm(fun_np(x0))),
 'root_box':[[float(x0[i]-r[i]),float(x0[i]+r[i])] for i in range(3)],
 'krawczyk_image':[[flo(q),fhi(q)] for q in Kraw],
 'strict_inclusion':inclusion,
 'spectral_parameter_scope':'uniform over accepted outward lambda3,lambda4,lambda5,lambda6 intervals',
 'delta45_definition':'(1/g-lambda4/12)(1/g-lambda5/12)-lambda4 lambda5 x^2/144',
 'branch_total_derivative_delta_midpoint':ddelta_dg,
 'branch_total_derivative_delta_interval':[flo(ddelta_iv),fhi(ddelta_iv)],
 'branch_transverse_crossing_is_simple':flo(ddelta_iv)>0,
 'critical_dimension':2,
 'critical_blocks':'one zero eigenvalue in each symmetry-related (4cos,5cos) and (4sin,5sin) block',
 'isotropy':'base period-four reflection-even field has stabilizer <T^4,R> ~= D3 (order 6)',
 'critical_representation':'real 2D standard D3 representation; T^4 acts as rotation by 2pi/3 and reflection acts by conjugation',
 'cubic_invariant':'Re(z^3) is D3-invariant and hence symmetry-allowed',
 'nonconclusion':'This is not a generic one-dimensional pitchfork and no nonlinear branch classification is claimed without cubic/quartic coefficient analysis.'
}
print(json.dumps(out,indent=2))
