#!/usr/bin/env python3
"""P2793/S1743: Z2^4 four-generator Cayley subclass exhaustion certificate.

P2792 exhausted the C16 two-jump circulant subclass.  This next bounded step
exhausts a different named 16-node 4-regular subclass: simple undirected Cayley
graphs on the elementary abelian group Z_2^4 generated by exactly four distinct
nonzero involutions.  The graph is connected exactly when the four generators
span GF(2)^4.

This is deliberately not a full connected 16-node 4-regular generator.  It is a
finite group-theoretic subclass certificate with exact quotienting, provenance,
charpoly, automorphism, and cross-matching against the current local/eight-class
representatives.
"""
from __future__ import annotations

import hashlib
import json
import math
from itertools import combinations
from pathlib import Path
from typing import Any

from p2468_s1418_strict_pointwise_interval_decimal_chunked_opposite_tail_replay_ledger_certificate import REPO, ROOT, rel
from p2506_s1456_strict_damping_rg_minimum_roughness_selector_candidate_certificate import append_once
from p2786_s1736_graph6_provenance_toolchain_gate import graph6_decode, graph6_encode
from p2787_s1737_small_canonical_generator_pipeline_audit import isomorphic
from p2788_s1738_complement_duality_exact_spectral_certificate import charpoly_expr, normalize_edges
from p2789_s1739_orbit_stabilizer_exact_quotient_certificate import automorphism_count

GEN = ROOT / "generated"
P2786 = GEN / "p2786_s1736_graph6_provenance_toolchain_gate.json"
P2791 = GEN / "p2791_s1741_eight_class_orbit_lower_bound_certificate.json"
P2792 = GEN / "p2792_s1742_c16_two_jump_circulant_subclass_exhaustion_certificate.json"
OUT = GEN / "p2793_s1743_z2_4_four_generator_cayley_subclass_exhaustion_certificate.json"
MD = GEN / "p2793_s1743_z2_4_four_generator_cayley_subclass_exhaustion_certificate.md"
STRICT_EQUATION_SHEET = ROOT / "STRICT_EQUATION_SHEET_KERNEL_TO_LTOTAL_CURRENT.md"
STRICT_LAGRANGIAN_DRAFT = ROOT / "STRICT_KERNEL_LAGRANGIAN_AND_EOM_DRAFT.md"
AGENTS = REPO / "AGENTS.md"

N = 16
NEGATIVE_EXPORT_FLAGS = [
    "canonical_16node_generator_certified",
    "canonical_geometry_source_exported",
    "strict_spectral_source_law_exported",
    "global_full_spectrum_geometry_theorem_exported",
    "kernel_geometry_closure_exported",
    "kernel_fully_expresses_nadsoliton_characteristics",
    "role_bearing_ltotal_promoted",
    "bridge_closure_exported",
    "selector_closure_exported",
    "toe_closure_exported",
]


def sha(path: Path) -> str | None:
    return hashlib.sha256(path.read_bytes()).hexdigest() if path.exists() else None


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else {"missing": True, "path": rel(path)}


def gf2_rank(vectors: tuple[int, ...]) -> int:
    basis = [0, 0, 0, 0]
    rank = 0
    for value in vectors:
        x = value
        while x:
            pivot = x.bit_length() - 1
            if basis[pivot]:
                x ^= basis[pivot]
            else:
                basis[pivot] = x
                rank += 1
                break
    return rank


def cayley_edges(generators: tuple[int, ...]) -> tuple[tuple[int, int], ...]:
    edges = set()
    for vertex in range(N):
        for generator in generators:
            edges.add(tuple(sorted((vertex, vertex ^ generator))))
    return normalize_edges(edges)


def local_representatives(p2786: dict[str, Any]) -> list[dict[str, Any]]:
    return [{
        "representative": row["representative"],
        "edges": normalize_edges(graph6_decode(row["graph6"])),
    } for row in p2786.get("graph6_provenance_witness", {}).get("provenance_rows", [])]


def eight_class_labels(p2791: dict[str, Any]) -> set[str]:
    rows = p2791.get("orbit_lower_bound_witness", {}).get("representative_rows", [])
    return {row["label"] for row in rows}


def quotient_z2_4_cayley() -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    raw_rows = []
    classes: list[dict[str, Any]] = []
    for gens in combinations(range(1, N), 4):
        rank = gf2_rank(gens)
        edges = cayley_edges(gens)
        row = {"generators": list(gens), "gf2_rank": rank, "connected": rank == 4, "edge_count": len(edges), "edges": edges}
        raw_rows.append(row)
        if rank != 4:
            continue
        for klass in classes:
            if isomorphic(edges, klass["representative_edges"], N):
                klass["generator_set_members"].append(list(gens))
                break
        else:
            classes.append({
                "class_index": len(classes),
                "representative_generators": list(gens),
                "representative_edges": edges,
                "generator_set_members": [list(gens)],
            })
    return raw_rows, classes


def z2_4_subclass_witness(p2786: dict[str, Any], p2791: dict[str, Any]) -> dict[str, Any]:
    raw_rows, classes = quotient_z2_4_cayley()
    locals_ = local_representatives(p2786)
    eight_labels = eight_class_labels(p2791)
    class_rows = []
    for klass in classes:
        edges = klass["representative_edges"]
        matching_locals = [row["representative"] for row in locals_ if isomorphic(edges, row["edges"], N)]
        matching_eight = [label for label in matching_locals if label in eight_labels]
        aut_size = automorphism_count(edges, N)
        graph6 = graph6_encode(list(edges), n=N)
        class_rows.append({
            "class_index": klass["class_index"],
            "representative_generators": klass["representative_generators"],
            "generator_set_member_count": len(klass["generator_set_members"]),
            "matching_p2786_local_representatives": matching_locals,
            "matching_p2791_eight_class_representatives": matching_eight,
            "represented_in_p2786_local_set": bool(matching_locals),
            "represented_in_p2791_eight_class_set": bool(matching_eight),
            "edge_count": len(edges),
            "automorphism_group_size": aut_size,
            "orbit_size_by_orbit_stabilizer": math.factorial(N) // aut_size,
            "graph6": graph6,
            "graph6_sha256": hashlib.sha256(graph6.encode("ascii")).hexdigest(),
            "adjacency_charpoly_coefficients": [int(c) for c in charpoly_expr(edges, N, "adjacency").all_coeffs()],
        })
    pair_rows = []
    for left_index, left in enumerate(classes):
        for right_index in range(left_index + 1, len(classes)):
            right = classes[right_index]
            pair_rows.append({
                "left_class_index": left["class_index"],
                "right_class_index": right["class_index"],
                "isomorphic": isomorphic(left["representative_edges"], right["representative_edges"], N),
            })
    connected_rows = [row for row in raw_rows if row["connected"]]
    disconnected_rows = [row for row in raw_rows if not row["connected"]]
    return {
        "source_class": "All simple undirected Cayley graphs Cay(Z2^4,S) where S has exactly four distinct nonzero involutions.",
        "raw_generator_set_count": len(raw_rows),
        "connected_generator_set_count": len(connected_rows),
        "disconnected_generator_set_count": len(disconnected_rows),
        "connected_isomorphism_class_count": len(classes),
        "pair_count_after_quotient": len(pair_rows),
        "class_rows": class_rows,
        "rank_histogram": {str(rank): sum(1 for row in raw_rows if row["gf2_rank"] == rank) for rank in range(1, 5)},
        "pairwise_class_rows": pair_rows,
        "all_connected_classes_pairwise_nonisomorphic": all(not row["isomorphic"] for row in pair_rows),
        "all_connected_classes_represented_in_p2786_local_set": all(row["represented_in_p2786_local_set"] for row in class_rows),
        "all_connected_classes_represented_in_p2791_eight_class_set": all(row["represented_in_p2791_eight_class_set"] for row in class_rows),
        "finite_certificate_statement": "The complete Z2^4 four-generator Cayley subclass has 1365 raw generator sets, 840 connected rank-4 sets, 1 connected isomorphism class, and that class is already represented among current local/eight-class witnesses.",
    }


def acceptance_matrix(witness: dict[str, Any], p2786: dict[str, Any], p2791: dict[str, Any], p2792: dict[str, Any]) -> dict[str, Any]:
    facts = {
        "p2786_graph6_gate_present": p2786.get("status") == "P2786_GRAPH6_PROVENANCE_TOOLCHAIN_GATE_NO_CLOSURE",
        "p2791_lower_bound_present": p2791.get("status") == "P2791_EIGHT_CLASS_ORBIT_LOWER_BOUND_CERTIFICATE_NO_CLOSURE",
        "p2792_circulant_subclass_present": p2792.get("status") == "P2792_C16_TWO_JUMP_CIRCULANT_SUBCLASS_EXHAUSTION_CERTIFICATE_NO_CLOSURE",
        "all_1365_generator_sets_enumerated": witness["raw_generator_set_count"] == 1365,
        "rank_filter_checked": witness["connected_generator_set_count"] == 840 and witness["disconnected_generator_set_count"] == 525,
        "one_connected_iso_class_found": witness["connected_isomorphism_class_count"] == 1,
        "all_class_pairs_checked_nonisomorphic": witness["pair_count_after_quotient"] == 0 and witness["all_connected_classes_pairwise_nonisomorphic"],
        "class_present_in_current_witness_sets": witness["all_connected_classes_represented_in_p2786_local_set"] and witness["all_connected_classes_represented_in_p2791_eight_class_set"],
        "canonical_16node_generator_certified": False,
        "strict_nadsoliton_spectral_source_law_exported": False,
        "kernel_or_ltotal_variational_coupling_exported": False,
    }
    return {
        "facts": facts,
        "accepted_as_complete_z2_4_four_generator_cayley_subclass_certificate": all(facts[key] for key in [
            "p2786_graph6_gate_present",
            "p2791_lower_bound_present",
            "p2792_circulant_subclass_present",
            "all_1365_generator_sets_enumerated",
            "rank_filter_checked",
            "one_connected_iso_class_found",
            "all_class_pairs_checked_nonisomorphic",
            "class_present_in_current_witness_sets",
        ]),
        "accepted_as_full_16node_canonical_generator_certificate": False,
        "accepted_as_strict_spectral_source_law": False,
        "accepted_as_canonical_nadsoliton_geometry_source": False,
        "accepted_as_ltotal_or_toe_promotion": False,
        "missing_criteria": [key for key, value in facts.items() if not value],
        "blocker": "The Z2^4 four-generator Cayley subclass is fully enumerated, but it collapses to one known connected class and remains only a named-subclass certificate; it exports neither a full connected 16-node 4-regular generator nor a strict K/L_total spectral source law.",
    }


def write_markdown(payload: dict[str, Any]) -> None:
    w = payload["z2_4_cayley_subclass_witness"]
    lines = [
        "# P2793/S1743 Z2^4 four-generator Cayley subclass exhaustion certificate",
        "",
        f"Status: `{payload['status']}`",
        "",
        "## Exact Z2^4 Cayley subclass result",
        f"- raw_generator_set_count={w['raw_generator_set_count']}",
        f"- connected_generator_set_count={w['connected_generator_set_count']}",
        f"- disconnected_generator_set_count={w['disconnected_generator_set_count']}",
        f"- rank_histogram={w['rank_histogram']}",
        f"- connected_isomorphism_class_count={w['connected_isomorphism_class_count']}",
        f"- pair_count_after_quotient={w['pair_count_after_quotient']}",
        f"- all_connected_classes_pairwise_nonisomorphic={w['all_connected_classes_pairwise_nonisomorphic']}",
        f"- all_connected_classes_represented_in_p2786_local_set={w['all_connected_classes_represented_in_p2786_local_set']}",
        f"- all_connected_classes_represented_in_p2791_eight_class_set={w['all_connected_classes_represented_in_p2791_eight_class_set']}",
        "",
        "## Decision",
        payload["decision"]["reason"],
        "",
        "## Recommendation",
        payload["decision"]["next_honest_step"],
    ]
    MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> dict[str, Any]:
    GEN.mkdir(exist_ok=True)
    p2786 = read_json(P2786)
    p2791 = read_json(P2791)
    p2792 = read_json(P2792)
    witness = z2_4_subclass_witness(p2786, p2791)
    acceptance = acceptance_matrix(witness, p2786, p2791, p2792)
    payload = {
        "status": "P2793_Z2_4_FOUR_GENERATOR_CAYLEY_SUBCLASS_EXHAUSTION_CERTIFICATE_NO_CLOSURE",
        "input_hashes": {"P2786": sha(P2786), "P2791": sha(P2791), "P2792": sha(P2792)},
        "input_statuses": {"P2786": p2786.get("status"), "P2791": p2791.get("status"), "P2792": p2792.get("status")},
        "audited_question": "Can a second named 16-node 4-regular group-generated subclass be fully exhausted without claiming full-class or source-law closure?",
        "z2_4_cayley_subclass_witness": witness,
        "acceptance_matrix": acceptance,
        "decision": {
            "negative_export_flags": {flag: False for flag in NEGATIVE_EXPORT_FLAGS},
            "reason": acceptance["blocker"],
            "next_honest_step": "Use P2793 only as a complete named-subclass certificate for the Z2^4 four-generator Cayley lane.  The next honest move remains exactly one of: supply/import an actual certified full connected 16-node 4-regular generator artifact/toolchain with graph6/hash provenance and run full exact quotient/charpoly/complement/orbit auditing; or export a strict nadsoliton spectral action/source law fixing the admissible class, target spectrum, and K/L_total coupling before testing.  Otherwise preserve the P2697-P2793 no-canonical-geometry/no-closure certificate.",
        },
    }
    OUT.write_text(json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")
    write_markdown(payload)
    append_once(STRICT_EQUATION_SHEET, "P2793/S1743 Z2^4 four-generator Cayley subclass exhaustion certificate", "## P2793/S1743 Z2^4 four-generator Cayley subclass exhaustion certificate\n\n`P2793/S1743` gives a complete enumeration of a second named 16-node 4-regular subclass: simple undirected Cayley graphs on `Z_2^4` generated by exactly four distinct nonzero involutions.  The audit enumerates 1365 generator sets, filters 840 connected rank-4 cases, quotients them to 1 connected isomorphism class, and verifies that this class is already represented in the current P2786/P2791 witness sets.  This is a complete named-subclass certificate only, not a full connected 16-node 4-regular generator, not a strict spectral source law, and not a `K`/`L_total` variational coupling.\n")
    append_once(STRICT_LAGRANGIAN_DRAFT, "P2793/S1743 Z2^4 Cayley-subclass Ltotal guard", "## P2793/S1743 Z2^4 Cayley-subclass Ltotal guard\n\n`P2793/S1743` adds no variational source term.  Complete enumeration of the named `Z_2^4` four-generator Cayley subclass strengthens finite graph bookkeeping and proves that this group-generated lane collapses to a known class, but a named-subclass result is not a sourced nonproxy `K`/`L_total` spectral action, not a canonical geometry theorem, and not a full 16-node generator.\n")
    append_once(AGENTS, "Current Z2^4 four-generator Cayley subclass guardrail (P2793/S1743, 2026-06-16)", "## Current Z2^4 four-generator Cayley subclass guardrail (P2793/S1743, 2026-06-16)\n\n- P2793 fully enumerates the named `Z_2^4` four-generator Cayley 4-regular subclass: 1365 raw generator sets, 840 connected rank-4 cases, 1 connected isomorphism class, and that class is already represented in the current P2786/P2791 witness sets.\n- This is a complete named-subclass certificate only; it is not the required full connected 16-node 4-regular generator/toolchain and does not source geometry from `K`/`L_total`.\n- Do not promote the `Z_2^4` Cayley-subclass exhaustion result to canonical geometry, strict spectral source law, selector closure, kernel full-expression, role-bearing `L_total`, bridge closure, role transfer, or ToE closure.  A next admissible move must supply an actual certified full 16-node generator artifact/toolchain or export a strict spectral action/source law before testing.\n")
    return payload


if __name__ == "__main__":
    main()
