#!/usr/bin/env python3
"""P2792/S1742: C16 two-jump circulant subclass exhaustion certificate.

P2791 gave an eight-orbit lower bound, but not a full generator.  This bounded
follow-up does not pretend to enumerate all connected 16-node 4-regular graphs.
Instead, it gives a complete proof-grade enumeration of one named subclass:
undirected circulant graphs on Z_16 generated by exactly two non-antipodal jump
pairs {±a, ±b}, 1 <= a < b <= 7.

The script enumerates all 21 jump pairs, filters the connected 4-regular cases,
quotients them by exact graph isomorphism, and checks whether the quotient
classes are already represented among the P2786 seven local representatives.
"""
from __future__ import annotations

import hashlib
import json
import math
from itertools import combinations
from pathlib import Path
from typing import Any

from p2468_s1418_strict_pointwise_interval_decimal_chunked_opposite_tail_replay_ledger_certificate import REPO, ROOT, rel
from p2506_s1456_strict_damping_rg_minimum_roughness_selector_candidate_certificate import append_once
from p2786_s1736_graph6_provenance_toolchain_gate import graph6_decode, graph6_encode
from p2787_s1737_small_canonical_generator_pipeline_audit import isomorphic
from p2788_s1738_complement_duality_exact_spectral_certificate import charpoly_expr, normalize_edges
from p2789_s1739_orbit_stabilizer_exact_quotient_certificate import automorphism_count

GEN = ROOT / "generated"
P2786 = GEN / "p2786_s1736_graph6_provenance_toolchain_gate.json"
P2791 = GEN / "p2791_s1741_eight_class_orbit_lower_bound_certificate.json"
OUT = GEN / "p2792_s1742_c16_two_jump_circulant_subclass_exhaustion_certificate.json"
MD = GEN / "p2792_s1742_c16_two_jump_circulant_subclass_exhaustion_certificate.md"
STRICT_EQUATION_SHEET = ROOT / "STRICT_EQUATION_SHEET_KERNEL_TO_LTOTAL_CURRENT.md"
STRICT_LAGRANGIAN_DRAFT = ROOT / "STRICT_KERNEL_LAGRANGIAN_AND_EOM_DRAFT.md"
AGENTS = REPO / "AGENTS.md"

N = 16
NEGATIVE_EXPORT_FLAGS = [
    "canonical_16node_generator_certified",
    "canonical_geometry_source_exported",
    "strict_spectral_source_law_exported",
    "global_full_spectrum_geometry_theorem_exported",
    "kernel_geometry_closure_exported",
    "kernel_fully_expresses_nadsoliton_characteristics",
    "role_bearing_ltotal_promoted",
    "bridge_closure_exported",
    "selector_closure_exported",
    "toe_closure_exported",
]


def sha(path: Path) -> str | None:
    return hashlib.sha256(path.read_bytes()).hexdigest() if path.exists() else None


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else {"missing": True, "path": rel(path)}


def circulant_edges(jumps: tuple[int, int], n: int = N) -> tuple[tuple[int, int], ...]:
    edges = set()
    for vertex in range(n):
        for jump in jumps:
            edges.add(tuple(sorted((vertex, (vertex + jump) % n))))
            edges.add(tuple(sorted((vertex, (vertex - jump) % n))))
    return normalize_edges(edges)


def connected(edges: tuple[tuple[int, int], ...], n: int = N) -> bool:
    adj = [set() for _ in range(n)]
    for a, b in edges:
        adj[a].add(b)
        adj[b].add(a)
    seen = {0}
    stack = [0]
    while stack:
        node = stack.pop()
        for nxt in adj[node] - seen:
            seen.add(nxt)
            stack.append(nxt)
    return len(seen) == n


def degree_sequence(edges: tuple[tuple[int, int], ...], n: int = N) -> list[int]:
    degree = [0] * n
    for a, b in edges:
        degree[a] += 1
        degree[b] += 1
    return degree


def quotient_connected_circulants() -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    raw_rows = []
    classes: list[dict[str, Any]] = []
    for jumps in combinations(range(1, 8), 2):
        edges = circulant_edges(jumps)
        row = {
            "jumps": list(jumps),
            "edge_count": len(edges),
            "degree_sequence": degree_sequence(edges),
            "connected": connected(edges),
            "edges": edges,
        }
        raw_rows.append(row)
        if not row["connected"]:
            continue
        for klass in classes:
            if isomorphic(edges, klass["representative_edges"], N):
                klass["jump_pair_members"].append(list(jumps))
                break
        else:
            classes.append({
                "class_index": len(classes),
                "representative_jumps": list(jumps),
                "representative_edges": edges,
                "jump_pair_members": [list(jumps)],
            })
    return raw_rows, classes


def local_representatives(p2786: dict[str, Any]) -> list[dict[str, Any]]:
    return [{
        "representative": row["representative"],
        "edges": normalize_edges(graph6_decode(row["graph6"])),
    } for row in p2786.get("graph6_provenance_witness", {}).get("provenance_rows", [])]


def circulant_subclass_witness(p2786: dict[str, Any]) -> dict[str, Any]:
    raw_rows, classes = quotient_connected_circulants()
    locals_ = local_representatives(p2786)
    class_rows = []
    for klass in classes:
        matching_locals = [row["representative"] for row in locals_ if isomorphic(klass["representative_edges"], row["edges"], N)]
        aut_size = automorphism_count(klass["representative_edges"], N)
        graph6 = graph6_encode(list(klass["representative_edges"]), n=N)
        class_rows.append({
            "class_index": klass["class_index"],
            "representative_jumps": klass["representative_jumps"],
            "jump_pair_members": klass["jump_pair_members"],
            "jump_pair_member_count": len(klass["jump_pair_members"]),
            "matching_p2786_local_representatives": matching_locals,
            "represented_in_p2786_local_set": bool(matching_locals),
            "edge_count": len(klass["representative_edges"]),
            "automorphism_group_size": aut_size,
            "orbit_size_by_orbit_stabilizer": math.factorial(N) // aut_size,
            "graph6": graph6,
            "graph6_sha256": hashlib.sha256(graph6.encode("ascii")).hexdigest(),
            "adjacency_charpoly_coefficients": [int(c) for c in charpoly_expr(klass["representative_edges"], N, "adjacency").all_coeffs()],
        })
    pair_rows = []
    for left_index, left in enumerate(classes):
        for right_index in range(left_index + 1, len(classes)):
            right = classes[right_index]
            pair_rows.append({
                "left_class_index": left["class_index"],
                "right_class_index": right["class_index"],
                "isomorphic": isomorphic(left["representative_edges"], right["representative_edges"], N),
            })
    connected_rows = [row for row in raw_rows if row["connected"]]
    disconnected_rows = [row for row in raw_rows if not row["connected"]]
    return {
        "source_class": "All undirected C16 two-jump 4-regular circulants generated by {±a, ±b}, 1 <= a < b <= 7.",
        "raw_jump_pair_count": len(raw_rows),
        "connected_jump_pair_count": len(connected_rows),
        "disconnected_jump_pair_count": len(disconnected_rows),
        "connected_isomorphism_class_count": len(classes),
        "pair_count_after_quotient": len(pair_rows),
        "raw_jump_pair_rows": [{key: value for key, value in row.items() if key != "edges"} for row in raw_rows],
        "class_rows": class_rows,
        "pairwise_class_rows": pair_rows,
        "all_connected_classes_pairwise_nonisomorphic": all(not row["isomorphic"] for row in pair_rows),
        "all_connected_classes_represented_in_p2786_local_set": all(row["represented_in_p2786_local_set"] for row in class_rows),
        "finite_certificate_statement": "The complete C16 two-jump circulant subclass has 21 raw jump pairs, 18 connected cases, 5 isomorphism classes, and all 5 classes are already represented among the P2786 seven local representatives.",
    }


def acceptance_matrix(witness: dict[str, Any], p2786: dict[str, Any], p2791: dict[str, Any]) -> dict[str, Any]:
    facts = {
        "p2786_graph6_gate_present": p2786.get("status") == "P2786_GRAPH6_PROVENANCE_TOOLCHAIN_GATE_NO_CLOSURE",
        "p2791_lower_bound_present": p2791.get("status") == "P2791_EIGHT_CLASS_ORBIT_LOWER_BOUND_CERTIFICATE_NO_CLOSURE",
        "all_21_two_jump_pairs_enumerated": witness["raw_jump_pair_count"] == 21,
        "connected_cases_filtered": witness["connected_jump_pair_count"] == 18 and witness["disconnected_jump_pair_count"] == 3,
        "five_connected_iso_classes_found": witness["connected_isomorphism_class_count"] == 5,
        "all_10_class_pairs_checked_nonisomorphic": witness["pair_count_after_quotient"] == 10 and witness["all_connected_classes_pairwise_nonisomorphic"],
        "all_five_classes_present_in_p2786_local_set": witness["all_connected_classes_represented_in_p2786_local_set"],
        "canonical_16node_generator_certified": False,
        "strict_nadsoliton_spectral_source_law_exported": False,
        "kernel_or_ltotal_variational_coupling_exported": False,
    }
    return {
        "facts": facts,
        "accepted_as_complete_c16_two_jump_circulant_subclass_certificate": all(facts[key] for key in [
            "p2786_graph6_gate_present",
            "p2791_lower_bound_present",
            "all_21_two_jump_pairs_enumerated",
            "connected_cases_filtered",
            "five_connected_iso_classes_found",
            "all_10_class_pairs_checked_nonisomorphic",
            "all_five_classes_present_in_p2786_local_set",
        ]),
        "accepted_as_full_16node_canonical_generator_certificate": False,
        "accepted_as_strict_spectral_source_law": False,
        "accepted_as_canonical_nadsoliton_geometry_source": False,
        "accepted_as_ltotal_or_toe_promotion": False,
        "missing_criteria": [key for key, value in facts.items() if not value],
        "blocker": "The C16 two-jump circulant subclass is fully enumerated and exhausted inside the P2786 local set, but this named subclass is only a small slice of connected 16-node 4-regular graphs and exports no strict K/L_total spectral source law.",
    }


def write_markdown(payload: dict[str, Any]) -> None:
    w = payload["circulant_subclass_witness"]
    lines = [
        "# P2792/S1742 C16 two-jump circulant subclass exhaustion certificate",
        "",
        f"Status: `{payload['status']}`",
        "",
        "## Exact C16 two-jump circulant result",
        f"- raw_jump_pair_count={w['raw_jump_pair_count']}",
        f"- connected_jump_pair_count={w['connected_jump_pair_count']}",
        f"- disconnected_jump_pair_count={w['disconnected_jump_pair_count']}",
        f"- connected_isomorphism_class_count={w['connected_isomorphism_class_count']}",
        f"- pair_count_after_quotient={w['pair_count_after_quotient']}",
        f"- all_connected_classes_pairwise_nonisomorphic={w['all_connected_classes_pairwise_nonisomorphic']}",
        f"- all_connected_classes_represented_in_p2786_local_set={w['all_connected_classes_represented_in_p2786_local_set']}",
        "",
        "## Decision",
        payload["decision"]["reason"],
        "",
        "## Recommendation",
        payload["decision"]["next_honest_step"],
    ]
    MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> dict[str, Any]:
    GEN.mkdir(exist_ok=True)
    p2786 = read_json(P2786)
    p2791 = read_json(P2791)
    witness = circulant_subclass_witness(p2786)
    acceptance = acceptance_matrix(witness, p2786, p2791)
    payload = {
        "status": "P2792_C16_TWO_JUMP_CIRCULANT_SUBCLASS_EXHAUSTION_CERTIFICATE_NO_CLOSURE",
        "input_hashes": {"P2786": sha(P2786), "P2791": sha(P2791)},
        "input_statuses": {"P2786": p2786.get("status"), "P2791": p2791.get("status")},
        "audited_question": "Can one named 16-node 4-regular subclass be fully generated and matched against the local representatives without claiming full-class closure?",
        "circulant_subclass_witness": witness,
        "acceptance_matrix": acceptance,
        "decision": {
            "negative_export_flags": {flag: False for flag in NEGATIVE_EXPORT_FLAGS},
            "reason": acceptance["blocker"],
            "next_honest_step": "Use P2792 only as a complete named-subclass certificate.  The next honest move remains exactly one of: supply/import an actual certified full connected 16-node 4-regular generator artifact/toolchain with graph6/hash provenance and run full exact quotient/charpoly/complement/orbit auditing; or export a strict nadsoliton spectral action/source law fixing the admissible class, target spectrum, and K/L_total coupling before testing.  Otherwise preserve the P2697-P2792 no-canonical-geometry/no-closure certificate.",
        },
    }
    OUT.write_text(json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")
    write_markdown(payload)
    append_once(STRICT_EQUATION_SHEET, "P2792/S1742 C16 two-jump circulant subclass exhaustion certificate", "## P2792/S1742 C16 two-jump circulant subclass exhaustion certificate\n\n`P2792/S1742` gives a complete enumeration of one named 16-node 4-regular subclass: undirected `C16` circulants generated by two non-antipodal jump pairs `{±a, ±b}` with `1 <= a < b <= 7`.  The audit finds 21 raw jump pairs, 18 connected cases, 5 isomorphism classes, 10 quotient pairs, and all 5 connected classes are represented inside the P2786 seven local representatives.  This is a complete subclass certificate only, not a full connected 16-node 4-regular generator, not a strict spectral source law, and not a `K`/`L_total` variational coupling.\n")
    append_once(STRICT_LAGRANGIAN_DRAFT, "P2792/S1742 C16 circulant-subclass Ltotal guard", "## P2792/S1742 C16 circulant-subclass Ltotal guard\n\n`P2792/S1742` adds no variational source term.  Complete enumeration of the named `C16` two-jump circulant subclass strengthens finite graph bookkeeping, but a named-subclass generator is not a sourced nonproxy `K`/`L_total` spectral action, not a canonical geometry theorem, and not a full 16-node generator.\n")
    append_once(AGENTS, "Current C16 two-jump circulant subclass guardrail (P2792/S1742, 2026-06-16)", "## Current C16 two-jump circulant subclass guardrail (P2792/S1742, 2026-06-16)\n\n- P2792 fully enumerates the named `C16` two-jump circulant 4-regular subclass: 21 raw jump pairs, 18 connected cases, 5 isomorphism classes, and all 5 connected classes represented among the P2786 seven local representatives.\n- This is a complete named-subclass certificate only; it is not the required full connected 16-node 4-regular generator/toolchain and does not source geometry from `K`/`L_total`.\n- Do not promote the circulant-subclass exhaustion result to canonical geometry, strict spectral source law, selector closure, kernel full-expression, role-bearing `L_total`, bridge closure, role transfer, or ToE closure.  A next admissible move must supply an actual certified full 16-node generator artifact/toolchain or export a strict spectral action/source law before testing.\n")
    return payload


if __name__ == "__main__":
    main()
