#!/usr/bin/env python3
"""P2797/S1747: external full-count gap certificate.

P2796 established that the repository does not currently contain a certified full
connected 16-node 4-regular generator artifact/toolchain.  P2797 adds a more
quantitative target-gap certificate by importing a narrowly scoped external count:
Markus Meringer's Regular Graphs page reports 8,037,418 connected 4-regular
simple graphs on 16 vertices (up to isomorphism; generated by GENREG lineage).

This script does not import the graph list and therefore is not a full generator.
It records the external target count, compares it to the current P2791 eight-class
witness set and P2795 named-subclass union, and computes the remaining class-count
gap.  The result is a proof-obligation sizing certificate, not closure.
"""
from __future__ import annotations

import hashlib
import json
from fractions import Fraction
from pathlib import Path
from typing import Any

from p2468_s1418_strict_pointwise_interval_decimal_chunked_opposite_tail_replay_ledger_certificate import REPO, ROOT, rel
from p2506_s1456_strict_damping_rg_minimum_roughness_selector_candidate_certificate import append_once

GEN = ROOT / "generated"
P2791 = GEN / "p2791_s1741_eight_class_orbit_lower_bound_certificate.json"
P2795 = GEN / "p2795_s1745_post_subclass_saturation_no_new_class_frontier_certificate.json"
P2796 = GEN / "p2796_s1746_full_generator_artifact_absence_provenance_gate.json"
OUT = GEN / "p2797_s1747_external_full_count_gap_certificate.json"
MD = GEN / "p2797_s1747_external_full_count_gap_certificate.md"
STRICT_EQUATION_SHEET = ROOT / "STRICT_EQUATION_SHEET_KERNEL_TO_LTOTAL_CURRENT.md"
STRICT_LAGRANGIAN_DRAFT = ROOT / "STRICT_KERNEL_LAGRANGIAN_AND_EOM_DRAFT.md"
AGENTS = REPO / "AGENTS.md"

EXTERNAL_FULL_COUNT = 8_037_418
EXTERNAL_SOURCE = {
    "name": "Markus Meringer Regular Graphs page",
    "url": "https://www.mathe2.uni-bayreuth.de/markus/reggraphs.html",
    "retrieved_utc_date": "2026-06-16",
    "table": "Connected regular graphs",
    "row": "vertices=16",
    "column": "degree=4",
    "reported_count": EXTERNAL_FULL_COUNT,
    "method_context": "The page states that most numbers were obtained by GENREG; the table row for vertices=16, degree=4 reports 8037418 connected regular graphs.",
}
NEGATIVE_EXPORT_FLAGS = [
    "canonical_16node_generator_certified",
    "canonical_geometry_source_exported",
    "strict_spectral_source_law_exported",
    "global_full_spectrum_geometry_theorem_exported",
    "kernel_geometry_closure_exported",
    "kernel_fully_expresses_nadsoliton_characteristics",
    "role_bearing_ltotal_promoted",
    "bridge_closure_exported",
    "selector_closure_exported",
    "toe_closure_exported",
]


def sha(path: Path) -> str | None:
    return hashlib.sha256(path.read_bytes()).hexdigest() if path.exists() else None


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else {"missing": True, "path": rel(path)}


def decimal_fraction(numerator: int, denominator: int, places: int = 12) -> str:
    return f"{numerator / denominator:.{places}f}"


def gap_witness(p2791: dict[str, Any], p2795: dict[str, Any], p2796: dict[str, Any]) -> dict[str, Any]:
    p2791_count = p2791.get("orbit_lower_bound_witness", {}).get("representative_count", 0)
    p2795_union_count = p2795.get("post_subclass_saturation_witness", {}).get("union_named_subclass_label_count", 0)
    p2795_new_beyond_p2791 = p2795.get("post_subclass_saturation_witness", {}).get("total_new_labels_beyond_p2791", 0)
    current_distinct_class_lower_bound = max(p2791_count, p2795_union_count)
    uncovered_gap_after_p2791 = EXTERNAL_FULL_COUNT - p2791_count
    uncovered_gap_after_named_subclasses = EXTERNAL_FULL_COUNT - current_distinct_class_lower_bound
    p2791_fraction = Fraction(p2791_count, EXTERNAL_FULL_COUNT)
    named_subclass_fraction = Fraction(p2795_union_count, EXTERNAL_FULL_COUNT)
    return {
        "external_source": EXTERNAL_SOURCE,
        "external_full_connected_16node_4regular_class_count": EXTERNAL_FULL_COUNT,
        "p2791_distinct_class_lower_bound": p2791_count,
        "p2795_named_subclass_union_class_count": p2795_union_count,
        "p2795_new_classes_beyond_p2791": p2795_new_beyond_p2791,
        "current_distinct_class_lower_bound": current_distinct_class_lower_bound,
        "uncovered_class_gap_after_p2791": uncovered_gap_after_p2791,
        "uncovered_class_gap_after_named_subclasses": uncovered_gap_after_named_subclasses,
        "p2791_coverage_fraction_exact": f"{p2791_fraction.numerator}/{p2791_fraction.denominator}",
        "p2791_coverage_fraction_decimal": decimal_fraction(p2791_count, EXTERNAL_FULL_COUNT),
        "named_subclass_union_fraction_exact": f"{named_subclass_fraction.numerator}/{named_subclass_fraction.denominator}",
        "named_subclass_union_fraction_decimal": decimal_fraction(p2795_union_count, EXTERNAL_FULL_COUNT),
        "p2796_required_artifact_present": p2796.get("full_generator_artifact_absence_witness", {}).get("required_artifact_present"),
        "p2796_full_generator_truth_row_count": p2796.get("full_generator_artifact_absence_witness", {}).get("full_generator_truth_row_count"),
        "finite_certificate_statement": "The current eight-class/local-subclass evidence covers only 8 of the externally reported 8,037,418 connected 16-node 4-regular isomorphism classes; 8,037,410 classes remain outside the current repository witness set.",
    }


def acceptance_matrix(witness: dict[str, Any], p2791: dict[str, Any], p2795: dict[str, Any], p2796: dict[str, Any]) -> dict[str, Any]:
    facts = {
        "p2791_lower_bound_present": p2791.get("status") == "P2791_EIGHT_CLASS_ORBIT_LOWER_BOUND_CERTIFICATE_NO_CLOSURE",
        "p2795_saturation_present": p2795.get("status") == "P2795_POST_SUBCLASS_SATURATION_NO_NEW_CLASS_FRONTIER_CERTIFICATE_NO_CLOSURE",
        "p2796_absence_gate_present": p2796.get("status") == "P2796_FULL_GENERATOR_ARTIFACT_ABSENCE_PROVENANCE_GATE_NO_CLOSURE",
        "external_count_recorded": witness["external_full_connected_16node_4regular_class_count"] == EXTERNAL_FULL_COUNT,
        "current_bound_strictly_below_external_count": witness["current_distinct_class_lower_bound"] < EXTERNAL_FULL_COUNT,
        "gap_is_positive_and_large": witness["uncovered_class_gap_after_p2791"] == 8_037_410,
        "named_subclasses_add_no_new_classes_beyond_p2791": witness["p2795_new_classes_beyond_p2791"] == 0,
        "p2796_still_has_no_required_generator_artifact": witness["p2796_required_artifact_present"] is False and witness["p2796_full_generator_truth_row_count"] == 0,
        "full_generator_artifact_imported": False,
        "strict_nadsoliton_spectral_source_law_exported": False,
        "kernel_or_ltotal_variational_coupling_exported": False,
    }
    return {
        "facts": facts,
        "accepted_as_external_full_count_gap_certificate": all(facts[key] for key in [
            "p2791_lower_bound_present",
            "p2795_saturation_present",
            "p2796_absence_gate_present",
            "external_count_recorded",
            "current_bound_strictly_below_external_count",
            "gap_is_positive_and_large",
            "named_subclasses_add_no_new_classes_beyond_p2791",
            "p2796_still_has_no_required_generator_artifact",
        ]),
        "accepted_as_full_16node_canonical_generator_certificate": False,
        "accepted_as_strict_spectral_source_law": False,
        "accepted_as_canonical_nadsoliton_geometry_source": False,
        "accepted_as_ltotal_or_toe_promotion": False,
        "missing_criteria": [key for key, value in facts.items() if not value],
        "blocker": "P2797 sizes the missing full-class obligation against an external GENREG-lineage count: current witnesses cover 8 classes while the reported full connected 16-node 4-regular class count is 8,037,418.  The imported number is a target/gap certificate only, not graph-list provenance or a strict source law.",
    }


def write_markdown(payload: dict[str, Any]) -> None:
    w = payload["external_full_count_gap_witness"]
    lines = [
        "# P2797/S1747 external full-count gap certificate",
        "",
        f"Status: `{payload['status']}`",
        "",
        "## External target count and current gap",
        f"- external_full_connected_16node_4regular_class_count={w['external_full_connected_16node_4regular_class_count']}",
        f"- p2791_distinct_class_lower_bound={w['p2791_distinct_class_lower_bound']}",
        f"- p2795_named_subclass_union_class_count={w['p2795_named_subclass_union_class_count']}",
        f"- p2795_new_classes_beyond_p2791={w['p2795_new_classes_beyond_p2791']}",
        f"- uncovered_class_gap_after_p2791={w['uncovered_class_gap_after_p2791']}",
        f"- p2791_coverage_fraction_exact={w['p2791_coverage_fraction_exact']}",
        f"- p2791_coverage_fraction_decimal={w['p2791_coverage_fraction_decimal']}",
        "",
        "## External source",
        f"- source={w['external_source']['name']}",
        f"- url={w['external_source']['url']}",
        f"- retrieved_utc_date={w['external_source']['retrieved_utc_date']}",
        "",
        "## Decision",
        payload["decision"]["reason"],
        "",
        "## Recommendation",
        payload["decision"]["next_honest_step"],
    ]
    MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> dict[str, Any]:
    GEN.mkdir(exist_ok=True)
    p2791 = read_json(P2791)
    p2795 = read_json(P2795)
    p2796 = read_json(P2796)
    witness = gap_witness(p2791, p2795, p2796)
    acceptance = acceptance_matrix(witness, p2791, p2795, p2796)
    payload = {
        "status": "P2797_EXTERNAL_FULL_COUNT_GAP_CERTIFICATE_NO_CLOSURE",
        "input_hashes": {"P2791": sha(P2791), "P2795": sha(P2795), "P2796": sha(P2796)},
        "input_statuses": {"P2791": p2791.get("status"), "P2795": p2795.get("status"), "P2796": p2796.get("status")},
        "audited_question": "How large is the remaining full-class gap if the external connected 16-node 4-regular count is used only as a target-count certificate?",
        "external_full_count_gap_witness": witness,
        "acceptance_matrix": acceptance,
        "decision": {
            "negative_export_flags": {flag: False for flag in NEGATIVE_EXPORT_FLAGS},
            "reason": acceptance["blocker"],
            "next_honest_step": "Use the external 8,037,418 count only as a target-count/gap obligation.  The next proof-grade move is to import the actual graph-list artifact/toolchain behind that count with graph6/hash provenance and run the full quotient/charpoly/complement/orbit audit, or else export a strict nadsoliton spectral action/source law fixing the admissible class and K/L_total coupling before testing.  Without one of those objects, preserve the P2697-P2797 no-canonical-geometry/no-closure certificate.",
        },
    }
    OUT.write_text(json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")
    write_markdown(payload)
    append_once(STRICT_EQUATION_SHEET, "P2797/S1747 external full-count gap certificate", "## P2797/S1747 external full-count gap certificate\n\n`P2797/S1747` imports a narrowly scoped external target count from Markus Meringer's Regular Graphs page: the connected regular graph table reports `8,037,418` connected 4-regular simple graphs on 16 vertices.  Against that target, the current P2791 witness covers 8 distinct classes and P2795 adds zero new classes beyond P2791, leaving a target-count gap of `8,037,410` classes.  This sizes the missing full-generator obligation, but it is not a graph-list artifact, not repository-local `graph6` provenance for the full class, not a strict spectral source law, and not a `K`/`L_total` variational coupling.\n")
    append_once(STRICT_LAGRANGIAN_DRAFT, "P2797/S1747 external full-count gap Ltotal guard", "## P2797/S1747 external full-count gap Ltotal guard\n\n`P2797/S1747` adds no variational source term.  The external count only sizes the gap between current local witnesses and the reported full connected 16-node 4-regular class count; it does not import the graph list, source a spectral action, or license any `K`/`L_total` promotion.\n")
    append_once(AGENTS, "Current external full-count gap guardrail (P2797/S1747, 2026-06-16)", "## Current external full-count gap guardrail (P2797/S1747, 2026-06-16)\n\n- P2797 records the external GENREG-lineage target count `8,037,418` connected 4-regular simple graphs on 16 vertices and computes that current P2791/P2795 evidence covers only 8 classes, leaving a target-count gap of `8,037,410`.\n- This is a target-count/gap certificate only; it is not the full graph-list artifact/toolchain, not full `graph6` provenance, and not a strict spectral source law.\n- Do not promote the external count to canonical geometry, strict spectral source law, selector closure, kernel full-expression, role-bearing `L_total`, bridge closure, role transfer, or ToE closure.  The next admissible move is importing the actual graph-list/toolchain provenance or exporting a strict spectral source law.\n")
    return payload


if __name__ == "__main__":
    main()
