#!/usr/bin/env python3
"""P2873/S1823: exhaustive dihedral Z12 endpoint-predicate no-go audit.

P2872 showed that the cyclic predecessor d=-1 mod 12 exactly represents the
endpoint target only after importing an orientation/boundary-arrow convention.
This packet closes the natural finite escape hatch: instead of checking only
the two adjacent endpoints {1,11}, enumerate all Boolean endpoint predicates on
Z12 and filter them by the full unoriented dihedral symmetry generated by
translation and reflection.

The result is intentionally negative.  Full dihedral invariance admits only the
empty and all-endpoint predicates, so it cannot select singleton 11, adjacent
pair {1,11}, or any endpoint localizer.  Even if translation is not imposed and
one only keeps reflection around 0, the invariant atoms are reflection-pairs
{1,11}, {2,10}, ..., plus fixed points 0 and 6; singleton 11 still requires an
orientation import.  No strict source law, orientation law, or unit-bearing
9/5 coupling theorem is exported.
"""
from __future__ import annotations

import json
from itertools import combinations
from typing import Any, Iterable

from p2468_s1418_strict_pointwise_interval_decimal_chunked_opposite_tail_replay_ledger_certificate import REPO, ROOT
from p2506_s1456_strict_damping_rg_minimum_roughness_selector_candidate_certificate import append_once
from p2803_s1753_meringer_scd_import_decode_validation_certificate import sha
from p2812_s1762_two_wl_refined_collision_audit import read_json
from p2855_s1805_z12_rational_phase_lattice_source_candidate_audit import GEN

P2872 = GEN / "p2872_s1822_cyclic_predecessor_endpoint_orientation_no_source_audit.json"
OUT = GEN / "p2873_s1823_exhaustive_dihedral_z12_endpoint_predicate_no_go_audit.json"
MD = GEN / "p2873_s1823_exhaustive_dihedral_z12_endpoint_predicate_no_go_audit.md"
STRICT_EQUATION_SHEET = ROOT / "STRICT_EQUATION_SHEET_KERNEL_TO_LTOTAL_CURRENT.md"
STRICT_LAGRANGIAN_DRAFT = ROOT / "STRICT_KERNEL_LAGRANGIAN_AND_EOM_DRAFT.md"
AGENTS = REPO / "AGENTS.md"

MODULUS = 12
ENDPOINTS = tuple(range(MODULUS))
TARGET_ENDPOINT = 11
SUCCESSOR_ENDPOINT = 1
ADJACENT_PAIR = frozenset({SUCCESSOR_ENDPOINT, TARGET_ENDPOINT})


def translate(endpoint: int, shift: int) -> int:
    return (endpoint + shift) % MODULUS


def reflect(endpoint: int) -> int:
    return (-endpoint) % MODULUS


def dihedral_images(endpoint: int) -> set[int]:
    return {translate(endpoint, shift) for shift in ENDPOINTS} | {translate(reflect(endpoint), shift) for shift in ENDPOINTS}


def act(predicate: frozenset[int], *, shift: int = 0, reflection: bool = False) -> frozenset[int]:
    if reflection:
        return frozenset(translate(reflect(endpoint), shift) for endpoint in predicate)
    return frozenset(translate(endpoint, shift) for endpoint in predicate)


def all_predicates() -> Iterable[frozenset[int]]:
    for size in range(MODULUS + 1):
        for subset in combinations(ENDPOINTS, size):
            yield frozenset(subset)


def is_dihedral_invariant(predicate: frozenset[int]) -> bool:
    return all(act(predicate, shift=shift, reflection=reflection) == predicate for shift in ENDPOINTS for reflection in (False, True))


def is_reflection0_invariant(predicate: frozenset[int]) -> bool:
    return act(predicate, reflection=True) == predicate


def orbit_under_group(predicate: frozenset[int], *, full_dihedral: bool) -> list[list[int]]:
    if full_dihedral:
        images = {act(predicate, shift=shift, reflection=reflection) for shift in ENDPOINTS for reflection in (False, True)}
    else:
        images = {predicate, act(predicate, reflection=True)}
    return sorted([sorted(image) for image in images], key=lambda xs: (len(xs), xs))


def reflection0_atoms() -> list[list[int]]:
    seen: set[int] = set()
    atoms: list[list[int]] = []
    for endpoint in ENDPOINTS:
        if endpoint in seen:
            continue
        atom = sorted({endpoint, reflect(endpoint)})
        seen.update(atom)
        atoms.append(atom)
    return atoms


def build_payload(p2872: dict[str, Any]) -> dict[str, Any]:
    predicates = list(all_predicates())
    dihedral_invariant = [predicate for predicate in predicates if is_dihedral_invariant(predicate)]
    reflection0_invariant = [predicate for predicate in predicates if is_reflection0_invariant(predicate)]
    singleton_11 = frozenset({TARGET_ENDPOINT})
    facts = {
        "p2872_rechecked": p2872.get("status") == "P2872_CYCLIC_PREDECESSOR_ENDPOINT_ORIENTATION_NO_SOURCE_AUDIT_NO_CLOSURE",
        "all_4096_boolean_endpoint_predicates_enumerated": len(predicates) == 2**MODULUS,
        "full_dihedral_invariant_predicates_are_only_empty_and_all": dihedral_invariant == [frozenset(), frozenset(ENDPOINTS)],
        "singleton_11_not_full_dihedral_invariant": not is_dihedral_invariant(singleton_11),
        "singleton_11_not_reflection0_invariant": not is_reflection0_invariant(singleton_11),
        "adjacent_pair_reflection0_invariant_but_not_singleton": is_reflection0_invariant(ADJACENT_PAIR) and ADJACENT_PAIR != singleton_11,
        "translation_orbit_of_11_is_all_z12": sorted(dihedral_images(TARGET_ENDPOINT)) == list(ENDPOINTS),
    }
    return {
        "status": "P2873_EXHAUSTIVE_DIHEDRAL_Z12_ENDPOINT_PREDICATE_NO_GO_AUDIT_NO_CLOSURE",
        "input_hashes": {"P2872": sha(P2872)},
        "exhaustive_dihedral_z12_endpoint_predicate_no_go_audit": {
            "input_status_rechecked": p2872.get("status"),
            "candidate_class": "all Boolean endpoint predicates on Z12 filtered by full D12 symmetry, with a reflection-only comparison boundary",
            "modulus": MODULUS,
            "predicate_count": len(predicates),
            "full_dihedral_invariant_predicates": [sorted(predicate) for predicate in dihedral_invariant],
            "full_dihedral_invariant_count": len(dihedral_invariant),
            "reflection0_invariant_count": len(reflection0_invariant),
            "reflection0_atoms": reflection0_atoms(),
            "singleton_11_full_dihedral_orbit": orbit_under_group(singleton_11, full_dihedral=True),
            "singleton_11_reflection0_orbit": orbit_under_group(singleton_11, full_dihedral=False),
            "adjacent_pair_reflection0_orbit": orbit_under_group(ADJACENT_PAIR, full_dihedral=False),
            "proof_certificate": {
                "enumeration_step": "All 2^12 Boolean endpoint predicates on Z12 are enumerated exactly.",
                "dihedral_step": "Translation transitivity makes any full D12-invariant endpoint predicate either empty or all of Z12; reflection adds no singleton-localizing escape hatch.",
                "reflection_boundary_step": "If translation is withheld, reflection around 0 admits the adjacent pair {1,11}, but not singleton 11; predecessor selection still imports orientation.",
                "sourcehood_step": "Current artifacts export no strict non-premise law selecting singleton 11 and no unit-bearing 9/5 coupling/localization theorem.",
            },
        },
        "acceptance_matrix": {
            "facts": facts,
            "accepted_as_dihedral_endpoint_source": False,
            "exports_boundary_source_law": False,
            "exports_orientation_source_law": False,
            "exports_selector_or_localizer_source": False,
            "exports_unit_bearing_coupling_localization_theorem": False,
            "exports_strict_damping_compression_bridge": False,
        },
        "decision": {
            "negative_export_flags": {
                "boundary_source_law_exported": False,
                "eta_source_exported": False,
                "prime5_source_exported": False,
                "selector_or_localizer_source_exported": False,
                "orientation_source_law_exported": False,
                "selector_closure_exported": False,
                "unit_bearing_coupling_localization_theorem_exported": False,
                "strict_damping_compression_bridge_exported": False,
                "full_kernel_bridge_exported": False,
                "role_transfer_exported": False,
                "ltotal_exported": False,
                "eom_closure_exported": False,
                "hamiltonian_closure_exported": False,
                "toe_closure_exported": False,
            },
            "reason": "P2873 exhausts all Boolean endpoint predicates on Z12.  Full D12 invariance leaves only empty/all predicates; reflection-only invariance keeps the unordered pair {1,11} but cannot choose predecessor 11.  Singleton 11 therefore remains an orientation/endpoint-label import, not a strict source law.",
            "next_honest_step": "Do not replay full-dihedral endpoint predicates, reflection-only adjacent pairs, cyclic predecessor, or endpoint-label imports as sourcehood.  A next proof-grade move must provide a new strict non-premise chiral/orientation source law selecting singleton 11 and a unit-bearing 9/5 coupling theorem, or pivot to a genuinely different typed object; otherwise preserve no-new-live-frontier.",
        },
    }


def write_markdown(payload: dict[str, Any]) -> None:
    audit = payload["exhaustive_dihedral_z12_endpoint_predicate_no_go_audit"]
    lines = [
        "# P2873/S1823 exhaustive dihedral Z12 endpoint-predicate no-go audit",
        "",
        f"Status: `{payload['status']}`",
        "",
        "## Exhaustive endpoint-predicate audit",
        f"- candidate class: `{audit['candidate_class']}`",
        f"- predicate count: `{audit['predicate_count']}`",
        f"- full dihedral invariant predicates: `{audit['full_dihedral_invariant_predicates']}`",
        f"- reflection-only atoms: `{audit['reflection0_atoms']}`",
        "",
        "## Boundary",
        payload["decision"]["reason"],
        "",
        "## Recommendation",
        payload["decision"]["next_honest_step"],
    ]
    MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> dict[str, Any]:
    GEN.mkdir(exist_ok=True)
    payload = build_payload(read_json(P2872))
    OUT.write_text(json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")
    write_markdown(payload)
    append_once(
        STRICT_EQUATION_SHEET,
        "P2873/S1823 exhaustive dihedral Z12 endpoint-predicate no-go audit",
        "## P2873/S1823 exhaustive dihedral Z12 endpoint-predicate no-go audit\n\n"
        "`P2873/S1823` exhausts all `2^12=4096` Boolean endpoint predicates on `Z12` after P2872.  Full `D12` invariance leaves only empty/all predicates, so it cannot select singleton `11` or any endpoint localizer.  If translation is withheld, reflection-only invariance admits the unordered adjacent pair `{1,11}`, but still cannot select predecessor `11` over successor `1`; singleton `11` remains an orientation/endpoint-label import.  No boundary source law, orientation law, eta source, strict damping bridge, unit-bearing `9/5` coupling theorem, `L_total`, EOM, Hamiltonian, role transfer, or ToE closure follows.\n",
    )
    append_once(
        STRICT_LAGRANGIAN_DRAFT,
        "P2873/S1823 dihedral endpoint predicate `L_total` guard",
        "## P2873/S1823 dihedral endpoint predicate `L_total` guard\n\n"
        "`P2873/S1823` adds no strict action term.  Exhaustive dihedral or reflection-only endpoint predicates do not export a unit-bearing boundary/source density, chiral orientation law, coupling coefficient, localization/pullback theorem, variational chain rule, nonproxy `L_total`, EOM, or Hamiltonian source.\n",
    )
    append_once(
        AGENTS,
        "Current exhaustive dihedral endpoint-predicate no-go guardrail (P2873/S1823, 2026-06-18)",
        "## Current exhaustive dihedral endpoint-predicate no-go guardrail (P2873/S1823, 2026-06-18)\n\n"
        "- P2873 exhausts all `2^12=4096` Boolean endpoint predicates on `Z12` after P2872 and filters them by full `D12` symmetry, with a reflection-only comparison boundary.\n"
        "- Full `D12` invariance leaves only empty/all predicates; reflection-only invariance can retain unordered adjacent pairs such as `{1,11}` but cannot choose predecessor `11` over successor `1`.\n"
        "- Do not promote full-dihedral endpoint predicates, reflection-only adjacent pairs, cyclic predecessor conventions, endpoint-label imports, Boolean projector predicates, Aut-character idempotents, prime-5 scaled coefficients, Dirichlet data, or log-scale harmonicity to strict damping/compression bridge, selector closure, role transfer, unit-bearing `L_total`, EOM, Hamiltonian, or ToE closure.\n"
        "- A next admissible proof-grade move must export a new strict non-premise chiral/orientation source law selecting singleton `11` and a unit-bearing `9/5` coupling theorem, or use a genuinely different new typed object; otherwise preserve no-new-live-frontier.\n",
    )
    return payload


if __name__ == "__main__":
    print(json.dumps(main(), indent=2, sort_keys=True, ensure_ascii=False))
