from __future__ import annotations

import json
import subprocess
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "fundamental_action_reconstruction" / "scratch" / "bridge_strict_completion_certificate_chain_integrity_probe.py"
REPORT_JSON = ROOT / "fundamental_action_reconstruction" / "scratch" / "bridge_strict_completion_certificate_chain_integrity_report.json"
REPORT_MD = ROOT / "fundamental_action_reconstruction" / "scratch" / "bridge_strict_completion_certificate_chain_integrity_report.md"


class StrictCompletionCertificateChainIntegrityProbeTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        subprocess.run([sys.executable, str(SCRIPT)], check=True, cwd=ROOT)
        cls.payload = json.loads(REPORT_JSON.read_text(encoding="utf-8"))

    def test_result_kind_sources_and_shared_objects(self):
        payload = self.payload
        self.assertEqual(
            payload["result_kind"],
            "SCRATCH_STRICT_COMPLETION_CERTIFICATE_CHAIN_INTEGRITY__FINITE_LEDGER_NO_BRIDGE_THEOREM",
        )
        self.assertIn("cross-consistent", payload["status"])
        self.assertEqual(set(payload["source_reports"]), {
            "necessity",
            "cocycle",
            "phase_zero",
            "phase_zero_rational",
            "phase_zero_margin",
            "phase_zero_node_clearance",
            "phase_zero_cell_partition",
            "phase_zero_carrier_edge_incidence",
            "phase_zero_carrier_prefix_node_matrix",
            "phase_zero_gf2_commutative_diagram",
            "phase_sign_path_cohomology_triviality",
            "phase_sign_reduced_coboundary_inverse",
            "phase_sign_node_support_interval_boundary",
            "phase_sign_flip_pair_interval_reconstruction",
            "phase_sign_support_euler_characteristic",
            "phase_sign_component_quotient_adjacency",
            "phase_sign_component_quotient_lift_matrix",
            "phase_sign_component_quotient_projection",
            "phase_sign_component_quotient_exact_sequence",
            "phase_sign_component_quotient_complement_inverse",
            "phase_sign_component_quotient_coordinate_isomorphism",
            "phase_sign_component_quotient_dual_basis",
            "phase_sign_component_quotient_coordinate_support_minimality",
            "phase_sign_component_quotient_coordinate_residual_syndrome",
            "phase_sign_component_quotient_coordinate_syndrome_decoder",
            "phase_sign_component_quotient_coordinate_syndrome_generator_basis",
            "phase_sign_cycle_closure_obstruction",
            "phase_zero_cell_sign",
            "phase_sign_z2_coboundary",
            "phase_sign_edge_support_minimality",
            "phase_sign_gf2_linear_system",
            "damping_monotonicity",
            "damping_exact_rational",
            "positive_factor_sign_separation",
            "low_order_no_go",
            "closure_plan_dependency",
            "s1_selector_margin_obstruction",
            "legacy_kernel_intermediate_bridge_guardrail",
            "legacy_to_strict_component_gap_matrix",
            "legacy_to_strict_damping_compression_separation",
            "legacy_to_strict_amplitude_scalar_normalization",
            "legacy_to_strict_finite_diagonal_completion_map",
            "legacy_to_strict_phase_frequency_affine_transport",
            "legacy_to_strict_damping_parameter_identifiability",
            "legacy_to_strict_finite_bridge_assembly",
            "legacy_to_strict_symbolic_cancellation",
            "legacy_role_transfer_pre_audit",
            "legacy_role_transfer_minimal_obligation_lattice",
            "theorem_frontier_cut",
            "theorem_frontier_truth_table",
            "theorem_frontier_atom_influence",
            "theorem_frontier_target_signature_lattice",
            "theorem_frontier_low_weight_extension",
            "anchor_h1_generator_classification",
            "release_scaffold",
            "release_source_coverage",
            "release_traceability_matrix",
            "toe_potential_readiness",
            "toe_proper_subset_obstruction",
            "toe_boolean_normal_form",
            "toe_boolean_essentiality",
            "toe_conditional_closure",
        })
        shared = payload["expected_shared_objects"]
        self.assertEqual(shared["phase_transport_sign_pattern"], [1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1])
        self.assertEqual(shared["phase_sign_flip_edges"], ["1->2", "5->6", "7->8", "9->10"])
        self.assertEqual(shared["unique_exact_completion_subset"], "alpha_normalization+phase_frequency_transport+damping_compression")

    def test_cross_checks_and_chain_summary(self):
        payload = self.payload
        self.assertTrue(payload["all_cross_checks_pass"])
        self.assertTrue(all(payload["cross_checks"].values()))
        checks = payload["cross_checks"]
        self.assertTrue(checks["necessity_has_unique_exact_full_APD_subset"])
        self.assertTrue(checks["phase_zero_rational_matches_float"])
        self.assertTrue(checks["phase_zero_margin_preserves_rational"])
        self.assertTrue(checks["phase_zero_node_clearance_preserves_rational"])
        self.assertTrue(checks["phase_zero_node_clearance_no_integer_degeneracy"])
        self.assertTrue(checks["phase_zero_cell_partition_preserves_node_clearance"])
        self.assertTrue(checks["phase_zero_cell_partition_ordered_disjoint"])
        self.assertTrue(checks["phase_zero_cell_partition_positive_cells"])
        self.assertTrue(checks["phase_zero_carrier_edge_incidence_preserves_cell_partition"])
        self.assertTrue(checks["phase_zero_carrier_edge_incidence_rank_full"])
        self.assertTrue(checks["phase_zero_carrier_edge_incidence_matches_gf2"])
        self.assertTrue(checks["phase_zero_carrier_prefix_preserves_cell_sign"])
        self.assertTrue(checks["phase_zero_carrier_prefix_matches_z2_nodes"])
        self.assertTrue(checks["phase_zero_carrier_prefix_edge_differences_match_incidence"])
        self.assertTrue(checks["phase_zero_gf2_diagram_all_checks_pass"])
        self.assertTrue(checks["phase_zero_gf2_diagram_matches_z2"])
        self.assertTrue(checks["phase_zero_gf2_diagram_inherits_ranks"])
        self.assertTrue(checks["phase_sign_path_cohomology_h1_zero"])
        self.assertTrue(checks["phase_sign_path_cohomology_anchor_reconstructs"])
        self.assertTrue(checks["phase_sign_path_cohomology_flips_match"])
        self.assertTrue(checks["phase_sign_reduced_coboundary_rank_full"])
        self.assertTrue(checks["phase_sign_reduced_coboundary_two_sided_inverse"])
        self.assertTrue(checks["phase_sign_reduced_coboundary_reconstructs_z2"])
        self.assertTrue(checks["phase_sign_reduced_coboundary_matches_path_and_gf2"])
        self.assertTrue(checks["phase_sign_node_support_intervals_match_expected"])
        self.assertTrue(checks["phase_sign_node_support_interval_boundary_rank_full"])
        self.assertTrue(checks["phase_sign_node_support_interval_boundary_reconstructs_z2"])
        self.assertTrue(checks["phase_sign_node_support_interval_boundary_formula"])
        self.assertTrue(checks["phase_sign_node_support_interval_boundary_matches_reduced"])
        self.assertTrue(checks["phase_sign_flip_pair_intervals_match_boundary"])
        self.assertTrue(checks["phase_sign_flip_pair_reconstructs_z2"])
        self.assertTrue(checks["phase_sign_flip_pair_parity_closes"])
        self.assertTrue(checks["phase_sign_flip_pair_matches_edge_support_and_reduced"])
        self.assertTrue(checks["phase_sign_support_euler_matches_expected"])
        self.assertTrue(checks["phase_sign_support_euler_characteristic_counts"])
        self.assertTrue(checks["phase_sign_support_euler_boundary_count"])
        self.assertTrue(checks["phase_sign_support_euler_matches_prior_components"])
        self.assertTrue(checks["phase_sign_component_quotient_matches_expected"])
        self.assertTrue(checks["phase_sign_component_quotient_tree_alternating"])
        self.assertTrue(checks["phase_sign_component_quotient_edges_match_flips"])
        self.assertTrue(checks["phase_sign_component_quotient_counts_match_prior"])
        self.assertTrue(checks["phase_sign_component_quotient_lift_commutes"])
        self.assertTrue(checks["phase_sign_component_quotient_lift_reconstructs_z2"])
        self.assertTrue(checks["phase_sign_component_quotient_lift_ranks_full"])
        self.assertTrue(checks["phase_sign_component_quotient_lift_matches_gf2"])
        self.assertTrue(checks["phase_sign_component_quotient_projection_section_identity"])
        self.assertTrue(checks["phase_sign_component_quotient_projection_projector_fixes_nodes"])
        self.assertTrue(checks["phase_sign_component_quotient_projection_boundary_split"])
        self.assertTrue(checks["phase_sign_component_quotient_projection_matches_lift"])
        self.assertTrue(checks["phase_sign_component_quotient_exact_sequence_rank_nullity"])
        self.assertTrue(checks["phase_sign_component_quotient_exact_sequence_image_kernel"])
        self.assertTrue(checks["phase_sign_component_quotient_exact_sequence_projector"])
        self.assertTrue(checks["phase_sign_component_quotient_exact_sequence_matches_projection_lift"])
        self.assertTrue(checks["phase_sign_component_quotient_complement_direct_sum"])
        self.assertTrue(checks["phase_sign_component_quotient_complement_annihilators"])
        self.assertTrue(checks["phase_sign_component_quotient_complement_fn_inverse"])
        self.assertTrue(checks["phase_sign_component_quotient_complement_audited_vector"])
        self.assertTrue(checks["phase_sign_component_quotient_coordinate_ranks_full"])
        self.assertTrue(checks["phase_sign_component_quotient_coordinate_two_sided_inverse"])
        self.assertTrue(checks["phase_sign_component_quotient_coordinate_audited_reconstructs"])
        self.assertTrue(checks["phase_sign_component_quotient_coordinate_matches_complement"])
        self.assertTrue(checks["phase_sign_component_quotient_dual_basis_pairing"])
        self.assertTrue(checks["phase_sign_component_quotient_dual_basis_coordinates"])
        self.assertTrue(checks["phase_sign_component_quotient_dual_basis_residuals_zero"])
        self.assertTrue(checks["phase_sign_component_quotient_dual_basis_reconstructs"])
        self.assertTrue(checks["phase_sign_component_quotient_coordinate_support_enumerates_all"])
        self.assertTrue(checks["phase_sign_component_quotient_coordinate_support_unique_minimal"])
        self.assertTrue(checks["phase_sign_component_quotient_coordinate_support_lower_weights_fail"])
        self.assertTrue(checks["phase_sign_component_quotient_coordinate_support_matches_dual_basis"])
        self.assertTrue(checks["phase_sign_component_quotient_coordinate_residual_syndromes_unique"])
        self.assertTrue(checks["phase_sign_component_quotient_coordinate_residual_zero_unique"])
        self.assertTrue(checks["phase_sign_component_quotient_coordinate_residual_nonmatches_fail"])
        self.assertTrue(checks["phase_sign_component_quotient_coordinate_residual_matches_support_minimality"])
        self.assertTrue(checks["phase_sign_component_quotient_coordinate_decoder_enumerates_all"])
        self.assertTrue(checks["phase_sign_component_quotient_coordinate_decoder_corrects_all_coordinates"])
        self.assertTrue(checks["phase_sign_component_quotient_coordinate_decoder_reencodes_all_residuals"])
        self.assertTrue(checks["phase_sign_component_quotient_coordinate_decoder_matches_residual_syndrome"])
        self.assertTrue(checks["phase_sign_component_quotient_coordinate_generator_all_decode"])
        self.assertTrue(checks["phase_sign_component_quotient_coordinate_generator_ranks_full"])
        self.assertTrue(checks["phase_sign_component_quotient_coordinate_generator_edges_match"])
        self.assertTrue(checks["phase_sign_component_quotient_coordinate_generator_matches_decoder"])
        self.assertTrue(checks["phase_sign_cycle_closure_h1_one"])
        self.assertTrue(checks["phase_sign_cycle_closure_zero_edge_exact"])
        self.assertTrue(checks["phase_sign_cycle_closure_odd_edge_obstructed"])
        self.assertTrue(checks["phase_sign_cycle_closure_matches_z2"])
        self.assertTrue(checks["phase_zero_cell_sign_preserves_cell_partition"])
        self.assertTrue(checks["phase_zero_cell_sign_no_trig_eval"])
        self.assertTrue(checks["phase_zero_cell_sign_edge_parity"])
        self.assertTrue(checks["phase_sign_z2_preserves_cell_sign"])
        self.assertTrue(checks["phase_sign_z2_all_intervals_pass"])
        self.assertTrue(checks["phase_sign_z2_prefix_reconstructs"])
        self.assertTrue(checks["phase_sign_edge_support_preserves_z2"])
        self.assertTrue(checks["phase_sign_edge_support_unique_assignment"])
        self.assertTrue(checks["phase_sign_edge_support_lower_supports_fail"])
        self.assertTrue(checks["phase_sign_gf2_preserves_edge_support"])
        self.assertTrue(checks["phase_sign_gf2_full_rank_unique_solution"])
        self.assertTrue(checks["phase_sign_gf2_inverse_checks_pass"])
        self.assertTrue(checks["damping_cannot_supply_sign_flips"])
        self.assertTrue(checks["damping_exact_rational_matches_float"])
        self.assertTrue(checks["damping_exact_rational_derivative_bound_negative"])
        self.assertTrue(checks["damping_exact_rational_edges_drop_by_mvt"])
        self.assertTrue(checks["positive_factor_sign_matches_z2"])
        self.assertTrue(checks["positive_factor_bits_all_zero"])
        self.assertTrue(checks["positive_factor_completion_flips_phase_only"])
        self.assertTrue(checks["low_order_no_go_all_listed_models_fail"])
        self.assertTrue(checks["closure_plan_dependency_sources_pass"])
        self.assertTrue(checks["closure_plan_dependency_matrix_triangular"])
        self.assertTrue(checks["closure_plan_dependency_recommends_bridge_guardrail"])
        self.assertTrue(checks["closure_plan_dependency_keeps_closure_open"])
        self.assertTrue(checks["s1_selector_margin_obstruction_sources_pass"])
        self.assertTrue(checks["s1_selector_margin_obstruction_certified"])
        self.assertTrue(checks["s1_selector_margin_locked_replay_fails"])
        self.assertTrue(checks["s1_selector_margin_no_positive_margin"])
        self.assertTrue(checks["legacy_kernel_intermediate_bridge_guardrail_sources_pass"])
        self.assertTrue(checks["legacy_kernel_intermediate_bridge_compression_recorded"])
        self.assertTrue(checks["legacy_kernel_intermediate_bridge_role_transfer_required"])
        self.assertTrue(checks["legacy_kernel_intermediate_bridge_keeps_selector_open"])
        self.assertTrue(checks["legacy_to_strict_component_gap_sources_pass"])
        self.assertTrue(checks["legacy_to_strict_component_gap_all_rows_certified"])
        self.assertTrue(checks["legacy_to_strict_component_gap_strict_sources_open"])
        self.assertTrue(checks["legacy_to_strict_component_gap_role_transfer_blocked"])
        self.assertTrue(checks["legacy_to_strict_damping_separation_sources_pass"])
        self.assertTrue(checks["legacy_to_strict_damping_separation_linear_no_go"])
        self.assertTrue(checks["legacy_to_strict_damping_separation_best_fit_not_exact"])
        self.assertTrue(checks["legacy_to_strict_damping_separation_no_bridge_claim"])
        self.assertTrue(checks["legacy_to_strict_amplitude_scalar_sources_pass"])
        self.assertTrue(checks["legacy_to_strict_amplitude_scalar_exact"])
        self.assertTrue(checks["legacy_to_strict_amplitude_scalar_domain_safe"])
        self.assertTrue(checks["legacy_to_strict_amplitude_scalar_no_role_transfer"])
        self.assertTrue(checks["legacy_to_strict_finite_diagonal_sources_pass"])
        self.assertTrue(checks["legacy_to_strict_finite_diagonal_reconstructs"])
        self.assertTrue(checks["legacy_to_strict_finite_diagonal_full_rank"])
        self.assertTrue(checks["legacy_to_strict_finite_diagonal_apd_and_no_scalar"])
        self.assertTrue(checks["legacy_to_strict_finite_diagonal_no_source_or_role"])
        self.assertTrue(checks["legacy_to_strict_phase_affine_sources_pass"])
        self.assertTrue(checks["legacy_to_strict_phase_affine_exact"])
        self.assertTrue(checks["legacy_to_strict_phase_affine_not_z12_automorphism"])
        self.assertTrue(checks["legacy_to_strict_phase_affine_bits_and_no_scalar"])
        self.assertTrue(checks["legacy_to_strict_phase_affine_no_source_or_selector"])
        self.assertTrue(checks["legacy_to_strict_damping_parameter_sources_pass"])
        self.assertTrue(checks["legacy_to_strict_damping_parameter_beta_eta_identified"])
        self.assertTrue(checks["legacy_to_strict_damping_parameter_cover_unique"])
        self.assertTrue(checks["legacy_to_strict_damping_parameter_legacy_linear_rejected"])
        self.assertTrue(checks["legacy_to_strict_damping_parameter_no_source_or_bridge"])
        self.assertTrue(checks["legacy_to_strict_finite_bridge_assembly_sources_pass"])
        self.assertTrue(checks["legacy_to_strict_finite_bridge_assembly_t99_scope_pass"])
        self.assertTrue(checks["legacy_to_strict_finite_bridge_assembly_exact"])
        self.assertTrue(checks["legacy_to_strict_finite_bridge_assembly_sign_log_coherent"])
        self.assertTrue(checks["legacy_to_strict_finite_bridge_assembly_limits_preserved"])
        self.assertTrue(checks["legacy_to_strict_symbolic_cancellation_sources_pass"])
        self.assertTrue(checks["legacy_to_strict_symbolic_cancellation_admissibility_pass"])
        self.assertTrue(checks["legacy_to_strict_symbolic_cancellation_formula_pass"])
        self.assertTrue(checks["legacy_to_strict_symbolic_cancellation_inherits_finite_witness"])
        self.assertTrue(checks["legacy_to_strict_symbolic_cancellation_limits_preserved"])
        self.assertTrue(checks["legacy_role_transfer_pre_audit_sources_pass"])
        self.assertTrue(checks["legacy_role_transfer_pre_audit_all_roles_blocked"])
        self.assertTrue(checks["legacy_role_transfer_pre_audit_rank_pass"])
        self.assertTrue(checks["legacy_role_transfer_pre_audit_sources_missing"])
        self.assertTrue(checks["legacy_role_transfer_pre_audit_limits_preserved"])
        self.assertTrue(checks["legacy_role_transfer_minimal_obligation_sources_pass"])
        self.assertTrue(checks["legacy_role_transfer_minimal_obligation_enumeration_pass"])
        self.assertTrue(checks["legacy_role_transfer_minimal_obligation_global_set_pass"])
        self.assertTrue(checks["legacy_role_transfer_minimal_obligation_beta_bottleneck_pass"])
        self.assertTrue(checks["legacy_role_transfer_minimal_obligation_limits_preserved"])
        self.assertTrue(checks["theorem_frontier_cut_sources_pass"])
        self.assertTrue(checks["theorem_frontier_cut_dag_pass"])
        self.assertTrue(checks["theorem_frontier_cut_closed_open_atoms_pass"])
        self.assertTrue(checks["theorem_frontier_cut_toe_cut_pass"])
        self.assertTrue(checks["theorem_frontier_cut_limits_preserved"])
        self.assertTrue(checks["theorem_frontier_truth_table_sources_pass"])
        self.assertTrue(checks["theorem_frontier_truth_table_atom_set_pass"])
        self.assertTrue(checks["theorem_frontier_truth_table_enumeration_pass"])
        self.assertTrue(checks["theorem_frontier_truth_table_target_counts_pass"])
        self.assertTrue(checks["theorem_frontier_truth_table_current_no_closure"])
        self.assertTrue(checks["theorem_frontier_truth_table_minimal_sets_pass"])
        self.assertTrue(checks["theorem_frontier_truth_table_limits_preserved"])
        self.assertTrue(checks["theorem_frontier_atom_influence_sources_pass"])
        self.assertTrue(checks["theorem_frontier_atom_influence_atom_set_pass"])
        self.assertTrue(checks["theorem_frontier_atom_influence_counts_pass"])
        self.assertTrue(checks["theorem_frontier_atom_influence_top_atom_pass"])
        self.assertTrue(checks["theorem_frontier_atom_influence_tie_classes_pass"])
        self.assertTrue(checks["theorem_frontier_atom_influence_limits_preserved"])
        self.assertTrue(checks["theorem_frontier_target_signature_lattice_sources_pass"])
        self.assertTrue(checks["theorem_frontier_target_signature_lattice_partition_pass"])
        self.assertTrue(checks["theorem_frontier_target_signature_lattice_reachability_pass"])
        self.assertTrue(checks["theorem_frontier_target_signature_lattice_counts_pass"])
        self.assertTrue(checks["theorem_frontier_target_signature_lattice_implications_pass"])
        self.assertTrue(checks["theorem_frontier_target_signature_lattice_limits_preserved"])
        self.assertTrue(checks["theorem_frontier_low_weight_extension_sources_pass"])
        self.assertTrue(checks["theorem_frontier_low_weight_extension_counts_pass"])
        self.assertTrue(checks["theorem_frontier_low_weight_extension_singleton_pass"])
        self.assertTrue(checks["theorem_frontier_low_weight_extension_pair_pass"])
        self.assertTrue(checks["theorem_frontier_low_weight_extension_blockers_pass"])
        self.assertTrue(checks["theorem_frontier_low_weight_extension_limits_preserved"])
        self.assertTrue(checks["anchor_h1_generator_classification_sources_pass"])
        self.assertTrue(checks["anchor_h1_generator_classification_path_h1_zero"])
        self.assertTrue(checks["anchor_h1_generator_classification_cycle_generator"])
        self.assertTrue(checks["anchor_h1_generator_classification_opinion_audited"])
        self.assertTrue(checks["release_scaffold_sources_pass"])
        self.assertTrue(checks["release_scaffold_docs_present"])
        self.assertTrue(checks["release_scaffold_inherits_finite_ledger"])
        self.assertTrue(checks["release_scaffold_limits_preserved"])
        self.assertTrue(checks["release_source_coverage_sources_pass"])
        self.assertTrue(checks["release_source_coverage_families_pass"])
        self.assertTrue(checks["release_source_coverage_lagrangian_eom_pass"])
        self.assertTrue(checks["release_source_coverage_limits_preserved"])
        self.assertTrue(checks["release_traceability_matrix_sources_pass"])
        self.assertTrue(checks["release_traceability_matrix_rank_pass"])
        self.assertTrue(checks["release_traceability_matrix_inherits_open_frontier"])
        self.assertTrue(checks["release_traceability_matrix_limits_preserved"])
        self.assertTrue(checks["toe_potential_readiness_sources_pass"])
        self.assertTrue(checks["toe_potential_readiness_doc_pass"])
        self.assertTrue(checks["toe_potential_readiness_frontier_counts_pass"])
        self.assertTrue(checks["toe_potential_readiness_low_weight_pass"])
        self.assertTrue(checks["toe_potential_readiness_limits_preserved"])
        self.assertTrue(checks["toe_proper_subset_obstruction_sources_pass"])
        self.assertTrue(checks["toe_proper_subset_obstruction_counts_pass"])
        self.assertTrue(checks["toe_proper_subset_obstruction_nearest_miss_pass"])
        self.assertTrue(checks["toe_proper_subset_obstruction_all_fail_pass"])
        self.assertTrue(checks["toe_proper_subset_obstruction_limits_preserved"])
        self.assertTrue(checks["toe_boolean_normal_form_sources_pass"])
        self.assertTrue(checks["toe_boolean_normal_form_component_degrees_pass"])
        self.assertTrue(checks["toe_boolean_normal_form_full_monomial_pass"])
        self.assertTrue(checks["toe_boolean_normal_form_inherits_obstruction_pass"])
        self.assertTrue(checks["toe_boolean_normal_form_limits_preserved"])
        self.assertTrue(checks["toe_boolean_essentiality_sources_pass"])
        self.assertTrue(checks["toe_boolean_essentiality_derivative_counts_pass"])
        self.assertTrue(checks["toe_boolean_essentiality_nearest_misses_pass"])
        self.assertTrue(checks["toe_boolean_essentiality_inherits_normal_form_pass"])
        self.assertTrue(checks["toe_boolean_essentiality_limits_preserved"])
        self.assertTrue(checks["toe_conditional_closure_sources_pass"])
        self.assertTrue(checks["toe_conditional_closure_sequents_pass"])
        self.assertTrue(checks["toe_conditional_closure_full_row_pass"])
        self.assertTrue(checks["toe_conditional_closure_inherits_boolean_frontier_pass"])
        self.assertTrue(checks["toe_conditional_closure_limits_preserved"])

        summary = payload["chain_summary"]
        self.assertTrue(summary["exact_APD_completion_certified"])
        self.assertTrue(summary["transport_cocycle_certified"])
        self.assertTrue(summary["phase_sign_source_certified"])
        self.assertTrue(summary["phase_node_clearance_certified"])
        self.assertTrue(summary["phase_cell_partition_certified"])
        self.assertTrue(summary["phase_carrier_edge_incidence_certified"])
        self.assertTrue(summary["phase_carrier_prefix_node_matrix_certified"])
        self.assertTrue(summary["phase_gf2_commutative_diagram_certified"])
        self.assertTrue(summary["phase_path_cohomology_triviality_certified"])
        self.assertTrue(summary["phase_reduced_coboundary_inverse_certified"])
        self.assertTrue(summary["phase_node_support_interval_boundary_certified"])
        self.assertTrue(summary["phase_flip_pair_interval_reconstruction_certified"])
        self.assertTrue(summary["phase_support_euler_characteristic_certified"])
        self.assertTrue(summary["phase_component_quotient_adjacency_certified"])
        self.assertTrue(summary["phase_component_quotient_lift_matrix_certified"])
        self.assertTrue(summary["phase_component_quotient_projection_certified"])
        self.assertTrue(summary["phase_component_quotient_exact_sequence_certified"])
        self.assertTrue(summary["phase_component_quotient_complement_inverse_certified"])
        self.assertTrue(summary["phase_component_quotient_coordinate_isomorphism_certified"])
        self.assertTrue(summary["phase_component_quotient_dual_basis_certified"])
        self.assertTrue(summary["phase_component_quotient_coordinate_support_minimality_certified"])
        self.assertTrue(summary["phase_component_quotient_coordinate_residual_syndrome_certified"])
        self.assertTrue(summary["phase_component_quotient_coordinate_syndrome_decoder_certified"])
        self.assertTrue(summary["phase_component_quotient_coordinate_syndrome_generator_basis_certified"])
        self.assertTrue(summary["phase_cycle_closure_boundary_certified"])
        self.assertTrue(summary["phase_cell_sign_certified"])
        self.assertTrue(summary["phase_z2_coboundary_certified"])
        self.assertTrue(summary["phase_edge_support_minimality_certified"])
        self.assertTrue(summary["phase_gf2_linear_system_certified"])
        self.assertTrue(summary["damping_envelope_certified"])
        self.assertTrue(summary["damping_exact_rational_calculus_certified"])
        self.assertTrue(summary["positive_factor_sign_separation_certified"])
        self.assertTrue(summary["simple_transport_readings_rejected"])
        self.assertFalse(summary["strict_dynamic_derivation_exported"])
        self.assertFalse(summary["bridge_theorem_exported"])
        self.assertTrue(summary["closure_plan_dependency_certified"])
        self.assertTrue(summary["s1_selector_margin_obstruction_certified"])
        self.assertTrue(summary["legacy_kernel_intermediate_bridge_guardrail_certified"])
        self.assertTrue(summary["legacy_to_strict_component_gap_matrix_certified"])
        self.assertTrue(summary["legacy_to_strict_damping_compression_separation_certified"])
        self.assertTrue(summary["legacy_to_strict_amplitude_scalar_normalization_certified"])
        self.assertTrue(summary["legacy_to_strict_finite_diagonal_completion_map_certified"])
        self.assertTrue(summary["legacy_to_strict_phase_frequency_affine_transport_certified"])
        self.assertTrue(summary["legacy_to_strict_damping_parameter_identifiability_certified"])
        self.assertTrue(summary["legacy_to_strict_finite_bridge_assembly_certified"])
        self.assertTrue(summary["legacy_to_strict_symbolic_cancellation_certified"])
        self.assertTrue(summary["legacy_role_transfer_pre_audit_certified"])
        self.assertTrue(summary["legacy_role_transfer_minimal_obligation_lattice_certified"])
        self.assertTrue(summary["theorem_frontier_cut_certified"])
        self.assertTrue(summary["theorem_frontier_truth_table_certified"])
        self.assertTrue(summary["theorem_frontier_atom_influence_certified"])
        self.assertTrue(summary["theorem_frontier_target_signature_lattice_certified"])
        self.assertTrue(summary["theorem_frontier_low_weight_extension_certified"])
        self.assertTrue(summary["anchor_h1_generator_classification_certified"])
        self.assertTrue(summary["release_scaffold_certified"])
        self.assertTrue(summary["release_source_coverage_certified"])
        self.assertTrue(summary["release_traceability_matrix_certified"])

    def test_frontier_proof_guardrails_and_markdown(self):
        frontier = self.payload["frontier_statement"]
        self.assertIn("internally consistent", frontier["positive_content"])
        self.assertIn("does not derive", frontier["negative_content"])
        self.assertIn("strict_phase_frequency", frontier["next_real_blocker"])
        self.assertIn("orientation_chi11_source", frontier["next_real_blocker"])
        self.assertIn("finite diagonal, continuous phase-affine, beta/eta identifiability, assembled A*P*D, and symbolic cancellation maps are exact", frontier["next_real_blocker"])

        proof = self.payload["proof_certificate"]
        self.assertIn("All prerequisite JSON reports", proof["ledger_step"])
        self.assertIn("common sign pattern", proof["shared_object_step"])
        self.assertIn("A+P+D", proof["factor_step"])
        self.assertIn("positive rational clearance", proof["node_clearance_step"])
        self.assertIn("ordered, disjoint", proof["cell_partition_step"])
        self.assertIn("column rank 4", proof["carrier_edge_incidence_step"])
        self.assertIn("C=L*M", proof["carrier_prefix_node_matrix_step"])
        self.assertIn("B*node_bits=edge_bits", proof["gf2_commutative_diagram_step"])
        self.assertIn("H^1(path;GF(2)) has dimension 0", proof["path_cohomology_step"])
        self.assertIn("rank(R)=11", proof["reduced_coboundary_inverse_step"])
        self.assertIn("R*P=I_11", proof["reduced_coboundary_inverse_step"])
        self.assertIn("[2,5] U [8,9]", proof["node_support_interval_boundary_step"])
        self.assertIn("rank 2", proof["node_support_interval_boundary_step"])
        self.assertIn("four flip edges", proof["node_support_interval_boundary_step"])
        self.assertIn("[1,5,7,9]", proof["flip_pair_interval_reconstruction_step"])
        self.assertIn("entry/exit cuts", proof["flip_pair_interval_reconstruction_step"])
        self.assertIn("no endpoint support", proof["flip_pair_interval_reconstruction_step"])
        self.assertIn("V=6", proof["support_euler_characteristic_step"])
        self.assertIn("V-E=C", proof["support_euler_characteristic_step"])
        self.assertIn("boundary_weight=2*C=4", proof["support_euler_characteristic_step"])
        self.assertIn("+[0,1]", proof["component_quotient_adjacency_step"])
        self.assertIn("V=5", proof["component_quotient_adjacency_step"])
        self.assertIn("four flip edges", proof["component_quotient_adjacency_step"])
        self.assertIn("S*q=node_bits", proof["component_quotient_lift_matrix_step"])
        self.assertIn("B_path*S=E*B_quotient", proof["component_quotient_lift_matrix_step"])
        self.assertIn("rank(S)=5", proof["component_quotient_lift_matrix_step"])
        self.assertIn("Q*node_bits=q", proof["component_quotient_projection_step"])
        self.assertIn("Q*S=I_5", proof["component_quotient_projection_step"])
        self.assertIn("H*B_path*S=0", proof["component_quotient_projection_step"])
        self.assertIn("rank 7", proof["component_quotient_exact_sequence_step"])
        self.assertIn("im(S)=ker(F)", proof["component_quotient_exact_sequence_step"])
        self.assertIn("S*Q fixes", proof["component_quotient_exact_sequence_step"])
        self.assertIn("[S N] has rank 12", proof["component_quotient_complement_inverse_step"])
        self.assertIn("Q*N=0", proof["component_quotient_complement_inverse_step"])
        self.assertIn("two-sided inverse", proof["component_quotient_complement_inverse_step"])
        self.assertIn("T=[Q;F]", proof["component_quotient_coordinate_isomorphism_step"])
        self.assertIn("U=[S | N*(F*N)^(-1)]", proof["component_quotient_coordinate_isomorphism_step"])
        self.assertIn("T*U=I_12", proof["component_quotient_coordinate_isomorphism_step"])
        self.assertIn("<T_i,U_j>=delta_ij", proof["component_quotient_dual_basis_step"])
        self.assertIn("b=sum_i(T_i b)U_i", proof["component_quotient_dual_basis_step"])
        self.assertIn("quotient_component_1", proof["component_quotient_dual_basis_step"])
        self.assertIn("2^12 coordinate vectors", proof["component_quotient_coordinate_support_minimality_step"])
        self.assertIn("unique minimum support", proof["component_quotient_coordinate_support_minimality_step"])
        self.assertIn("quotient_component_3", proof["component_quotient_coordinate_support_minimality_step"])
        self.assertIn("2^12 residual syndromes", proof["component_quotient_coordinate_residual_syndrome_step"])
        self.assertIn("zero syndrome", proof["component_quotient_coordinate_residual_syndrome_step"])
        self.assertIn("4095 nonmatching coordinates", proof["component_quotient_coordinate_residual_syndrome_step"])
        self.assertIn("c+T*r(c)=c_target", proof["component_quotient_coordinate_syndrome_decoder_step"])
        self.assertIn("U*T*s=s", proof["component_quotient_coordinate_syndrome_decoder_step"])
        self.assertIn("2^12 residual syndromes", proof["component_quotient_coordinate_syndrome_decoder_step"])
        self.assertIn("T*U_i=e_i", proof["component_quotient_coordinate_syndrome_generator_basis_step"])
        self.assertIn("4096*12 hypercube edge", proof["component_quotient_coordinate_syndrome_generator_basis_step"])
        self.assertIn("r(c+e_i)+r(c)=U_i", proof["component_quotient_coordinate_syndrome_generator_basis_step"])
        self.assertIn("bridge guardrail", proof["closure_plan_dependency_step"])
        self.assertIn("QW-2191/orientation", proof["closure_plan_dependency_step"])
        self.assertIn("no closure claim", proof["closure_plan_dependency_step"])
        self.assertIn("no S1 witness is exported", proof["s1_selector_margin_obstruction_step"])
        self.assertIn("worst_margin_to_target=-0.99", proof["s1_selector_margin_obstruction_step"])
        self.assertIn("never become positive", proof["s1_selector_margin_obstruction_step"])
        self.assertIn("intermediate incomplete bridge kernel", proof["legacy_kernel_intermediate_bridge_guardrail_step"])
        self.assertIn("role-transfer audit is required after full bridge", proof["legacy_kernel_intermediate_bridge_guardrail_step"])
        self.assertIn("beta_tors->chi_11/QW-2191/ToE remain open", proof["legacy_kernel_intermediate_bridge_guardrail_step"])
        self.assertIn("amplitude, phase/frequency transport, damping/compression", proof["legacy_to_strict_component_gap_matrix_step"])
        self.assertIn("every row has a finite certificate", proof["legacy_to_strict_component_gap_matrix_step"])
        self.assertIn("matrix rank 2", proof["legacy_to_strict_component_gap_matrix_step"])
        self.assertIn("gamma=d^(4/5)", proof["legacy_to_strict_damping_compression_separation_step"])
        self.assertIn("no single legacy-linear torsion gamma", proof["legacy_to_strict_damping_compression_separation_step"])
        self.assertIn("best L2 linear fit", proof["legacy_to_strict_damping_compression_separation_step"])
        self.assertIn("K_legacy_ont(d)=alpha_geo*L_shape(d)", proof["legacy_to_strict_amplitude_scalar_normalization_step"])
        self.assertIn("alpha_geo^{-1} removes only the global scalar", proof["legacy_to_strict_amplitude_scalar_normalization_step"])
        self.assertIn("does not derive strict A(d)", proof["legacy_to_strict_amplitude_scalar_normalization_step"])
        self.assertIn("Q=diag(K_strict/K_legacy)", proof["legacy_to_strict_finite_diagonal_completion_map_step"])
        self.assertIn("GF(2) support rank 12", proof["legacy_to_strict_finite_diagonal_completion_map_step"])
        self.assertIn("not a source theorem", proof["legacy_to_strict_finite_diagonal_completion_map_step"])
        self.assertIn("theta_L(x(d))=theta_S(d)", proof["legacy_to_strict_phase_frequency_affine_transport_step"])
        self.assertIn("rejects Z12 unit+offset reindexing", proof["legacy_to_strict_phase_frequency_affine_transport_step"])
        self.assertIn("does not export omega/phi source", proof["legacy_to_strict_phase_frequency_affine_transport_step"])
        self.assertIn("beta=S(1)-1=1", proof["legacy_to_strict_damping_parameter_identifiability_step"])
        self.assertIn("(S(d)-1)^5=d^9", proof["legacy_to_strict_damping_parameter_identifiability_step"])
        self.assertIn("does not export a strict beta/eta source", proof["legacy_to_strict_damping_parameter_identifiability_step"])
        self.assertIn("K_legacy_ont(d)*A(d)*P(d)*D(d)=K_strict_gate(d)", proof["legacy_to_strict_finite_bridge_assembly_step"])
        self.assertIn("Q_assembly=diag(K_strict/K_legacy)", proof["legacy_to_strict_finite_bridge_assembly_step"])
        self.assertIn("T99 comparison scope", proof["legacy_to_strict_finite_bridge_assembly_step"])
        self.assertIn("(alpha*cL/Lden)*(1/alpha)*(cS/cL)*(Lden/Sden)=cS/Sden", proof["legacy_to_strict_symbolic_cancellation_step"])
        self.assertIn("alpha!=0", proof["legacy_to_strict_symbolic_cancellation_step"])
        self.assertIn("do not derive sources or role transfer", proof["legacy_to_strict_symbolic_cancellation_step"])
        self.assertIn("GF(2) dependency matrix of rank 4", proof["legacy_role_transfer_pre_audit_step"])
        self.assertIn("blocks all four roles", proof["legacy_role_transfer_pre_audit_step"])
        self.assertIn("missing alpha_geo, beta_tors, and chi_11", proof["legacy_role_transfer_pre_audit_step"])
        self.assertIn("enumerates all 16 subsets", proof["legacy_role_transfer_minimal_obligation_lattice_step"])
        self.assertIn("one all-role minimal set of size 4", proof["legacy_role_transfer_minimal_obligation_lattice_step"])
        self.assertIn("beta_tors is the shared bottleneck", proof["legacy_role_transfer_minimal_obligation_lattice_step"])
        self.assertIn("acyclic 15-node dependency DAG", proof["theorem_frontier_cut_step"])
        self.assertIn("ToE open leaf cut of size 7", proof["theorem_frontier_cut_step"])
        self.assertIn("no closure atom is exported", proof["theorem_frontier_cut_step"])
        self.assertIn("2^7=128 assignments", proof["theorem_frontier_truth_table_step"])
        self.assertIn("minimal weight 3", proof["theorem_frontier_truth_table_step"])
        self.assertIn("current all-false assignment closes no target", proof["theorem_frontier_truth_table_step"])
        self.assertIn("exports no atom", proof["theorem_frontier_truth_table_step"])
        self.assertIn("7*4*64 finite atom-target cases", proof["theorem_frontier_atom_influence_step"])
        self.assertIn("unique top logical bottleneck", proof["theorem_frontier_atom_influence_step"])
        self.assertIn("total critical count 73", proof["theorem_frontier_atom_influence_step"])
        self.assertIn("tie at 17", proof["theorem_frontier_atom_influence_step"])
        self.assertIn("promoted to a theorem source", proof["theorem_frontier_atom_influence_step"])
        self.assertIn("exactly 6 reachable signatures out of 16", proof["theorem_frontier_target_signature_lattice_step"])
        self.assertIn("role-transfer closure implies selector closure", proof["theorem_frontier_target_signature_lattice_step"])
        self.assertIn("ToE closure implies all targets", proof["theorem_frontier_target_signature_lattice_step"])
        self.assertIn("no signature is promoted to closure", proof["theorem_frontier_target_signature_lattice_step"])
        self.assertIn("all 7 singleton and 21 pair extensions", proof["theorem_frontier_low_weight_extension_step"])
        self.assertIn("chi11_selector_source is the only singleton unlock", proof["theorem_frontier_low_weight_extension_step"])
        self.assertIn("all contain chi11", proof["theorem_frontier_low_weight_extension_step"])
        self.assertIn("no singleton or pair closes bridge", proof["theorem_frontier_low_weight_extension_step"])
        self.assertIn("C0 gauge fix", proof["anchor_h1_generator_classification_step"])
        self.assertIn("C1/im(delta) H^1 generator", proof["anchor_h1_generator_classification_step"])
        self.assertIn("accepted only in weak form", proof["anchor_h1_generator_classification_step"])
        self.assertIn("DIAGRAMS_STRICT_KERNEL_TRANSFORMATION.md", proof["release_scaffold_step"])
        self.assertIn("STRICT_KERNEL_LAGRANGIAN_AND_EOM_DRAFT.md", proof["release_scaffold_step"])
        self.assertIn("STRICT_KERNEL_LEGACY_ROLE_TRANSFER_AUDIT_DRAFT.md", proof["release_scaffold_step"])
        self.assertIn("P1866/P2315", proof["release_scaffold_step"])
        self.assertIn("no identity bridge", proof["release_scaffold_step"])
        self.assertIn("broad rg grep provenance", proof["release_source_coverage_step"])
        self.assertIn("P1622/P1866/P2315/P2316", proof["release_source_coverage_step"])
        self.assertIn("N87/N103", proof["release_source_coverage_step"])
        self.assertIn("no full EOM closure", proof["release_source_coverage_step"])
        self.assertIn("6x4 source-to-section matrix", proof["release_traceability_matrix_step"])
        self.assertIn("GF(2) rank 4", proof["release_traceability_matrix_step"])
        self.assertIn("bookkeeping only", proof["release_traceability_matrix_step"])
        self.assertIn("professor-level finite assessment", proof["toe_potential_readiness_step"])
        self.assertIn("1 of 128", proof["toe_potential_readiness_step"])
        self.assertIn("minimal ToE weight is 7", proof["toe_potential_readiness_step"])
        self.assertIn("6 reachable signatures out of 16", proof["toe_potential_readiness_step"])
        self.assertIn("unique top bottleneck", proof["toe_potential_readiness_step"])
        self.assertIn("not ToE closure", proof["toe_potential_readiness_step"])
        self.assertIn("all 127 proper subsets", proof["toe_proper_subset_obstruction_step"])
        self.assertIn("toe_closure=false", proof["toe_proper_subset_obstruction_step"])
        self.assertIn("seven six-atom nearest misses", proof["toe_proper_subset_obstruction_step"])
        self.assertIn("no six-or-fewer atom package", proof["toe_proper_subset_obstruction_step"])
        self.assertIn("GF(2) ANF", proof["toe_boolean_normal_form_step"])
        self.assertIn("single degree-3 monomial", proof["toe_boolean_normal_form_step"])
        self.assertIn("single degree-7 full-frontier monomial", proof["toe_boolean_normal_form_step"])
        self.assertIn("no lower-degree ANF terms", proof["toe_boolean_normal_form_step"])
        self.assertIn("not ToE closure", proof["toe_boolean_normal_form_step"])
        self.assertIn("finite Boolean derivatives", proof["toe_boolean_essentiality_step"])
        self.assertIn("derivative support count 1", proof["toe_boolean_essentiality_step"])
        self.assertIn("six-atom nearest miss", proof["toe_boolean_essentiality_step"])
        self.assertIn("nonparticipants have zero", proof["toe_boolean_essentiality_step"])
        self.assertIn("not ToE closure", proof["toe_boolean_essentiality_step"])
        self.assertIn("four finite sequents", proof["toe_conditional_closure_step"])
        self.assertIn("all seven atoms imply all four target bits", proof["toe_conditional_closure_step"])
        self.assertIn("current zero-atom row remains unclosed", proof["toe_conditional_closure_step"])
        self.assertIn("assumption-conditional closure", proof["toe_conditional_closure_step"])
        self.assertIn("not unconditional ToE closure", proof["toe_conditional_closure_step"])
        self.assertIn("closed 12-cycle", proof["cycle_closure_step"])
        self.assertIn("odd closing-edge perturbation", proof["cycle_closure_step"])
        self.assertIn("without fresh trigonometric evaluation", proof["cell_sign_step"])
        self.assertIn("every interval parity law", proof["z2_coboundary_step"])
        self.assertIn("2^11 edge assignments", proof["edge_support_minimality_step"])
        self.assertIn("rank 11", proof["gf2_linear_system_step"])
        self.assertIn("phase only", proof["envelope_step"])
        self.assertIn("-179/100", proof["exact_damping_step"])
        self.assertIn("zero Z2 sign bits", proof["positive_factor_sign_step"])

        hard_limits = "\n".join(self.payload["hard_limits"])
        self.assertIn("K_strict_gate remains the current live/full", hard_limits)
        self.assertIn("No unqualified identity K_legacy_ont == K_strict_gate", hard_limits)
        self.assertIn("No proof derives A(d), P(d), D(d)", hard_limits)
        self.assertIn("No beta_tors -> chi_11 theorem", hard_limits)
        self.assertIn("No QW-2191 selector discharge", hard_limits)
        self.assertIn("No ToE closure", hard_limits)
        self.assertTrue(REPORT_MD.exists())


if __name__ == "__main__":
    unittest.main()
