#!/usr/bin/env python3
"""Scratch theorem-prep probe: recursive phase-normalized Puiseux inverse.

The eta+1 packet showed a hand-derived next coefficient in a local two-channel
near-field map.  This probe turns that computation into a finite recurrence.
For eta=9/5, it solves

    L_legacy_norm(x(d)) = S_strict_norm(d)

as a generalized Puiseux series with exponents generated by 1 and eta, through
a fixed cutoff.  Because the normalized legacy kernel has a nonzero linear
coefficient, the recurrence can solve one coefficient at a time.

Honest interpretation: this is a local formal inverse witness, not a physical
bridge.  In fact, its existence is partly a warning: local reparameterization is
too easy unless a strict-side transport/RG law derives the coefficients.
"""
from __future__ import annotations

import json
import math
from collections import defaultdict
from fractions import Fraction
from pathlib import Path
from typing import Any

import numpy as np

HERE = Path(__file__).resolve().parent
OUT_JSON = HERE / "bridge_phase_normalized_formal_inverse_report.json"
OUT_MD = HERE / "bridge_phase_normalized_formal_inverse_report.md"
ETA_PLUS_ONE = HERE / "bridge_phase_normalized_puiseux_eta_plus_one_report.json"
ROBUSTNESS = HERE / "bridge_strict_kernel_robustness_opinion_audit_report.json"

ETA = Fraction(9, 5)
MAX_EXP = Fraction(5, 1)
ALPHA_GEO = 4.0 * math.log(2.0)
LEGACY = {"omega": math.pi / 4.0, "phi": math.pi / 6.0, "beta_tors": 0.01}
STRICT = {"omega": 0.18575, "phi": 0.16250, "beta": 1.0, "eta": float(ETA)}
SMALL_D = np.array([1e-4, 1e-3, 1e-2, 2e-2, 5e-2], dtype=float)

Series = dict[Fraction, float]


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def exponent_label(exp: Fraction) -> str:
    if exp.denominator == 1:
        return str(exp.numerator)
    return f"{exp.numerator}/{exp.denominator}"


def trig_ratio_coeff(omega: float, phi: float, n: int) -> float:
    """Coefficient of cos(omega*x+phi)/cos(phi) at x^n."""
    if n % 2 == 0:
        k = n // 2
        return ((-1.0) ** k) * omega**n / math.factorial(n)
    k = (n - 1) // 2
    return -math.tan(phi) * ((-1.0) ** k) * omega**n / math.factorial(n)


def legacy_coefficients(max_n: int) -> dict[int, float]:
    out: dict[int, float] = {}
    beta_t = LEGACY["beta_tors"]
    for n in range(max_n + 1):
        out[n] = sum(trig_ratio_coeff(LEGACY["omega"], LEGACY["phi"], i) * ((-beta_t) ** (n - i)) for i in range(n + 1))
    return out


def strict_series(max_exp: Fraction) -> Series:
    ordinary_max = int(max_exp)
    carrier = {Fraction(n, 1): trig_ratio_coeff(STRICT["omega"], STRICT["phi"], n) for n in range(ordinary_max + 1)}
    damping = {k * ETA: (-1.0) ** k for k in range(int(max_exp / ETA) + 1)}
    out: defaultdict[Fraction, float] = defaultdict(float)
    for e1, c1 in carrier.items():
        for e2, c2 in damping.items():
            exp = e1 + e2
            if exp <= max_exp:
                out[exp] += c1 * c2
    return dict(out)


def exponent_grid(max_exp: Fraction) -> list[Fraction]:
    exps = set()
    for m in range(int(max_exp) + 1):
        for n in range(int(max_exp / ETA) + 1):
            exp = Fraction(m, 1) + n * ETA
            if 0 < exp <= max_exp:
                exps.add(exp)
    return sorted(exps)


def series_mul(a: Series, b: Series, max_exp: Fraction) -> Series:
    out: defaultdict[Fraction, float] = defaultdict(float)
    for ea, ca in a.items():
        for eb, cb in b.items():
            exp = ea + eb
            if exp <= max_exp:
                out[exp] += ca * cb
    return {exp: coeff for exp, coeff in out.items() if abs(coeff) > 1e-18}


def series_pow(a: Series, power: int, max_exp: Fraction) -> Series:
    if power == 0:
        return {Fraction(0, 1): 1.0}
    out = dict(a)
    for _ in range(power - 1):
        out = series_mul(out, a, max_exp)
    return out


def compose_legacy(x_series: Series, legacy_l: dict[int, float], max_exp: Fraction) -> Series:
    max_power = int(max_exp)  # x starts at exponent 1, so higher powers exceed cutoff.
    out: defaultdict[Fraction, float] = defaultdict(float)
    out[Fraction(0, 1)] += legacy_l[0]
    for power in range(1, max_power + 1):
        xp = series_pow(x_series, power, max_exp)
        for exp, coeff in xp.items():
            out[exp] += legacy_l[power] * coeff
    return dict(out)


def solve_puiseux_recurrence(max_exp: Fraction) -> dict[str, Any]:
    legacy_l = legacy_coefficients(int(max_exp))
    strict = strict_series(max_exp)
    grid = exponent_grid(max_exp)
    x_series: Series = {}
    rows = []
    l1 = legacy_l[1]
    for exp in grid:
        known = compose_legacy(x_series, legacy_l, max_exp).get(exp, 0.0)
        target = strict.get(exp, 0.0)
        coeff = (target - known) / l1
        x_series[exp] = coeff
        rows.append(
            {
                "exponent": exponent_label(exp),
                "exponent_float": float(exp),
                "target_coeff": target,
                "known_without_new_coeff": known,
                "x_coeff": coeff,
                "residual_after_solve": l1 * coeff + known - target,
            }
        )
    composed = compose_legacy(x_series, legacy_l, max_exp)
    residuals = []
    for exp in [Fraction(0, 1)] + grid:
        residuals.append(
            {
                "exponent": exponent_label(exp),
                "legacy_composed_coeff": composed.get(exp, 0.0),
                "strict_coeff": strict.get(exp, 0.0),
                "residual": composed.get(exp, 0.0) - strict.get(exp, 0.0),
            }
        )
    return {
        "legacy_linear_coefficient_nonzero": abs(l1) > 1e-14,
        "legacy_l1": l1,
        "legacy_coefficients": {str(k): v for k, v in legacy_l.items()},
        "strict_series_coefficients": {exponent_label(k): v for k, v in sorted(strict.items())},
        "x_series_coefficients": {exponent_label(k): v for k, v in sorted(x_series.items())},
        "recurrence_rows": rows,
        "coefficient_residuals": residuals,
        "max_abs_coefficient_residual": max(abs(row["residual"]) for row in residuals),
    }


def legacy_normalized(x: np.ndarray) -> np.ndarray:
    return np.cos(LEGACY["omega"] * x + LEGACY["phi"]) / math.cos(LEGACY["phi"]) / (1.0 + LEGACY["beta_tors"] * x)


def strict_normalized(d: np.ndarray) -> np.ndarray:
    return np.cos(STRICT["omega"] * d + STRICT["phi"]) / math.cos(STRICT["phi"]) / (1.0 + d ** float(ETA))


def sample_rows(x_coeffs: dict[str, float]) -> list[dict[str, float]]:
    rows = []
    for value in SMALL_D:
        x = 0.0
        for label, coeff in x_coeffs.items():
            if "/" in label:
                num, den = [int(part) for part in label.split("/")]
                exp = num / den
            else:
                exp = float(label)
            x += coeff * value**exp
        residual = float(legacy_normalized(np.array([x]))[0] - strict_normalized(np.array([value]))[0])
        rows.append(
            {
                "d": float(value),
                "x_truncated": x,
                "residual": residual,
                "abs_residual_over_d_next_order_5p4": abs(residual) / value ** (float(MAX_EXP) + float(ETA) - 1.0),
            }
        )
    return rows


def main() -> None:
    previous = load_json(ETA_PLUS_ONE)
    robustness = load_json(ROBUSTNESS)
    recurrence = solve_puiseux_recurrence(MAX_EXP)
    rows = sample_rows(recurrence["x_series_coefficients"])

    report = {
        "status": "OPEN_PHASE_NORMALIZED_FORMAL_INVERSE_TRACE_NO_BRIDGE_THEOREM",
        "result_kind": "SCRATCH_PHASE_NORMALIZED_FORMAL_INVERSE_PROBE__NOT_A_THEOREM",
        "source_reports": {
            "eta_plus_one_puiseux": str(ETA_PLUS_ONE.relative_to(HERE.parents[1])),
            "strict_kernel_robustness": str(ROBUSTNESS.relative_to(HERE.parents[1])),
        },
        "constants": {"alpha_geo": ALPHA_GEO, "eta": str(ETA), "max_exp": str(MAX_EXP), "legacy": LEGACY, "strict": STRICT},
        "formal_inverse_recurrence": recurrence,
        "sample_residual_rows": rows,
        "upstream_replay": {
            "eta_plus_one_match": previous["coefficient_match_passes_through_eta_plus_one"],
            "eta_plus_one_first_unmatched_order": previous["coefficient_match"]["first_unmatched_expected_order"],
            "robustness_support": robustness["support_score"],
        },
        "honest_interpretation": [
            "A local formal Puiseux inverse exists through the cutoff because the normalized legacy linear coefficient is nonzero.",
            "This explains why finite-order local matching can keep succeeding; by itself it is not evidence of a physical bridge.",
            "The real proof obligation is deriving the recurrence coefficients from strict-side transport/RG structure or proving that no such derivation exists.",
        ],
        "hard_limits": [
            "No identity K_legacy_ont == K_strict_gate is exported.",
            "No global Z12 distance map is derived.",
            "No strict-side physical transport law deriving the formal inverse is exported.",
            "No legacy physical-role transfer is licensed.",
            "No QW-2191 selector discharge and no ToE closure are claimed.",
        ],
        "next_honest_step": "Stop treating local coefficient matching as sufficient; seek a strict-side recurrence law for the Puiseux coefficients, with a non-arbitrary initial condition and global admissibility constraints.",
    }

    OUT_JSON.write_text(json.dumps(report, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")
    OUT_MD.write_text(
        "# Scratch phase-normalized formal inverse probe\n\n"
        "Status: recursive Puiseux inverse through cutoff; no bridge theorem.\n\n"
        f"- Legacy normalized linear coefficient nonzero: `{recurrence['legacy_linear_coefficient_nonzero']}` with `L1={recurrence['legacy_l1']:.12f}`.\n"
        f"- Solved `{len(recurrence['recurrence_rows'])}` Puiseux coefficients through exponent `{MAX_EXP}`; max coefficient residual `{recurrence['max_abs_coefficient_residual']:.3e}`.\n"
        "- Honest read: finite-order local matching is expected from invertibility; it is not yet a physical bridge.\n"
        "- Required next proof object: strict-side recurrence/transport law plus global Z12 admissibility, not another unconstrained local fit.\n"
        "- No false pass: no kernel identity, no global Z12 map, no strict transport derivation, no QW-2191 discharge, no ToE closure.\n",
        encoding="utf-8",
    )
    print(OUT_JSON)
    print(OUT_MD)


if __name__ == "__main__":
    main()
