#!/usr/bin/env python3
"""Scratch probe: distance-5 band-pass support selector certificate.

The previous distance-histogram polarity certificate showed why the plain
attractive strict-gate Dirichlet action clusters support: it rewards short
internal distances.  This packet checks the simplest polarity-changing support
source that would actually select the fifth-step resonance support class.

Let h_5(S) be the number of internal pairs in a 5-node support S whose cyclic
Z_12 distance is 5.  The graph on Z_12 connecting distance-5 pairs is a 12-cycle
because gcd(5,12)=1.  Therefore any 5-node support induces at most 4 such edges,
and equality is achieved exactly by five consecutive vertices in that distance-5
cycle.  In the ordinary Z_12 labels this is precisely the fifth-step support
orbit generated by step 5/7.

This proves a model-internal conditional selector schema:

    if a strict support action maximizes h_5(S), or equivalently minimizes
    -h_5(S), then the support is forced to the fifth-step orbit.

It still does not derive that band-pass/repulsive support action from strict
nadsoliton geometry, and it does not choose a unique translate/orientation or
ledger assignment.  QW-2191 remains open.
"""
from __future__ import annotations

import itertools
import json
import math
from fractions import Fraction
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
POLARITY = HERE / "bridge_strict_alpha_support_distance_histogram_polarity_certificate_report.json"
OUT_JSON = HERE / "bridge_strict_alpha_bandpass_d5_support_selector_certificate_report.json"
OUT_MD = HERE / "bridge_strict_alpha_bandpass_d5_support_selector_certificate_report.md"

Z12_NODE_COUNT = 12
SUPPORT_SIZE = 5
DISTANCE_SELECTED = 5
TARGET_BINARY_EXPONENT = 8
DENOMINATOR = 3
STRICT_TARGET_ETA = 9.0 / 5.0
NAD12_SUPPORT_SIZE = 12
ALPHA_SCALE = 4.0
FIFTH_STEP_SUPPORT_ORDERED = (0, 7, 2, 9, 4)
FIFTH_STEP_SUPPORT = tuple(sorted(FIFTH_STEP_SUPPORT_ORDERED))
CONTIGUOUS_SUPPORT = (0, 1, 2, 3, 4)
BALANCED_LEDGER = (2, 2, 2, 1, 1)


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def cyclic_distance(left: int, right: int) -> int:
    raw = abs(left - right) % Z12_NODE_COUNT
    return min(raw, Z12_NODE_COUNT - raw)


def distance_histogram(support: tuple[int, ...]) -> tuple[int, ...]:
    counts = [0] * (Z12_NODE_COUNT // 2)
    for left, right in itertools.combinations(support, 2):
        counts[cyclic_distance(left, right) - 1] += 1
    return tuple(counts)


def h5_count(support: tuple[int, ...]) -> int:
    return distance_histogram(support)[DISTANCE_SELECTED - 1]


def eta_from_product(product: Fraction, branch_count: int) -> float:
    correction = float(product) ** (1.0 / branch_count)
    return math.log(NAD12_SUPPORT_SIZE * correction) / math.log(ALPHA_SCALE)


def distance_cycle_support(start: int, step: int = DISTANCE_SELECTED) -> tuple[int, ...]:
    return tuple(sorted((start + index * step) % Z12_NODE_COUNT for index in range(SUPPORT_SIZE)))


def fifth_step_orbit_supports() -> list[tuple[int, ...]]:
    supports = []
    for start in range(Z12_NODE_COUNT):
        support = distance_cycle_support(start, DISTANCE_SELECTED)
        if support not in supports:
            supports.append(support)
    return supports


def support_gap_signature(support: tuple[int, ...]) -> tuple[int, ...]:
    nodes = sorted(support)
    return tuple(sorted((nodes[(index + 1) % len(nodes)] - node) % Z12_NODE_COUNT for index, node in enumerate(nodes)))


def support_rows() -> list[dict[str, Any]]:
    rows = []
    for support in itertools.combinations(range(Z12_NODE_COUNT), SUPPORT_SIZE):
        hist = distance_histogram(support)
        rows.append(
            {
                "support": list(support),
                "gap_signature": list(support_gap_signature(support)),
                "distance_histogram": list(hist),
                "h5": hist[DISTANCE_SELECTED - 1],
                "bandpass_energy_minus_h5": -hist[DISTANCE_SELECTED - 1],
            }
        )
    return rows


def induced_cycle_edge_count(support: tuple[int, ...]) -> int:
    support_set = set(support)
    # Count distance-5 graph edges once.  The distance-5 graph is a simple cycle;
    # using +5 counts each undirected edge twice over all vertices, so divide by 2.
    directed_hits = sum(1 for node in support_set if (node + DISTANCE_SELECTED) % Z12_NODE_COUNT in support_set)
    return directed_hits // 2


def main() -> None:
    polarity_report = load_json(POLARITY)
    rows = support_rows()
    max_h5 = max(row["h5"] for row in rows)
    next_best_h5 = max(row["h5"] for row in rows if row["h5"] < max_h5)
    min_bandpass_energy = min(row["bandpass_energy_minus_h5"] for row in rows)
    maximizers = [row for row in rows if row["h5"] == max_h5]
    fifth_orbit = fifth_step_orbit_supports()
    product = Fraction(2 ** TARGET_BINARY_EXPONENT, DENOMINATOR ** SUPPORT_SIZE)
    contiguous_hist = distance_histogram(CONTIGUOUS_SUPPORT)
    fifth_hist = distance_histogram(FIFTH_STEP_SUPPORT)

    report = {
        "status": "OPEN_STRICT_ALPHA_BANDPASS_D5_SUPPORT_SELECTOR_CERTIFICATE_NO_STRICT_SOURCE_THEOREM",
        "result_kind": "SCRATCH_STRICT_ALPHA_BANDPASS_D5_SUPPORT_SELECTOR_CERTIFICATE_PROBE__NOT_A_THEOREM",
        "source_reports": {
            "support_distance_histogram_polarity_certificate": str(POLARITY.relative_to(ROOT)),
        },
        "previous_polarity_replay": {
            "result_kind": polarity_report["result_kind"],
            "plain_dirichlet_gap_formula": polarity_report["contiguous_vs_fifth_certificate"]["exact_two_orbit_gap_formula"],
            "plain_dirichlet_prefers_contiguous": polarity_report["contiguous_vs_fifth_certificate"]["contiguous_is_global_indicator_minimum"],
            "plain_dirichlet_makes_fifth_maximum": polarity_report["contiguous_vs_fifth_certificate"]["fifth_step_is_global_indicator_maximum"],
        },
        "target_identity_replay": {
            "q_power_product": f"{product.numerator}/{product.denominator}",
            "eta_residual_vs_9_5": eta_from_product(product, SUPPORT_SIZE) - STRICT_TARGET_ETA,
            "balanced_ledger": list(BALANCED_LEDGER),
        },
        "distance_5_cycle_theorem": {
            "graph": "G_5 on Z_12 with edges {i,i+5}",
            "gcd_5_12": math.gcd(DISTANCE_SELECTED, Z12_NODE_COUNT),
            "is_single_12_cycle": math.gcd(DISTANCE_SELECTED, Z12_NODE_COUNT) == 1,
            "support_size": SUPPORT_SIZE,
            "max_induced_edges_bound": SUPPORT_SIZE - 1,
            "reason": "A proper k-vertex subset of a cycle induces at most k-1 edges; here k=5 and the distance-5 graph is a 12-cycle.",
        },
        "bandpass_selector_scan": {
            "support_count": len(rows),
            "max_h5": max_h5,
            "next_best_h5": next_best_h5,
            "h5_gap_to_next_best": max_h5 - next_best_h5,
            "min_bandpass_energy_minus_h5": min_bandpass_energy,
            "maximizer_count": len(maximizers),
            "maximizers": maximizers,
            "fifth_step_orbit_supports": [list(support) for support in fifth_orbit],
            "maximizers_equal_fifth_step_orbit": sorted(tuple(row["support"]) for row in maximizers) == sorted(fifth_orbit),
            "fifth_step_support_ordered": list(FIFTH_STEP_SUPPORT_ORDERED),
            "fifth_step_support_canonical": list(FIFTH_STEP_SUPPORT),
            "fifth_step_histogram": list(fifth_hist),
            "contiguous_support": list(CONTIGUOUS_SUPPORT),
            "contiguous_histogram": list(contiguous_hist),
            "contiguous_h5": contiguous_hist[DISTANCE_SELECTED - 1],
            "fifth_step_h5": fifth_hist[DISTANCE_SELECTED - 1],
        },
        "conditional_selector_schema": {
            "support_premise": "strict support action contains a term that maximizes h_5(S), equivalently minimizes -h_5(S)",
            "ledger_premise": "separate convex/Schur-convex ledger selector supplies balanced ledger (2,2,2,1,1)",
            "conditional_output": "support lies in the fifth-step orbit and ledger is balanced",
            "remaining_selector_obligations": [
                "derive the h_5 band-pass/repulsive support action from strict nadsoliton geometry",
                "choose a unique translate/source phase inside the 12-support orbit",
                "choose orientation/order and assignment of the balanced ledger on the support",
                "discharge QW-2191 rather than adding the support premise by hand",
            ],
        },
        "candidate_interpretation": {
            "supported_by_this_probe": True,
            "content": "A clean support selector exists at the finite model level: maximizing distance-5 internal pairs selects exactly the fifth-step support orbit.",
            "why_this_is_more_proof_like": "The graph-theoretic bound h_5<=4 follows from the distance-5 graph being a 12-cycle, and the exhaustive scan confirms exactly 12 maximizers, the fifth-step translates.",
            "why_this_is_not_enough": "The probe does not derive the required distance-5 band-pass action or the remaining translate/orientation/assignment selector from strict nadsoliton geometry.",
        },
        "hard_limits": [
            "No identity K_legacy_ont == K_strict_gate is exported.",
            "No legacy physical-role transfer is licensed.",
            "The distance-5 band-pass support selector is a conditional model-internal support premise, not a derived strict nadsoliton action theorem.",
            "No theorem derives branch count m=5, total exponent n=8, denominator 3, or binary-rescale quotient.",
            "The fifth-step orbit is selected only up to translate; no unique source phase, orientation, or assignment theorem is exported.",
            "No Aut(Z_12)/N462/QW-2191 selector obstruction is discharged.",
            "No theorem derives eta=9/5 without the branch model, denominator/quotient convention, convex ledger selector, and distance-5 support premise.",
            "No QW-2191 selector discharge and no ToE closure are claimed.",
        ],
        "next_honest_step": "Try to derive a strict distance-5 band-pass/repulsive support term from nadsoliton geometry; otherwise keep h_5 maximization as an explicit non-strict support axiom.",
    }

    OUT_JSON.write_text(json.dumps(report, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")
    OUT_MD.write_text(
        "# Scratch strict-alpha band-pass d5 support selector certificate probe\n\n"
        "Status: distance-5 band-pass support selector certificate; no strict source theorem.\n\n"
        f"- Graph fact: distance-5 edges on `Z12` form one 12-cycle because `gcd(5,12)={math.gcd(DISTANCE_SELECTED, Z12_NODE_COUNT)}`.\n"
        f"- Support scan: `{len(rows)}` supports; max `h5={max_h5}`, next-best `h5={next_best_h5}`, maximizers `{len(maximizers)}`.\n"
        f"- Maximizers equal fifth-step orbit: `{sorted(tuple(row['support']) for row in maximizers) == sorted(fifth_orbit)}`.\n"
        f"- Fifth-step histogram `{list(fifth_hist)}` vs contiguous histogram `{list(contiguous_hist)}`.\n"
        f"- Target replay: `q^5={product.numerator}/{product.denominator}`, eta residual `{eta_from_product(product, SUPPORT_SIZE)-STRICT_TARGET_ETA:.3e}`.\n"
        "- Honest read: maximizing distance-5 pairs is a clean finite support selector, but the strict source for that band-pass polarity is not derived.\n"
        "- No false pass: no strict support action theorem, no QW-2191 discharge, no ToE closure.\n",
        encoding="utf-8",
    )
    print(OUT_JSON)
    print(OUT_MD)


if __name__ == "__main__":
    main()
